### ISSUE TITLE
RuntimeError: Unable to find a valid profile for this image.

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#110]
Hi,
I have the following problem to run rekall:

    DEBUG:rekall.1:Logging level set to 10
    DEBUG:rekall.1:Voting round with base: None
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
    DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
    DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
    DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
    DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
    DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
    DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
    DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
    INFO:rekall.1:Added aff4://4b8b95ce-a9b1-4fbf-a41d-1f13607ad301/PhysicalMemory as physical memory
    DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
    DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
    DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
    DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
    DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
    DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
    DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
    DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
    DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
    DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
    DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
    DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
    DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
    DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
    DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
    DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
    DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
    DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
    DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
    DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
    INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
    DEBUG:rekall.1:Will detect profile using these Detectors: nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
    DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/inventory.gz
    DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/inventory.gz
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/nt/eprocess_index.gz
    INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/root/.rekall_cache
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/nt/index.gz
    INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/root/.rekall_cache
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/OSX/index.gz
    INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/root/.rekall_cache
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/pe.gz
    INFO:rekall.1:Loaded profile pe from Local Cache Directory:/root/.rekall_cache
    DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/ntfs.gz
    INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/root/.rekall_cache
    DEBUG:rekall.1:Skipped profile LinuxGeneric/3.10.0-229.14.1.el7.x86_64 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/3.10.0-229.14.1.el7.x86_64 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.18-mips from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.18-mips from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.17_mvl21-malta-mips_fp_le from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.17_mvl21-malta-mips_fp_le from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.31-uc0 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.31-uc0 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.31
    Class from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.31
    Class from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.22-XR100-v1.1.6 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.22-XR100-v1.1.6 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.17 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.17 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.2.14openrg from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.2.14openrg from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.31.8 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.31.8 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.32-5-sparc64-smp from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.32-5-sparc64-smp from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.22.18 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.22.18 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.27-ubnt0, from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.27-ubnt0, from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.38-2-686 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.38-2-686 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.18-1000.ISS.54 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.4.18-1000.ISS.54 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.17.14_stm22_0041-STB1001H from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.17.14_stm22_0041-STB1001H from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.16 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile LinuxGeneric/2.6.16 from http://profiles.rekall-forensic.com (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.16.27 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
    DEBUG:rekall.1:Skipped profile Debian/2.6.16.27 from http://profiles.rekall-forensic.com (Not in inventory)
    ERROR:rekall.1:No profiles match this image. Try specifying manually.
    Traceback (most recent call last):
      File "/root/venv_rekall/bin/rekal", line 9, in <module>
        load_entry_point('rekall-core==1.4.1', 'console_scripts', 'rekal')()
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/rekal.py", line 104, in main
        user_session=user_session)
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/args.py", line 418, in parse_args
        command_metadata = user_session.plugins.Metadata(plugin_name)
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/session.py", line 102, in Metadata
        return self.plugin_db.GetActivePlugin(name)
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/plugin.py", line 371, in GetActivePlugin
        if plugin_cls.is_active(self.session):
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 60, in is_active
        return (super(AbstractWindowsCommandPlugin, cls).is_active(session) and
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/plugin.py", line 198, in is_active
        session.profile != None)
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/session.py", line 903, in profile
        res = self.GetParameter("profile_obj")
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/session.py", line 629, in GetParameter
        result = self._RunParameterHook(item)
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/session.py", line 664, in _RunParameterHook
        result = hook.calculate()
      File "/root/venv_rekall/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 576, in calculate
        "Unable to find a valid profile for this image. "
    RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.

Linu Kernel version:  **Linux forensics 3.10.0-327.3.1.el7.x86_64** #1 SMP Wed Dec 9 14:09:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Linux Distro: **Centos 7.1**

**Comment by scudette** [comment]
For Linux systems you must build a profile first. See the documentation
here:

http://memory-analysis.rekall-forensic.com/www/06-Linux_Memory_analysis/


Am 02.01.2016 9:11 nachm. schrieb "fpusersuggest" <notifications@github.com

**Comment by parkisan** [comment]
Thanks for the report!

You'll have to create the profile, as we don't have it for this version of
CentOS.

You have instructions here:
http://memory-analysis.rekall-forensic.com/www/06-Linux_Memory_analysis/

**Comment by fpusersuggest** [comment]
Hi to both,
I have some problems again to build the profile.
Well, I have:

1. Downloaded the source and unzipped
2. gone to tools/linux
3. built the profile with **make profile**
4. converted with **rekal convert_profile profile/3.10.0-327.3.1.el7.x86_64.zip profile/Centos7.1_3.10.0-327.3.1.el7.x86_64**
5. copied to the profiles repo with **cp profile/Centos7.1_3.10.0-327.3.1.el7.x86_64  /root/venv_rekall/profiles/** 
6. added the path to /root/.rekallrc file and in the variable repository_path.

then I run rekall and I have the following errors:

```
[1] box.aff4 19:05:40> pslist
WARNING:rekall.1:Inventory for repository "/root/venv_rekall/profiles" seems malformed. Are you behind a captive portal or proxy? If this is a custom repository, did you forget to create an inventory? You must use the tools/profiles/build_profile_repo.py tool with the --inventory flag.
WARNING:rekall.1:Inventory for repository "/root/venv_rekall/profiles" seems malformed. Are you behind a captive portal or proxy? If this is a custom repository, did you forget to create an inventory? You must use the tools/profiles/build_profile_repo.py tool with the --inventory flag.
WARNING:rekall.1:Inventory for repository "/root/venv_rekall/profiles" seems malformed. Are you behind a captive portal or proxy? If this is a custom repository, did you forget to create an inventory? You must use the tools/profiles/build_profile_repo.py tool with the --inventory flag.
```
and it does not find the profile. Then I try to pass it by argument:

```
(venv_rekall)[root@forensics venv_rekall]# rekal -f ../aff4/box.aff4 -p profiles/Centos7.1_3.10.0-327.3.1.el7.x86_64 pslist
CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
```

**Comment by parkisan** [comment]
Can you rerun pslist with -v to maybe see what's failing?

**Comment by scudette** [comment]
Hi
When you make a single profile you need to specify the path to it with the
-p parameter. You don't need to change any thing in the config file.

A profile repository is a specially structured directory which I don't
think is what you have. You can mirror the actual profile repository
locally and add the profile to it instead and then you can change the path
to e repository.

Thanks
Michael.
Am 03.01.2016 1:13 vorm. schrieb "fpusersuggest" <notifications@github.com>:

**Comment by fpusersuggest** [comment]
@parkisan pslist -v
```
DEBUG:rekall.1:Opened local file /root/venv_rekall/profiles/Centos7.1_3.10.0-327.3.1.el7.x86_64
DEBUG:rekall.1:Logging level set to 10
DEBUG:rekall.1:Voting round with base: None
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
INFO:rekall.1:Added aff4://4b8b95ce-a9b1-4fbf-a41d-1f13607ad301/PhysicalMemory as physical memory
DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
DEBUG:rekall.1:Opened local file /root/venv_rekall/profiles/Centos7.1_3.10.0-327.3.1.el7.x86_64
DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': 'profiles/Centos7.1_3.10.0-327.3.1.el7.x86_64', 'proc_regex': None, 'task': None, 'pid': None, 'task_head': None, 'phys_task': None, 'method': ['InitTask']})
DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
DEBUG:rekall.1:Found Kernel slide -0x32000.
DEBUG:rekall.1:Failed to verify dtb @ 0x1918000
INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
```

@scudette I used the -p parameter

**Comment by parkisan** [comment]
That's interesting. It looks like it may have KASLR enabled or we
misidentified it.
You're running the latest version of Rekall, right? Have you tried with the
git head? (i.e git clone https://github.com/google/rekall.git )

On the running system, can you also share the output of:

# grep linux_proc_banner /boot/System.map-$(uname -r)
# grep linux_proc_banner /proc/kallsyms

**Comment by fpusersuggest** [comment]
Thank for your anwer.
Well the things become more complicated. I downloaded rekall with **git clone https://github.com/google/rekall.git** but I don't know how to install it from virtualenv because If I run it I have an other error:
```
(venv_rekall)[root@forensics rekall]# ./rekall-core/rekall/rekal.py --version
Traceback (most recent call last):
  File "./rekall-core/rekall/rekal.py", line 54, in <module>
    class Run(plugin.PrivilegedMixIn, plugin.Command):
AttributeError: 'module' object has no attribute 'PrivilegedMixIn'
(venv_rekall)[root@forensics rekall]# pwd
/root/venv_rekall/head/rekall
```

In the README I don't see any instructins to install it.

**Comment by scudette** [comment]
CD rekall-core
Python setup.py install
Am 03.01.2016 8:20 nachm. schrieb "fpusersuggest" <notifications@github.com

**Comment by fpusersuggest** [comment]
Hi,
well this is the output:
```
# ./rekall/rekal.py --version
This is Rekall Version 1.4.1.post.dev27 (Etzel)
{u'full-revisionid': u'548b0b38c02aad33839027bb9422c1e9c54e4152', u'dirty': False, u'version': u'1.4.1.post.dev27', u'error': None}
```
and
```
# ./rekall/rekal.py -f /root/aff4/box.aff4 -p /root/venv_rekall/profiles/Centos7.1_3.10.0-327.3.1.el7.x86_64 pslist
CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
Traceback (most recent call last):     
  File "./rekall/rekal.py", line 119, in <module>
    main()
  File "./rekall/rekal.py", line 116, in main
    user_session.Flush()
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/session.py", line 930, in Flush
    self.cache.Flush()
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/cache.py", line 245, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/session.py", line 631, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/session.py", line 664, in _RunParameterHook
    result = hook.calculate()
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/plugins/linux/misc.py", line 86, in calculate
    address_space = self.session.GetParameter("default_address_space")
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/session.py", line 631, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/session.py", line 664, in _RunParameterHook
    result = hook.calculate()
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/plugins/guess_profile.py", line 511, in calculate
    return self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/root/venv_rekall/lib/python2.7/site-packages/rekall_core-1.4.1.post.dev27-py2.7.egg/rekall/plugins/core.py", line 438, in GetVirtualAddressSpace
    "A DTB value was found but failed to verify. "
rekall.plugin.PluginError: A DTB value was found but failed to verify. See logging messages for more information.
```

they look the same version:
```
# /root/venv_rekall/bin/rekal.py --version
This is Rekall Version 1.4.1.post.dev27 (Etzel)
{u'full-revisionid': u'548b0b38c02aad33839027bb9422c1e9c54e4152', u'dirty': False, u'version': u'1.4.1.post.dev27', u'error': None}
# /root/venv_rekall/head/rekall/rekall-core/rekall/rekal.py  --version
This is Rekall Version 1.4.1.post.dev27 (Etzel)
{u'full-revisionid': u'548b0b38c02aad33839027bb9422c1e9c54e4152', u'dirty': False, u'version': u'1.4.1.post.dev27', u'error': None}
```

**Comment by parkisan** [comment]
Could you provide the output of the previous 2 commands I mentioned
earlier? To see the offset of linux_proc_banner both from kallsyms and
System.map.

**Comment by fpusersuggest** [comment]
Hi,
I am sorry I haven't seen your earlier commands because they were quoted inside my post.
Anyway:
```
# grep linux_proc_banner /boot/System.map-$(uname -r)
ffffffff8164d080 R linux_proc_banner
# grep linux_proc_banner /proc/kallsyms
ffffffff8164d080 R linux_proc_banner
```

**Comment by fpusersuggest** [comment]
Hi again,
anyway the server is fresh and new. It is a vps then I think the bug should be easy to reproduce.
Anyway I can send u the sample memory.

**Comment by scudette** [comment]
Thanks - that would make it easier to debug. Could you also please include the zip file you compiled above for the profile?

**Comment by jersten** [comment]
Experiencing exact issue when creating custom profile on Ubuntu 16.04.2
