### ISSUE TITLE
AttributeError raised: No such vtype: _MMPTE

### ISSUE THREAD

**Issue by MPurple** [google/rekall#129]
Hi Everyone, 

When I try to execute this code:
```
from rekall import session
from rekall.plugins.overlays import windows

s = session.Session(filename = r"\\.\pmem", autodetect = ["nt_index", "pe"], profile_path=["http://profiles.rekall-forensic.com"])
s.default_address_space
```
I get this error:

> INFO:rekall.1:Autodetected physical address space WinPmemAddressSpace
> INFO:rekall.1:Loaded profile nt/eprocess_index from URL:http://profiles.rekall-forensic.com (in 0.34299993515 sec)
> INFO:rekall.1:Loaded profile nt/index from URL:http://profiles.rekall-forensic.com (in 0.421999931335 sec)
> INFO:rekall.1:Loaded profile pe from URL:http://profiles.rekall-forensic.com (in 0.203000068665 sec)
> INFO:rekall.1:Loaded profile ntdll/GUID/743996EA223643DFA2C1AA9BFDDCFE502 from URL:http://profiles.rekall-forensic.com (in 0.421999931335 sec)
> INFO:rekall.1:Detection method nt_index yielded profile <AMD64 profile ntdll/GUID/743996EA223643DFA2C1AA9BFDDCFE502 (Ntdll)>
> Traceback (most recent call last):
>   File "<pyshell#1>", line 1, in <module>
>     s.default_address_space
>   File "C:\Python27\lib\site-packages\rekall\utils.py", line 927, in __get__
>     return super(safe_property, self).__get__(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\rekall\session.py", line 649, in default_address_space
>     return self.GetParameter("default_address_space")
>   File "C:\Python27\lib\site-packages\rekall\session.py", line 714, in GetParameter
>     result = self._RunParameterHook(item)
>   File "C:\Python27\lib\site-packages\rekall\session.py", line 749, in _RunParameterHook
>     result = hook.calculate()
>   File "C:\Python27\lib\site-packages\rekall\plugins\guess_profile.py", line 690, in calculate
>     return self.session.plugins.load_as().GetVirtualAddressSpace()
>   File "C:\Python27\lib\site-packages\rekall\plugins\core.py", line 413, in GetVirtualAddressSpace
>     self.session.kernel_address_space = find_dtb.CreateAS(dtb)
>   File "C:\Python27\lib\site-packages\rekall\plugins\core.py", line 264, in CreateAS
>     profile=self.profile)
>   File "C:\Python27\lib\site-packages\rekall\registry.py", line 72, in __call__
>     res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
>   File "C:\Python27\lib\site-packages\rekall\plugins\windows\pagefile.py", line 245, in __init__
>     pte = self.session.profile._MMPTE()
>   File "C:\Python27\lib\site-packages\rekall\obj.py", line 2372, in __getattr__
>     raise AttributeError("No such vtype: %s" % attr)
> RuntimeError: AttributeError raised: No such vtype: _MMPTE

Is this a normal behaviour ?

**Comment by scudette** [comment]
Can you please check which profile is detected for your image? Look for a line similar to

```
INFO:rekall.1:Loaded profile nt/GUID/XXXXXXXX from URL:http://profiles.rekall-forensic.com (in 0.421999931335 sec)
```

I know MS sometimes release broken PDB files which do not have all the symbols.

**Comment by MPurple** [comment]
Thank you for your help !

I get that:

> INFO:rekall.1:Autodetected physical address space WinPmemAddressSpace
> INFO:rekall.1:Loaded profile nt/eprocess_index from URL:http://profiles.rekall-forensic.com (in 0.68700003624 sec)
> INFO:rekall.1:Loaded profile nt/index from URL:http://profiles.rekall-forensic.com (in 0.921999931335 sec)
> INFO:rekall.1:Loaded profile pe from URL:http://profiles.rekall-forensic.com (in 0.343000173569 sec)
> INFO:rekall.1:Loaded profile ntdll/GUID/743996EA223643DFA2C1AA9BFDDCFE502 from URL:http://profiles.rekall-forensic.com (in 0.828000068665 sec)
> INFO:rekall.1:Detection method nt_index yielded profile <AMD64 profile ntdll/GUID/743996EA223643DFA2C1AA9BFDDCFE502 (Ntdll)>
> <AMD64 profile ntdll/GUID/743996EA223643DFA2C1AA9BFDDCFE502 (Ntdll)>

Is there a way to patch broken PDB files ?

**Comment by scudette** [comment]
I assume the problem went away once you upgraded your kernel?

BTW if you are using live memory you should always use the `windows_kernel_file` detector because this will always work. On an image the `rsds` detector is best. The `nt_index detector` is not so reliable and sometimes fails. The `pe` detector is not used for memory images so it is useless (doesn't hurt to include it but it does nothing).
