### ISSUE TITLE
Windows 10, unable to find a valid profile for this image.

### ISSUE THREAD

**Issue by debernal** [google/rekall#131]
Hello, 

I have collected a Win 10 x 64 aff memory dump using winpmem_2.0.1.exe. I am a new user to rekal. When I try to open it, it doesn´t find the valid profile for the image. Below you will see the verbose output. Thanks for the help.

I added the following lines to .rekallrc file, but the error was not fixed.
profile_path:
  - https://raw.githubusercontent.com/google/rekall-profiles

```
C:\Program Files\Rekall>rekal.exe -v -f E:\win7x64.aff pslist
DEBUG:rekall.1:Logging level set to 10
DEBUG:rekall.1:Voting round with base: None
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'>
DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Filename does not look like a device.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
INFO:rekall.1:Added aff4://e48b88a5-df34-433d-bbac-c57464b75494/PhysicalMemory as physical memory
DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'>
DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
DEBUG:rekall.1:Failed instantiating Win32FileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
DEBUG:rekall.1:Will detect profile using these Detectors: nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\inventory.gz
DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\inventory.gz
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\nt\eprocess_index.gz
INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\username\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\nt\index.gz
INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:C:\Users\username\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\OSX\index.gz
INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:C:\Users\username\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\pe.gz
INFO:rekall.1:Loaded profile pe from Local Cache Directory:C:\Users\username\.rekall_cache
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\v1.0\ntfs.gz
INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:C:\Users\username\.rekall_cache
DEBUG:rekall.1:Skipped profile nt/GUID/C832C21B77FF44DCB0AF5F51247340E51 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
DEBUG:rekall.1:Skipped profile nt/GUID/C832C21B77FF44DCB0AF5F51247340E51 from http://profiles.rekall-forensic.com (Not in inventory)
DEBUG:rekall.1:Will build local profile nt/GUID/C832C21B77FF44DCB0AF5F51247340E51
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:Error: HTTP Error 404: Not Found
DEBUG:rekall.1:Skipped profile nt/GUID/7F1B103E78104AE2AA8D8E1E303484AD1 from https://raw.githubusercontent.com/google/rekall-profiles/master (Not in inventory)
DEBUG:rekall.1:Skipped profile nt/GUID/7F1B103E78104AE2AA8D8E1E303484AD1 from http://profiles.rekall-forensic.com (Not in inventory)
DEBUG:rekall.1:Will build local profile nt/GUID/7F1B103E78104AE2AA8D8E1E303484AD1
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:Error: HTTP Error 404: Not Found
ERROR:rekall.1:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.rekal", line 104, in main
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.args", line 418, in parse_args
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 102, in Metadata
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.plugin", line 371, in GetActivePlugin
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.windows.common", line 60, in is_active
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.plugin", line 198, in is_active
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 903, in profile
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 629, in GetParameter
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.session", line 664, in _RunParameterHook
  File "C:\Users\mic\rekall\build\rekal\out00-PYZ.pyz\rekall.plugins.guess_profile", line 576, in calculate
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.


```

**Comment by scudette** [comment]
How big is this image? Which version of Rekall are you running? We have recently upgraded the default value of --autodetect_scan_length to a larger value since we found that the default (1Gb) was often too small. Maybe try to set it to a larger value (say 100Gb):

```
rekal.exe -v -f E:\win7x64.aff --autodetect_scan_length 100000000000  pslist
```

You can see that it finds a couple of false positive profiles which are not in our repository but then they are available from Microsoft either (the 404 not found). Do you know if this is a public version of windows or is it somehow special?

Finally it would help if you could attach the file c:\windows\system32\ntoskrnl.exe from the original system. The next release will automatically acquire this file but winpmem 2.0.1 does not.

**Comment by debernal** [comment]
Hello Michael, thanks for your support.

The memory dump is 4 GB. I am running 1.4.1.post.dev14 (Etzel)

```
C:\WINDOWS\system32>rekal --version
This is Rekall Version 1.4.1.post.dev14 (Etzel)
{u'full-revisionid': u'a1623719a81b953691e92d4655586181a82e6a5f', u'dirty': True, u'version': u'1.4.1.post.dev14', u'error': None}
```
I repeated the process all over again and issued the command that you shared and it worked! :) After giving it some minutes for scanning, It was able to show the process list. Is there a list of the currently supported modules for Windows 10?
If I reissue the pslist command it takes some time to rescan it using the windtb scanner. Is it possible to save the dtb locations so that if the command is reissued it is identified more rapidly or 

provide the dtb addresses and or profile so that additional commands are executed more rapidly?

This was the debug output right before it showed the process list
```
DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': None, 'proc_regex': None, 'phys_eprocess': None, 'pid': None, 'eprocess': None, 'method': ['PsActiveProcessHead', 'CSRSS', 'PspCidTable', 'Sessions', 'Handles']})
DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
DEBUG:rekall.1:Found _EPROCESS @ 0x105F780CE (DTB: 0x49440000)
DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.
DEBUG:rekall.1:Found _EPROCESS @ 0x12558D853 (DTB: 0x61725400)
DEBUG:rekall.1:Found _EPROCESS @ 0x13A7A8A40 (DTB: 0x1AA000)
DEBUG:rekall.1:Opened local file C:\Users\username\.rekall_cache\sessions\v1.0\sessions\aca84e89c8433acb6c5806c5203074b1534c19fe\default_address_space.gz
```

Thanks, it worked great! Thanks for the tool it is very useful.

**Comment by vvissams** [comment]
Hello Michael,

I am facing similar problems on Windows 10. (Unable to find valid profiles).

I have captured the memory dump with winpmem 2.1 version and used " --autodetect_scan_length 100000000000" as you mentioned. 

Here is the output trace

# rekal -v -f test1.aff4  --autodetect_scan_length 100000000000  pslist
2016-04-15 16:54:29,306:DEBUG:rekall.1:Logging level set to 10
2016-04-15 16:54:29,306:DEBUG:rekall.1:Voting round with base: None
2016-04-15 16:54:29,307:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-04-15 16:54:29,307:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2016-04-15 16:54:29,307:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-04-15 16:54:29,308:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2016-04-15 16:54:29,309:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-04-15 16:54:29,309:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2016-04-15 16:54:29,309:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-04-15 16:54:29,309:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2016-04-15 16:54:29,310:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-04-15 16:54:29,310:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2016-04-15 16:54:29,310:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-04-15 16:54:29,310:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2016-04-15 16:54:29,311:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-04-15 16:54:29,311:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2016-04-15 16:54:29,311:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-04-15 16:54:29,311:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2016-04-15 16:54:29,311:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-04-15 16:54:29,312:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2016-04-15 16:54:29,312:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-04-15 16:54:29,312:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2016-04-15 16:54:29,312:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-04-15 16:54:29,506:INFO:rekall.1:Added aff4://ee77a60f-0146-4956-8dc2-dd4b5da7431f/PhysicalMemory as physical memory
2016-04-15 16:54:29,511:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
2016-04-15 16:54:29,512:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
2016-04-15 16:54:29,513:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-04-15 16:54:29,523:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2016-04-15 16:54:29,524:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-04-15 16:54:29,524:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-04-15 16:54:29,524:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-04-15 16:54:29,524:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-04-15 16:54:29,524:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-04-15 16:54:29,525:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-04-15 16:54:29,525:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-04-15 16:54:29,525:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-04-15 16:54:29,525:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-04-15 16:54:29,525:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2016-04-15 16:54:29,526:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-04-15 16:54:29,526:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2016-04-15 16:54:29,527:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-04-15 16:54:29,527:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2016-04-15 16:54:29,527:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-04-15 16:54:29,528:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2016-04-15 16:54:29,528:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-04-15 16:54:29,529:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2016-04-15 16:54:29,529:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-04-15 16:54:29,531:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2016-04-15 16:54:29,531:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2016-04-15 16:54:29,531:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2016-04-15 16:54:29,538:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2016-04-15 16:54:29,539:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2016-04-15 16:54:29,539:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2016-04-15 16:54:29,539:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2016-04-15 16:54:29,541:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2016-04-15 16:54:29,544:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2016-04-15 16:54:29,545:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2016-04-15 16:54:29,550:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2016-04-15 16:54:29,550:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2016-04-15 16:54:29,550:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2016-04-15 16:54:29,550:INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
2016-04-15 16:54:29,559:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-04-15 16:54:30,925:DEBUG:rekall.1:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz
2016-04-15 16:54:30,976:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/inventory.gz
2016-04-15 16:54:31,639:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-04-15 16:54:31,693:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/inventory.gz
2016-04-15 16:54:31,694:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/Linux/index.gz
2016-04-15 16:54:31,703:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/root/.rekall_cache (in 0.00871086120605 sec)
2016-04-15 16:54:31,704:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/nt/eprocess_index.gz
2016-04-15 16:54:31,787:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/root/.rekall_cache (in 0.0834510326385 sec)
2016-04-15 16:54:31,787:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/nt/index.gz
2016-04-15 16:54:31,853:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/root/.rekall_cache (in 0.065376996994 sec)
2016-04-15 16:54:31,855:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/OSX/index.gz
2016-04-15 16:54:31,862:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/root/.rekall_cache (in 0.00768804550171 sec)
2016-04-15 16:54:31,863:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/pe.gz
2016-04-15 16:54:31,881:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/root/.rekall_cache (in 0.0179100036621 sec)
2016-04-15 16:54:31,881:DEBUG:rekall.1:Trying method pe, offset 0
2016-04-15 16:54:31,883:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-04-15 16:54:31,884:DEBUG:rekall.1:Trying method rsds, offset 0
2016-04-15 16:54:31,906:DEBUG:rekall.1:Trying method linux_index, offset 0
2016-04-15 16:54:31,906:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2016-04-15 16:54:31,907:DEBUG:rekall.1:Trying method nt_index, offset 0
2016-04-15 16:54:32,891:DEBUG:rekall.1:Trying method ntfs, offset 0
2016-04-15 16:54:32,892:DEBUG:rekall.1:Opened local file /root/.rekall_cache/v1.0/ntfs.gz
2016-04-15 16:54:32,896:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/root/.rekall_cache (in 0.00418210029602 sec)
2016-04-15 16:55:38,176:ERROR:rekall.1:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "/usr/local/bin/rekal", line 9, in <module>
    load_entry_point('rekall-core==1.5.0.post.dev3', 'console_scripts', 'rekal')()
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 99, in main
    user_session=user_session)
  File "/usr/local/lib/python2.7/dist-packages/rekall/args.py", line 418, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 125, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 607, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/darwin/common.py", line 99, in is_active
    return (super(DarwinOnlyMixin, cls).is_active(session) and
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 249, in is_active
    session.profile != None)
  File "/usr/local/lib/python2.7/dist-packages/rekall/utils.py", line 927, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 989, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 714, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 749, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/guess_profile.py", line 819, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
