### ISSUE TITLE
AttributeError: No such vtype: init_crypto

### ISSUE THREAD

**Issue by elceef** [google/rekall#135]
```
$ rekal --version
This is Rekall Version 1.4.1.post.dev74 (Furka)
{u'full-revisionid': u'0e9d86497cf752a04fcb1f5cf7ffeb3be20c5a46', u'dirty': False, u'version': u'1.4.1.post.dev74', u'error': None}
```

When trying to use mimikatz plugin on a converted hibernation file (hiberfil.sys) the following error occurs:

```
2016-04-13 12:13:53,578:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1.post0.dev74-py2.7.egg/rekall/session.py", line 825, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1.post0.dev74-py2.7.egg/rekall/plugins/windows/mimikatz.py", line 524, in render
    lsasrv.init_crypto()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1.post0.dev74-py2.7.egg/rekall/obj.py", line 2373, in __getattr__
    raise AttributeError("No such vtype: %s" % attr)
AttributeError: No such vtype: init_crypto
```

**Comment by scudette** [comment]
This error occurs when we are unable to load the profile for lsasrv. Can you please include the entire log when you run with the --verbose flag?   It may be that mimikatz does not work on this windows version.

**Comment by elceef** [comment]
```
2016-04-13 21:00:56,877:DEBUG:rekall.1:Running plugin (mimikatz) with args (()) kwargs ({})
2016-04-13 21:00:56,878:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/dtb.gz
2016-04-13 21:00:56,880:DEBUG:rekall.1:Decoded in 0.000180959701538 sec.
2016-04-13 21:00:56,882:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/v1.0/nt/eprocess_index.gz
2016-04-13 21:00:56,937:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/elceef/.rekall_cache (in 0.0557811260223 sec)
2016-04-13 21:00:56,944:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/default_address_space.gz
2016-04-13 21:00:56,948:DEBUG:rekall.1:Decoded in 0.00322008132935 sec.
        LUID               Type       Sess         SID          Module   Info        Domain            User         SType                Secret             
-------------------- ----------------  --  -------------------- ------- ------- ---------------- ---------------- --------- --------------------------------
2016-04-13 21:00:56,950:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/pslist_PsActiveProcessHead.gz
2016-04-13 21:00:56,951:DEBUG:rekall.1:Decoded in 0.000227928161621 sec.
2016-04-13 21:00:56,952:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/pslist_CSRSS.gz
2016-04-13 21:00:56,952:DEBUG:rekall.1:Decoded in 0.000200033187866 sec.
2016-04-13 21:00:56,953:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/pslist_PspCidTable.gz
2016-04-13 21:00:56,954:DEBUG:rekall.1:Decoded in 0.000193119049072 sec.
2016-04-13 21:00:56,954:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/pslist_Sessions.gz
2016-04-13 21:00:56,955:DEBUG:rekall.1:Decoded in 0.000188112258911 sec.
2016-04-13 21:00:56,955:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/pslist_Handles.gz
2016-04-13 21:00:56,956:DEBUG:rekall.1:Decoded in 0.000153064727783 sec.
2016-04-13 21:00:57,005:DEBUG:rekall.1:Switching to process context: lsass.exe (Pid 844@0xfa800ade4b10)
2016-04-13 21:00:57,010:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/kernel_base.gz
2016-04-13 21:00:57,011:DEBUG:rekall.1:Decoded in 0.000294923782349 sec.
2016-04-13 21:00:57,114:DEBUG:rekall.1:Switching to Kernel context
2016-04-13 21:00:57,135:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/sessions/v1.0/sessions/6ceacb60805681c67eb22df544a3acf8c6bbbeb1/ObjectTypeMap.gz
2016-04-13 21:00:57,136:DEBUG:rekall.1:Decoded in 0.000855207443237 sec.
2016-04-13 21:01:01,594:DEBUG:rekall.1:Switching to process context: lsass.exe (Pid 844@0xfa800ade4b10)
2016-04-13 21:01:01,596:DEBUG:rekall.1:Switching to Kernel context
2016-04-13 21:01:01,845:DEBUG:rekall.1:Switching to process context: lsass.exe (Pid 844@0xfa800ade4b10)
2016-04-13 21:01:02,007:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/v1.0/pe.gz
2016-04-13 21:01:02,020:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/elceef/.rekall_cache (in 0.0127079486847 sec)
2016-04-13 21:01:02,411:DEBUG:rekall.1:Opened local file /home/elceef/.rekall_cache/v1.0/lsasrv/index.gz
2016-04-13 21:01:02,419:INFO:rekall.1:Loaded profile lsasrv/index from Local Cache Directory:/home/elceef/.rekall_cache (in 0.00886392593384 sec)
2016-04-13 21:01:02,432:DEBUG:rekall.1:Building profile from PE Exports for lsasrv
2016-04-13 21:01:02,437:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1.post0.dev74-py2.7.egg/rekall/session.py", line 825, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1.post0.dev74-py2.7.egg/rekall/plugins/windows/mimikatz.py", line 524, in render
    lsasrv.init_crypto()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.4.1.post0.dev74-py2.7.egg/rekall/obj.py", line 2373, in __getattr__
    raise AttributeError("No such vtype: %s" % attr)
AttributeError: No such vtype: init_crypto
```

**Comment by scudette** [comment]
The problem here is that we can not identify lsasrv exactly because the
GUID is not mapped in. Rekall needs to get the GUID so it can download the
PDB file from the Microsoft symbol server (so it knows where all the keys
are). Sometimes the GUID is not mapped in memory in this case Rekall tries
to match the index we have of all the versions of lsasrv we know about. In
order to match though the GUID much be known in advance.

Failing this it tries to build a partial profile from exported symbols (the
message "Building profile from PE Exports for lsasrv") but this is not
going to work because the keys are not exported symbols and for mimikatz
plugin this is not good enough.

You can actually override what Rekall is trying to detect by supplying the
correct profile (and GUID) by hand. For example here I have an image which
mimikatz works on. You can see it trying to match the index until it
decides the best match is lsasrv/GUID/FF09E40EF2EB4613981E1B22DF7AF1F82
(which is correct in this case):

2016-04-13
13:28:27,872:DEBUG:rekall.1:lsasrv/GUID/D2169DDD06EA47F191CC1D39AE40D2082
matched offset 0x14bbc0+0x7fefca40000=0x7fefcb8bbc0 ('Negotiat')
2016-04-13
13:28:27,874:DEBUG:rekall.1:lsasrv/GUID/D2169DDD06EA47F191CC1D39AE40D2082
matches 3/11 comparison points
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x153180+0x7fefca40000=0x7fefcb93180
('E\x00n\x00t\x00e\x00r\x00p\x00r\x00i\x00s\x00e\x00
\x00C\x00r\x00e\x00d\x00e\x00n\x00t\x00i\x00a\x00l\x00')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x152710+0x7fefca40000=0x7fefcb92710
('P\x00r\x00e\x00f\x00e\x00r\x00r\x00e\x00d\x00')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x154200+0x7fefca40000=0x7fefcb94200
('C\x00:\x00\\\x00W\x00i\x00n\x00d\x00o\x00w\x00s\x00')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x152760+0x7fefca40000=0x7fefcb92760
('M\x00i\x00c\x00r\x00o\x00s\x00o\x00f\x00t\x00')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x151b70+0x7fefca40000=0x7fefcb91b70
('m\x00s\x00p\x00r\x00i\x00v\x00s\x00')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x14bbc0+0x7fefca40000=0x7fefcb8bbc0 ('Negotiat')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0xdbbcf+0x7fefca40000=0x7fefcb1bbcf ('\x90')
2016-04-13
13:28:27,875:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0xb580f+0x7fefca40000=0x7fefcaf580f ('\x90')
2016-04-13
13:28:27,876:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matched offset 0x56af+0x7fefca40000=0x7fefca456af ('\x90')
2016-04-13
13:28:27,876:DEBUG:rekall.1:lsasrv/GUID/CD66008F62B94F4E86FD0B791C8E830B2
matches 9/11 comparison points
2016-04-13 13:28:27,881:DEBUG:rekall.1:Opened local file
/home/scudette/.rekall_cache/v1.0/lsasrv/GUID/FF09E40EF2EB4613981E1B22DF7AF1F82.gz
2016-04-13 13:28:27,939:INFO:rekall.1:Loaded profile
lsasrv/GUID/FF09E40EF2EB4613981E1B22DF7AF1F82 from Local Cache
Directory:/home/scudette/.rekall_cache (in 0.0578849315643 sec)
2016-04-13 13:28:27,941:DEBUG:rekall.1:Opened local file
/home/scudette/.rekall_cache/v1.0/mimikatz/AMD64.gz
2016-04-13 13:28:28,055:INFO:rekall.1:Loaded profile mimikatz/AMD64 from
Local Cache Directory:/home/scudette/.rekall_cache (in 0.11435508728 sec)
00000000:0001814c    Interactive      1    S-1-5-21-347710756-1 msv
Primary mic-PC           mic              NTLM
 8fd6bcdb5cfa96997d2e09d613157cee
                                           046549666-1343233156


                                           -1000


00000000:0001814c    Interactive      1    S-1-5-21-347710756-1 msv
Primary mic-PC           mic              SHA1
 d18ff9fb45ab511db40ffa00
                                           046549666-1343233156


                                           -1000




... Then it works well.

Now we can force it to use another profile. Rekall uses the address
resolver to manage profiles for different modules (e.g. dlls, kernel
drivers etc). There is a different address resolver for every process
context (because they have different memory layout) so first we need to
switch to the correct process of lsass.exe:

[1] swapper_test.aff4 13:34:45> cc 500
------------------------------> cc(500)
2016-04-13 13:36:10,228:DEBUG:rekall.1:Running plugin (cc) with args
((500,)) kwargs ({})
2016-04-13 13:36:10,284:DEBUG:rekall.1:Switching to process context:
lsass.exe (Pid 500@0xfa800215b360)
Switching to process context: lsass.exe (Pid 500@0xfa800215b360)
           Out<5> Plugin: cc


And then we get the module that maintain information about "lsasrv" and
forcibly assign it a different profile:

[1] swapper_test.aff4 13:28:29>
session.address_resolver.GetModuleByName("lsasrv").profile =
session.LoadProfile("lsasrv/GUID/F0E6F20C048E4944A231EF54A67CCC2A2")

Now we run mimikatz again (and it will try to use the incorrect profile
which wont actually work :-)

What version of windows are you trying to analyze? I dont think mimikarz
specifically is too tested on later versions (Win10) so it might not work.

Thanks
Michael.

**Comment by elceef** [comment]
This hibernation file has been extracted from a Windows 7 SP1 x64 box.
