### ISSUE TITLE
"TypeError: slice indices must be integers or None or have an __index__ method" Traceback Error in multiple commands

### ISSUE THREAD

**Issue by Komasa** [google/rekall#148]
I am fairly new to Rekall and currently trying to analyse a memory image from a Windows 10 Pro x64 machine Version 1511 Build 10586.218
The error seems independent of the tool used for dumping (I tried Dumpit, WinPmem and FTK-imager-lite)
The error looks like this when running with an empty cache is:

 >(rekall) ~/Forensik/working rekall -v -f /mnt/hostshare/ftkdump.mem psscan
WARNING:rekall.1:Cache directory inaccessible. Disabling.
2016-05-17 14:36:21,082:WARNING:rekall.1:Cache directory inaccessible. Disabling.
2016-05-17 14:36:21,084:WARNING:rekall.1:Cache directory inaccessible. Disabling.
2016-05-17 14:36:21,085:DEBUG:rekall.1:Logging level set to 10
2016-05-17 14:36:21,085:WARNING:rekall.1:Cache directory inaccessible. Disabling.
2016-05-17 14:36:21,086:DEBUG:rekall.1:Voting round with base: None
2016-05-17 14:36:21,086:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-05-17 14:36:21,086:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2016-05-17 14:36:21,086:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-05-17 14:36:21,086:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2016-05-17 14:36:21,086:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-05-17 14:36:21,086:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2016-05-17 14:36:21,086:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-05-17 14:36:21,087:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2016-05-17 14:36:21,087:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-05-17 14:36:21,087:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2016-05-17 14:36:21,087:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-05-17 14:36:21,087:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2016-05-17 14:36:21,087:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-05-17 14:36:21,088:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2016-05-17 14:36:21,088:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-05-17 14:36:21,088:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2016-05-17 14:36:21,088:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-05-17 14:36:21,088:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2016-05-17 14:36:21,088:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-05-17 14:36:21,088:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2016-05-17 14:36:21,088:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-05-17 14:36:21,094:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
2016-05-17 14:36:21,094:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2016-05-17 14:36:21,095:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /mnt/hostshare/ftkdump.mem_info
2016-05-17 14:36:21,095:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2016-05-17 14:36:21,097:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2016-05-17 14:36:21,097:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2016-05-17 14:36:21,097:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-05-17 14:36:21,099:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2016-05-17 14:36:21,099:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-05-17 14:36:21,100:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-05-17 14:36:21,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-05-17 14:36:21,100:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-05-17 14:36:21,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-05-17 14:36:21,100:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-05-17 14:36:21,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-05-17 14:36:21,100:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-05-17 14:36:21,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-05-17 14:36:21,100:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2016-05-17 14:36:21,100:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-05-17 14:36:21,100:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2016-05-17 14:36:21,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-05-17 14:36:21,101:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2016-05-17 14:36:21,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-05-17 14:36:21,101:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2016-05-17 14:36:21,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-05-17 14:36:21,101:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2016-05-17 14:36:21,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-05-17 14:36:21,101:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2016-05-17 14:36:21,101:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2016-05-17 14:36:21,102:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2016-05-17 14:36:21,102:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2016-05-17 14:36:21,102:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2016-05-17 14:36:21,102:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2016-05-17 14:36:21,102:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2016-05-17 14:36:21,102:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2016-05-17 14:36:21,102:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2016-05-17 14:36:21,102:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2016-05-17 14:36:21,103:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2016-05-17 14:36:21,103:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2016-05-17 14:36:21,103:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2016-05-17 14:36:21,103:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2016-05-17 14:36:21,103:WARNING:rekall.1:Cache directory inaccessible. Disabling.
2016-05-17 14:36:21,103:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-05-17 14:36:21,822:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-05-17 14:36:22,076:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-05-17 14:36:23,136:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/Linux/index.gz
2016-05-17 14:36:23,224:DEBUG:rekall.1:Adding Linux/index to local cache.
2016-05-17 14:36:23,270:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/striker/.rekall_cache (in 1.02424407005 sec)
2016-05-17 14:36:24,023:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/eprocess_index.gz
2016-05-17 14:36:24,167:DEBUG:rekall.1:Adding nt/eprocess_index to local cache.
2016-05-17 14:36:24,308:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/striker/.rekall_cache (in 1.03703689575 sec)
2016-05-17 14:36:24,992:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/index.gz
2016-05-17 14:36:25,405:DEBUG:rekall.1:Adding nt/index to local cache.
2016-05-17 14:36:25,703:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/striker/.rekall_cache (in 1.39478707314 sec)
2016-05-17 14:36:26,446:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/OSX/index.gz
2016-05-17 14:36:26,448:DEBUG:rekall.1:Adding OSX/index to local cache.
2016-05-17 14:36:26,449:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/striker/.rekall_cache (in 0.746206998825 sec)
2016-05-17 14:36:27,462:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/pe.gz
2016-05-17 14:36:27,475:DEBUG:rekall.1:Adding pe to local cache.
2016-05-17 14:36:27,504:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/striker/.rekall_cache (in 1.0543551445 sec)
2016-05-17 14:36:27,504:DEBUG:rekall.1:Trying method pe, offset 0
2016-05-17 14:36:27,506:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-05-17 14:36:27,506:DEBUG:rekall.1:Trying method rsds, offset 0
2016-05-17 14:36:27,506:DEBUG:rekall.1:Trying method linux_index, offset 0
2016-05-17 14:36:27,506:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2016-05-17 14:36:27,507:DEBUG:rekall.1:Trying method nt_index, offset 0
2016-05-17 14:36:27,507:DEBUG:rekall.1:Trying method ntfs, offset 0
2016-05-17 14:36:28,659:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/ntfs.gz
2016-05-17 14:36:28,660:DEBUG:rekall.1:Adding ntfs to local cache.
2016-05-17 14:36:28,662:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/striker/.rekall_cache (in 1.15509605408 sec)
2016-05-17 14:36:31,291:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/GUID/1A603169B1B942A092B69787CCB7C4811.gz
2016-05-17 14:36:32,229:DEBUG:rekall.1:Adding nt/GUID/1A603169B1B942A092B69787CCB7C4811 to local cache.
2016-05-17 14:36:33,548:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/undocumented.gz
2016-05-17 14:36:33,550:DEBUG:rekall.1:Adding nt/undocumented to local cache.
2016-05-17 14:36:33,552:WARNING:rekall.1:Unable to parse profile section $CONSTANT_TYPES
2016-05-17 14:36:33,553:INFO:rekall.1:Loaded profile nt/undocumented from Local Cache Directory:/home/striker/.rekall_cache (in 0.69104886055 sec)
2016-05-17 14:36:33,553:WARNING:rekall.1:Unable to parse profile section $CONSTANT_TYPES
2016-05-17 14:36:33,661:INFO:rekall.1:Loaded profile nt/GUID/1A603169B1B942A092B69787CCB7C4811 from Local Cache Directory:/home/striker/.rekall_cache (in 4.54711508751 sec)
2016-05-17 14:36:33,886:DEBUG:rekall.1:Found _EPROCESS @ 0x27A5A40 (DTB: 0x1AA000)
2016-05-17 14:36:33,894:INFO:rekall.1:Detected ntkrnlmp.pdb with GUID 1A603169B1B942A092B69787CCB7C4811
2016-05-17 14:36:33,894:DEBUG:rekall.1:Detection method rsds worked at offset 0x2669940
2016-05-17 14:36:33,895:DEBUG:rekall.1:Running plugin (psscan) with args (()) kwargs ({'profile': None, 'scan_in_kernel': False})
2016-05-17 14:36:34,013:INFO:rekall.1:Detected kernel base at 0xF80122813000
2016-05-17 14:36:34,036:DEBUG:rekall.1:Listed 53 processes using PsActiveProcessHead
2016-05-17 14:36:34,589:DEBUG:rekall.1:Listed 45 processes using CSRSS
2016-05-17 14:36:35,791:DEBUG:rekall.1:Listed 53 processes using PspCidTable
2016-05-17 14:36:35,817:DEBUG:rekall.1:Listed 51 processes using Sessions
2016-05-17 14:36:35,864:DEBUG:rekall.1:Listed 48 processes using Handles
- _EPROCESS (P)          Name          PID    Offset(V)     PPID       PDB       Stat       Time created             Time exited       
  -------------- -------------------- ----- -------------- ------ -------------- ---- ------------------------ ------------------------
2016-05-17 14:36:35,907:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 825, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/filescan.py", line 415, in render
    for pool_obj, eprocess in self.scan_processes():
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/filescan.py", line 353, in scan
    for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 341, in scan
    for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
  File "/usr/lib/python2.7/site-packages/rekall/scan.py", line 355, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "/usr/lib/python2.7/site-packages/rekall/scan.py", line 248, in check_addr
    val = check.check(buffer_as, offset)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 260, in check
    buffer_as, offset + self.tag_offset)
  File "/usr/lib/python2.7/site-packages/rekall/scan.py", line 164, in check
    if buffer_as.data.startswith(self.needle, buffer_offset):
TypeError: slice indices must be integers or None or have an __index__ method

2016-05-17 14:36:35,907:CRITICAL:root:slice indices must be integers or None or have an __index__ method. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.5.0.post5', 'console_scripts', 'rekall')()
  File "/usr/lib/python2.7/site-packages/rekall/rekal.py", line 103, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 828, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 825, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/filescan.py", line 415, in render
    for pool_obj, eprocess in self.scan_processes():
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/filescan.py", line 353, in scan
    for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 341, in scan
    for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
  File "/usr/lib/python2.7/site-packages/rekall/scan.py", line 355, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "/usr/lib/python2.7/site-packages/rekall/scan.py", line 248, in check_addr
    val = check.check(buffer_as, offset)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 260, in check
    buffer_as, offset + self.tag_offset)
  File "/usr/lib/python2.7/site-packages/rekall/scan.py", line 164, in check
    if buffer_as.data.startswith(self.needle, buffer_offset):
TypeError: slice indices must be integers or None or have an __index__ method

Commands with the same error are: psxview, netscan, devicetree and probably a bunch of others

**Comment by scudette** [comment]
Hi, thanks for reporting this. This is actually a duplicate of another issue. The issue is that the PDB file provided by Microsoft for your profile is broken as it is missing _POOL_HEADER in it. 

You can fix it for yourself by editing the profile in your local cache 1A603169B1B942A092B69787CCB7C4811.gz and manually adding the _POOL_HEADER definition (its just json). You can copy from any other win7 or win10 profile that works:

```
"_POOL_HEADER": [16, {
   "AllocatorBackTraceIndex": [8, ["unsigned short", {}]], 
   "BlockSize": [0, ["BitField", {
    "end_bit": 24, 
    "start_bit": 16, 
    "target": "unsigned long"
   }]], 
```

We need to think of a way to fix this automatically when MS release broken profiles (this also breaks the windows debugger but in the Rekall case you can actually do something about it and move on with life - the windows debugger is going to be totally broken on this image).

**Comment by scudette** [comment]
Duplicate of #143
