### ISSUE TITLE
rekall hangs and eat all the CPU

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#156]
Hi !
I tried to use `Rekall` to analyze a memory dump of a `Windows XP 64bits SP1` image,
but it didn't work since it was hanging and eating one CPU.
The memory dump has been generated with `virsh dump` and it's size is 130 Mb.

I installed `Rekall` using a `virtualenv` and `pip`, and i'm using the version `1.5.1`.

There is the output of `Rekall` when I try to use it to list processes :

```
rekall -v -f dump.raw pslist
2016-06-25 22:13:50,025:DEBUG:rekall.1:Logging level set to 10
2016-06-25 22:13:50,026:DEBUG:rekall.1:Voting round with base: None
2016-06-25 22:13:50,026:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-06-25 22:13:50,026:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2016-06-25 22:13:50,026:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-06-25 22:13:50,026:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2016-06-25 22:13:50,026:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-06-25 22:13:50,026:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2016-06-25 22:13:50,026:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-06-25 22:13:50,027:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2016-06-25 22:13:50,027:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-06-25 22:13:50,028:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2016-06-25 22:13:50,028:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2016-06-25 22:13:50,028:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at dump.raw_info
2016-06-25 22:13:50,028:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2016-06-25 22:13:50,028:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2016-06-25 22:13:50,029:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2016-06-25 22:13:50,029:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2016-06-25 22:13:50,029:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4d564551
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2016-06-25 22:13:50,030:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2016-06-25 22:13:50,030:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2016-06-25 22:13:50,030:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2016-06-25 22:13:50,030:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2016-06-25 22:13:50,030:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2016-06-25 22:13:50,030:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2016-06-25 22:13:50,030:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2016-06-25 22:13:50,031:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2016-06-25 22:13:50,031:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2016-06-25 22:13:50,032:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2016-06-25 22:13:50,032:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2016-06-25 22:13:50,032:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2016-06-25 22:13:50,032:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2016-06-25 22:13:50,032:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2016-06-25 22:13:50,032:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2016-06-25 22:13:50,033:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-06-25 22:13:50,961:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-06-25 22:13:51,218:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-06-25 22:13:52,221:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/Linux/index.gz
2016-06-25 22:13:52,338:DEBUG:rekall.1:Adding Linux/index to local cache.
2016-06-25 22:13:52,375:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/developer/.rekall_cache (in 1.03603506088 sec)
2016-06-25 22:13:53,236:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/eprocess_index.gz
2016-06-25 22:13:53,375:DEBUG:rekall.1:Adding nt/eprocess_index to local cache.
2016-06-25 22:13:53,485:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/developer/.rekall_cache (in 1.1098048687 sec)
2016-06-25 22:13:54,356:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/index.gz
2016-06-25 22:13:54,599:DEBUG:rekall.1:Adding nt/index to local cache.
2016-06-25 22:13:54,844:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/developer/.rekall_cache (in 1.35830903053 sec)
2016-06-25 22:13:55,701:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/OSX/index.gz
2016-06-25 22:13:55,701:DEBUG:rekall.1:Adding OSX/index to local cache.
2016-06-25 22:13:55,703:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/developer/.rekall_cache (in 0.859523057938 sec)
2016-06-25 22:13:56,567:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/pe.gz
2016-06-25 22:13:56,573:DEBUG:rekall.1:Adding pe to local cache.
2016-06-25 22:13:56,598:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/developer/.rekall_cache (in 0.894378900528 sec)
2016-06-25 22:13:56,598:DEBUG:rekall.1:Trying method pe, offset 0
2016-06-25 22:13:56,600:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-06-25 22:13:56,600:DEBUG:rekall.1:Trying method rsds, offset 0
2016-06-25 22:13:56,600:DEBUG:rekall.1:Trying method linux_index, offset 0
2016-06-25 22:13:56,600:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2016-06-25 22:13:56,600:DEBUG:rekall.1:Trying method nt_index, offset 0
2016-06-25 22:13:56,600:DEBUG:rekall.1:Trying method ntfs, offset 0
2016-06-25 22:13:57,435:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/ntfs.gz
2016-06-25 22:13:57,436:DEBUG:rekall.1:Adding ntfs to local cache.
2016-06-25 22:13:57,438:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:/home/developer/.rekall_cache (in 0.837167024612 sec)
2016-06-25 22:13:57,498:DEBUG:rekall.1:Skipped profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2 from https://github.com/google/rekall-profiles/raw/master (Not in inventory)
2016-06-25 22:13:57,499:DEBUG:rekall.1:Skipped profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2 from http://profiles.rekall-forensic.com (Not in inventory)
2016-06-25 22:13:57,499:DEBUG:rekall.1:Will build local profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2
Extracting cabinet: /tmp/tmppImQrp/ntoskrnl.pd_
  extracting ntoskrnl.pdb

All done, no errors.
2016-06-25 22:14:01,037:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/mspdb.gz
2016-06-25 22:14:01,039:DEBUG:rekall.1:Adding mspdb to local cache.
2016-06-25 22:14:01,053:INFO:rekall.1:Loaded profile mspdb from Local Cache Directory:/home/developer/.rekall_cache (in 1.00004506111 sec)
2016-06-25 22:14:22,017:WARNING:rekall.1:Profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2 fetched and built. Please consider reporting this profile to the Rekall team so we may add it to the public profile repository.
2016-06-25 22:14:22,191:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/v1.0/nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2.gz
2016-06-25 22:14:22,388:INFO:rekall.1:Loaded profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2 from Local Cache Directory:/home/developer/.rekall_cache (in 0.196746826172 sec)
2016-06-25 22:14:22,399:DEBUG:rekall.1:Found _EPROCESS @ 0x24736C (DTB: 0x371000)
2016-06-25 22:14:22,402:DEBUG:rekall.1:_EPROCESS.ThreadListHead does not reflect.
Traceback (most recent call last):
  File "/home/developer/Bureau/rekall/venv/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.5.1', 'console_scripts', 'rekall')()
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
    user_session=user_session)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/args.py", line 419, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/session.py", line 131, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugin.py", line 784, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/darwin/common.py", line 97, in is_active
    return (super(DarwinOnlyMixin, cls).is_active(session) and
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugin.py", line 342, in is_active
    session.profile != None)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/utils.py", line 954, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/session.py", line 1028, in profile
    res = self.GetParameter("profile_obj")
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/session.py", line 742, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/session.py", line 777, in _RunParameterHook
    result = hook.calculate()
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 819, in calculate
    profile_obj = self.ScanProfiles()
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 754, in ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 378, in DetectFromHit
    return self._test_rsds(rsds)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 383, in _test_rsds
    profile = self.VerifyProfile("nt/GUID/%s" % rsds.GUID_AGE)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 357, in VerifyProfile
    return self._ApplyFindDTB(self.find_dtb_impl, profile)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 99, in _ApplyFindDTB
    for address_space in find_dtb_plugin.address_space_hits():
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 138, in address_space_hits
    for dtb, eprocess in self.dtb_eprocess_hits():
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 145, in dtb_eprocess_hits
    for eprocess in self.scan_for_process():
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 128, in scan_for_process
    address_space=self.physical_address_space).scan():
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 82, in scan
    for offset in super(WinDTBScanner, self).scan(offset, maxlen):
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/scan.py", line 378, in scan
    self.skip(buffer_as, scan_offset))
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/scan.py", line 278, in skip
    skip_value = s.skip(buffer_as, offset)
  File "/home/developer/Bureau/rekall/venv/lib/python2.7/site-packages/rekall/scan.py", line 180, in skip
    dindex = buffer_as.data.find(self.needle, buffer_offset + 1)
KeyboardInterrupt
```

As you can see, I had to stop the analysis because it was hanging on something.
What should I do ?

Thanks !

**Comment by scudette** [comment]
Is the image compressed? What kind of image is it? 130mb seems very small.
Maybe it's truncated?

Generally with raw images rekall has to scan to try and detect various
things it needs like the dtb and the profile. This is pretty expensive and
sometimes it doesn't work because it keeps trying different profiles then
applying the dtb scanner repeatedly. We have a parameter to limit the
amount of scanning so it doesn't use too much CPU but in recent versions we
increased that limit because many images need a lot of scanning (signatures
might be right at the end).

When you use winpmem or rekall itself to take the image the profile is
captured on the running system (because winpmem also acquires the kernel
binary). The dtb is also recorded so you don't need to scan for it.
Therefore we recommend you use an image format that supports additional
metadata, ideally winpmem. A typical aff4 image takes under a second to
load even for very large images because it does not do any scanning.

**Comment by Wenzel** [comment]
Hi !
Thanks for the quick reply !

Unless `virsh` is compressing the image, it's not compressed, but i don't think so because I checked
on the guest and Windows XP x64 is really consuming only 130Mb of RAM idle !
This is the `file` output : `QEMU suspend to disk image`

I think that it's a bug in Rekall, because I waited 5-10 minutes for the scanning to end, but it didn't,
and the image is very small, that's why i was thinking that Rekall was stuck in an infinite loop.

Also, I cannot use `winpmem` to acquire the image because my guest does not have an internet access.
I may be able to use shared folders though, but i would prefer to stay with my raw image.

I can send you the image if that could help you.

**Comment by noxdafox** [comment]
QEMU has got several ways to acquire memory snapshots: disk + memory, live migration, full core dumps.

Looking at the size of your memory snapshot, I assume you're acquiring the memory using the QEMU savevm command which stores only the allocated memory using a sparse file.
As far as I know, tools such as Rekall does not support these snapshot formats (it's a pity as there are several advantages using them).

You need to use QEMU pmemsave command in order to acquire a full linear snapshot of the memory. The output file should have roughly the same size of the total memory you assigned to your VM.

With libvirt, you can use the virDomainCoreDump API with VIR_DUMP_MEMORY_ONLY and the VIR_DOMAIN_CORE_DUMP_RAW flags enabled.

Here you have an acquisition example (Python) which goes around few libvirt caveats.

https://github.com/F-Secure/see/blob/master/plugins/memory.py#L195

It would be quite beneficial to add support for vmemsave formats though.

1. It only acquires the used memory resulting in smaller files

2. It does not requires a VM to be paused (live migration) making memory acquisition transparent to the guest

3. It's relatively faster compared to the full acquisition

4. Unfortunately unallocated memory will be lost making hard to retrieve memory artifacts not in use anymore. Maybe the savevm API could support the retrieval of unallocated memory leaving the unused away.

**Comment by Wenzel** [comment]
Hi !

@noxdafox is right, I was using a partial memory dump, containing only the virtual memory.

I used `virDomainCoreDump` to get a physical memory dump, which sizes (`641Mb`) now matches better the RAM allocation of my guest system (`512 Mb`).

I was able to list running processes using this raw memory dump, so the error was mine for not using a complete physical memory dump.

Besides, i encountered another issue when I tried to use the Python API to list processes.
Using the following code, which is given as an example in the [Rekall tutorial](http://www.rekall-forensic.com/docs/Manual/tutorial.html#_automating_rekall) :
~~~
#!/usr/bin/env python

import logging

from rekall import session
from rekall import plugins                           # 1

# Setup logging as required. Rekall will log to the standard logging service.
logging.basicConfig(level=logging.DEBUG)

s = session.Session(                                 # 2
  filename="winxp64.raw",
  autodetect=["rsds"],
  logger=logging.getLogger(),
  profile_path=[
      "http://profiles.rekall-forensic.com"
  ])

print s.plugins.pslist(method="PsActiveProcessHead") #
~~~
I have the following error :
~~~
ERROR:root:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "./test.py", line 19, in <module>
    print s.plugins.pslist(method="PsActiveProcessHead") #
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/session.py", line 144, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/session.py", line 124, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/plugin.py", line 784, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/plugins/darwin/common.py", line 97, in is_active
    return (super(DarwinOnlyMixin, cls).is_active(session) and
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/plugin.py", line 342, in is_active
    session.profile != None)
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/utils.py", line 954, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/session.py", line 1028, in profile
    res = self.GetParameter("profile_obj")
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/session.py", line 742, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/session.py", line 777, in _RunParameterHook
    result = hook.calculate()
  File "/home/developer/Bureau/rekall/venv/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 822, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
~~~

Why `Rekall` is able to list processes with the command line
`rekall -f winxp64.raw pslist`, and not able to do the same thing with the Python API ?

Thanks !

**Comment by scudette** [comment]
You need to tell Rekall how much scanning you are prepared to do. This is used to make sure it fails early enough on very large images and does not just spin out of control:

```
s = session.Session(                                 # 2                                                                                  
  filename="winxp64.raw",
  autodetect=["rsds"],
  logger=logging.getLogger(),
  autodetect_scan_length=18446744073709551616,
  profile_path=[
      "http://profiles.rekall-forensic.com"
  ])
```

I will update the tutorial to reflect this.

If you would like to request to add a new image file format support please open a feature request and attach a sample image and maybe the steps to create such an image.

**Comment by noxdafox** [comment]
Is the Guest Os relevant? Would a small Linux guest be enough as a sample image?

**Comment by scudette** [comment]
I dont think the guest matters too much - a Linux guest would be great. If you could please also include a standard full memory image taken at almost the same time it would be great for comparison.

**Comment by noxdafox** [comment]
Sure, I'll pause the guest and take both.

I guess this issue can be close right Mathieu?

2016-06-29 10:26 GMT+03:00 Michael Cohen <notifications@github.com>:

**Comment by Wenzel** [comment]
Hi !
Even with the parameter `autodetect_scan_length=18446744073709551616` in the `Session` constructor, I still get the same error when i try to call `s.plugins.pslist(method="PsActiveProcessHead")`

You mentionned that maybe I should add new file format support, but when I use the command line, I am able to list the processes in my image, which means that is it already supported by  rekall, right ?

**Comment by scudette** [comment]
Its hard to tell whats going on without seeing the debug messages. I just noticed that the tutorial recommends setting up the logger with logging.basicConfig() but the problem with that function is that if anything has called the logging system before, it will completely ignore this. So the only way basicConfig() can work is if is it called immediately at the top of the file:

```
#!/usr/bin/env python                                                                                                                     

import logging

# Setup logging as required. Rekall will log to the standard logging service.                                                             
logging.basicConfig(level=logging.DEBUG)

from rekall import session
from rekall import plugins                           # 1                                                                                  

s = session.Session(                                 # 2                                                                                  
  filename="/home/scudette/images/win7.elf",
  autodetect=["rsds"],
  logger=logging.getLogger(),
  autodetect_scan_length=18446744073709551616,
  profile_path=[
      "http://profiles.rekall-forensic.com"
  ])

print s.plugins.pslist(method="PsActiveProcessHead") #                                                                                    
```

This is a weird gotcha in python's logging module. If you try this way you will see the helpful logging messages which will help you debug why its not working - you probably just need to supply a couple of other things to the session constructor. If rekall itself works then you can print the content of the session to get an idea of which session parameters are specified and then you just copy those.

My comment related to the image format was about getting the original image format supported (the qemu sparse memory is it a qcow format?).

**Comment by Wenzel** [comment]
Thank you for the tip about putting `logging.basicConfig(level=logging.DEBUG)` at the top of the file, I was able to see the log output !
I noticed the following lines :
~~~
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
DEBUG:root:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:root:Autodetected physical address space Elf64CoreDump
DEBUG:root:Will detect profile using these Detectors: rsds
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/pe.gz
INFO:root:Loaded profile pe from URL:http://profiles.rekall-forensic.com (in 0.113515853882 sec)
DEBUG:root:Trying method rsds, offset 0
DEBUG:root:Skipped profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2 from http://profiles.rekall-forensic.com (Not in inventory)
ERROR:root:No profiles match this image. Try specifying manually.
~~~
and i compared this output to the one i already had with `rekall` command line :
~~~
[1] winxp64.raw 03:32:41> pslist
2016-06-30 03:32:43,582:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/sessions/v1.0/sessions/index.gz
2016-06-30 03:32:43,588:DEBUG:rekall.1:Decoded in 0.00606513023376 sec.
2016-06-30 03:32:43,591:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/sessions/v1.0/sessions/e4187fe011c949bbeabbec469b1c166fba93203f/profile.gz
2016-06-30 03:32:43,591:DEBUG:rekall.1:Decoded in 0.000371932983398 sec.
2016-06-30 03:32:43,592:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/sessions/v1.0/sessions/e4187fe011c949bbeabbec469b1c166fba93203f/image_fingerprint.gz
2016-06-30 03:32:43,593:DEBUG:rekall.1:Decoded in 0.00131487846375 sec.
2016-06-30 03:32:43,594:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/sessions/v1.0/inventory.gz
2016-06-30 03:32:43,596:DEBUG:rekall.1:Decoded in 0.00170683860779 sec.
2016-06-30 03:32:43,599:DEBUG:rekall.1:Flushed profile_obj in 0.00549507141113
2016-06-30 03:32:43,599:INFO:rekall.1:Detected fingerprinted image e4187fe011c949bbeabbec469b1c166fba93203f
2016-06-30 03:32:43,599:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/sessions/v1.0/sessions/e4187fe011c949bbeabbec469b1c166fba93203f/profile.gz
2016-06-30 03:32:43,600:DEBUG:rekall.1:Decoded in 8.58306884766e-05 sec.
2016-06-30 03:32:44,474:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-06-30 03:32:44,568:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/v1.0/inventory.gz
2016-06-30 03:32:44,665:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-06-30 03:32:44,808:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/v1.0/inventory.gz
2016-06-30 03:32:44,810:DEBUG:rekall.1:Opened local file /home/developer/.rekall_cache/v1.0/nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2.gz
2016-06-30 03:32:45,086:INFO:rekall.1:Loaded profile nt/GUID/7BAC9352CD4C497BAC3DAF42289B10AD2 from Local Cache Directory:/home/developer/.rekall_cache (in 0.276598930359 sec)
~~~

which helped me to conclude that i needed to add this line in my script :
~~~
profile_path=[
            "/home/developer/.rekall_cache",
            "http://profiles.rekall-forensic.com"   
        ])
~~~

and now my script is working :)

But I still have to use the `rekall` command line tool first because it will handle the building of the cache.
Can i have the same behaviour using the Python API ?

Thanks !

**Comment by scudette** [comment]
Ah ok so that makes more sense now!

Rekall tries to get the profile from the profile repository but if we dont have the profile there rekall has to do something. It can fail or it can go on to contact the Microsoft symbol server by itself. The Rekall command line tool just does this - it goes off and builds its own profile by itself. But when you use Rekall as a library we cant just go out to connect to servers on the internet - we have no idea which application we are running in and if it is appropriate to connect to servers, so we just fail.

If you want your application to also connect to the symbol server you need to:
1. Add a cache directory with cache_dir parameter.
2. Configure the following parameters in your session:

```
  autodetect_build_local = basic
  autodetect_build_local_tracked = set(['win32k', 'ntdll', 'nt', 'tcpip'])
```

Build local means to fetch the pdb file and build the profiles locally. Basic means it will only fetch profiles for the tracked modules and fail for the rest - that is the default Rekall command line tool setting. Full means it will try to fetch pdb files for every module (can be slow).

**Comment by Wenzel** [comment]
It worked !
thanks.
