### ISSUE TITLE
Arp plugin on Linux fails with AttributeError in rekall/obj.py

### ISSUE THREAD

**Issue by jaredmichaelsmith** [google/rekall#158]
When running the `arp` plugin on Linux in live mode with the command `sudo rekall --live arp` (detected profile is `Linux/Ubuntu/14.04/x86_64/3.19.0-25-generic`) I get the following:

```
(sample-project-client)ojt@sample-project1:~/projects/sample-project/src/sample-project$ sudo rekall --live arp
                 IP Address                           MAC              Device
--------------------------------------------- -------------------- ---------------
                                    10.0.0.60    00:11:43:e3:5a:bc            eth0
                                    127.0.0.1    00:00:00:00:00:00              lo
2016-07-01 23:13:08,358:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/session.py", line 840, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugin.py", line 678, in render
    for row in self.collect():
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugins/linux/arp.py", line 129, in collect
    for ip, mac, devname in self.get_handle_tables():
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugins/linux/arp.py", line 81, in get_handle_tables
    for table in tables.walk_list("next"):
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/obj.py", line 1457, in walk_list
    item = getattr(item, list_member).deref()
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/obj.py", line 1425, in __getattr__
    raise AttributeError(attr)
AttributeError: next

2016-07-01 23:13:08,359:CRITICAL:root:next. Try --debug for more information.
Traceback (most recent call last):
  File "/home/ojt/.virtualenvs/sample-project-client/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.5.2.post1', 'console_scripts', 'rekall')()
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/rekal.py", line 103, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/session.py", line 843, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/session.py", line 840, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugin.py", line 678, in render
    for row in self.collect():
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugins/linux/arp.py", line 129, in collect
    for ip, mac, devname in self.get_handle_tables():
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugins/linux/arp.py", line 81, in get_handle_tables
    for table in tables.walk_list("next"):
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/obj.py", line 1457, in walk_list
    item = getattr(item, list_member).deref()
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/obj.py", line 1425, in __getattr__
    raise AttributeError(attr)
AttributeError: next
```

The python version is 2.7.11 and the output of `rekall --version` is:

```
(sample-project-client)ojt@sample-project1:~/projects/sample-project/src/sample-project$ rekall --version
This is Rekall Version 1.5.2.post1 (Furka)
{'pep440': u'1.5.2.post1', u'rc': u'0', u'version': u'1.5.2', 'error': 'Not in a git repository.', u'codename': u'Furka', u'post': u'1'}
```

It looks like it may be hitting this error when it tries to keep stepping over the ARP table and it somehow can't.

Any ideas @scudette?

Here is some more sample output leading right up to the bug, this time with the `--verbose` flag:

```
(sample-project-client)ojt@sample-project1:~/projects/sample-project/src/sample-project$ sudo /usr/local/bin/rekall --live --verbose --repository_path "http://profiles.rekall-forensic.com" -F data arp
2016-07-01 23:04:26,695:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2016-07-01 23:04:26,695:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2016-07-01 23:04:26,696:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
2016-07-01 23:04:26,696:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2016-07-01 23:04:26,697:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-07-01 23:04:26,697:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2016-07-01 23:04:26,697:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-07-01 23:04:26,697:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2016-07-01 23:04:26,697:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-07-01 23:04:26,698:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2016-07-01 23:04:26,698:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-07-01 23:04:26,698:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2016-07-01 23:04:26,705:DEBUG:rekall.1:Succeeded instantiating KCoreAddressSpace
2016-07-01 23:04:26,705:DEBUG:rekall.1:Voting round with base: KCoreAddressSpace
2016-07-01 23:04:26,705:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2016-07-01 23:04:26,707:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2016-07-01 23:04:26,707:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2016-07-01 23:04:26,707:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-07-01 23:04:26,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2016-07-01 23:04:26,708:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-07-01 23:04:26,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2016-07-01 23:04:26,708:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-07-01 23:04:26,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2016-07-01 23:04:26,709:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-07-01 23:04:26,709:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2016-07-01 23:04:26,709:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2016-07-01 23:04:26,709:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2016-07-01 23:04:26,709:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2016-07-01 23:04:26,709:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2016-07-01 23:04:26,710:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2016-07-01 23:04:26,710:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2016-07-01 23:04:26,710:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2016-07-01 23:04:26,710:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2016-07-01 23:04:26,710:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2016-07-01 23:04:26,710:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2016-07-01 23:04:26,711:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2016-07-01 23:04:26,711:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2016-07-01 23:04:26,711:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2016-07-01 23:04:26,711:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2016-07-01 23:04:26,711:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2016-07-01 23:04:26,711:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2016-07-01 23:04:26,712:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2016-07-01 23:04:26,712:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2016-07-01 23:04:26,713:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2016-07-01 23:04:26,713:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2016-07-01 23:04:26,713:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2016-07-01 23:04:26,713:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2016-07-01 23:04:26,713:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2016-07-01 23:04:26,713:INFO:rekall.1:Autodetected physical address space KCoreAddressSpace
2016-07-01 23:04:26,716:DEBUG:rekall.1:Logging level set to 10
2016-07-01 23:04:26,716:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-07-01 23:04:26,850:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-07-01 23:04:26,865:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/inventory.gz
2016-07-01 23:04:26,865:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/Linux/index.gz
2016-07-01 23:04:26,873:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/ojt/.rekall_cache (in 0.00776600837708 sec)
2016-07-01 23:04:26,874:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/nt/eprocess_index.gz
2016-07-01 23:04:26,903:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/ojt/.rekall_cache (in 0.0296041965485 sec)
2016-07-01 23:04:26,904:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/nt/index.gz
2016-07-01 23:04:26,987:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:/home/ojt/.rekall_cache (in 0.0839219093323 sec)
2016-07-01 23:04:26,988:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/OSX/index.gz
2016-07-01 23:04:26,989:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/ojt/.rekall_cache (in 0.000890016555786 sec)
2016-07-01 23:04:26,989:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/pe.gz
2016-07-01 23:04:27,000:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/ojt/.rekall_cache (in 0.0105350017548 sec)
2016-07-01 23:04:27,000:DEBUG:rekall.1:Trying method pe, offset 0
2016-07-01 23:04:27,002:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-07-01 23:04:27,002:DEBUG:rekall.1:Trying method rsds, offset 0
2016-07-01 23:04:27,003:DEBUG:rekall.1:Trying method linux_index, offset 0
2016-07-01 23:04:27,003:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2016-07-01 23:04:27,119:DEBUG:rekall.1:Found /proc/kallsyms of size: 4276874
2016-07-01 23:04:27,805:INFO:rekall.1:LinuxIndexDetector found profile Linux/Ubuntu/14.04/x86_64/3.19.0-25-generic with 6/6 matches.
2016-07-01 23:04:27,806:DEBUG:rekall.1:Opened local file /home/ojt/.rekall_cache/v1.0/Linux/Ubuntu/14.04/x86_64/3.19.0-25-generic.gz
2016-07-01 23:04:28,394:INFO:rekall.1:Loaded profile Linux/Ubuntu/14.04/x86_64/3.19.0-25-generic from Local Cache Directory:/home/ojt/.rekall_cache (in 0.588397026062 sec)
2016-07-01 23:04:28,396:INFO:rekall.1:Found slide 0x0
2016-07-01 23:04:28,396:DEBUG:rekall.1:Calculating page offset...
2016-07-01 23:04:28,396:DEBUG:rekall.1:Calculating page offset...
2016-07-01 23:04:28,415:INFO:rekall.1:Detection method linux_index yielded profile <AMD64 profile Linux/Ubuntu/14.04/x86_64/3.19.0-25-generic (Linux)>
2016-07-01 23:04:28,417:DEBUG:rekall.1:Running plugin (arp) with args (()) kwargs ({'profile': None})
2016-07-01 23:04:28,513:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/session.py", line 840, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugin.py", line 678, in render
    for row in self.collect():
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugins/linux/arp.py", line 129, in collect
    for ip, mac, devname in self.get_handle_tables():
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/plugins/linux/arp.py", line 81, in get_handle_tables
    for table in tables.walk_list("next"):
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/obj.py", line 1457, in walk_list
    item = getattr(item, list_member).deref()
  File "/home/ojt/.virtualenvs/sample-project-client/local/lib/python2.7/site-packages/rekall/obj.py", line 1425, in __getattr__
    raise AttributeError(attr)
AttributeError: next
```

**Comment by scudette** [comment]
Thanks for reporting!

The arp() plugin just walks the list of neigh_table structs. You can see here in older versions (3.16):
http://lxr.free-electrons.com/source/include/net/neighbour.h?v=3.16#L192

```
192 struct neigh_table {
193         struct neigh_table      *next;
194         int                     family;
195         int                     entry_size;
196         int                     key_len;
197         __u32                   (*hash)(const void *pkey,
198                                         const struct net_device *dev,
199                                         __u32 *hash_rnd);
```

It is a single linked list with a next pointer. But in 3.19 the next pointer disappeared:
http://lxr.free-electrons.com/source/include/net/neighbour.h?v=3.19#L192

```
struct neigh_table {
193         int                     family;
194         int                     entry_size;
195         int                     key_len;
196         __u32                   (*hash)(const void *pkey,
197                                         const struct net_device *dev,
198                                         __u32 *hash_rnd);
```

You can see that previously the global neigh_tables was a linked list:
http://lxr.free-electrons.com/source/net/core/neighbour.c?v=3.16#L59
```
 59 static struct neigh_table *neigh_tables;
```

But now it is just an array
http://lxr.free-electrons.com/source/net/core/neighbour.c?v=3.19#L1517
```
1517 static struct neigh_table *neigh_tables[NEIGH_NR_TABLES] __read_mostly;
```

I have prepared a fix here:
https://codereview.appspot.com/297650043/

**Comment by jaredmichaelsmith** [comment]
Great! Thank you. I'll check this out in the next release.
