### ISSUE TITLE
Invalid requirement: efilter

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#167]
Hi !

I tried to install rekall in a virtualenv on Debian 8 and i think there is an error with the efilter dependency.

Python version : `2.7.9`
pip version : `1.5.6`

These are the commands that i used :
~~~
virtualenv venv
source venv/bin/activate
pip install --upgrade setuptools
pip install rekall
~~~

And this the output that i get after running `pip install rekall` :

~~~
Downloading/unpacking rekall
  Running setup.py (path:/tmp/pip-build-4rNKTc/rekall/setup.py) egg_info for package rekall
    
    warning: no files found matching '*' under directory 'test_data'
    warning: no previously-included files matching '*.a' found under directory 'tools'
    warning: no previously-included files matching '*.la' found under directory 'tools'
    warning: no previously-included files matching '*.lo' found under directory 'tools'
    warning: no previously-included files matching '*.o' found under directory 'tools'
    warning: no previously-included files matching '*' found under directory '.git'
    warning: no previously-included files matching '*' found under directory 'build'
    warning: no previously-included files matching '*' found under directory 'tools/pmem/.deps'
    warning: no previously-included files found matching 'tools/pmem/linpmem'
Downloading/unpacking rekall-core>=1.5.0 (from rekall)
  Running setup.py (path:/tmp/pip-build-4rNKTc/rekall-core/setup.py) egg_info for package rekall-core
    
    warning: no previously-included files matching '*' found under directory '.git'
    warning: no previously-included files matching '*' found under directory 'build'
    warning: no previously-included files matching '*.pyc' found under directory 'rekall'
    warning: no previously-included files matching '*.a' found under directory 'tools'
    warning: no previously-included files matching '*.la' found under directory 'tools'
    warning: no previously-included files matching '*.lo' found under directory 'tools'
    warning: no previously-included files matching '*.o' found under directory 'tools'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '*.pyc'
  Invalid requirement: u'efilter == 1!1.3' (("Expected ',' or end-of-list in", u'efilter == 1!1.3', 'at', u'!1.3')) in requirement rekall-core>=1.5.0 (from rekall)
Downloading/unpacking ipython>=4.1.2,<5.0 (from rekall)
....
~~~

We can see here that there is an error with `efilter` :
~~~
Invalid requirement: u'efilter == 1!1.3' (("Expected ',' or end-of-list in", u'efilter == 1!1.3', 'at', u'!1.3')) in requirement rekall-core>=1.5.0 (from rekall)
~~~

And in fact, when i try to use rekall, i have an import error related to `efilter` :

~~~
Traceback (most recent call last):
  File "./script.py", line 23, in <module>
    from rekall import plugins
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/__init__.py", line 10, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/ewf.py", line 27, in <module>
    from rekall.plugins.tools import ewf
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/tools/__init__.py", line 36, in <module>
    from rekall.plugins.tools import profile_tool
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 102, in <module>
    from rekall.plugins.common import profile_index
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/common/__init__.py", line 6, in <module>
    from rekall.plugins.common import efilter_plugins
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/common/efilter_plugins/__init__.py", line 1, in <module>
    from rekall.plugins.common.efilter_plugins import info
  File "/home/developer/project01/venv/local/lib/python2.7/site-packages/rekall/plugins/common/efilter_plugins/info.py", line 20, in <module>
    from efilter.protocols import structured
ImportError: No module named efilter.protocols
~~~

So is this a python packaging error ?

Thanks !

**Comment by scudette** [comment]
please upgrade your pip package first (you should also try to run a
more recent python version since this one might not support ssl
properly):

pip install --upgrade pip setuptools

**Comment by Wenzel** [comment]
Hi !
Upgrading pip solved the issue :)

Thanks for your quick reply !
