### ISSUE TITLE
Error running psscan on Windows 10 v1607

### ISSUE THREAD

**Issue by jtsylve** [google/rekall#174]
```
rekal --version
This is Rekall Version 1.5.3 (Furka)
{'revisionid': 'd57800c45b71ad3f0522a63f187e5bb6513f1bc0', 'pep440': u'1.5.3', 'dev': None, u'version': u'1.5.3', 'dirty': False, u'rc': u'0', u'codename': u'Furka', u'post': u'0'}
```

```
2016-08-15 16:44:24,872:WARNING:rekall.1:Buffer has no offset in object _UNICODE_STRING. Check that vtypes has a concrete definition for it.
2016-08-15 16:44:24,873:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
    for row in self.collect():
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/filescan.py", line 417, in collect
    for run in self.generate_memory_ranges():
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 570, in generate_memory_ranges
    for pool in pool_plugin.find_non_paged_pool():
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/pool.py", line 109, in find_non_paged_pool
    "nt!MmNonPagedPoolStart", "Pointer").v()
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/common/address_resolver.py", line 220, in get_constant_object
    self._EnsureInitialized()
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 306, in _EnsureInitialized
    KernelModule(ldr_module=ldr_entry, session=self.session))
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 232, in __init__
    self.filename = ldr_module.filename or ldr_module.name
  File "/usr/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/overlays/windows/common.py", line 623, in filename
    return object_tree_plugin.FileNameWithDrive(unicode(self.FullDllName))
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/overlays/windows/common.py", line 668, in __unicode__
    return self.v().strip("\x00") or u""
  File "/usr/local/lib/python2.7/site-packages/rekall/plugins/overlays/windows/common.py", line 651, in v
    data = self.Buffer.dereference_as(
  File "/usr/local/lib/python2.7/site-packages/rekall/obj.py", line 1433, in __getattr__
    raise AttributeError(attr)
RuntimeError: AttributeError raised: Buffer
```

**Comment by scudette** [comment]
This bug should now be fixed after the commit of https://github.com/google/rekall/commit/89b67aed60fb989e6448b6b926527fb32003c52f
