### ISSUE TITLE
Win 10 PDB not found (404) - Loop

### ISSUE THREAD

**Issue by Fetchered** [google/rekall#175]
Using Win 10 Home - 1511
OS Build 10586.545
WinPmem 2.1 post 4
Rekall 1.52 Furka x64
Mem dump is Win 10x64 - filename mem.raw (--format raw with winpmem)
Receiving following error:

[1] mem.raw 21:02:35> pslist
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntoskrnl.pdb/DDA2B202016-08-16 21:02:49,158:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/DDA2B202016-08-16 21:02:49,394:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/DDA2B202016-08-16 21:02:49,638:ERROR:rekall.1:Error: HTTP Error 404: Not Found
Microsoft (R) File Expansion Utility  Version 10.0.10011.16384
Copyright (c) Microsoft Corporation. All rights reserved.

Adding c:\users\fetch\appdata\local\temp\tmpbfp8ia\ntkrnlmp.pdb to Extraction Queue

Expanding Files ....

Expanding Files Complete ...
2016-08-16 21:03:19,134:WARNING:rekall.1:Profile nt/GUID/DDA2B209BF8B4F469DD9A61ABEF7DEA71 fetched and built. Please consider reporting this profile to the Rekall team so we may add it to the public profile repository.
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntoskrnl.pdb/DDA2B202016-08-16 21:03:20,259:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/DDA2B202016-08-16 21:03:20,500:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/DDA2B202016-08-16 21:03:20,736:ERROR:rekall.1:Error: HTTP Error 404: Not Found
Microsoft (R) File Expansion Utility  Version 10.0.10011.16384
Copyright (c) Microsoft Corporation. All rights reserved.

Adding c:\users\fetch\appdata\local\temp\tmpum8zt9\ntkrnlmp.pdb to Extraction Queue

And it just repeats itself over and over.

**Comment by scudette** [comment]
It is likely that this is not the correct GUID for your image so Rekall is fetching it locally, then it does not validate so it keeps trying. It should probably give up when it does not validate correctly.

It is common for there to be several signatures in the same image. You must remember that when Rekall is opening an image in RAW format it has to guess the correct GUID and this is error prone. This is why you should generally avoid RAW images. You can force it to use a certain profile if you know what the GUID should be. You can get the correct GUID by actually copying out the kernel file from the machine during acquisition (most reliable method) or you can run version_scan on the raw image:

```
$ rekal -f ~/images/win7.elf version_scan --name_regex krnl
  Offset (P)             GUID/Version                         PDB
-------------- --------------------------------- ------------------------------
     0x27bb5fc F8E2A8B5C9B74BF4A6E4A48F180099942 ntkrnlmp.pdb
```

I suspect there may be several hits, and one of them will be the correct one. You can force Rekall to use a certain profile using the --profile flag:

```
$ rekal -f ~/images/win7.elf --profile nt/GUID/F8E2A8B5C9B74BF4A6E4A48F180099942 pslist
  _EPROCESS            Name          PID   PPID   Thds    Hnds    Sess  Wow64           Start                     Exit          
-------------- -------------------- ----- ------ ------ -------- ------ ------ ------------------------ ------------------------
0xfa80008959e0 System                   4      0     84      511      - False  2012-10-01 21:39:51Z     -                       
0xfa80024f85d0 svchost.exe            236    480     19      455      0 False  2012-10-01 14:40:01Z     -                       
0xfa8001994310 smss.exe               272      4      2       29      - False  2012-10-01 21:39:51Z     - 
```

**Comment by Fetchered** [comment]
I tried using the GUID which the version_scan provided.
0x14ffaf674 DDA2B209BF8B4F469DD9A61ABEF7DEA71 ntkrnlmp.pdb
However that still gave me the 404 not found error.

I guess what I need to resolve first is, how to get the correct pdb files from the Symbols db when rekall keeps giving me a 404 error. When I attempt to access the URL giving me the issue, http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/DDA2B20, it doesn't exist, however the same URL with https does. How do I change where rekall fetches the symbols from so I can attempt to update the URL?

**Comment by shiftykey** [comment]
I'm having the same issue. Can't find the online symbol files.

**Comment by scudette** [comment]
MS has been making some changes to the symbol server in recent times. Maybe the URL must now be over SSL

https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/tools/mspdb.py#L121

@shiftykey  can you please try to see if changing the URL to https helps? Also are you using the latest Rekall release or git head? This might be related to https://github.com/google/rekall/issues/298

**Comment by 31bbb** [comment]
I am also running into this issue:
```
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntoskrnl.pdb/14113F38C1934DC7B3C1DC98ACC6B2152/ntoskrnl.pdb
2018-10-13 11:02:58,482:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/14113F38C1934DC7B3C1DC98ACC6B2152/ntkrnlpa.pdb  
2018-10-13 11:02:58,729:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/14113F38C1934DC7B3C1DC98ACC6B2152/ntkrpamp.pdb  
2018-10-13 11:03:02,399:DEBUG:rekall.1:Opened local file /home/a/Desktop/rekall-profiles/v1.0/mspdb.gz
```

I am using the latest release of rekall:
```
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).
```

I decided to cut from `master@rekall`, and same thing:
```
$ rekal -f ../mem 
No handlers could be found for logger "rekall.plugins.tools"

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.3.dev37 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] mem 11:09:42> pslist
2018-10-13 11:09:44,996:WARNING:rekall.1:UserAndGroups has no offset in object _TOKEN. Check that vtypes has a concrete definition for it.
----------------> pslist()
_EPROCESS          name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
---------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
2018-10-13 11:09:45,040:ERROR:rekall.1:Instantiating a Struct class _LIST_ENTRY without an overlay. Please ensure an overlay is defined.
2018-10-13 11:09:45,041:WARNING:rekall.1:ExitTime has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:VadRoot has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:CreateTime has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:Token has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:Session has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:InheritedFromUniqueProcessId has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:UniqueProcessId has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,041:WARNING:rekall.1:ImageFileName has no offset in object _EPROCESS. Check that vtypes has a concrete definition for it.
2018-10-13 11:09:45,042:ERROR:rekall.1:Instantiating a Struct class _LIST_ENTRY without an overlay. Please ensure an overlay is defined.
2018-10-13 11:09:45,042:ERROR:rekall.1:Instantiating a Struct class _HANDLE_TABLE without an overlay. Please ensure an overlay is defined.
Out<11:09:45> Plugin: pslist (WinPsList)
```

```
$ cat ~/.rekallrc 
cache_dir: .rekall_cache
repository_path:
- https://github.com/google/rekall-profiles/raw/master
- http://profiles.rekall-forensic.com
```

I purge: `$ rm -rf ~/.rekall*`

I then specify profiles manually:

```
$ rekal -v -f ../mem --repository_path /home/a/Desktop/rekall-profiles/
No handlers could be found for logger "rekall.plugins.tools"
2018-10-13 11:11:49,617:DEBUG:rekall.1:Logging level set to 10
2018-10-13 11:11:49,619:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': None})
```

Notice that profiles still set to `None`; this is a 32-bit Windows 7.

Still failing on downloading symbols:
```
2018-10-13 11:12:23,065:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/14113F38C1934DC7B3C1DC98ACC6B2152/ntkrnlpa.pdb
2018-10-13 11:12:23,235:ERROR:rekall.1:Error: HTTP Error 404: Not Found
```

It has fortunately gotten further when using `pslist`:

```
----------------> pslist()
2018-10-13 11:13:00,197:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({})
_EPROCESS          name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
---------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
2018-10-13 11:13:00,286:DEBUG:rekall.1:Listed 36 processes using PsActiveProcessHead
2018-10-13 11:13:01,320:DEBUG:rekall.1:Listed 32 processes using CSRSS
2018-10-13 11:13:01,769:DEBUG:rekall.1:Listed 36 processes using PspCidTable
2018-10-13 11:13:01,798:DEBUG:rekall.1:Listed 34 processes using Sessions
2018-10-13 11:13:01,896:DEBUG:rekall.1:Listed 35 processes using Handles
0x83d33860 System                   4      0           70          510          - False  2018-10-13 16:15:51Z     -                       
0x843e0170 smss.exe               216      4            2           29          - False  2018-10-13 16:15:51Z     -                       
0x84ac24c8 csrss.exe              284    276            8          332          0 False  2018-10-13 16:15:51Z     -                       
0x84df79d8 svchost.exe            324    428            5           97          0 False  2018-10-13 13:15:57Z     -                       
0x84ae6328 wininit.exe            332    276            3           77          0 False  2018-10-13 16:15:52Z     -                       
0x84ae85e0 csrss.exe              340    324            8          359          1 False  2018-10-13 16:15:52Z     -                       
0x84af4128 winlogon.exe           368    324            3          111          1 False  2018-10-13 16:15:52Z     -                       
0x84b1cd20 services.exe           428    332            9          190          0 False  2018-10-13 16:15:52Z     -                       
0x84b27d20 lsass.exe              436    332            7          552          0 False  2018-10-13 16:15:52Z     -                       
0x84b29d20 lsm.exe                444    332           10          143          0 False  2018-10-13 16:15:52Z     -                       
0x84e675c8 powershell.exe         508   1340            6          519          1 False  2018-10-13 13:50:56Z     -                       
0x84b5c938 svchost.exe            552    428           10          344          0 False  2018-10-13 16:15:52Z     -                       
0x84b62358 VBoxService.ex         612    428           12          120          0 False  2018-10-13 16:15:52Z     -                       
0x84b71140 svchost.exe            676    428            7          235          0 False  2018-10-13 13:15:54Z     -                       
0x84b96b48 svchost.exe            740    428           19          441          0 False  2018-10-13 13:15:54Z     -                       
0x84ba5958 svchost.exe            808    428           15          365          0 False  2018-10-13 13:15:54Z     -                       
0x84badbb0 svchost.exe            836    428           13          318          0 False  2018-10-13 13:15:54Z     -                       
0x84bbdd20 svchost.exe            864    428           30         1032          0 False  2018-10-13 13:15:54Z     -                       
0x84c10380 svchost.exe           1112    428           13          347          0 False  2018-10-13 13:15:54Z     -                       
0x84ae3030 dwm.exe               1276    808            3           71          1 False  2018-10-13 13:15:55Z     -                       
0x84c6a698 spoolsv.exe           1312    428           14          280          0 False  2018-10-13 13:15:55Z     -                       
0x84c6db28 taskhost.exe          1320    428            9          241          1 False  2018-10-13 13:15:55Z     -                       
0x84c74d20 explorer.exe          1340   1268           30          885          1 False  2018-10-13 13:15:55Z     -                       
0x84c90ca0 svchost.exe           1400    428           17          298          0 False  2018-10-13 13:15:55Z     -                       
0x83df6030 SearchIndexer.        1424    428           11          640          0 False  2018-10-13 13:16:01Z     -                       
0x84d04d20 VBoxTray.exe          1560   1340           13          152          1 False  2018-10-13 13:15:55Z     -                       
0x84d2a4b8 svchost.exe           1660    428           10          140          0 False  2018-10-13 13:15:56Z     -                       
0x84d3b400 svchost.exe           1716    428            8          159          0 False  2018-10-13 13:15:56Z     -                       
0x8409c658 rekal.exe             2280   1340          107          608          1 False  2018-10-13 13:18:12Z     -                       
0x840e6030 conhost.exe           2324    340            2           53          1 False  2018-10-13 13:18:12Z     -                       
0x84e2d9c8 wuauclt.exe           2900    864            3           87          1 False  2018-10-13 13:18:59Z     -                       
0x83edf468 conhost.exe           3116    340            2           56          1 False  2018-10-13 13:50:56Z     -                       
0x84f8a5f8 bhvpbpv.exe           3400   3364            6          250          1 False  2018-10-13 13:17:32Z     -                       
0x84e2dcd8 winpmem-2.1.po        3540    508            1           45          1 False  2018-10-13 13:57:34Z     -                       
0x8410f518 audiodg.exe           3572    740            4          121          0 False  2018-10-13 13:56:29Z     -                       
0x840e1030 svchost.exe           4092    428           12          362          0 False  2018-10-13 13:17:57Z     -                       
Out<11:13:02> Plugin: pslist (WinPsList)
```

**Comment by mikesimone** [comment]
So, I've tried editing it to https in the mspdb.py file, but I can't seem to get it to compile to an executable and replace my existing one. I've cloned the latest 1.7.3 github, I've created my virtualenv, and I see it create eggs and stuff, but I can't get any of it to run. Any chance a new build with it updated and pre-compiled is on the way soon?

**Comment by DaveCLowe** [comment]
Windows 7 image =-
Sorry, but same issue here where there's a 404 on the PDB 
http://msdl.microsoft.com/download/symbols/ntoskrnl.pdb/4EC39E6D760F4A26A5192B89B2E0158E1/ntoskrnl.pd_

nonroot@8b3e74444169:~/files$ rekall -f memdump.raw version_scan --name_regex krnl
  Offset (P)             GUID/Version                         PDB
-------------- --------------------------------- ------------------------------
0x000002861590 4EC39E6D760F4A26A5192B89B2E0158E1 ntkrnlmp.pdb
0x0000c908d6c0 D372A6779D6643FAB5F8CA3D0C2E2CB01 ntoskrnl.pdb
nonroot@8b3e74444169:~/files$ rekall -f memdump.raw --profile nt/GUID/4EC39E6D760F4A26A5192B89B2E0158E1 pslist
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntoskrnl.pdb/4EC39E6D760F4A26A5192B89B2E0158E1/ntoskrnl.pd_
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 9, in <module>
    load_entry_point('rekall==1.3.2', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 59, in main
    user_session=user_session)
  File "/usr/local/lib/python2.7/dist-packages/rekall/args.py", line 415, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 98, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 349, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/windows/common.py", line 62, in is_active
    return (super(AbstractWindowsCommandPlugin, cls).is_active(session) and
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 198, in is_active
    session.profile != None)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 784, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 519, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 547, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/guess_profile.py", line 495, in calculate
    profile_obj = self.ScanProfiles()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/guess_profile.py", line 441, in ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/guess_profile.py", line 295, in DetectFromHit
    profile = self.VerifyProfile("nt/GUID/%s" % rsds.GUID_AGE)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/guess_profile.py", line 279, in VerifyProfile
    build_local_profile.fetch_and_parse(profile_name)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/profile_tool.py", line 773, in fetch_and_parse
    data = self._fetch_and_parse(module_name, guid)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/profile_tool.py", line 737, in _fetch_and_parse
    module_name, guid))
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 212, in FetchPDBFile
    cwd=temp_dir)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by hehnope** [comment]
@DaveCLowe just use SIFT workstation. I know that isnt a valid solution, but SIFT actually works properly.

**Comment by scudette** [comment]
I have no problems downloading the actual pdb:
```
$ rekal fetch_pdb ntkrnlmp 4EC39E6D760F4A26A5192B89B2E0158E1  -v
Webconsole disabled: cannot import name 'webconsole_plugin'
2019-03-27 15:45:31,883:DEBUG:rekall.1:Logging level set to 10
2019-03-27 15:45:31,886:DEBUG:rekall.1:Running plugin (fetch_pdb) with args (()) kwargs ({'pdb_filename': 'ntkrnlmp', 'guid': '4EC39E6D760F4A26A5192B89B2E0158E1', 'dump_dir': None, 'verbosity': 1})
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/4EC39E6D760F4A26A5192B89B2E0158E1/ntkrnlmp.pdb
```

It would be helpful to see debugging messages if you run it with -v flag. Otherwise just download the pdb manually then parse it into a profile and use that. Make sure you use a recent rekall too - the MS symbol server protocol has changed.

**Comment by DaveCLowe** [comment]
Thanks @scudette - fixed in newer version. The docker images on the public docker registry are using an older version. 

Working path:
http://msdl.microsoft.com/download/symbols/**ntkrnlmp**.pdb/4EC39E6D760F4A26A5192B89B2E0158E1/ntkrnlmp.pdb

Old version path:
http://msdl.microsoft.com/download/symbols/**ntoskrnl**.pdb/4EC39E6D760F4A26A5192B89B2E0158E1/ntoskrnl.**pd_**
