### ISSUE TITLE
error: unrecognized arguments: --profile

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#187]
# rekall  -f /dev/mem aff4acquire /mnt/sda1/wi.aff4 --profile tools/linux/4.1.3-smp-wifislax.json 
    usage: rekall [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F FORMAT]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
              [--logging_format LOGGING_FORMAT]
              [--performance {normal,fast,thorough}]
              [--live [{API,Memory} [{API,Memory} ...]]] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--highlighting_style {manni,igor,lovelace,xcode,vim,autumn,vs,rrt,native,perldoc,borland,tango,emacs,friendly,monokai,paraiso-dark,colorful,murphy,bw,pastie,algol_nu,paraiso-light,trac,default,algol,fruity}]
              [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
              [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
              [--pagefile [PAGEFILE [PAGEFILE ...]]]
              [--autodetect {linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
              [--autodetect_threshold AUTODETECT_THRESHOLD]
              [--autodetect_build_local {full,basic,none}]
              [--autodetect_scan_length AUTODETECT_SCAN_LENGTH] [--version]
              [-] [--compression COMPRESSION] [--append] [--also_memory]
              [--also_mapped_files] [--also_pagefile]
              [--files [FILES [FILES ...]]] [--max_file_size MAX_FILE_SIZE]
              [--gce_credentials GCE_CREDENTIALS]
              [--gce_credentials_path GCE_CREDENTIALS_PATH]
              destination
    rekall: error: unrecognized arguments: --profile tools/linux/4.1.3-smp-wifislax.json

**Comment by scudette** [comment]
The aff4acquire plugin does not take a profile arg. Does it not work without providing the profile?

**Comment by fpusersuggest** [comment]
here is the output of:

    # rekal -f /dev/mem aff4acquire /mnt/sda1/wi.aff4
    2016-10-03 14:56:45,201:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
    2016-10-03 14:56:47,825:ERROR:rekall.1:No profiles match this image. Try specifying manually.
    2016-10-03 14:56:47,842:CRITICAL:rekall.1:Traceback (most recent call last):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
        for row in self.collect():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 573, in collect
        for x in self.collect_acquisition():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 592, in collect_acquisition
        for x in self._collect_acquisition(output_urn=output_urn):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 640, in _collect_acquisition
        resolver, volume, file_globs):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 522, in copy_files
        for x in self._copy_file_to_image(resolver, volume, path):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 432, in _copy_file_to_image
        if self.session.profile.metadata("os") == "windows":
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 1056, in profile
        res = self.GetParameter("profile_obj")
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 762, in GetParameter
        result = self._RunParameterHook(item)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 797, in _RunParameterHook
        result = hook.calculate()
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 830, in calculate
        "Unable to find a valid profile for this image. "
    RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
    
    Will use compression: https://github.com/google/snappy
    Imaging Physical Memory:
    Wrote 0 mb of Physical Memory to aff4://668584d3-2ce9-438d-8844-453c73c7557b/PhysicalMemory
    Adding file /proc/kallsyms
    2016-10-03 14:56:47,843:CRITICAL:root:Unable to find a valid profile for this image. Try using -v for more details.. Try --debug for more information.
    Traceback (most recent call last):
      File "/home/rekal/venv/bin/rekal", line 11, in <module>
        sys.exit(main())
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
        user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 863, in RunPlugin
        self._HandleRunPluginException(ui_renderer, e)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
        for row in self.collect():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 573, in collect
        for x in self.collect_acquisition():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 592, in collect_acquisition
        for x in self._collect_acquisition(output_urn=output_urn):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 640, in _collect_acquisition
        resolver, volume, file_globs):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 522, in copy_files
        for x in self._copy_file_to_image(resolver, volume, path):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 432, in _copy_file_to_image
        if self.session.profile.metadata("os") == "windows":
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 1056, in profile
        res = self.GetParameter("profile_obj")
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 762, in GetParameter
        result = self._RunParameterHook(item)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 797, in _RunParameterHook
        result = hook.calculate()
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 830, in calculate
        "Unable to find a valid profile for this image. "
    RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.


Also [here](https://github.com/google/rekall/tree/master/tools/linux) you say to use  --profile option..

**Comment by scudette** [comment]
The /dev/mem file is not usable by Rekall - We normally use /proc/kcore. You dont really need to specify this anyway:

```
rekall --live - aff4acquire /mnt/sda1/wi.aff4
or 
rekall -f /proc/kcore aff4acquire /mnt/sda1/wi.aff4
```

Should work.

The link you referred to says to specify the profile if you want to analyse the system (i.e this drops you into the interactive shell where you might run plugins which need the profile):

```
bash$ rekal.py --profile Ubuntu-3.8.0-34-generic.json -f my_image.dd
```

**Comment by fpusersuggest** [comment]
# rekall --live - aff4acquire /mnt/sda1/wi.aff4
    2016-10-04 13:50:23,795:CRITICAL:rekall.1:Traceback (most recent call last):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
        for row in self.collect():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 569, in collect
        for x in self.collect_acquisition():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 592, in collect_acquisition
        for x in self._collect_acquisition(output_urn=output_urn):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 620, in _collect_acquisition
        resolver, volume):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 313, in copy_physical_address_space
        total_length = self._WriteToTarget(resolver, source, image_stream)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 335, in _WriteToTarget
        image_stream.WriteStream(helper_map, progress=progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 348, in WriteStream
        _MapStreamHelper(self.resolver, source, self), progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 107, in __init__
        raise RuntimeError("Source map is empty when calling WriteStream()")
    RuntimeError: Source map is empty when calling WriteStream()
    
    Will use compression: https://github.com/google/snappy
    Will load physical address space from live plugin.
    Imaging Physical Memory:
    2016-10-04 13:50:23,795:CRITICAL:root:Source map is empty when calling WriteStream(). Try --debug for more information.
    Traceback (most recent call last):
      File "/home/rekal/venv/bin/rekall", line 11, in <module>
        sys.exit(main())
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
        user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 863, in RunPlugin
        self._HandleRunPluginException(ui_renderer, e)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
        for row in self.collect():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 569, in collect
        for x in self.collect_acquisition():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 592, in collect_acquisition
        for x in self._collect_acquisition(output_urn=output_urn):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 620, in _collect_acquisition
        resolver, volume):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 313, in copy_physical_address_space
        total_length = self._WriteToTarget(resolver, source, image_stream)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 335, in _WriteToTarget
        image_stream.WriteStream(helper_map, progress=progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 348, in WriteStream
        _MapStreamHelper(self.resolver, source, self), progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 107, in __init__
        raise RuntimeError("Source map is empty when calling WriteStream()")
    RuntimeError: Source map is empty when calling WriteStream()


    # rekall -f /proc/kcore aff4acquire /mnt/sda1/wi.aff4
        2016-10-04 13:53:43,006:CRITICAL:rekall.1:Traceback (most recent call last):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
        for row in self.collect():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 573, in collect
        for x in self.collect_acquisition():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 592, in collect_acquisition
        for x in self._collect_acquisition(output_urn=output_urn):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 620, in _collect_acquisition
        resolver, volume):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 313, in copy_physical_address_space
        total_length = self._WriteToTarget(resolver, source, image_stream)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 335, in _WriteToTarget
        image_stream.WriteStream(helper_map, progress=progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 348, in WriteStream
        _MapStreamHelper(self.resolver, source, self), progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 107, in __init__
        raise RuntimeError("Source map is empty when calling WriteStream()")
    RuntimeError: Source map is empty when calling WriteStream()
    
    Will use compression: https://github.com/google/snappy
    Imaging Physical Memory:
    2016-10-04 13:53:43,006:CRITICAL:root:Source map is empty when calling WriteStream(). Try --debug for more information.
    Traceback (most recent call last):
      File "/home/rekal/venv/bin/rekall", line 11, in <module>
        sys.exit(main())
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
        user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 863, in RunPlugin
        self._HandleRunPluginException(ui_renderer, e)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
        for row in self.collect():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 573, in collect
        for x in self.collect_acquisition():
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 592, in collect_acquisition
        for x in self._collect_acquisition(output_urn=output_urn):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 620, in _collect_acquisition
        resolver, volume):
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 313, in copy_physical_address_space
        total_length = self._WriteToTarget(resolver, source, image_stream)
      File "/home/rekal/venv/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 335, in _WriteToTarget
        image_stream.WriteStream(helper_map, progress=progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 348, in WriteStream
        _MapStreamHelper(self.resolver, source, self), progress)
      File "/home/rekal/venv/lib/python2.7/site-packages/pyaff4/aff4_map.py", line 107, in __init__
        raise RuntimeError("Source map is empty when calling WriteStream()")
    RuntimeError: Source map is empty when calling WriteStream()


this issue is the same as #160
