### ISSUE TITLE
TypeError while collecting "PythonDistInfo" with artifact_collector

### ISSUE THREAD

**Issue by raviteja7** [google/rekall#197]
Hi Michael
I built the profile from the precompiled kernel module using convert_profile. When I run artifact_collector with PythonDistInfo, I am receiving a type error.

(venv) root@vps325778:~# rekal -p 4.4.0-22-generic.json --live Memory --debug -v
2016-10-11 23:56:24,938:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2016-10-11 23:56:24,938:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2016-10-11 23:56:24,938:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2016-10-11 23:56:24,939:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2016-10-11 23:56:24,940:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
2016-10-11 23:56:24,940:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2016-10-11 23:56:24,941:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-10-11 23:56:24,941:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2016-10-11 23:56:24,941:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-10-11 23:56:24,941:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2016-10-11 23:56:24,942:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-10-11 23:56:24,942:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2016-10-11 23:56:24,942:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-10-11 23:56:24,943:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2016-10-11 23:56:24,948:DEBUG:rekall.1:Succeeded instantiating KCoreAddressSpace
2016-10-11 23:56:24,948:DEBUG:rekall.1:Voting round with base: KCoreAddressSpace
2016-10-11 23:56:24,949:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2016-10-11 23:56:24,949:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2016-10-11 23:56:24,949:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2016-10-11 23:56:24,950:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2016-10-11 23:56:24,950:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2016-10-11 23:56:24,950:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-10-11 23:56:24,951:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2016-10-11 23:56:24,951:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-10-11 23:56:24,951:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2016-10-11 23:56:24,951:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-10-11 23:56:24,951:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2016-10-11 23:56:24,952:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-10-11 23:56:24,952:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2016-10-11 23:56:24,952:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2016-10-11 23:56:24,952:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2016-10-11 23:56:24,952:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2016-10-11 23:56:24,952:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2016-10-11 23:56:24,953:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2016-10-11 23:56:24,953:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2016-10-11 23:56:24,953:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2016-10-11 23:56:24,953:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2016-10-11 23:56:24,954:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2016-10-11 23:56:24,954:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2016-10-11 23:56:24,954:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2016-10-11 23:56:24,954:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2016-10-11 23:56:24,955:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2016-10-11 23:56:24,955:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2016-10-11 23:56:24,955:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2016-10-11 23:56:24,955:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2016-10-11 23:56:24,955:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2016-10-11 23:56:24,955:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2016-10-11 23:56:24,956:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2016-10-11 23:56:24,957:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2016-10-11 23:56:24,957:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2016-10-11 23:56:24,957:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2016-10-11 23:56:24,957:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2016-10-11 23:56:24,957:INFO:rekall.1:Autodetected physical address space KCoreAddressSpace
2016-10-11 23:56:24,959:DEBUG:rekall.1:Logging level set to 10
2016-10-11 23:56:24,960:DEBUG:rekall.1:Opened local file /root/4.4.0-22-generic.json
2016-10-11 23:56:25,765:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': '4.4.0-22-generic.json'})

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.5.3.post1.dev8 (Furka).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] Live(/proc/kcore) 23:56:37> artifact_collector("PythonModuleInfo")
2016-10-11 23:56:37,546:DEBUG:rekall.1:Running plugin (artifact_collector) with args (('PythonModuleInfo',)) kwargs ({})
2016-10-11 23:56:38,580:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-10-11 23:56:39,971:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/artifacts.gz
2016-10-11 23:56:40,175:DEBUG:rekall.1:Skipping Artifact OSXUsers: Definition OSXUsers: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,176:DEBUG:rekall.1:Skipping Artifact OSXUserDownloadsDirectory: Definition OSXUserDownloadsDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,176:DEBUG:rekall.1:Skipping Artifact OSXUserDocumentsDirectory: Definition OSXUserDocumentsDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,176:DEBUG:rekall.1:Skipping Artifact OSXUserMusicDirectory: Definition OSXUserMusicDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,176:DEBUG:rekall.1:Skipping Artifact OSXUserDesktopDirectory: Definition OSXUserDesktopDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,177:DEBUG:rekall.1:Skipping Artifact OSXUserLibraryDirectory: Definition OSXUserLibraryDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,177:DEBUG:rekall.1:Skipping Artifact OSXUserMoviesDirectory: Definition OSXUserMoviesDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,177:DEBUG:rekall.1:Skipping Artifact OSXUserPicturesDirectory: Definition OSXUserPicturesDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,177:DEBUG:rekall.1:Skipping Artifact OSXUserPublicDirectory: Definition OSXUserPublicDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,177:DEBUG:rekall.1:Skipping Artifact OSXApplications: Definition OSXApplications: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,178:DEBUG:rekall.1:Skipping Artifact OSXApplicationSupport: Definition OSXApplicationSupport: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,179:DEBUG:rekall.1:Skipping Artifact OSXLoadedKexts: Definition OSXLoadedKexts: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,179:DEBUG:rekall.1:Skipping Artifact OSXMountedDMGs: Definition OSXMountedDMGs: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,180:DEBUG:rekall.1:Skipping Artifact IPTablesRules: Definition IPTablesRules: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,181:DEBUG:rekall.1:Skipping Artifact LinuxMountCmd: Definition LinuxMountCmd: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,181:DEBUG:rekall.1:Skipping Artifact ListProcessesPsCommand: Definition ListProcessesPsCommand: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,181:DEBUG:rekall.1:Skipping Artifact LoadedKernelModules: Definition LoadedKernelModules: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,183:DEBUG:rekall.1:Skipping Artifact LinuxSysctlCmd: Definition LinuxSysctlCmd: No supported sources: [u'COMMAND']
2016-10-11 23:56:40,188:DEBUG:rekall.1:Skipping Artifact WindowsUserDownloadsDirectory: Definition WindowsUserDownloadsDirectory: No supported sources: [u'DIRECTORY']
2016-10-11 23:56:40,190:INFO:rekall.1:Loaded profile artifacts from URL:https://github.com/google/rekall-profiles/raw/master (in 1.2447309494 sec)
--------------------------
Artifact: PythonModuleInfo
--------------------------
------------------------
Artifact: PythonDistInfo
------------------------
2016-10-11 23:56:40,427:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/root/rekall/rekall-core/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/root/rekall/rekall-core/rekall/plugin.py", line 720, in render
    for row in self.collect():
  File "/root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py", line 935, in collect
    for x in self._collect():
  File "/root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py", line 940, in _collect
    for hit in self.collect_artifact(artifact_name):
  File "/root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py", line 909, in collect_artifact
    collector=self):
  File "/root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py", line 482, in apply
    for result in collector.collect_artifact(name):
  File "/root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py", line 909, in collect_artifact
    collector=self):
  File "/root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py", line 466, in apply
    row[name] = type(info[name])
TypeError: 'FileInformation' object has no attribute '__getitem__'

> /root/rekall/rekall-core/rekall/plugins/response/forensic_artifacts.py(466)apply()
-> row[name] = type(info[name])
(Pdb)

I tested the same on a different box (kernel version 3.19.0-42) and it worked fine

Thanks

**Comment by scudette** [comment]
Thanks for reporting. I am working on the artifacts system as we speak (hence this breakage) and will have a fix out to this shortly.

**Comment by raviteja7** [comment]
It works now. Thanks
