### ISSUE TITLE
Ensure cabextract is installed.

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#205]
HI, I have a windows 10 memory sample that I am trying to analyze from a linux box. The problem is that it does not find the cabextract command which is installed.
The folloing is the error:

      
    /tmp/tmpeKQ8Sk/ntdll.pd_: no valid cabinets found
    
    All done, errors in processing 1 file(s)
    2016-10-20 12:28:26,807:CRITICAL:rekall.1:Traceback (most recent call last):
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugin.py", line 701, in render
        renderer.table_row(*new_row, **row)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1400, in table_row
        super(TextRenderer, self).table_row(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/renderer.py", line 493, in table_row
        self.table.render_row(row=row, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1141, in render_row
        return self.write_row(self.get_row(*row, **options),
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1131, in get_row
        result.append(c.render_row(x, **options))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1035, in render_row
        result = object_renderer.render_row(target, **merged_opts)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 442, in render_row
        cell = method(target, **options)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/renderers/base_objects.py", line 237, in render_full
        instruction.address, instruction.hexbytes, instruction.text)))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 177, in text
        canonical = self.GetCanonical()
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 162, in GetCanonical
        operands=self.operands)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 131, in operands
        self._comment = self.format_indirect(target, op.size)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 199, in format_indirect
        target_name = ", ".join(self.resolver.format_address(target))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/common/address_resolver.py", line 314, in format_address
        address, max_distance=max_distance)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/common/address_resolver.py", line 331, in get_nearest_constant_by_address
        if module.profile != None:
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 176, in profile
        return self.load_profile(force=False)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 183, in load_profile
        self.build_local_profile(profile_name, force=force))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 136, in build_local_profile
        build_local_profile.fetch_and_parse(profile_name)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1217, in fetch_and_parse
        data = self._fetch_and_parse(module_name, guid)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1188, in _fetch_and_parse
        outfd.write(fetch_pdb_plugin.FetchPDBFile())
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 211, in FetchPDBFile
        "Ensure cabextract is installed.\n" % output_file)
    RuntimeError: Failed to decompress output file /tmp/tmpeKQ8Sk/ntdll.pdb. Ensure cabextract is installed.
    
    
    2016-10-20 12:28:26,808:CRITICAL:root:Failed to decompress output file /tmp/tmpeKQ8Sk/ntdll.pdb. Ensure cabextract is installed.
    . Try --debug for more information.
    Traceback (most recent call last):
      File "/home/mylinuxuser/virtualenv/reakall/bin/rekal", line 11, in <module>
        sys.exit(main())
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
        user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/session.py", line 863, in RunPlugin
        self._HandleRunPluginException(ui_renderer, e)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugin.py", line 701, in render
        renderer.table_row(*new_row, **row)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1400, in table_row
        super(TextRenderer, self).table_row(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/renderer.py", line 493, in table_row
        self.table.render_row(row=row, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1141, in render_row
        return self.write_row(self.get_row(*row, **options),
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1131, in get_row
        result.append(c.render_row(x, **options))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 1035, in render_row
        result = object_renderer.render_row(target, **merged_opts)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/ui/text.py", line 442, in render_row
        cell = method(target, **options)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/renderers/base_objects.py", line 237, in render_full
        instruction.address, instruction.hexbytes, instruction.text)))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 177, in text
        canonical = self.GetCanonical()
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 162, in GetCanonical
        operands=self.operands)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 131, in operands
        self._comment = self.format_indirect(target, op.size)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/disassembler.py", line 199, in format_indirect
        target_name = ", ".join(self.resolver.format_address(target))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/common/address_resolver.py", line 314, in format_address
        address, max_distance=max_distance)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/common/address_resolver.py", line 331, in get_nearest_constant_by_address
        if module.profile != None:
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
        return super(safe_property, self).__get__(*args, **kwargs)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 176, in profile
        return self.load_profile(force=False)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 183, in load_profile
        self.build_local_profile(profile_name, force=force))
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/windows/address_resolver.py", line 136, in build_local_profile
        build_local_profile.fetch_and_parse(profile_name)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1217, in fetch_and_parse
        data = self._fetch_and_parse(module_name, guid)
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1188, in _fetch_and_parse
        outfd.write(fetch_pdb_plugin.FetchPDBFile())
      File "/home/mylinuxuser/virtualenv/reakall/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 211, in FetchPDBFile
        "Ensure cabextract is installed.\n" % output_file)
    RuntimeError: Failed to decompress output file /tmp/tmpeKQ8Sk/ntdll.pdb. Ensure cabextract is installed.
    

but:

    $ cabextract --help
    Usage: cabextract [options] [-d dir] <cabinet file(s)>
    
    This will extract all files from a cabinet or executable cabinet.
    For multi-part cabinets, only specify the first file in the set.
    
    Options:
      -v   --version     print version / list cabinet
      -h   --help        show this help page
      -l   --list        list contents of cabinet
      -t   --test        test cabinet integrity
      -q   --quiet       only print errors and warnings
      -L   --lowercase   make filenames lowercase
      -f   --fix         fix (some) corrupted cabinets
      -p   --pipe        pipe extracted files to stdout
      -s   --single      restrict search to cabs on the command line
      -F   --filter      extract only files that match the given pattern
      -d   --directory   extract all files to the given directory
    
    cabextract 1.6 (C) 2000-2011 Stuart Caie <kyzer@4u.net>
    This is free software with ABSOLUTELY NO WARRANTY.

Oh, I have investigated more deeply and ..

    $ wget http://msdl.microsoft.com/download/symbols/ntdll.pdb/41C94DD545BD4FCBA2E8F404185B97DC1/ntdll.pd_
    --2016-10-20 12:40:48--  http://msdl.microsoft.com/download/symbols/ntdll.pdb/41C94DD545BD4FCBA2E8F404185B97DC1/ntdll.pd_
    Risoluzione di msdl.microsoft.com (msdl.microsoft.com)... 104.44.204.77
    Connessione a msdl.microsoft.com (msdl.microsoft.com)|104.44.204.77|:80... connesso.
    Richiesta HTTP inviata, in attesa di risposta... 302 Redirect
    Posizione: http://msdl.microsoft.com:80/download/symbols/error.htm [segue]
    --2016-10-20 12:40:49--  http://msdl.microsoft.com/download/symbols/error.htm
    Connessione a msdl.microsoft.com (msdl.microsoft.com)|104.44.204.77|:80... connesso.
    Richiesta HTTP inviata, in attesa di risposta... 200 OK
    Lunghezza: 2354 (2,3K) [text/html]
    Salvataggio in: "ntdll.pd_"

    ntdll.pd_                                          100%[================================================================================================================>]   2,30K  --.-KB/s    in 0s    
    
    2016-10-20 12:41:52 (150 MB/s) - "ntdll.pd_" salvato [2354/2354]

and...

    
    $ file ntdll.pd_
    ntdll.pd_: HTML document, ASCII text, with CRLF line terminators

and...

    $ mv ntdll.pd_ ntdll.html
    $ lynx -dump ntdll.html       
      Microsoft Internet Symbol Server
           _______________________________________________________________

        The data you requested cannot be retrieved.

         You have reached this page because either you or an application that
         you are running has tried to retrieve debugging data from
         Microsoft.  The requested data is either not available or needs to
         be retrieved by using the latest Microsoft Symbol Server technology.

         This internet debugging data storage site is provided by Microsoft
         to enhance debugging by automatically retrieving debugging files for
         various Microsoft products during a debugging session. The data at
         this site is not browseable. Instead, it is accessed by the
         Microsoft Symbol Server technology that ships with [1]Microsoft
         Debugging Tools for Windows.

         For more information about how to use the Microsoft Internet Symbol
         Server [2]click here.
           _______________________________________________________________

         Last Updated: Monday, June 12, 2006
         © 2006 Microsoft Corporation. All rights reserved.  [3]Terms of Use
          [4]Privacy Statement.

    References

       1. http://www.microsoft.com/whdc/devtools/debugging/default.mspx
       2. http://www.microsoft.com/whdc/devtools/debugging/debugstart.mspx
       3. http://www.microsoft.com/info/cpyright.htm
       4. http://privacy.microsoft.com/en-us/default.aspx

**Comment by fpusersuggest** [comment]
Oh, It's a duplicated bug. Already fixed.
