### ISSUE TITLE
DumpFiles plugin error

### ISSUE THREAD

**Issue by db1525** [google/rekall#206]
Hi,

DumpFiles seems to throw the following error every time it's run with the 'file_objects' option.
The file gets dumped though, but the error always occurs.

Thanks,

Dan

--------------------------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-88-890b9fb42a7e> in <module>()
----> 1 dumpfiles(file_objects=0x81e7f8d8)

C:\PROGRA~1\Rekall\rekall\obj.pyc in __call__(self, *args, **kwargs)

C:\PROGRA~1\Rekall\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)

C:\PROGRA~1\Rekall\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)

C:\PROGRA~1\Rekall\rekall\plugin.pyc in render(self, renderer, **options)

C:\PROGRA~1\Rekall\rekall\plugins\windows\cache.pyc in collect(self)

AttributeError: 'DumpFiles' object has no attribute 'vacb_by_cache_map'
[1] cridex.vmem 12:01:23> dumpfiles(file_objects=0x81e7f8d8)
        Type         Phys Offset File Offset File Length Filename
-------------------- ----------- ----------- ----------- --------
ImageSectionObject    0x5c9e000         0x0       0x400  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6ea7000       0x400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6ea8000      0x1400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6ea9000      0x2400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6eaa000      0x3400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6eab000      0x4400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6eac000      0x7400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6ead000      0xb400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6eae000     0x10400      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6eaf000     0x11800       0x600  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
ImageSectionObject    0x6eb0000     0x11e00       0x400  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
DataSectionObject     0x587d000         0x0      0x1000  .\./_Device_HarddiskVolume1_WINDOWS_system32_browser.dll
2016-10-24 12:01:23,404:CRITICAL:rekall.1:Traceback (most recent call last):
  File "rekall\session.py", line 860, in RunPlugin
  File "rekall\plugin.py", line 691, in render
  File "rekall\plugins\windows\cache.py", line 284, in collect
AttributeError: 'DumpFiles' object has no attribute 'vacb_by_cache_map'

**Comment by pyrohaz4good** [comment]
+1
@scudette 
In some cases, rekall does NOT dump the whole file as the OP mentions. You can try reproducing by dumping the kernel file object "RecentFileCache.bcf". In an image I have, the full output of the file does not dump when compared dumping with vol dumpfiles. Same error is given as above.

**Comment by scudette** [comment]
That seems to be the same as #245?  Have you tried to reproduce with git head?

**Comment by pyrohaz4good** [comment]
I'm told from someone else who pulled this commit and applied it that the fix removes the error but files are still not dumping fully. I asked him to comment here with details.
