### ISSUE TITLE
403/502 Http errors fetching symbols

### ISSUE THREAD

**Issue by wh1t3-n01s3** [google/rekall#208]
Running Rekal from a new virtual environment in 3 different locations all have issues retrieving symbols from the msdl site, with a mention of cabextract not being installed.  Cabextract is installed.  Tried using stored rekall-profiles but system doesn't seem to honor the --profile_path switch or the /.rekallrc file.  I see where a similar/identical issue was submitted appr. 29 days ago but thought it was resolved.

**rekal -f memdump.aff4 --profile_path /Tools/rekall-profiles/**
`usage: rekal [-v] [-q] [--debug] [--output_style {concise,full}]
             [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
             [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
             [--pager PAGER] [--paging_limit PAGING_LIMIT]
             [--colors {auto,yes,no}] [-F FORMAT]
             [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
             [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
             [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
             [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
             [--logging_format LOGGING_FORMAT]
             [--performance {normal,fast,thorough}]
             [--live [{API,Memory} [{API,Memory} ...]]] [--dtb DTB]
             [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
             [--cache_dir CACHE_DIR]
             [--highlighting_style {manni,igor,lovelace,xcode,vim,autumn,vs,rrt,native,perldoc,borland,tango,emacs,friendly,monokai,paraiso-dark,colorful,murphy,bw,pastie,algol_nu,paraiso-light,trac,default,algol,fruity}]
             [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
             [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
             [--pagefile [PAGEFILE [PAGEFILE ...]]]
             [--autodetect {linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
             [--autodetect_threshold AUTODETECT_THRESHOLD]
             [--autodetect_build_local {full,basic,none}]
             [--autodetect_scan_length AUTODETECT_SCAN_LENGTH] [--version] [-]`
**rekal: error: unrecognized arguments: --profile_path /Tools/rekall-profiles/**

**./rekallrc**
`_cache_dir: .rekall_cache`
`repository_path: ['https://github.com/google/rekall-profiles/raw/master', 'http://profiles.rekall-forensic.com']`
`profile_path:`
`  - /Tools/rekall.profiles`
`# - http://profiles.rekall.googlecode.com/git/`
 ` - https://raw.githubusercontent.com/google/rekall-profiles_`

**System 1, DigitalOcean droplet with root**
rekal -f memdump.aff4 imageinfo
2016-11-03 10:54:12,215:ERROR:rekall.1:Error: HTTP Error 403: Forbidden
2016-11-03 10:54:12,442:ERROR:rekall.1:Error: HTTP Error 403: Forbidden
2016-11-03 10:54:12,674:ERROR:rekall.1:Error: HTTP Error 403: Forbidden
/tmp/tmpZLjWUu/ntkrnlmp.pd_: no valid cabinets found

All done, errors in processing 1 file(s)
Traceback (most recent call last):
  File "/root/Rekal/bin/rekal", line 11, in <module>
    sys.exit(main())
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/rekal.py", line 95, in main
    user_session=user_session)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/args.py", line 430, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/session.py", line 138, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugin.py", line 929, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/windows/common.py", line 59, in is_active
    return (super(AbstractWindowsCommandPlugin, cls).is_active(session) and
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugin.py", line 385, in is_active
    session.profile != None)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/utils.py", line 982, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/session.py", line 1056, in profile
    res = self.GetParameter("profile_obj")
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/session.py", line 762, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/session.py", line 797, in _RunParameterHook
    result = hook.calculate()
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 827, in calculate
    profile_obj = self.ScanProfiles()
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 755, in ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 378, in DetectFromHit
    return self._test_rsds(rsds)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 383, in _test_rsds
    profile = self.VerifyProfile("nt/GUID/%s" % rsds.GUID_AGE)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 349, in VerifyProfile
    build_local_profile.fetch_and_parse(profile_name)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1229, in fetch_and_parse
    data = self._fetch_and_parse(module_name, guid)
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1188, in _fetch_and_parse
    outfd.write(fetch_pdb_plugin.FetchPDBFile())
  File "/root/Rekal/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 211, in FetchPDBFile
    "Ensure cabextract is installed.\n" % output_file)
RuntimeError: Failed to decompress output file /tmp/tmpZLjWUu/ntkrnlmp.pdb. Ensure cabextract is installed.

_(Rekal) # apt list cabextract
Listing... Done
cabextract/trusty,now 1.4-4 amd64 [installed]_

**System 2, Ubuntu 16.04 behind proxy with no required authentication, again with a new virtualenv and pip install rekall.**

[1] memdump.aff4 10:30:55> imageinfo
2016-11-03 10:31:25,259:ERROR:rekall.1:Error: HTTP Error 502: No data received from server or forwarder
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/DE2B2D14D72E4F68B6B2E207983501F92/ntkrnlpa.pd_
2016-11-03 10:31:26,703:ERROR:rekall.1:Error: HTTP Error 403: Forbidden
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/DE2B2D14D72E4F68B6B2E207983501F92/ntkrpamp.pd_  
2016-11-03 10:31:27,460:ERROR:rekall.1:Error: HTTP Error 403: Forbidden
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/DE2B2D14D72E4F68B6B2E207983501F92/ntkrnlmp.pd_  
2016-11-03 10:31:59,549:ERROR:rekall.1:Error: HTTP Error 502: No data received from server or forwarder
----------------------------> imageinfo()0xa00000)                                                                       
        Fact         Value
-------------------- -----
Kernel DTB           0x185000
NT Build             -    
NT Build Ex          -    
Signed Drivers       -    
Time (UTC)           -    
Time (Local)         -    
2016-11-03 10:32:52,385:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/Tools/Rekal/local/lib/python2.7/site-packages/rekall/session.py", line 860, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/Tools/Rekal/local/lib/python2.7/site-packages/rekall/plugin.py", line 691, in render
    for row in self.collect():
  File "/Tools/Rekal/local/lib/python2.7/site-packages/rekall/plugins/windows/misc.py", line 228, in collect
    yield ("Sec Since Boot", self.GetBootTime(kuser_shared))
  File "/Tools/Rekal/local/lib/python2.7/site-packages/rekall/plugins/windows/misc.py", line 202, in GetBootTime
    int(kuser_shared.TickCountLow))     # WinXP
  File "/Tools/Rekal/local/lib/python2.7/site-packages/rekall/obj.py", line 1433, in __getattr__
    raise AttributeError(attr)
AttributeError: TickCountLow

**Comment by raviteja7** [comment]
Hi,

rekal doesn't take the argument --profile_path. If you want to explicitly specify the profile you do it with
rekal --profile <profile>

![image](https://cloud.githubusercontent.com/assets/2549509/20020742/304d554e-a2a9-11e6-9ef5-eb893c9175dc.png)

Also if you are using stored profiles then you don't have to use both profile_path repository_path. You can just use repository_path

![image](https://cloud.githubusercontent.com/assets/2549509/20020998/78430988-a2aa-11e6-9aea-ce1b37cd811d.png)


Also from the logs you posted, I think you may have made a mistake

![image](https://cloud.githubusercontent.com/assets/2549509/20021119/d53095e8-a2aa-11e6-87a4-ff998ac23b90.png)

Thanks

**Comment by wh1t3-n01s3** [comment]
Building from src this morning pulled 1.6.0 instead of the 1.5.3 I was getting yesterday which resolved the issue.

**Comment by wh1t3-n01s3** [comment]
As an aside, the image was obtained from a Win7Sp1 x86 machine using winpmem -o outfile.  Imageinfo now displays:
Kernel DTB           0x185000
NT Build             7601.win7sp1_ldr.160930-0600
NT Build Ex          7601.23564.x86fre.win7sp1_ldr.160930-0600
Signed Drivers       True 
Time (UTC)           2016-11-02 18:52:12Z
Time (Local)         2016-11-02 14:52:12-0400
Sec Since Boot       1686885.2389
NtSystemRoot         C:\Windows
