### ISSUE TITLE
Pip install of new Rekall agent fails

### ISSUE THREAD

**Issue by fligi7** [google/rekall#209]
Attempting to install/test per the blog post here:

http://rekall-forensic.blogspot.com/2016/10/the-rekall-agent-whitepaper.html

`[rekall-agent_venv]$ pip install -e ./rekall-core/ ./rekall-agent/ .`
> Invalid requirement: './rekall-agent/'
> It looks like a path. Does it exist ?`

**Comment by scudette** [comment]
These instructions refer to installing from source so you need to git clone the source first:

```
git clone https://github.com/google/rekall.git
cd rekall
pip install -e ./rekall-core/ ./rekall-agent/ .
```

This will make pip install the packages in these directories (instead of downloading the released packages from the repository).

Since Rekall 1.6.0 was released recently you do not need to do this - just install the released packages if you want:
```
$ virtualenv  /tmp/MyEnv
New python executable in /tmp/MyEnv/bin/python
Installing setuptools, pip...done.
$ source /tmp/MyEnv/bin/activate
$ pip install --upgrade setuptools pip wheel
$ pip install rekall-agent
```

The quick start is described in the README file:
https://github.com/google/rekall/tree/master/rekall-agent

**Comment by fligi7** [comment]
Thanks!

**Comment by fligi7** [comment]
Unfortunately, installation (on OSX 10.10.5) using the above instructions yields the following error(s):

>$ rekal -h
Traceback (most recent call last):
  File "/Users/test/Projects/rekall-agent_venv/bin/rekal", line 7, in <module>
    from rekall.rekal import main
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall/rekal.py", line 39, in <module>
    entry_point.load()
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/__init__.py", line 15, in <module>
    from rekall_agent import ui
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/ui/__init__.py", line 5, in <module>
    from rekall_agent.ui import ipython
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/ui/ipython.py", line 3, in <module>
    from IPython.core import magic
ImportError: No module named IPython.core

**Comment by scudette** [comment]
The "." in the final arg of the pip install command is supposed to refer to the top level rekall directory which will cause pip to install this file https://github.com/google/rekall/blob/master/setup.py.  This file declares a dependency on ipython (which is what is missing here).

You are right in pointing out that rekall-agent attempts to use ipython without declaring its own dependency on it. This is wrong because it breaks installs of the agent without ipython (which is only needed for the controller). That import should be optional.

**Comment by fligi7** [comment]
Sorry, to be clear, I was referring to the following installation commands:

>$ virtualenv  /tmp/MyEnv
New python executable in /tmp/MyEnv/bin/python
Installing setuptools, pip...done.
$ source /tmp/MyEnv/bin/activate
$ pip install --upgrade setuptools pip wheel
$ pip install rekall-agent

**Comment by scudette** [comment]
Yep, this was fixed here:
https://github.com/google/rekall/commit/d71538f150d146d7ec461088f3772b705d839a40#diff-b173e970f8a052b74ea9c6e7774ed32cR7

If you install ipython or just rekall as well (which pulls in ipython) it should work.  If you want to experiment with the rekall agent controller you probably really want ipython to be installed anyway.

**Comment by fligi7** [comment]
Did another fresh install via `pip install rekall-agent`, of which running rekal yields the following error:

> $ rekal -h
Traceback (most recent call last):
  File "/Users/test/Projects/rekall-agent_venv/bin/rekal", line 7, in <module>
    from rekall.rekal import main
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall/rekal.py", line 39, in <module>
    entry_point.load()
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2344, in load
    self.require(*args, **kwargs)
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 838, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 17.0 (/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages), Requirement.parse('setuptools>=18.5'), set(['html5lib']))

I went on to install rekall via `pip install rekall`, of which yields a different error:

> $ rekal -h
Traceback (most recent call last):
  File "/Users/test/Projects/rekall-agent_venv/bin/rekal", line 7, in <module>
    from rekall.rekal import main
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall/rekal.py", line 39, in <module>
    entry_point.load()
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/__init__.py", line 3, in <module>
    from rekall_agent import client_actions
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/client_actions/__init__.py", line 5, in <module>
    from rekall_agent.client_actions import interrogate
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/client_actions/interrogate.py", line 28, in <module>
    from rekall_agent import crypto
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/rekall_agent/crypto.py", line 48, in <module>
    from cryptography.hazmat.backends import openssl
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 47, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 250, in <module>
    _verify_openssl_version(Binding.lib.SSLeay())
  File "/Users/test/Projects/rekall-agent_venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 230, in _verify_openssl_version
    "You are linking against OpenSSL 0.9.8, which is no longer "
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

**Comment by scudette** [comment]
On OSX you need to use ports or brew to have a working build system. I would recommend you use the ports python instead of the python provided by Apple because it is too old. Also openssl shipped by Apple is too old and no longer supported. If you have ports installed you should be able to get everything working by simply creating the virtualenv from the ports version of python.

Maybe we need to be more explicit in the documentation for OSX. An OSX system without ports or brew is not really usable as a development platform.  I was planning to also release a binary package for OSX which will have no external dependencies so that might also be an option for testing.

**Comment by fligi7** [comment]
I would definitely upvote clarification/revamping of the documentation for OSX.

I currently have brew installed. Looks like there is a way to get this all working using custom virtualenv and python environments, but honestly that ROI doesn't look great to me right now. An executable OSX binary would be great, obviously, to avoid other users having to go through this.
