### ISSUE TITLE
Issues with fetch_pdb and downloading of pdb files

### ISSUE THREAD

**Issue by madsumm** [google/rekall#218]
Errors when Rekall tries to download new PDB.

```
# rekal fetch_pdb ntkrnlmp.pd_ C3B9B2085FCD4C789407AB3A4E0D24811
 Trying to fetch https://msdl.microsoft.com/download/symbols/ntkrnlmp.pd_.pdb/C3B9B2085FCD4C789407AB3A4E0D24811/ntkrnlmp.pd_.pd_
2016-12-01 14:12:09,846:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 174, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp
HTTPError: HTTP Error 404: Not Found
```
None of the profiles can be built.

**Comment by scudette** [comment]
Heh we were just talking about this very guid.  It appears that Microsoft
does not have that one on the symbol server yet. We will try to reach out
to chase it up.

On 30 Nov 2016 22:27, "madsumm" <notifications@github.com> wrote:

Errors when Rekall tries to download new PDB.

# rekal fetch_pdb ntkrnlmp.pd_ C3B9B2085FCD4C789407AB3A4E0D24811
 Trying to fetch
https://msdl.microsoft.com/download/symbols/ntkrnlmp.pd_.pdb/C3B9B2085FCD4C789407AB3A4E0D24811/ntkrnlmp.pd_.pd_
2016-12-01 <https://msdl.microsoft.com/download/symbols/ntkrnlmp.pd_.pdb/C3B9B2085FCD4C789407AB3A4E0D24811/ntkrnlmp.pd_.pd_2016-12-01>
14:12:09,846:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py",
line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py",
line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py",
line 174, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp
HTTPError: HTTP Error 404: Not Found

None of the profiles can be built.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/rekall/issues/218>, or mute the thread

**Comment by c0de90e7** [comment]
Hello,

First of all, I know my question is probably late and may be of no use/unrelated.

The thing is this file pdb is now downloading fine but the problem is the pdb has functions/addresses info but 0 types in it.

After strugging with this for a while I started looking into the executable itself ( ntkrnlmp.exe ) and noticed a weird thing: the IMAGE_DEBUG_DIRECTORY array on the PE headers has two entries, one with a type=0x00000002 ( CODEVIEW debug info, the common one ) which is pointing to ntkrnlmp.pdb and another one with type=0x0000000D which is unknown.

I have been looking for info on this new/unknown debug type just in case it was a new tool or a new dbghlp.dll version required or so, but I found nothing. Official Microsoft's PECOFF documentation updated to latest version ( jan 23, 2017 ) is missing this type also.

This was a desperate research just in case Microsoft decided to split debugging info of new executables into the common CodeView info and just for functions/globals addresses and then this new unknown  type=0x0000000D.

The CodeView entry has it's block of data starting with signature "RSDS" ( the usual CodeView signature ) and the unknown entry has quite large block of data starting with a signature of 0,"UGP". A search for this gave no results :(

I also tried loading the ntkrnlmp.exe file in IDA ( Interactive DisAssembler ) and it does warn about this unknown 13 ( 0x0000000D ) debug type in the IMAGE_DEBUG_DIRECTORY of the PE file. And again, 0 types in the PDB.

This is actually giving me trouble trying to debug a BSOD. I have force-loaded other Windows 10 x64 version PDB and used some types and all but I am still having a hard time for other commands, etc.

Dis you guys find more info on this particular version of ntkrnlmp.exe, do you have any clue on this ?

Thanks in advance and sorry if this brings more time-loss ;(

**Comment by scudette** [comment]
We have also seen many pdb files which were stripped of type information. We have reached out to MS to have some of these corrected and they were eventually fixed, but we occasionally see them come up. I dont think this is anything deliberate from MS because it has been corrected before.

TBH when I needed to analyze a system with missing types it usually works to just copy the types (in the json file) from another similar pdb file (same version etc). It is not as rigorous but it tends to work most of the time.
