### ISSUE TITLE
plugins.lsmod error

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#222]
Hi, I have the following error on Ubuntu 16.04:
    # uname -a
    Linux dt2261016 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

    [1] box.aff4 18:23:00> lsmod
    ---------------------> lsmod()
       virtual         start         size            name        
    -------------- -------------- ---------- --------------------
    2016-12-15 18:23:03,149:CRITICAL:rekall.1:Traceback (most recent call last):
      File "/home/venv2/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
        result = plugin_obj.render(ui_renderer) or plugin_obj
      File "/home/venv2/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
        for row in self.collect():
      File "/home/venv2/local/lib/python2.7/site-packages/rekall/plugins/linux/lsmod.py", line 51, in collect
        module.module_core.deref(),
      File "/home/venv2/local/lib/python2.7/site-packages/rekall/obj.py", line 1433, in __getattr__
        raise AttributeError(attr)
    AttributeError: module_core
    
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-67b73071f2e2> in <module>()
    ----> 1 lsmod()
    
    /home/venv2/local/lib/python2.7/site-packages/rekall/obj.pyc in __call__(self, *args, **kwargs)
        137         new_kwargs = self._kwargs.copy()
        138         new_kwargs.update(kwargs)
    --> 139         return self._target(*(self._args + args), **new_kwargs)
        140 
        141     def get_default_arguments(self):
    
    /home/venv2/local/lib/python2.7/site-packages/rekall/session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
        860                 self.last = plugin_obj
        861             except (Exception, KeyboardInterrupt) as e:
    --> 862                 self._HandleRunPluginException(ui_renderer, e)
        863 
        864             finally:
    
    /home/venv2/local/lib/python2.7/site-packages/rekall/session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
        857                     raise ValueError(
        858                         "Invalid plugin: %s" % original_plugin_obj)
    --> 859                 result = plugin_obj.render(ui_renderer) or plugin_obj
        860                 self.last = plugin_obj
        861             except (Exception, KeyboardInterrupt) as e:
    
    /home/venv2/local/lib/python2.7/site-packages/rekall/plugin.pyc in render(self, renderer, **options)
        724 
        725         renderer.table_header(self.table_header, **table_options)
    --> 726         for row in self.collect():
        727             if isinstance(row, (list, tuple)):
        728                 renderer.table_row(*row, **options)
    
    /home/venv2/local/lib/python2.7/site-packages/rekall/plugins/linux/lsmod.pyc in collect(self)
         49         for module in self.get_module_list():
         50             yield (module.obj_offset,
    ---> 51                    module.module_core.deref(),
         52                    module.init_size + module.core_size,
         53                    module.name)
    
    /home/venv2/local/lib/python2.7/site-packages/rekall/obj.pyc in __getattr__(self, attr)
       1431         result = self.m(attr)
       1432         if result == None:
    -> 1433             raise AttributeError(attr)
       1434 
       1435         return result
    
    AttributeError: module_core

**Comment by scudette** [comment]
This should be fixed with a1059f57393fb778e33dacbc4c83cbc948dd1edc

**Comment by fpusersuggest** [comment]
Yes it's fixed. 
But the problem I have written in the google group is still there.

`[1] box3-4.4.0-57-generic.aff4 10:24:30> plugins.check_task_fops
---------------------------------------> plugins.check_task_fops()
             task                          member                address     module
------------------------------ ------------------------------ -------------- ------
0x880225706200 gnome-shell   2185 aio_fsync                      0xffffff817398       
0x880225706200 gnome-shell   2185 check_flags                    0xffffff817398       
0x880225706200 gnome-shell   2185 fallocate                      0xffffff817396       
0x880225706200 gnome-shell   2185 fasync                         0xffffff817398       
0x880225706200 gnome-shell   2185 flock                          0xffffff817397       
0x880225706200 gnome-shell   2185 flush                          0xffffff817399       
0x880225706200 gnome-shell   2185 fsync                          0xffffff817398       
0x880225706200 gnome-shell   2185 get_unmapped_area              0xffffff817398       
0x880225706200 gnome-shell   2185 lock                           0xffffff817398       
0x880225706200 gnome-shell   2185 release                        0xffffff817398       
0x880225706200 gnome-shell   2185 sendpage                       0xffffff817398       
0x880225706200 gnome-shell   2185 setlease                       0xffffff817397       
0x880225706200 gnome-shell   2185 splice_read                    0xffffff817397       
0x880225706200 gnome-shell   2185 splice_write                   0xffffff817397       
0x880225706200 gnome-shell   2185 unlocked_ioctl                       0xdeadbe       
Out<10:24:51> Plugin: check_task_fops (CheckTaskFops)
`
All those lines are red.
