### ISSUE TITLE
failing to start rekall from standalone setup

### ISSUE THREAD

**Issue by Abhisar** [google/rekall#223]
I made a local setup of rekal and it ranl and then tried to port to it to a portale USB. When i try to start rekall it fails because of:
`Traceback (most recent call last):
  File "rekal.py", line 3, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\rekal.py", line 43, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\__init__.py", line 4, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\addrspaces\__init__.py", line 10, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\addrspaces\ewf.py", line 27, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\tools\__init__.py", line 30, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\tools\disassembler.py", line 25, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_capstone-3.0.4.post2-py2.7-win32.egg\capstone\__init__.py", line 254, in <module>
ImportError: ERROR: fail to load the dynamic library.
Failed to execute script rekal`

Because i figured out the issue coming  whileloading capstone.dll from C:\Rekal\capstone\capstone.dll , inserted some print statement just to see the path from where it is trying to load the dlls.Eventough it is present in the path still it fails.Any leads please ?

`PS C:\Rekal> .\rekal.exe
LOOOOOpp 1capstone.dllC:\Rekal\capstone
C:\Rekal\capstone\capstone.dll
LOOOOOpp 1libcapstone.so.3C:\Rekal\capstone
C:\Rekal\capstone\libcapstone.so.3
LOOOOOpp 1libcapstone.soC:\Rekal\capstone
C:\Rekal\capstone\libcapstone.so
LOOOOOpp 1libcapstone.dylibC:\Rekal\capstone
C:\Rekal\capstone\libcapstone.dylib
LOOOOOpp 2
LOOOOOpp 2
LOOOOOpp 2
LOOOOOpp 2
LOOOOOpp 3capstone.dll
LOOOOOpp 3libcapstone.so.3
LOOOOOpp 3libcapstone.so
LOOOOOpp 3libcapstone.dylib
Traceback (most recent call last):
  File "rekal.py", line 3, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\rekal.py", line 43, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\__init__.py", line 4, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\addrspaces\__init__.py", line 10, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\addrspaces\ewf.py", line 27, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\tools\__init__.py", line 30, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_core-1.6.1.dev7-py2.7.egg\rekall\plugins\tools\disassembler.py", line 25, in <module>
  File "c:\users\abhisa~1.moh\appdata\local\temp\pip-build-pxmapm\pyinstaller\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
  File "site-packages\rekall_capstone-3.0.4.post2-py2.7-win32.egg\capstone\__init__.py", line 254, in <module>
ImportError: ERROR: fail to load the dynamic library.
Failed to execute script rekal`

**Comment by hoyt-harness** [comment]
I'm having the same issues.
