### ISSUE TITLE
SPARQLWrapper and html5lib not found

### ISSUE THREAD

**Issue by hj0x3** [google/rekall#231]
With rdflib 4.2.2 packages SPARQLWrapper and html5lib have been demoted  from install_requires to test_requires and and extra_require.  As a result a normal rekall install generates warnings on missing html5lib, and an exception on missing SPARQLWrapper.

Ref: https://github.com/RDFLib/rdflib/pull/675

```
> rekall
/home/harry/bin/python2-venv/lib/python2.7/site-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')
/home/harry/bin/python2-venv/lib/python2.7/site-packages/rdflib/plugins/parsers/hturtle.py:32: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'will not be available.')
Traceback (most recent call last):
  File "/home/harry/bin/python2-venv/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/rekall/rekal.py", line 39, in <module>
    entry_point.load()
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/rekall/plugins/addrspaces/__init__.py", line 43, in <module>
    import rekall.plugins.addrspaces.aff4
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.py", line 408, in <module>
    import rdflib.plugins.stores.sparqlstore
  File "/home/harry/bin/python2-venv/lib/python2.7/site-packages/rdflib/plugins/stores/sparqlstore.py", line 24, in <module>
    "Install with 'easy_install SPARQLWrapper'")
Exception: SPARQLWrapper not found! SPARQL Store will not work.Install with 'easy_install SPARQLWrapper'
```

**Comment by Wenzel** [comment]
Hi,
I also have this issue here and cannot start Rekall.

**Comment by scudette** [comment]
This should be fixed now. Thanks for reporting.
