### ISSUE TITLE
Fresh install of Rekall - every command gives TypeError

### ISSUE THREAD

**Issue by jimmythefish12** [google/rekall#235]
Win 10 x64 Enterprise:

Commands used:
C:\Program Files\Rekall>rekal --live pslist -v
C:\Program Files\Rekall>rekal --live pstree -v
C:\Program Files\Rekall>rekal --live malfind -v

Exact output of every command no matter what plugin I use:
Traceback (most recent call last):
  File "rekal.py", line 8, in <module>
  File "site-packages\rekall\rekal.py", line 95, in main
  File "site-packages\rekall\args.py", line 407, in parse_args
  File "site-packages\rekall\args.py", line 219, in ParseGlobalArgs
  File "site-packages\rekall\session.py", line 433, in __exit__
  File "site-packages\rekall\session.py", line 252, in _set_live
  File "site-packages\rekall\obj.py", line 139, in __call__
  File "site-packages\rekall\registry.py", line 72, in __call__
  File "site-packages\rekall\plugins\tools\live_windows.py", line 74, in __init__
  File "site-packages\rekall\plugin.py", line 620, in __init__
  File "site-packages\rekall\plugin.py", line 600, in __init__
  File "site-packages\rekall\plugin.py", line 120, in parse
TypeError: Arg mode must be one of ['API', 'Memory']
Failed to execute script rekal

thanks

**Comment by scudette** [comment]
It is telling you that the --live argument must be one of Memory or API:

```
rekall -v --live Memory pslist    <----- Lists processes using memory analysis
rekall -v --live API pslist    <--- lists processes using the API.
```

**Comment by jimmythefish12** [comment]
Oh, must be a feature of the newer Rekalls. This didn't used to exist! Thanks
