### ISSUE TITLE
RuntimeError: Unable to instantiate physical_address_space from filename /cases/sources/mac/mac-sample-1.bin.

### ISSUE THREAD

**Issue by juju4** [google/rekall#237]
Hello,

I hit this error when executing rekall through jenkins but not on shell

Jenkins build log
```
Started by user admin_ffate
Building in workspace /var/lib/jenkins/jobs/RekallMac/workspace
[workspace] $ /bin/sh -xe /tmp/hudson381421794101866085.sh
+ [[ ! -d /artifacts/bbbb2 ]]
+ mkdir /artifacts/bbbb2
+ rekall -f /cases/sources/mac/mac-sample-1.bin pslist
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 95, in main
    user_session=user_session)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/args.py", line 430, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 138, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 947, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 413, in is_active
    profile = (session.profile != None and
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/utils.py", line 1009, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 1055, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 761, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 796, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 733, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename /cases/sources/mac/mac-sample-1.bin.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

shell execution
```
# rekall -f /cases/sources/mac/mac-sample-1.bin pslist
  obj_offset           name          pid   alive    ppid   uid   is64bit           start_time                 cr3
-------------- -------------------- ----- -------- ------ ------ ------- ------------------------------ ---------------
0xff800dcfccc0 kernel_task              0 True     0      0      True    2014-06-20 21:43:15+0000            0xf1e4000
0xff801378ea80 launchd                  1 True     0      0      True    2014-06-20 21:43:15+0000            0xdd58000
0xff801ca81098                         1 False    1      789076 False   -                              -
0xff801ca81950                         1 False    1      789334 False   -                              -
0xff801378e130 UserEventAgent          11 True     1      0      True    2014-06-20 21:43:17+0000            0xb391000
0xff801378d7e0 kextd                   12 True     1      0      True    2014-06-20 21:43:17+0000            0xbc9e000
[...]
```

any idea why?

Thanks

sample from https://www.memoryanalysis.net/amf
system build with https://github.com/juju4/ansible-forensicator-fate/ (that build, but not in travis for unexplained reason currently) and rekall 1.6.0

**Comment by scudette** [comment]
Make sure that Jenkins can access the profile repository.  If you enable
debugging using the -v flag we can get more information but typically of
you can not access the profile repo then auto detection will fail.

**Comment by juju4** [comment]
That's it. too simple. Thanks!
