### ISSUE TITLE
how to simply test rekall agent + server install working?

### ISSUE THREAD

**Issue by juju4** [google/rekall#246]
Hello,

I added agent and http server to my ansible role
https://github.com/juju4/ansible-rekall/

but I want to add a check in serverspec to ensure kitchen test with server (agent+server on same system) is working fine. (like https://github.com/juju4/ansible-rekall/blob/master/test/integration/default/serverspec/rekall_spec.rb)

any simple call to launch rekall ? as if on server to do a request on client like 
```
launch_hunt("ListProcessFlow")
```
from https://rekall-forensic.blogspot.ca/2016/10/the-rekall-agent-whitepaper.html
or to list all connected agents?
is it needed to write a hunt file?
I did not managed to launch rekall in "rekall agent" mode like on your screenshots.

Thanks

**Comment by scudette** [comment]
What are you trying to actually test? In order to make the client and server talk to each other you need to generate compatible configuration files. This is the process. First make a directory to store configs and write configs into there (presumably you want to test local http server):

```
(Dev) scudette:~$ mkdir /tmp/test.dir
(Dev) scudette:~$ rekall agent_server_initialize_http --base_url http://127.0.0.1:8000/ --bind_port 8000 --bind_address 127.0.0.1 --client_writeback_path /tmp/test.dir/.rekall_agent /tmp/test.dir/
Message
-------                                                                                   
Generating new CA private key into /tmp/test.dir/ca.private_key.pem and /tmp/test.dir/ca.cert.pem
Generating new Server private keys into /tmp/test.dir/server.private_key.pem and /tmp/test.dir/server.certificate.pem
Writing server config file /tmp/test.dir/server.config.yaml                               
Writing client config file /tmp/test.dir/client.config.yaml                               
Done!                                                                                     
(Dev) scudette:~$ ls /tmp/test.dir/                                                       
ca.cert.pem         client.config.yaml      server.config.yaml
ca.private_key.pem  server.certificate.pem  server.private_key.pem     
```
Next start the server and the client in the background. They should enrol
```
(Dev) scudette:~$ rekall  --agent_config /tmp/test.dir/server.config.yaml http_server &
(Dev) scudette:~$ rekall  --agent_config /tmp/test.dir/client.config.yaml agent &
```

You can check that the client writeback is now created at `/tmp/test.dir/.rekall_agent`.

Run the worker once which should process all the queue (in real life you would run with --loop 5 to keep working every 5 seconds).

```
(Dev) scudette:~$ rekall -v --agent_config /tmp/test.dir/server.config.yaml worker
```
You can now run the controller:
```
(Dev) scudette:~$ rekall --agent_config /tmp/test.dir/server.config.yaml agent_controller                                                                                       
----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.6.1.dev11 (Gotthard).           
                                                                                          
"We can remember it for you wholesale!"                                                   
                                                                                          
This program is free software; you can redistribute it and/or modify it under             
the terms of the GNU General Public License.                                              
                                                                                          
See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.              
----------------------------------------------------------------------------              
[1] Rekall Agent 18:43:22> show_clients
-------------------------> show_clients()
2017-03-12 18:43:22,918:INFO:rekall.1:"GET /clients.sqlite HTTP/1.1" 304 -                
Online     client_id                      hostname                      os      MAC Usernames first_time last_time Labels install_time
------ ------------------ ----------------------------------------- ----------- --- --------- ---------- --------- ------ ------------
       C.01748b67faa479e6 desktop.c.fourth-carport-147912.internal  Linux 64bit                          -                            
Out<18:43:23> Plugin: show_clients (SearchClients)                  
```

**Comment by juju4** [comment]
ah, I mistook agent_controller for another daemon but from your example, it is the server console.

so these commands should be valid tests, right?
```
rekall --agent_config /tmp/test.dir/server.config.yaml agent_controller show_clients
rekall --agent_config /tmp/test.dir/server.config.yaml agent_controller 'launch_hunt("ListProcessFlow")'
```

the rest of the config should be correct. I followed the blog post. Was not sure how to use it without a grr setup or a hunt/flow file.

Thanks

**Comment by scudette** [comment]
The controller is the ipython shell interface you use to admin the system. It is interactive actually and so it is not suitable as a single run tool.

If you just want to run the show_client and exist then you can run it as a script:
```
(Dev) scudette:~$ rekal --agent_config /tmp/test.dir/server.config.yaml run --script "session.SetParameter('agent_mode', 'controller'); show_clients()"
Online      client_id                      hostname                       os      MAC Usernames first_time last_time Labels install_time
------ ------------------- ----------------------------------------- ------------ --- --------- ---------- --------- ------ ------------
       C.963d5591be808fe3  desktop.c.fourth-carport-147912.internal  Linux 64bit            
```

**Comment by juju4** [comment]
That seemed perfect but when I executed, got a 404
```
# rekall --agent_config /etc/rekall-server/server.config.yaml run --script "session.SetParameter('agent_mode', 'controller'); show_clients();"
2017-03-14 02:31:57,873:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/ui/clients.py", line 66, in collect
    session=self.session) as collection:
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/result_collections.py", line 153, in load_from_location
    filename = collection_location.get_local_filename()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/locations/http.py", line 302, in get_local_filename
    return self._report_error(completion_routine, resp)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/locations/http.py", line 243, in _report_error
    raise IOError(response.text)
IOError: <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 404.
<p>Message: File not found.
<p>Error code explanation: 404 = Nothing matches the given URI.
</body>


Online client_id hostname os MAC Usernames first_time last_time Labels install_time
------ --------- -------- -- --- --------- ---------- --------- ------ ------------
2017-03-14 02:31:57,936:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 855, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 914, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 74, in __init__
    exec script in self.session.locals
  File "<string>", line 1, in <module>
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/obj.py", line 139, in __call__
    return self._target(*(self._args + args), **new_kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/ui/clients.py", line 66, in collect
    session=self.session) as collection:
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/result_collections.py", line 153, in load_from_location
    filename = collection_location.get_local_filename()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/locations/http.py", line 302, in get_local_filename
    return self._report_error(completion_routine, resp)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_agent/locations/http.py", line 243, in _report_error
    raise IOError(response.text)   
IOError: <head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 404.
<p>Message: File not found.
<p>Error code explanation: 404 = Nothing matches the given URI.
</body>
[...]
# tail -f /var/log/syslog
[...]
Mar 14 02:31:57 default-server-ubuntu-1604 rekall[4392]: 2017-03-14 02:31:57,870:INFO:rekall.1:"GET /clients.sqlite HTTP/1.1" 404 -
```

or 
```
# rekall --agent_config /etc/rekall-server/server.config.yaml run --script "session.SetParameter('agent_mode', 'controller'); launch_hunt("ListProcessFlow");"
2017-03-14 02:34:18,255:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 855, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 914, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 74, in __init__
    exec script in self.session.locals
  File "<string>", line 1, in <module>
NameError: name 'ListProcessFlow' is not defined

2017-03-14 02:34:18,258:CRITICAL:root:name 'ListProcessFlow' is not defined. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 855, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 914, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 74, in __init__
    exec script in self.session.locals
  File "<string>", line 1, in <module>
NameError: name 'ListProcessFlow' is not defined
```

**Comment by juju4** [comment]
found it... rekall-agent service not running

```
# rekall --agent_config /etc/rekall-server/server.config.yaml run --script "session.SetParameter('agent_mode', 'controller'); show_clients();" 
Online      client_id               hostname                os      MAC Usernames first_time last_time Labels install_time
------ ------------------- --------------------------- ------------ --- --------- ---------- --------- ------ ------------
       C.b9cb4c6711aee1eb  default-server-ubuntu-1604  Linux 64bit
```

ListProcessFlow still failed.
