### ISSUE TITLE
mimikatz plugin doesn't recover plaintext (wdigest) passwords

### ISSUE THREAD

**Issue by jeffmcjunkin** [google/rekall#252]
For some reason, rekall's mimikatz module isn't working as expected in my testing, detailed below. It looks like the msv section is working correctly, but the wdigest section is not.

I was able to replicate the issue using [modern.ie](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), specifically Windows 7 SP1 x86 with IE11 for VMware. The password for the IEUser user is "Passw0rd!", and it's a freely-available VM which hopefully makes for a reproducible testing setup.

Output from Mimikatz 2.2.1 (latest release) from within the VM as a baseline:
```
C:\Users\IEUser\Desktop\Win32>mimikatz.exe

  .#####.   mimikatz 2.1.1 (x86) built on Apr  9 2017 23:24:06
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 21 modules * * */

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonpasswords

Authentication Id : 0 ; 108403 (00000000:0001a773)
Session           : Interactive from 1
User Name         : IEUser
Domain            : IE11WIN7
Logon Server      : IE11WIN7
Logon Time        : 4/19/2017 10:06:00 AM
SID               : S-1-5-21-3463664321-2923530833-3546627382-1000
        msv :
         [00000003] Primary
         * Username : IEUser
         * Domain   : IE11WIN7
         * NTLM     : fc525c9683e8fe067095ba2ddc971889
         * SHA1     : e53d7244aa8727f5789b01d8959141960aad5d22
         [00010000] CredentialKeys
         * NTLM     : fc525c9683e8fe067095ba2ddc971889
         * SHA1     : e53d7244aa8727f5789b01d8959141960aad5d22
        tspkg :
        wdigest :
         * Username : IEUser
         * Domain   : IE11WIN7
         * Password : Passw0rd!
        kerberos :
         * Username : IEUser
         * Domain   : IE11WIN7
         * Password : (null)
        ssp :
        credman :
         [00000000]
         * Username : IE8Win7\IEUser
         * Domain   : IE8Win7\IEUser
         * Password : Passw0rd!
[skipping other mimikatz output...]
```

I then took a snapshot of the VM (I'm using VMware Workstation Pro 12.5.5 build-5234757) and ran rekall (installed https://github.com/google/rekall/releases/tag/v1.6.0 via `dpkg` on an Ubuntu 16.04 x64 host) as follows:

```
jeff@blue:~/dev$ rekall -f ~/vmware/temp_modern.ie_Win7_IE11/temp_modern.ie_Win7_IE11-Snapshot2.vmem mimikatz
        LUID               Type       Sess         SID          Module   Info        Domain            User         SType                Secret             
-------------------- ---------------- ---- -------------------- ------- ------- ---------------- ---------------- --------- --------------------------------
00000000:00180761    -                -    -                    wdigest         IE11WIN7         IEUser           password  -                               
00000000:001806e6    -                -    -                    wdigest         IE11WIN7         IEUser           password  -                               
00000000:0001a773    -                -    -                    wdigest         IE11WIN7         IEUser           password  -                               
00000000:0001a6fe    -                -    -                    wdigest         IE11WIN7         IEUser           password  -                               
00000000:000003e5    -                -    -                    wdigest                                           password  -                               
00000000:000003e4    -                -    -                    wdigest         WORKGROUP        IE11WIN7$        password  -                               
00000000:000003e7    -                -    -                    wdigest         WORKGROUP        IE11WIN7$        password  -                         
```

Note the distinct lack of "Passw0rd!" appearing in the output.

Thinking it could be an issue with the .vmem format support*, I used the latest `winpmem` in the VM as follows:
```
C:\Users\IEUser\Downloads>winpmem-2.1.post4.exe -o win7_ie11.aff4
```

I then copied the output file to my host and re-ran rekall as follows:
```
jeff@blue:~/dev$ rekall -f ~/Downloads/win7_ie11.aff4 mimikatz
        LUID               Type       Sess         SID          Module   Info        Domain            User         SType                Secret             
-------------------- ---------------- ---- -------------------- ------- ------- ---------------- ---------------- --------- --------------------------------
00000000:00180761    -                -    -                    wdigest         IE11WIN7         IEUser           password  -                               
00000000:001806e6    -                -    -                    wdigest         IE11WIN7         IEUser           password  -                               
00000000:000003e5    -                -    -                    wdigest                                           password  -                               
00000000:000003e4    -                -    -                    wdigest         WORKGROUP        IE11WIN7$        password  -                               
00000000:000003e7    -                -    -                    wdigest         WORKGROUP        IE11WIN7$        password  -                               
```

I haven't really examined [the code](https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/windows/mimikatz.py) other than a cursory view -- it's way beyond me, honestly. Hopefully providing reproducible issues is good enough :)

I've uploaded the memory image in question to Dropbox: https://www.dropbox.com/s/ij87sa73fq8fl78/win7_ie11.aff4?dl=0

* I did in fact have issues using the .vmem file from a paused VM instead of the one from a snapshotted VM, but that appears to be a separate issue. I'm not sure if I should file a separate issue for that.

**Comment by jeffmcjunkin** [comment]
For what it's worth, I encounter the same issue in modern.ie's Windows 8 / IE 11 VM:

Output from mimikatz.exe as a baseline:
```
C:\Users\IEUser\Desktop\Win32>mimikatz.exe

  .#####.   mimikatz 2.1.1 (x86) built on Apr  9 2017 23:24:06
 .## ^ ##.  "A La Vie, A L'Amour"
 ## / \ ##  /* * *
 ## \ / ##   Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 '## v ##'   http://blog.gentilkiwi.com/mimikatz             (oe.eo)
  '#####'                                     with 21 modules * * */

mimikatz # privilege::debug
Privilege '20' OK

mimikatz # sekurlsa::logonpasswords

Authentication Id : 0 ; 3806735 (00000000:003a160f)
Session           : Interactive from 2
User Name         : IEUser
Domain            : IE11Win8_1
Logon Server      : IE11WIN8_1
Logon Time        : 4/20/2017 9:26:04 AM
SID               : S-1-5-21-2968750198-2704521508-3360548841-1001
        msv :
         [00000003] Primary
         * Username : IEUser
         * Domain   : IE11Win8_1
         * NTLM     : fc525c9683e8fe067095ba2ddc971889
         * SHA1     : e53d7244aa8727f5789b01d8959141960aad5d22
         [00010000] CredentialKeys
         * NTLM     : fc525c9683e8fe067095ba2ddc971889
         * SHA1     : e53d7244aa8727f5789b01d8959141960aad5d22
        tspkg :
        wdigest :
         * Username : IEUser
         * Domain   : IE11Win8_1
         * Password : (null)
        livessp :
        kerberos :
         * Username : IEUser
         * Domain   : IE11Win8_1
         * Password : (null)
        ssp :
        credman :
         [00000000]
         * Username : IE11Win8_1\IEUser
         * Domain   : IE11Win8_1\IEUser
         * Password : Passw0rd!
```
Exporting memory with `winpmem.exe` and running rekall against it:
```
jeff@desktop:~$ rekall  -f ~/Downloads/win8_ie11.aff4 mimikatz
        LUID               Type       Sess         SID          Module   Info        Domain            User         SType                Secret             
-------------------- ---------------- ---- -------------------- ------- ------- ---------------- ---------------- --------- --------------------------------
2017-04-20 10:03:36,366:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 529, in collect
    secret) in lsasrv.logons(lsass_logons):
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 362, in logons
    dec_cred = self.decrypt(primary_cred.Credentials.Raw)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 244, in decrypt
    return self.decrypt_nt6(encrypted)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 271, in decrypt_nt6
    cipher = DES3.new(self.des_key, DES3.MODE_CBC, self.iv[:8])
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 114, in new
    return DES3Cipher(key, *args, **kwargs)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 76, in __init__
    blockalgo.BlockAlgo.__init__(self, _DES3, key, *args, **kwargs)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: Invalid key size (must be either 16 or 24 bytes long)

2017-04-20 10:03:36,366:CRITICAL:root:Invalid key size (must be either 16 or 24 bytes long). Try --debug for more information.
Traceback (most recent call last):
  File "/usr/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 529, in collect
    secret) in lsasrv.logons(lsass_logons):
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 362, in logons
    dec_cred = self.decrypt(primary_cred.Credentials.Raw)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 244, in decrypt
    return self.decrypt_nt6(encrypted)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/mimikatz.py", line 271, in decrypt_nt6
    cipher = DES3.new(self.des_key, DES3.MODE_CBC, self.iv[:8])
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 114, in new
    return DES3Cipher(key, *args, **kwargs)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/Crypto/Cipher/DES3.py", line 76, in __init__
    blockalgo.BlockAlgo.__init__(self, _DES3, key, *args, **kwargs)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: Invalid key size (must be either 16 or 24 bytes long)
```
Since `--debug` isn't useful for me, I re-ran with `-v` and put the output in a Gist: https://gist.github.com/jeffmcjunkin/1c0e72c992e4212bea46ad235b47923f

**Comment by dfirfpi** [comment]
Hi @jeffmcjunkin, I have quite solid bets about the issues. I'll start working on them.

**Comment by dfirfpi** [comment]
Hi @jeffmcjunkin, the Win7 and Win8 issues are not related. Let's start from **Win7**.

By the way, thank you for providing the ram image, it was truly helpful. First, the Rekall mimikatz plugin, as its parent, uses Windows debugging symbols to find the proper locations of artifacts, as the _crypto material_ needed to decrypt memory stored passwords. So, if you have the _**right**_ symbols you'll get the _**right**_ data, otherwise you could face weird scenarios, as it happened.

Every module (here lsass, the **critical** lsasrv and wdigest) stores its PDB file name and, more important, the **GUID** in its RSDS PE section: Rekall will parse that section, extract the GUID and PDB file name, search online (_rekall-profiles_) and in the local cache (_.rekall_cache_ folder) for that profile(s). If a match is found, Rekall will load the proper **profile**, otherwise it will download from Microsoft servers the missing profile and update the local cache. Everything out of the box.

What happens when Rekall has not PDB file name and GUID information? **This is the root cause of the Win7 issue you reported**. In your scenario, the PE RSDS section of lsasrv and wdigest modules are not mapped in memory, as you can easily check with

```
rekal.py -f win7_ie11.aff4 version_scan --name_regex "(lsasrv|wdigest|lsass)"

    offset                   guid                             pdb
-------------- --------------------------------- ------------------------------
   0x1d8dc6b4   99320ABAD53144FD80E718C62218D69D2       lsass.pdb
```
So Rekall has not such information. Still it will try to work out of the box, by using a _comparison points algorithm_ to choose between the available modules which one is the most suitable to be used. You can check the output by specifying the verbose flag, **-v**. The outcome works well for wdigest (the encrypted data is correct), but it's wrong for lsasrv, which "keeps" the decryption key and more valuable data... Indeed, the issue could had been detected by spotting the missing SIDs and credentials types.

The _failure_ is due to the lack of the needed **lsasrv**.pdb / GUID in Rekall's profiles. Luckily we have the disk image, so we can extract the lsasrv.dll and look for its RSDS: **B9FA04C195614B77AF71E1377BCBF7BB2** is the missing  GUID. 

**NOTE**:  you could run **winpmem** with the _--also_mapped_files_ argument to include the loaded modules in the AFF4 acquisition. You should then avoid such issues.

Let's add the missing lsasrv profile to the local Rekall repository: thanks to @scudette for the support!

1. Download from github the rekall-profiles repository. You get a fully populated _.rekall_cache/v1.0_ folder
2. Add the missing GUID to _.rekall_cache/v1.0/src/lsasrv/guids.yaml_
3. Run `rekall manage_repo -v` from the _.rekall_cache/_ directory: the missing profiles will be added
4. run the mimikatz plugin now (output truncated for space)

```
00000000:001806e6    Interactive      2    S-1-5-21-3463664321- msv     Primary IE11WIN7         IEUser           NTLM      fc525c9683e8fe067095ba2ddc971889
                                           2923530833-354662738
                                           2-1000
00000000:001806e6    Interactive      2    S-1-5-21-3463664321- msv     Primary IE11WIN7         IEUser           SHA1      e53d7244aa8727f5789b01d895914196
                                           2923530833-354662738                                                             0aad5d22
                                           2-1000
00000000:00180761    Interactive      2    S-1-5-21-3463664321- wdigest         IE11WIN7         IEUser           password  P a s s w 0 r d !
                                           2923530833-354662738
                                           2-1000
00000000:001806e6    Interactive      2    S-1-5-21-3463664321- wdigest         IE11WIN7         IEUser           password  P a s s w 0 r d !
```

You could do the same by hand, which is useful when dealing with _unknown_ Windows kernel profiles: get the PDB / GUID info for the desired module, run rekall **fetch_pdb** and then **parse_pdb** to get a Rekall profile, a JSON file. Put somewhere and, from the interactive sessione **before** invoking mimikatz, execute `session.SetParameter("lsasrv_profile", <the json obtained>)`.

For example I put the _B9Fa04c195614b77af71e1377bcbf7bb.gz_ profile in the _.rekall_cache\v1.0\lsasrv\GUID_ folder and I executed, before the mimikatz plugin,
`session.SetParameter("lsasrv_profile", "lsasrv/GUID/B9Fa04c195614b77af71e1377bcbf7bb2")`

Last, the mimikatz plugin **should** warn the user about the missing crypto material, at least.

**Comment by dfirfpi** [comment]
hi @jeffmcjunkin , finally here is the patch (see the pull request).
Now Windows 8.1 is supported, for wdigest, livessp and, at least, NTLM and SHA1 hashes plus DPAPI keys.
Indeed Microsoft changed some structs... You should finally get a proper output. Be careful to update the mimikatz profile files, attached to the previous pull request.

Waiting your feedback.

**Comment by jeffmcjunkin** [comment]
@dfirfpi After updating to your build of rekall and swapping out the AMD64.gz and I386.gz files, I see the correct hashes appearing in rekall's output, as shown below:

```
jeff@desktop:~/dev$ rekall --repository_path /home/jeff/dev/rekall-profiles/  -f ~/Downloads/win8_ie11.aff4 mimikatz
        LUID               Type       Sess         SID          Module   Info        Domain            User         SType                Secret             
-------------------- ---------------- ---- -------------------- ------- ------- ---------------- ---------------- --------- --------------------------------
00000000:003a160f    Interactive      2    S-1-5-21-2968750198- msv     Primary IE11Win8_1       IEUser           NTLM      fc525c9683e8fe067095ba2ddc971889
                                           2704521508-336054884                                                                                             
                                           1-1001                                                                                                           
00000000:003a160f    Interactive      2    S-1-5-21-2968750198- msv     Primary IE11Win8_1       IEUser           SHA1      e53d7244aa8727f5789b01d895914196
                                           2704521508-336054884                                                             0aad5d22                        
                                           1-1001                                                                                                           
00000000:003a15f4    Interactive      2    S-1-5-21-2968750198- msv     Primary IE11Win8_1       IEUser           NTLM      fc525c9683e8fe067095ba2ddc971889
                                           2704521508-336054884                                                                                             
                                           1-1001                                                                                                           
00000000:003a15f4    Interactive      2    S-1-5-21-2968750198- msv     Primary IE11Win8_1       IEUser           SHA1      e53d7244aa8727f5789b01d895914196
                                           2704521508-336054884                                                             0aad5d22                        
                                           1-1001                                                                                                           
2017-07-19 14:17:06,695:WARNING:root:Unable to properly initialize wdigest.

jeff@desktop:~/dev/rekall-profiles/v1.0/mimikatz$ sha1sum *
01fc895532cfbb9eb363d63e2580641ed9d47acd  AMD64.gz
5ccaa630027f94098a82c54e254f0e38f6c58867  AMD64.gz.old
4140b9ded7877d8a2cfd0a7c434198c3901dc97a  I386.gz
cecc0b918e5344a75452912102d74a21279dd816  I386.gz.old
jeff@desktop:~/dev/rekall-profiles/v1.0/mimikatz$ ls -lh
total 228K
-rw-rw-r-- 1 jeff jeff 76K Jul 19 14:03 AMD64.gz
-rw-rw-r-- 1 jeff jeff 33K Jul 19 14:03 AMD64.gz.old
-rw-rw-r-- 1 jeff jeff 75K Jul 19 14:03 I386.gz
-rw-rw-r-- 1 jeff jeff 31K Jul 19 14:03 I386.gz.old
```

Thanks for taking this on!

**Comment by jeffmcjunkin** [comment]
@dfirfpi Since you've looked at the mimikatz plugin recently, I have a follow-on question. How difficult do you think it would be to include credman as well? Given the below output from mimikatz.exe, it appears to be the credential package in Windows 8.1 that still stores the cleartext password:

```
mimikatz # sekurlsa::logonPasswords

Authentication Id : 0 ; 85654 (00000000:00014e96)
Session           : Interactive from 1
User Name         : IEUser
Domain            : IE11Win8_1
Logon Server      : IE11WIN8_1
Logon Time        : 7/19/2017 2:05:08 PM
SID               : S-1-5-21-2968750198-2704521508-3360548841-1001
        msv :
         [00000003] Primary
         * Username : IEUser
         * Domain   : IE11Win8_1
         * NTLM     : fc525c9683e8fe067095ba2ddc971889
         * SHA1     : e53d7244aa8727f5789b01d8959141960aad5d22
         [00010000] CredentialKeys
         * NTLM     : fc525c9683e8fe067095ba2ddc971889
         * SHA1     : e53d7244aa8727f5789b01d8959141960aad5d22
        tspkg :
        wdigest :
         * Username : IEUser
         * Domain   : IE11Win8_1
         * Password : (null)
        livessp :
        kerberos :
         * Username : IEUser
         * Domain   : IE11Win8_1
         * Password : (null)
        ssp :
        credman :
         [00000000]
         * Username : IE11Win8_1\IEUser
         * Domain   : IE11Win8_1\IEUser
         * Password : Passw0rd!
```

I completely understand if you just don't want to implement it :) On behalf of pentesters everywhere, I just wanted to check.

**Comment by dfirfpi** [comment]
Hi @jeffmcjunkin, you're very welcome!
Regarding the _credssp_ it should not be so much work... so yes, but please could you share the win8.1 ram image you're using, as you did for the win7?

**Comment by jeffmcjunkin** [comment]
@dfirfpi Yup, I'm uploading it now but here's the link: https://www.dropbox.com/s/umneboohto98wru/win8_ie11.aff4?dl=0

That should be ready in another hour or so.

Thanks!
