### ISSUE TITLE
Netscan not working with Win10x64

### ISSUE THREAD

**Issue by chinmay1** [google/rekall#253]
2017-04-22 18:00:35,700:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/netscan.py", line 209, in collect
    state) in self.generate_hits(run):
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/netscan.py", line 128, in generate_hits
    address_space=run.address_space)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/share/python/rekall-forensic/local/lib/python2.7/site-packages/rekall/plugins/windows/netscan.py", line 62, in __init__
    raise RuntimeError(repr(min_size))
RuntimeError: <Cant find object _TCP_LISTENER in profile <AMD64 profile tcpip/GUID/B93D662FAE7C47ADBFE5CC97C06CC3F31 (BasicPEProfile)>?>
RuntimeError: <Cant find object _TCP_LISTENER in profile <AMD64 profile tcpip/GUID/B93D662FAE7C47ADBFE5CC97C06CC3F31 (BasicPEProfile)>?>

Imaged via winpmem2.1post4
Netstat commands returns no output. 

Any help would be appreciated.
Thank you.

**Comment by scudette** [comment]
Netscan is particularly difficult to make work across every version because
it depends on undocumented structures. We find that this plugin often fails
either because it uses the wrong structure or because the structures we
have are not correct for that version of windows.

**Comment by chinmay1** [comment]
Is there anyway i can pull the network connections any other way?

**Comment by dennisieur** [comment]
@chinmay1 
Hi, can you provide your windws 10 x64 image or image version number?

**Comment by ctmayhew** [comment]
Hi - I'm having this same issue. Tried using 1.6.0 and the latest build from GitHub (1.6.3) - same issue.

`RuntimeError: <Cant find object _TCP_LISTENER in profile <AMD64 profile tcpip/GUID/B93D662FAE7C47ADBFE5CC97C06CC3F31 (BasicPEProfile)>?>`

I can supply my memory image - it is an image I create and does not contain client data.
