### ISSUE TITLE
Problems executing plugins on OSX 10.12 (live & memorydump)

### ISSUE THREAD

**Issue by pettai** [google/rekall#259]
This system is (still) running 10.12.4 (16E195) in line with the profile I used (taken from the lastest rekall-profiles):

```
(ReKall) MacBook-Air:~ myuser$ rekall [--profile 10.12.4_16E195.64bit] pslist
Traceback (most recent call last):
  File "/tmp/ReKall/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/rekal.py", line 95, in main
    user_session=user_session)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/args.py", line 433, in parse_args
    "Plugin %s is not available for this configuration" % plugin_name)
rekall.plugin.PluginError: Plugin pslist is not available for this configuration
```

Dumping the memory first using osxpmem.app and then run rekall on the dump, yields:

```
(ReKall) MacBook-Air:~ myuser$ rekall [--profile 10.12.4_16E195.64bit] -f MacBook-Air-10.12.4.aff4 pslist
  obj_offset           name          pid   alive    ppid   uid   is64bit           start_time                 cr3
-------------- -------------------- ----- -------- ------ ------ ------- ------------------------------ ---------------
2017-05-16 09:36:24,144:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/darwin/processes.py", line 48, in collect
    for proc in self.filter_processes():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/darwin/common.py", line 477, in filter_processes
    key=lambda proc: proc.pid)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 359, in __iter__
    for x in self.collect():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/common/efilter_plugins/search.py", line 182, in collect
    for result in producer.produce():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 802, in produce
    for row in self.collect():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 816, in collect
    for offset in self.session.GetParameter(self.hook_name):
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 761, in GetParameter
    result = self._RunParameterHook(item)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 796, in _RunParameterHook
    result = hook.calculate()
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/darwin/zones.py", line 72, in calculate
    for offset in zone.known_offsets:
AttributeError: 'list' object has no attribute 'known_offsets'

2017-05-16 09:36:24,145:CRITICAL:root:'list' object has no attribute 'known_offsets'. Try --debug for more information.
Traceback (most recent call last):
  File "/tmp/ReKall/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/rekal.py", line 106, in main
    user_session.Flush()
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 1125, in Flush
    hook(*args)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/cache.py", line 251, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 761, in GetParameter
    result = self._RunParameterHook(item)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 796, in _RunParameterHook
    result = hook.calculate()
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/darwin/misc.py", line 256, in calculate
    for task in self.session.plugins.pslist().filter_processes():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/darwin/common.py", line 477, in filter_processes
    key=lambda proc: proc.pid)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 359, in __iter__
    for x in self.collect():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/common/efilter_plugins/search.py", line 182, in collect
    for result in producer.produce():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 802, in produce
    for row in self.collect():
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugin.py", line 816, in collect
    for offset in self.session.GetParameter(self.hook_name):
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 761, in GetParameter
    result = self._RunParameterHook(item)
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/session.py", line 796, in _RunParameterHook
    result = hook.calculate()
  File "/tmp/ReKall/lib/python2.7/site-packages/rekall/plugins/darwin/zones.py", line 72, in calculate
    for offset in zone.known_offsets:
AttributeError: 'list' object has no attribute 'known_offsets'
```

**Comment by pettai** [comment]
This one was fixed by https://github.com/google/rekall/pull/262

**Comment by pettai** [comment]
a bit trigger happy. #262 didn't fix it, but was a little improvement...

**Comment by jwilsonsc** [comment]
Error messages associated with this include `ValueError: Zone 'socket' doesn't exist.` and `ValueError: Zone 'proc' doesn't exist.`

These seem to be related to https://github.com/google/rekall/blob/354d1a6e6ba12d296b995eca8d20b6803b88cb00/rekall-core/rekall/plugins/darwin/zones.py#L62, https://github.com/google/rekall/blob/354d1a6e6ba12d296b995eca8d20b6803b88cb00/rekall-core/rekall/plugins/darwin/zones.py#L120, and https://github.com/google/rekall/blob/354d1a6e6ba12d296b995eca8d20b6803b88cb00/rekall-core/rekall/plugins/darwin/zones.py#L187

When running these particular `zone_name`s, the return `zone = []`

As a note, running `lsmod` and `machine_info` in interactive mode does work with these profiles.
