### ISSUE TITLE
Win7SP1 via VMIFS: AttributeError: paravirt_enabled

### ISSUE THREAD

**Issue by mbushou** [google/rekall#260]
Good morning,

I think I've hit a bug trying to use Rekall against a VMIFS-provided (@tklengyel) Windows memory image.

Despite being a Windows image, in the output below it looks like we find ourselves in rekall/plugins/linux/common.py

This was run on Xen 4.7.1 using a stock win7sp1 VM taken from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

```
 $ rekall --version
This is Rekall Version 1.6.0 (Gotthard)
{'pep440': u'1.6.0', u'rc': u'0', u'version': u'1.6.0', 'error': 'Not in a git repository.', u'codename': u'Gotthard', u'post': u'0'}
```

`$ sudo /home/user/libvmi/tools/vmifs/vmifs name win7sp1_1 /home/user/vmifs  
`

`$ sudo rekall -vf /home/user/vmifs/mem pslist
`

```
2017-05-18 09:04:00,690:DEBUG:rekall.1:Logging level set to 10
2017-05-18 09:04:00,692:DEBUG:rekall.1:Voting round with base: None
2017-05-18 09:04:00,693:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2017-05-18 09:04:00,693:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2017-05-18 09:04:00,693:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2017-05-18 09:04:00,693:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2017-05-18 09:04:00,693:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2017-05-18 09:04:00,694:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2017-05-18 09:04:00,694:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2017-05-18 09:04:00,694:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2017-05-18 09:04:00,694:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2017-05-18 09:04:00,695:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2017-05-18 09:04:00,695:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2017-05-18 09:04:00,696:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2017-05-18 09:04:00,696:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2017-05-18 09:04:00,696:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2017-05-18 09:04:00,696:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2017-05-18 09:04:00,696:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2017-05-18 09:04:00,696:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2017-05-18 09:04:00,697:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2017-05-18 09:04:00,697:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2017-05-18 09:04:00,697:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2017-05-18 09:04:00,697:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2017-05-18 09:04:00,697:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2017-05-18 09:04:00,697:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2017-05-18 09:04:00,701:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2017-05-18 09:04:00,701:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2017-05-18 09:04:00,702:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/user/vmifs/mem_info
2017-05-18 09:04:00,702:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2017-05-18 09:04:00,702:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2017-05-18 09:04:00,703:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2017-05-18 09:04:00,703:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2017-05-18 09:04:00,703:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2017-05-18 09:04:00,703:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2017-05-18 09:04:00,705:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53
2017-05-18 09:04:00,706:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2017-05-18 09:04:00,706:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2017-05-18 09:04:00,706:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2017-05-18 09:04:00,706:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2017-05-18 09:04:00,706:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2017-05-18 09:04:00,707:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2017-05-18 09:04:00,707:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2017-05-18 09:04:00,707:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2017-05-18 09:04:00,707:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2017-05-18 09:04:00,707:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2017-05-18 09:04:00,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2017-05-18 09:04:00,708:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2017-05-18 09:04:00,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2017-05-18 09:04:00,708:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2017-05-18 09:04:00,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2017-05-18 09:04:00,708:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2017-05-18 09:04:00,708:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2017-05-18 09:04:00,709:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2017-05-18 09:04:00,709:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2017-05-18 09:04:00,709:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2017-05-18 09:04:00,709:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2017-05-18 09:04:00,710:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2017-05-18 09:04:00,710:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2017-05-18 09:04:00,710:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2017-05-18 09:04:00,710:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2017-05-18 09:04:00,710:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2017-05-18 09:04:00,710:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2017-05-18 09:04:00,712:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2017-05-18 09:04:00,712:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2017-05-18 09:04:00,712:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2017-05-18 09:04:00,712:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2017-05-18 09:04:00,712:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2017-05-18 09:04:00,712:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2017-05-18 09:04:00,713:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/index.gz
2017-05-18 09:04:00,715:DEBUG:rekall.1:Decoded in 0.00113415718079 sec.
2017-05-18 09:04:00,715:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/profile.gz
2017-05-18 09:04:00,716:DEBUG:rekall.1:Decoded in 7.08103179932e-05 sec.
2017-05-18 09:04:00,716:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/image_fingerprint.gz
2017-05-18 09:04:00,716:DEBUG:rekall.1:Decoded in 0.000269174575806 sec.
2017-05-18 09:04:00,717:INFO:rekall.1:Detected fingerprinted image 969fe4e449f529cec5307ac9b08bb6a385a61162
2017-05-18 09:04:00,717:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/profile.gz
2017-05-18 09:04:00,717:DEBUG:rekall.1:Decoded in 5.50746917725e-05 sec.
2017-05-18 09:04:00,717:DEBUG:rekall.1:Opened local file /home/user/kernels/rekall/4.8.6-300.fc25.x86_64.json
2017-05-18 09:04:01,589:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/mode_darwin_memory.gz
2017-05-18 09:04:01,590:DEBUG:rekall.1:Decoded in 0.000220060348511 sec.
2017-05-18 09:04:01,590:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/mode_live_api.gz
2017-05-18 09:04:01,590:DEBUG:rekall.1:Decoded in 5.91278076172e-05 sec.
2017-05-18 09:04:01,591:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/mode_windows_memory.gz
2017-05-18 09:04:01,591:DEBUG:rekall.1:Decoded in 5.3882598877e-05 sec.
2017-05-18 09:04:01,591:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/mode_linux_memory.gz
2017-05-18 09:04:01,592:DEBUG:rekall.1:Decoded in 7.08103179932e-05 sec.
2017-05-18 09:04:01,594:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': None, 'proc_regex': None, 'task': None, 'verbosity': 1, 'pids': None, 'method': ['InitTask']})
2017-05-18 09:04:01,595:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2017-05-18 09:04:01,597:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/kernel_slide.gz
2017-05-18 09:04:01,598:DEBUG:rekall.1:Decoded in 0.000131845474243 sec.
2017-05-18 09:04:01,598:DEBUG:rekall.1:Calculating page offset...
2017-05-18 09:04:01,598:DEBUG:rekall.1:Calculating page offset...
2017-05-18 09:04:01,599:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 855, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 914, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rekall/plugin.py", line 853, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 418, in GetVirtualAddressSpace
    for address_space in find_dtb.address_space_hits():
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 253, in address_space_hits
    address_space = self.VerifyHit(hit)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 160, in VerifyHit
    address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 243, in VerifyHit
    return self.CreateAS(hit)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 259, in CreateAS
    address_space_cls = self.GetAddressSpaceImplementation()
  File "/usr/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 188, in GetAddressSpaceImplementation
    if pv_info.paravirt_enabled and pv_info.paravirt_enabled == 1:
  File "/usr/lib/python2.7/site-packages/rekall/obj.py", line 1433, in __getattr__
    raise AttributeError(attr)
AttributeError: paravirt_enabled

2017-05-18 09:04:01,599:CRITICAL:root:paravirt_enabled. Try --debug for more information.
2017-05-18 09:04:01,600:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/sessions/969fe4e449f529cec5307ac9b08bb6a385a61162/image_fingerprint.gz
2017-05-18 09:04:01,600:DEBUG:rekall.1:Decoded in 7.70092010498e-05 sec.
2017-05-18 09:04:01,601:DEBUG:rekall.1:Opened local file /root/.rekall_cache/sessions/v1.0/inventory.gz
2017-05-18 09:04:01,602:DEBUG:rekall.1:Decoded in 0.00108122825623 sec.
2017-05-18 09:04:01,604:DEBUG:rekall.1:Flushed profile_obj in 0.00378704071045
Traceback (most recent call last):
  File "/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 855, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rekall/session.py", line 914, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rekall/plugin.py", line 853, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 418, in GetVirtualAddressSpace
    for address_space in find_dtb.address_space_hits():
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 253, in address_space_hits
    address_space = self.VerifyHit(hit)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 160, in VerifyHit
    address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 243, in VerifyHit
    return self.CreateAS(hit)
  File "/usr/lib/python2.7/site-packages/rekall/plugins/core.py", line 259, in CreateAS
    address_space_cls = self.GetAddressSpaceImplementation()
  File "/usr/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 188, in GetAddressSpaceImplementation
    if pv_info.paravirt_enabled and pv_info.paravirt_enabled == 1:
  File "/usr/lib/python2.7/site-packages/rekall/obj.py", line 1433, in __getattr__
    raise AttributeError(attr)
AttributeError: paravirt_enabled

```

**Comment by mbushou** [comment]
So in the output above I noticed a rekall profile belonging to another VM.  I deleted the rekall cache, tried again, and pslist works for Windows now.
