### ISSUE TITLE
Unable to get netscan

### ISSUE THREAD

**Issue by Vikran** [google/rekall#261]
Using rekal on windows 10 64 profile with live memory image 32GB, able to detect profile and is able to pslist , psscan, psxview but netstat dont show any connection (i have created persistence connection) without error , but netscan fails:

2017-05-24 21:01:14,752:DEBUG:rekall.1:Opened local file C:\Users\Username\.rekall_cache\sessions\v1.0\sessions\900548f86e7e4bb830dd5f29692a676644864d80\image_fingerprint.gz
2017-05-24 21:01:14,770:DEBUG:rekall.1:Decoded in 0.0 sec.
2017-05-24 21:01:14,775:DEBUG:rekall.1:Flushed profile_obj in 0.00300002098083
Traceback (most recent call last):
  File "rekal.py", line 8, in <module>
  File "site-packages\rekall\rekal.py", line 99, in main
  File "site-packages\rekall\session.py", line 862, in RunPlugin
  File "site-packages\rekall\session.py", line 859, in RunPlugin
  File "site-packages\rekall\plugin.py", line 726, in render
  File "site-packages\rekall\plugins\windows\netscan.py", line 209, in collect
  File "site-packages\rekall\plugins\windows\netscan.py", line 128, in generate_hits
  File "site-packages\rekall\registry.py", line 72, in __call__
  File "site-packages\rekall\plugins\windows\netscan.py", line 62, in __init__
RuntimeError: <Cant find object _TCP_LISTENER in profile <AMD64 profile tcpip/GUID/4B72023F35CF27430A12743915560F4B1 (BasicPEProfile)>?>
Failed to execute script rekal

Vikrant

**Comment by scudette** [comment]
The netscan (and sockets etc) plugins relies on mostly reverse engineered structures which have not been updated as windows versions evolved. It is more likely to work on win7 than win10 and maybe not even in every case.


When using Rekall in live mode you can run the WMI plugin on windows to see a list of sockets. We should probably provide a set of API specific network connection enumeration plugins.

**Comment by Vikran** [comment]
Thanks alot appreciate quick response will try one of the live mode with WMI.
