### ISSUE TITLE
RuntimeError: AttributeError raised: '_StdoutProxy' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by sidahmed-malaoui** [google/rekall#265]
I was trying to use `rekall` on a manually generated windows 7 memory image (manually crashed using the technique in this video [https://www.youtube.com/watch?v=0_9xoMbiBTk](https://www.youtube.com/watch?v=0_9xoMbiBTk)). 

I started rekall (v1.6) on this memory image with the command : `rekal -f MEMORY.DMP --verbose`. When I used the Tabulation, I got theses log messages [https://gist.github.com/sidahmed-malaoui/511992737856f5ff22ac092fb055d999](https://gist.github.com/sidahmed-malaoui/511992737856f5ff22ac092fb055d999) where `rekal` is trying to download something, then give this error : 
>RuntimeError: AttributeError raised: '_StdoutProxy' object has no attribute 'fileno'

**Comment by sidahmed-malaoui** [comment]
Here is the memory image used to produce the error [https://mega.nz/#!pthHQBqb!-R0QXHU12l44IQHA1AQjboiYpr2Gympr5lwXOq5ifj4](https://mega.nz/#!pthHQBqb!-R0QXHU12l44IQHA1AQjboiYpr2Gympr5lwXOq5ifj4) .

**Comment by sidahmed-malaoui** [comment]
Should I provide more informations ? or is this issue not important at all ?

**Comment by scudette** [comment]
As you can see from the logs, Rekall is trying to download the PDB file from Microsoft. Since PDB files are distributed as cab files, Rekall is trying to shell out to cab extract https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/tools/mspdb.py#L206 .

Either you do not have cabextract installed, or there is something weird about this system in shelling out. This might be a python problem  in the subprocess module since we just use it as documented.

I would suggest to first make sure cabextract is properly installed.

**Comment by sidahmed-malaoui** [comment]
I just installed `cabextract` using the command `sudo apt-get install cabextract`, and the same error still occurs : 

>Exception in thread Thread-117:ytes                                                                                                 
Traceback (most recent call last):                                                                                                  
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner                                                            
    self.run()                                                                                                                      
  File "/usr/lib/python2.7/threading.py", line 754, in run                                                                          
    self.__target(*self.__args, **self.__kwargs)                                                                                    
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 860, in run                   
    completions = list(buffer.completer.get_completions(document, complete_event))                                                  
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/IPython/terminal/ptutils.py", line 51, in get_completions        
    cursor_pos=document.cursor_position_col                                                                                         
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/IPython/core/completer.py", line 1179, in complete               
    self.matches = matcher(text)                                                                                                    
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/IPython/core/completer.py", line 767, in python_matches          
    matches = self.global_matches(text)                                                                                             
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/IPython/core/completer.py", line 316, in global_matches          
    self.namespace.keys(),                                                                                                          
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/session.py", line 1165, in keys                           
    return list(self)                                                                                                               
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/session.py", line 1154, in __iter__                       
    res.update(self["plugins"].__dir__())                                                                                           
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/session.py", line 160, in __dir__                         
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)                                                               
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugin.py", line 383, in GetActiveClasses                 
    if command_cls.is_active(session):                                                                                              
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugin.py", line 413, in is_active                        
    profile = (session.profile != None and
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/utils.py", line 1009, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/session.py", line 1055, in profile
    res = self.GetParameter("profile_obj")
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/session.py", line 761, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/session.py", line 796, in _RunParameterHook
    result = hook.calculate()
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 757, in calculate
    profile_obj = self.ScanProfiles()
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 625, in ScanProfiles
    return self._ScanProfiles()
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 683, in _ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 378, in DetectFromHit
    return self._test_rsds(rsds)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 383, in _test_rsds
    profile = self.VerifyProfile("nt/GUID/%s" % rsds.GUID_AGE)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 349, in VerifyProfile
    build_local_profile.fetch_and_parse(profile_name)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1229, in fetch_and_pe
    data = self._fetch_and_parse(module_name, guid)
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/tools/profile_tool.py", line 1188, in _fetch_and_e
    outfd.write(fetch_pdb_plugin.FetchPDBFile())
  File "/home/no_one/.rekall_env/local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 206, in FetchPDBFile
    stdout=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 382, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 818, in _get_handles
    c2pwrite = stdout.fileno()
RuntimeError: AttributeError raised: '_StdoutProxy' object has no attribute 'fileno'

**Comment by scudette** [comment]
What version of python have you got?

**Comment by sidahmed-malaoui** [comment]
Python 2 version : 
>2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118] on linux2

Python 3 version : 
>3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux

Default python version (got using `ls -l $(which python)` :
>lrwxrwxrwx 1 root root 9 juin   7 12:40 /usr/bin/python -> python2.7*
