### ISSUE TITLE
Latest Rekall cannot find resource messages.yaml

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#267]
Hi,

I cannot run the latest version of `rekall` from pip.

After installing, it gives the following error when i run it 

~~~
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 39, in <module>
    entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/__init__.py", line 3, in <module>
    from rekall_agent import client_actions
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/client_actions/__init__.py", line 5, in <module>
    from rekall_agent.client_actions import interrogate
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/client_actions/interrogate.py", line 31, in <module>
    from rekall_agent.messages import agent
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/messages/__init__.py", line 1, in <module>
    from rekall_agent.messages import agent
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/messages/agent.py", line 15, in <module>
    prefix="messages")
  File "/usr/local/lib/python2.7/dist-packages/rekall/resources.py", line 62, in get_resource
    raise IOError("Unable to find resource %s" % filename)
IOError: Unable to find resource messages.yaml
~~~

I can reproduce the error on a Docker container, so i think it's serious:

~~~Dockerfile
FROM ubuntu:latest

RUN apt update
RUN apt-get install -y \
        python-dev \
        python-pip \
        ncurses-dev \
        libffi-dev \
        libssl-dev

RUN pip install --upgrade setuptools pip wheel
RUN pip install rekall-agent rekall

ENTRYPOINT ["rekall"]
~~~

Thanks !

**Comment by scudette** [comment]
Currently the only supported way to install rekall is in a virtual
environment. Maybe the docker file can be changed to use a virtual
environment?

I think there are some bugs or inconsistencies with the way pip handles
resource paths between system install and virtual environment that make it
difficult to support both. Since virtual environments are the easiest and
universal way to distribute and install python packages we choose to only
support that.


On 26 Jun 2017 3:29 AM, "Mathieu Tarral" <notifications@github.com> wrote:

Hi,

I cannot run the latest version of rekall from pip.

After installing, it gives the following error when i run it

Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line
39, in <module>
    entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 2303, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py",
line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/__init__.py",
line 3, in <module>
    from rekall_agent import client_actions
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/client_actions/__init__.py",
line 5, in <module>
    from rekall_agent.client_actions import interrogate
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/client_actions/interrogate.py",
line 31, in <module>
    from rekall_agent.messages import agent
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/messages/__init__.py",
line 1, in <module>
    from rekall_agent.messages import agent
  File "/usr/local/lib/python2.7/dist-packages/rekall_agent/messages/agent.py",
line 15, in <module>
    prefix="messages")
  File "/usr/local/lib/python2.7/dist-packages/rekall/resources.py",
line 62, in get_resource
    raise IOError("Unable to find resource %s" % filename)
IOError: Unable to find resource messages.yam

I can reproduce the error on a Dockerfile:

FROM ubuntu:latest
RUN apt updateRUN apt-get install -y \
        python-dev \
        python-pip \
        ncurses-dev \
        libffi-dev \
        libssl-dev
RUN pip install --upgrade setuptools pip wheelRUN pip install
rekall-agent rekall
ENTRYPOINT ["rekall"]

Thanks !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/rekall/issues/267>, or mute the thread

**Comment by Wenzel** [comment]
Hi Michael,

thanks for your reply.

I tried with the virtualenv and it works.

Thanks for your help !
