### ISSUE TITLE
strange output format

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#294]
Hi, 
I have the following strange output format on psaux:

```
 PID   UID   GID                       Command                      
----- ----- ----- --------------------------------------------------
1     [__un [__un /sbin/init splash                                 
      named named                                                   
      _1119 _1122                                                   
      0     2                                                       
      uid]  gid]                                                    
      @ 0x8 @ 0x8                                                   
      80035 80035                                                   
      73D48 73D48                                                   
      4     8                                                       
2     [__un [__un [kthreadd]                                        
      named named                                                   
      _1119 _1122                                                   
      0     2                                                       
      uid]  gid]                                                    
      @ 0x8 @ 0x8                                                   
      80225 80225                                                   
      9669C 9669C                                                   
      4     8                                                       
```
kernel:
4.4.0-96-generic #119-Ubuntu SMP
Command line:
`# rekal -f ub.aff4 --profile 4.4.0-96-generic.json psaux`

and --verbose:
```
2017-10-12 13:00:07,737:DEBUG:rekall.1:Logging level set to 10
2017-10-12 13:00:07,738:DEBUG:rekall.1:Opened local file /root/rekall/4.4.0-96-generic.json
2017-10-12 13:00:08,485:DEBUG:rekall.1:Voting round with base: None
2017-10-12 13:00:08,485:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2017-10-12 13:00:08,486:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2017-10-12 13:00:08,486:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2017-10-12 13:00:08,486:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2017-10-12 13:00:08,486:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2017-10-12 13:00:08,487:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2017-10-12 13:00:08,487:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2017-10-12 13:00:08,487:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2017-10-12 13:00:08,487:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2017-10-12 13:00:08,487:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2017-10-12 13:00:08,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2017-10-12 13:00:08,488:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2017-10-12 13:00:08,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2017-10-12 13:00:08,488:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2017-10-12 13:00:08,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2017-10-12 13:00:08,488:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2017-10-12 13:00:08,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2017-10-12 13:00:08,488:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2017-10-12 13:00:08,488:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2017-10-12 13:00:08,489:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2017-10-12 13:00:08,489:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2017-10-12 13:00:08,489:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2017-10-12 13:00:08,489:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2017-10-12 13:00:08,560:INFO:rekall.1:Added aff4://5cebb59b-d459-4338-98ee-a48a069194c7/PhysicalMemory as physical memory
2017-10-12 13:00:08,564:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
2017-10-12 13:00:08,564:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
2017-10-12 13:00:08,564:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2017-10-12 13:00:08,564:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2017-10-12 13:00:08,564:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2017-10-12 13:00:08,566:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2017-10-12 13:00:08,566:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2017-10-12 13:00:08,567:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2017-10-12 13:00:08,567:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2017-10-12 13:00:08,567:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2017-10-12 13:00:08,567:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2017-10-12 13:00:08,567:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2017-10-12 13:00:08,567:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2017-10-12 13:00:08,567:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2017-10-12 13:00:08,567:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2017-10-12 13:00:08,567:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2017-10-12 13:00:08,568:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2017-10-12 13:00:08,568:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2017-10-12 13:00:08,568:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2017-10-12 13:00:08,568:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2017-10-12 13:00:08,568:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2017-10-12 13:00:08,568:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2017-10-12 13:00:08,569:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2017-10-12 13:00:08,569:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2017-10-12 13:00:08,569:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2017-10-12 13:00:08,569:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2017-10-12 13:00:08,569:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2017-10-12 13:00:08,569:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2017-10-12 13:00:08,569:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2017-10-12 13:00:08,569:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2017-10-12 13:00:08,570:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2017-10-12 13:00:08,570:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2017-10-12 13:00:08,570:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2017-10-12 13:00:08,570:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2017-10-12 13:00:08,571:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2017-10-12 13:00:08,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2017-10-12 13:00:08,571:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2017-10-12 13:00:08,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2017-10-12 13:00:08,571:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2017-10-12 13:00:08,571:INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
2017-10-12 13:00:08,580:DEBUG:rekall.1:Opened local file /root/rekall/4.4.0-96-generic.json
2017-10-12 13:00:09,225:DEBUG:rekall.1:Running plugin (psaux) with args (()) kwargs ({'profile': '4.4.0-96-generic.json', 'proc_regex': None, 'task': None, 'verbosity': 1, 'pids': None, 'method': ['InitTask']})
2017-10-12 13:00:09,227:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2017-10-12 13:00:09,256:DEBUG:rekall.1:Found /proc/kallsyms of size: 6329631
2017-10-12 13:00:09,401:DEBUG:rekall.1:Calculating page offset...
2017-10-12 13:00:09,401:DEBUG:rekall.1:Calculating page offset...
 PID   UID   GID                       Command                      
----- ----- ----- --------------------------------------------------
1     [__un [__un /sbin/init splash                                 
      named named                                                   
      _1119 _1122                                                   
      0     2                                                       
      uid]  gid]                                                    
      @ 0x8 @ 0x8                                                   
      80035 80035                                                   
      73D48 73D48                                                   
      4     8                                                       

```

**Comment by scudette** [comment]
Hi, 
 As you can see it is trying to print the uid and gid of the process, but this has been converted to a struct now (instead of simply an int like in previous version of linux kernel). It is actually an anonymous struct (which rekall names as unnamed_11190 etc). 

As you see this code:
https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/overlays/linux/linux.py#L72

Sets up a redirection from proc.gid to try a number of possible positions for the information. The first position is task.cred.uid.val (i.e. it just pulls the value from inside the struct). I just tested this on 4.10 kernel and it works fine. Are you running a version later than this commit https://github.com/google/rekall/commit/79ad2a6e206d49eee6460df11973089961beb9d9 which fixed the issue?  Or did we miss something with 4.4 kernels?

**Comment by fpusersuggest** [comment]
it's the stable version.. I mean I have installed rekall with:

```                                                
$ virtualenv  /tmp/MyEnv                           
New python executable in /tmp/MyEnv/bin/python     
Installing setuptools, pip...done.                 
$ source /tmp/MyEnv/bin/activate                   
$ pip install --upgrade setuptools pip wheel       
$ pip install rekall-agent rekall                  
```                                                

and the patch https://github.com/google/rekall/commit/79ad2a6e206d49eee6460df11973089961beb9d9 is not aplied. Then I have tried to install rekall from git with the following steps:

```                                                         
$ virtualenv  /tmp/MyEnv                                    
New python executable in /tmp/MyEnv/bin/python              
Installing setuptools, pip...done.                          
$ source /tmp/MyEnv/bin/activate                            
$ pip install --upgrade setuptools pip wheel                
$ git clone https://github.com/google/rekall.git rekall     
$ pip install --editable rekall/rekall-lib                  
$ pip install --editable rekall/rekall-core                 
$ pip install --editable rekall/rekall-agent                
$ pip install --editable rekall                             
```                                                         

but pip is stopped at:

```

(18ott2017) root@mypc:~/REKALL/18ott2017# pip install --editable rekall/rekall-core 
Obtaining file:///root/REKALL/18ott2017/rekall/rekall-core
Collecting artifacts==20160114 (from rekall-core==1.7.1.dev2)
Collecting pyaff4<0.30,>=0.24 (from rekall-core==1.7.1.dev2)
Collecting PyYAML==3.11 (from rekall-core==1.7.1.dev2)
Collecting acora==2.0 (from rekall-core==1.7.1.dev2)
Requirement already satisfied: arrow==0.7.0 in ./lib/python2.7/site-packages (from rekall-core==1.7.1.dev2)
Collecting rekall-efilter==1.5.2 (from rekall-core==1.7.1.dev2)
  Using cached rekall_efilter-1.5.2-py2-none-any.whl
Collecting intervaltree==2.1.0 (from rekall-core==1.7.1.dev2)
Collecting pycrypto==2.6.1 (from rekall-core==1.7.1.dev2)
Collecting pyelftools==0.24 (from rekall-core==1.7.1.dev2)
Collecting pyparsing==2.1.5 (from rekall-core==1.7.1.dev2)
  Using cached pyparsing-2.1.5-py2.py3-none-any.whl
Collecting pytz==2016.4 (from rekall-core==1.7.1.dev2)
  Using cached pytz-2016.4-py2.py3-none-any.whl
Collecting psutil<6.0,>=5.0 (from rekall-core==1.7.1.dev2)
  Using cached psutil-5.4.0.tar.gz
Collecting rekall-capstone==3.0.5 (from rekall-core==1.7.1.dev2)
  Could not find a version that satisfies the requirement rekall-capstone==3.0.5 (from rekall-core==1.7.1.dev2) (from versions: 3.0.4.post2)
No matching distribution found for rekall-capstone==3.0.5 (from rekall-core==1.7.1.dev2)
```

**Comment by scudette** [comment]
Oh thanks for the report. I must have forgotten to upload the rekall-capstone release. I just did so, or you can also install that from its git head at https://github.com/rekall-innovations/rekall-capstone

**Comment by fpusersuggest** [comment]
ok, I have finished the installation but it does not work, I have reinstalled but the error persist:

```
(19ott2017) root@dt2261016:~/REKALL/19ott2017# rekal -f /root/rekall/ub.aff4 --profile 4.4.0-97-generic.json psaux
Traceback (most recent call last):
  File "/root/REKALL/19ott2017/bin/rekal", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekal')()
  File "/root/REKALL/19ott2017/rekall/rekall-core/rekall/rekal.py", line 97, in main
    user_session=user_session)
  File "/root/REKALL/19ott2017/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/root/REKALL/19ott2017/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/root/REKALL/19ott2017/rekall/rekall-core/rekall/plugin.py", line 961, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/root/REKALL/19ott2017/rekall/rekall-core/rekall/plugin.py", line 427, in is_active
    profile = (session.profile != None and
  File "/root/REKALL/19ott2017/rekall/rekall-lib/rekall_lib/utils.py", line 1072, in __get__
    raise RuntimeError(message, sys.exc_info()[2])
RuntimeError: ("AttributeError raised: 'MemoryDataStore' object has no attribute 'QueryPredicateObject'", <traceback object at
0x7fa5bc096fc8>)

```

**Comment by scudette** [comment]
Hmm there seems to be a problem with the release versioning. I will press another RC today.

**Comment by scudette** [comment]
Ok I realized what was going on - pyaff4 made a new bugfix release but broke API compatibility. I made a new release of pyaff4==0.26.post2 which should fix this.

Rekall pins the pyaff4 version to >0.24<0.30 so it should just pick the new release and work.

**Comment by fpusersuggest** [comment]
```
(23ott2017) root@mypc:~/REKALL/23ott2017# pip install --editable rekall/rekall-core
Obtaining file:///root/REKALL/23ott2017/rekall/rekall-core
Collecting artifacts==20160114 (from rekall-core==1.7.1.dev3)
Collecting pyaff4<0.30,>=0.24 (from rekall-core==1.7.1.dev3)
  Downloading pyaff4-0.26.post3.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 112kB/s 
Collecting PyYAML==3.11 (from rekall-core==1.7.1.dev3)
Collecting acora==2.0 (from rekall-core==1.7.1.dev3)
Requirement already satisfied: arrow==0.7.0 in ./lib/python2.7/site-packages (from rekall-core==1.7.1.dev3)
Collecting rekall-efilter==1.6 (from rekall-core==1.7.1.dev3)
  Could not find a version that satisfies the requirement rekall-efilter==1.6 (from rekall-core==1.7.1.dev3) (from versions: 1.5.2)
No matching distribution found for rekall-efilter==1.6 (from rekall-core==1.7.1.dev3)
```

**Comment by scudette** [comment]
Oh you are installing from git head. If you want to do that, you will also need to install rekall-efilter from git head (since it is not released yet):

```
git clone https://github.com/rekall-innovations/efilter
pip install -e efilter/
```

Otherwise just install from pypi normally which will give the rc1 pre-release 17.0.rc1 (should have the commit in it):
```
pip install --pre rekall
```

**Comment by fpusersuggest** [comment]
looks better

```
2386  1000  1000  /bin/sh -c /usr/lib/x86_64-linux-gnu/zeitgeist    
                  /zeitgeist-maybe-vacuum; /usr/bin/zeitgeist-daemon
2390  1000  1000  /usr/bin/zeitgeist-daemon                         
2400  1000  1000  /usr/lib/x86_64-linux-gnu/zeitgeist-fts           
2494  1000  1000  /usr/lib/evolution/evolution-calendar-factory-    
                  subprocess --factory local --bus-name org.gnome.ev
                  olution.dataserver.Subprocess.Backend.Calendarx232
                  2x2 --own-path /org/gnome/evolution/dataserver/Sub
                  process/Backend/Calendar/2322/2                   
2508  1000  1000  bash                                              


```

**Comment by scudette** [comment]
Thanks for reporting :-).
