### ISSUE TITLE
rekall error (http 404 not found) while trying to fetch symbols for PDB file

### ISSUE THREAD

**Issue by ritesh175** [google/rekall#298]
I am seeing an error when I ran below command :
rekall fetch_pdb ntkrnlmp.pdb 7f7bb59aa81b44db8c030780ba2a8a2127f7

Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/7f7bb59aa81b44db8c030780ba2a8a2127f7/ntkrnlmp.pd_
2017-10-27 16:03:41,626:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 862, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 153, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 175, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2017-10-27 16:03:41,626:CRITICAL:root:HTTP Error 404: Not Found. Try --debug for more information.                          
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.0rc1', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 102, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 865, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 862, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 153, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 175, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

I have also verified that I am able to ping : msdl.microsoft.com 
does this mean MS does not have symbols for my kernel PDB file ?

**Comment by dsweet04** [comment]
We are seeing this problem on a regular basis. Every new patch changes the kernel and the systems are getting patched before the symbol files are available from Microsoft in many cases. This makes live analysis of systems extremely difficult.

**Comment by scudette** [comment]
According to https://blogs.msdn.microsoft.com/windbg/2017/10/18/update-on-microsofts-symbol-server/
 the situation is supposed to improve soon (or it is already improved?)

**Comment by srpape** [comment]
Possibly related, I'm seeing this error :
```
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/095BC104DF8F482AB8B6029096C1D22F2/ntkrnlmp.pd_
2017-10-30 16:54:34,765:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/papes/.local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/papes/.local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/home/papes/.local/lib/python2.7/site-packages/rekall/plugins/tools/mspdb.py", line 174, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
```

The [URL](http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/095BC104DF8F482AB8B6029096C1D22F2/ntkrnlmp.pd_) is indeed a 404, but if I change the "pd_" to "pdb", the link [works](http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/095BC104DF8F482AB8B6029096C1D22F2/ntkrnlmp.pdb).

**Comment by ritesh175** [comment]
Thanks srpape for useful datapoint, 
Was able to work around my issue by changing the script to fetch uncompressed file (changed the file extension from pd_ to pdb) and commented out entire code that was for decompressing the downloaded symbol file

**Comment by scudette** [comment]
Hah this is brilliant! Thanks for figuring this out. It is a huge help to not have to deal with CAB compressed files any more :-).

**Comment by smaresca** [comment]
Very nice! @scudette I bet it's a side effect of the new symbol server infrastructure. 

thanks as well  @ritesh175

**Comment by Alibm73** [comment]
hi everyone, I'm new to rekall and i have the same issue.
i want to change pd_ to pdb but i don't know how to do that

```
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/dd08dd42692b43f199a079d60e79d2171/ntkrnlmp.pd_
2019-02-11 15:53:45,226:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 174, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2019-02-11 15:53:45,226:CRITICAL:root:HTTP Error 404: Not Found. Try --debug for more information.                       
Traceback (most recent call last):
  File "/usr/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.6.0', 'console_scripts', 'rekall')()
  File "/usr/lib/python2.7/dist-packages/rekall/rekal.py", line 99, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/lib/python2.7/dist-packages/rekall/session.py", line 862, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/lib/python2.7/dist-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 152, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/lib/python2.7/dist-packages/rekall/plugins/tools/mspdb.py", line 174, in FetchPDBFile
    url_handler = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```
@srpape @scudette @smaresca 

i copied the link and changed it to pdb to see if it works, it worked and downloaded it manually, but i don't know how to apply the change.

**Comment by Alibm73** [comment]
this is the command i used
```
rekall fetch_pdb ntkrnlmp dd08dd42692b43f199a079d60e79d2171
```

**Comment by scudette** [comment]
This seems to work:

```
$ rekall fetch_pdb ntkrnlmp dd08dd42692b43f199a079d60e79d2171
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/dd08dd42692b43f199a079d60e79d2171/ntkrnlmp.pdb
```

Are you use a recent version?

**Comment by Alibm73** [comment]
my rekall version is:
```
This is Rekall Version 1.6.0 (Gotthard)
{'pep440': u'1.6.0', u'rc': u'0', u'version': u'1.6.0', 'error': 'Not in a git repository.', u'codename': u'Gotthard', u'post': u'0'}
```
I'm sorry if my questions are basic, I'm new to this.
I'm using the " https://drakvuf.com/ " documentation.
When i use:
```
rekall fetch_pdb ntkrnlmp dd08dd42692b43f199a079d60e79d2171
```
I get the above error and it is trying to fetch it from:
```
http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/dd08dd42692b43f199a079d60e79d2171/ntkrnlmp.pd_
```
but the correct version is:
```
http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/dd08dd42692b43f199a079d60e79d2171/ntkrnlmp.pdb
```
as you can see the end of the line is different. I don't know how to force it to use the <.pdb> version not the <pd_>version

@scudette

**Comment by scudette** [comment]
Yeah Microsoft changed the symbol server about 2-3 years back to serve uncompressed PDB instead of compressed ones. Vesion 1.6 is probably about that old. You should try a more recent version.

**Comment by Alibm73** [comment]
Thank you very much for your help
@scudette

**Comment by TimHi** [comment]
Hi, 
i'm experiencing the same issue like Alibm73:  
```
tim@240:~/Documents$ rekall fetch_pdb ntkrpamp 3844dbb920174967be7aa4a2c20430fa2
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/3844dbb920174967be7aa4a2c20430fa2/ntkrpamp.pdb
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/3844dbb920174967be7aa4a2c20430fa2/ntkrpamp.pd_  
2019-04-18 12:03:50,424:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/rekall_core-1.7.2rc1-py3.6.egg/rekall/plugins/tools/mspdb.py", line 245, in FetchPDBFile
    url, pdb_filename, guid, basename)
  File "/usr/local/lib/python3.6/dist-packages/rekall_core-1.7.2rc1-py3.6.egg/rekall/plugins/tools/mspdb.py", line 228, in DownloadUncompressedPDBFile
    url_handler = urllib.request.urlopen(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

I'm also preparing to use drakvuf but i'm running on:  
```
This is Rekall Version 1.7.2.rc1 (Hurricane Ridge)
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.2', 'error': 'Not in a git repository.', 'pep440': '1.7.2.rc1'}
```
Is this related to the symbol server or did i install it wrongly?

**Comment by Alibm73** [comment]
@TimHi hello Tim
<fetch_pdb> doesn't work with <ntkrpamp> anymore. use <ntkrnlmp> instead.
```python
rekall fetch_pdb ntkrpamp 3844dbb920174967be7aa4a2c20430fa2
```

**Comment by Alibm73** [comment]
@TimHi 
hello tim. 
rekall fetch_pdb doesn't work with <ntkrpamp> anymore. use <ntkrnlmp> instead.

**Comment by TimHi** [comment]
Thanks for the quick answer, worked fine!
