### ISSUE TITLE
"A DTB value was found but failed to verify" with Windows 10 memory image

### ISSUE THREAD

**Issue by ant1** [google/rekall#300]
I downloaded the Windows 10 memory image from http://bit.ly/526_challenge

I installed rekall in virtualenv  (version 1.7.0rc1)

When I try to run rekall against this memory image,  I get errors:

```
$ rekal.py -f Downloads/win10.img imageinfo
2017-10-29 18:01:13,990:CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
Traceback (most recent call last):                 
  File "/tmp/MyEnv/bin/rekal.py", line 112, in <module>
    main()
  File "/tmp/MyEnv/bin/rekal.py", line 109, in main
    user_session.Flush()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 1128, in Flush
    hook(*args)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/cache.py", line 251, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 764, in GetParameter
    result = self._RunParameterHook(item)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 799, in _RunParameterHook
    result = hook.calculate()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/windows/misc.py", line 279, in calculate
    result.append((system_time_offset, phys_as.read(system_time_offset, 8)))
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/standard.py", line 71, in read
    addr = int(addr)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

With volatility it seems ok:

```
% vol.py -f win10.img imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win10x64
                     AS Layer1 : Win10AMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (/home/redacted/Downloads/win10.img)
                      PAE type : No PAE
                           DTB : 0x1aa000L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2016-05-13 14:19:07 UTC+0000
     Image local date and time : 2016-05-13 07:19:07 -0700
```

**Comment by ant1** [comment]
This issue looks similar to issue #236 so I tried adding "--autodetect rsds"

```
$ rekal.py --autodetect rsds -f Downloads/win10.img imageinfo
        key          value
-------------------- -----
Kernel DTB           0x1aa000
NT Build             10240.th1.150709-1700s 0xf801f2a82000 / 
NT Build Ex          10240.16384.amd64fre.th1.150709-1700
Signed Drivers       -    
Time (UTC)           2016-05-13 14:19:07Z
Time (Local)         2016-05-13 07:19:07-0700
Sec Since Boot       3837.109375
NtSystemRoot         C:\Windows
```

**Comment by scudette** [comment]
Yes it looks like the profile index is confusing the autodetection. Specifying --autodetect rsds prevents the profile index from being used which stops the false positive from confusing the detector. 

We need to either improve the quality of the profile index or stop using it by default. 

Although, theoretically, a failure to autodetect should resume with the next autodetection method and not break everything. Maybe this is a bug.
