### ISSUE TITLE
RuntimeError: Unable to create http server.

### ISSUE THREAD

**Issue by kevthehermit** [google/rekall#304]
Trying to get the new agent up and running follwing the steps in the readme. 

```
(rekallenv) localadmin@rekall:~$ rekall agent_server_initialize_http ~/rekall_http/ --base_url http://127.0.0.1:8000/ --bind_port=8000 --client_writeback_path ~/.rekall_agent
Message
-------
Reusing existing CA keys in /home/localadmin/rekall_http/ca.cert.pem
Reusing existing server keys in /home/localadmin/rekall_http/server.certificate.pem
Server config at /home/localadmin/rekall_http/server.config.yaml exists. Remove to regenerate.
Writing client config file /home/localadmin/rekall_http/client.config.yaml
Done!  
(rekallenv) localadmin@rekall:~$ rekall -v --agent_config ~/rekall_http/server.config.yaml http_server2017-11-01 11:49:04,928:DEBUG:rekall.1:Logging level set to 10
2017-11-01 11:49:04,959:DEBUG:rekall.1:Running plugin (http_server) with args (()) kwargs ({'verbosity': 1})
2017-11-01 11:49:04,960:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall_agent/servers/http.py", line 714, in collect
    httpd = CreateServer(session=self.session)
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall_agent/servers/http.py", line 699, in CreateServer
    raise RuntimeError("Unable to create http server.")
RuntimeError: Unable to create http server.

2017-11-01 11:49:04,961:CRITICAL:root:Unable to create http server.. Try --debug for more information.
Traceback (most recent call last):
  File "/home/localadmin/rekallenv/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall/rekal.py", line 99, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall/session.py", line 859, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall/plugin.py", line 726, in render
    for row in self.collect():
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall_agent/servers/http.py", line 714, in collect
    httpd = CreateServer(session=self.session)
  File "/home/localadmin/rekallenv/local/lib/python2.7/site-packages/rekall_agent/servers/http.py", line 699, in CreateServer
    raise RuntimeError("Unable to create http server.")
RuntimeError: Unable to create http server.
(rekallenv) localadmin@rekall:~$ 
```

Looking at the current version in github there is no http.py its now http_server.py

Tried to install manually from github instead of pip and i get 

```
rekall: error: unrecognized arguments: agent_server_initialize_http
```

**Comment by scudette** [comment]
Hi
 the stand alone http server is now deprecated and removed. You need to use the appengine Dev server to run it locally.

These are the updated instructions http://dfrws2017.rekall-forensic.com/Rekall%20Workshop.pdf

Looks like we need to update the README file and remove the agent_server_initialize_http plugin (you do not need to configure the server any more).

**Comment by kevthehermit** [comment]
Seen thanks
