### ISSUE TITLE
AttributeError: paravirt_enabled

### ISSUE THREAD

**Issue by cchlcai** [google/rekall#308]
I used rekall to get process list from an ubuntu16.04 imagefile 
but it does not work.

root@heavencai-OptiPlex-7040:/# rekal -f test.img pslist --profile='/4.8.0-36-generic' --debug
2017-11-06 10:16:23,831:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/session.py", line 858, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/session.py", line 917, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/registry.py", line 72, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugin.py", line 860, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 418, in GetVirtualAddressSpace
    for address_space in find_dtb.address_space_hits():
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 253, in address_space_hits
    address_space = self.VerifyHit(hit)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/linux/common.py", line 160, in VerifyHit
    address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 243, in VerifyHit
    return self.CreateAS(hit)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/core.py", line 259, in CreateAS
    address_space_cls = self.GetAddressSpaceImplementation()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/plugins/linux/common.py", line 188, in GetAddressSpaceImplementation
    if pv_info.paravirt_enabled and pv_info.paravirt_enabled == 1:
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/obj.py", line 1433, in __getattr__
    raise AttributeError(attr)
AttributeError: paravirt_enabled

> /usr/local/lib/python2.7/dist-packages/rekall_core-1.6.0-py2.7.egg/rekall/obj.py(1433)__getattr__()
-> raise AttributeError(attr)
(Pdb)

**Comment by scudette** [comment]
Should be fixed in the recent release 1.7.2rc1
