### ISSUE TITLE
ImportError: fail to load the dynamic library

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#310]
Hi,

I tried to install the latest release of `Rekall` (`1.7.1`), system wide, in a docker environment based on Debian Jessie, and it raised an `ImportError`

~~~
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/__init__.py", line 30, in <module>
    from rekall.plugins.tools import disassembler
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/disassembler.py", line 29, in <module>
    import capstone
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 250, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
~~~

The Dockerfile is used for testing:
~~~Dockerfile
FROM debian:jessie

RUN apt-get update
RUN apt-get install -y python-dev python-pip ncurses-dev

# updating pip for Rekall installation
RUN pip install --upgrade setuptools pip wheel

# install rekall
RUN pip install rekall

ENTRYPOINT ["/usr/local/bin/rekall"]
~~~

Is this a bug introduced by python3 ? i never had this issue before.

Regards.

**Comment by scudette** [comment]
You are installing outside a virtual environment. This is not supported.

Please create a virtual environment first.

**Comment by scudette** [comment]
If you can figure out where the dll ended up we could add it to the dll search path here:

https://github.com/rekall-innovations/rekall-capstone/blob/master/patches/000001.patch#L8

**Comment by Wenzel** [comment]
Right here:

~~~
$ find / 'libcapstone.so'
/usr/local/lib/python2.7/dist-packages/libcapstone.so
~~~

**Comment by scudette** [comment]
Strange - If I try this with the system python I get:
```
>>> import distutils.sysconfig
>>> distutils.sysconfig.get_python_lib()
'/usr/lib/python2.7/dist-packages'
```

Which seems correct.

**Comment by Wenzel** [comment]
Rekall is installed in /usr/local here :)

**Comment by scudette** [comment]
What does distutils.sysconfig.get_python_lib() give?

**Comment by Wenzel** [comment]
Same

~~~
>>> import distutils.sysconfig
>>> distutils.sysconfig.get_python_lib()
'/usr/lib/python2.7/dist-packages'
~~~

**Comment by Wenzel** [comment]
Copying the library in `/usr/lib` is a temporary fix for me
~~~
$ cp /usr/local/lib/python2.7/dist-packages/libcapstone.so /usr/lib/
$ rekall
[1] Default session 11:32:55>
~~~

**Comment by scudette** [comment]
Should be fixed in the recent release 1.7.2rc1

**Comment by Wenzel** [comment]
An update with the latest release:
~~~Dockerfile
FROM debian:jessie

RUN apt-get update
RUN apt-get install -y python-dev python-pip ncurses-dev

# updating pip for Rekall installation
RUN pip install --upgrade setuptools pip wheel

# install rekall
RUN pip install rekall==1.7.2rc1

ENTRYPOINT ["/usr/local/bin/rekall"]
~~~

Output:
~~~
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.1'), set(['pyasn1-modules']))
~~~

And when i try to use the Python3 version

~~~Dockerfile
FROM debian:jessie

RUN apt-get update
RUN apt-get install -y python3-dev python3-pip ncurses-dev

# updating pip for Rekall installation
RUN pip3 install --upgrade setuptools pip wheel

# install rekall
RUN pip3 install rekall==1.7.2rc1

ENTRYPOINT ["/usr/local/bin/rekall"]
~~~

~~~
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python3.4/dist-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/usr/local/lib/python3.4/dist-packages/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/usr/local/lib/python3.4/dist-packages/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/usr/local/lib/python3.4/dist-packages/rekall/plugins/tools/__init__.py", line 30, in <module>
    from rekall.plugins.tools import disassembler
  File "/usr/local/lib/python3.4/dist-packages/rekall/plugins/tools/disassembler.py", line 29, in <module>
    import capstone
  File "/usr/local/lib/python3.4/dist-packages/capstone/__init__.py", line 252, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
~~~

So there is still an issue with the Python3 version of Rekall i think.

Thanks !

**Comment by scudette** [comment]
The first issue is again due to not installing in a virtual env - it seems to be using the pyasn1 from the system (/usr/lib/python2.7/dist-packages) instead of installing the later one (i have pyasn1==0.4.2). Can you force it upgrade that one too? What if you do `pip install --upgrade rekall==1.7.2rc1`

For the second search path problem, we now have this in the search path:

```
_path_list = [pkg_resources.resource_filename(__name__, 'lib'),
              join(split(__file__)[0], 'lib'),
              '',
              distutils.sysconfig.get_python_lib(),
              distutils.sysconfig.get_python_lib() + "/capstone",
              distutils.sysconfig.get_python_lib().replace("/usr/lib", "/usr/local/lib"),
              distutils.sysconfig.get_python_lib().replace("/usr/lib", "/usr/local/lib") + "/capstone",
              "/usr/local/lib/" if sys.platform == 'darwin' else '/usr/lib64']
```
Where is it putting `libcapstone.so` this time?

**Comment by Wenzel** [comment]
Hi,

> The first issue is again due to not installing in a virtual env

Yes, i understand that you are not supported, and i'm thankful for you trying to answer the issues i'm posting.

> What if you do pip install --upgrade rekall==1.7.2rc1

It worked.
~~~
root@7d11dbc48c46:/# pip install --upgrade rekall==1.7.2rc1
root@7d11dbc48c46:/# rekall
[1] Default session 02:47:38>
~~~


> Where is it putting libcapstone.so this time?
~~~
root@af5ee99a7f8d:/# find / -name libcapstone.so
/usr/local/lib/python3.4/dist-packages/capstone/libcapstone.so
~~~

**Comment by scudette** [comment]
Ok so it works with python 2.7. The problem with installing into the system is that now it upgraded the system version of pyasn1 and most distros have tools which need that old version. So this might have broken the distro tools :-(. 

We do have this in the search path:
```
distutils.sysconfig.get_python_lib().replace("/usr/lib", "/usr/local/lib") + "/capstone",
```

What is the value of `distutils.sysconfig.get_python_lib()` on python 3.4?

**Comment by Wenzel** [comment]
Here is why it cannot find the library:

~~~

root@af5ee99a7f8d:/# python3
>>> import distutils.sysconfig
>>> distutils.sysconfig.get_python_lib()
'/usr/lib/python3/dist-packages'
>>> distutils.sysconfig.get_python_lib().replace("/usr/lib", "/usr/local/lib") + "/capstone"
'/usr/local/lib/python3/dist-packages/capstone'
root@bf82be4a2238:/# ls /usr/local/lib/python3/dist-packages/capstone
ls: cannot access /usr/local/lib/python3/dist-packages/capstone: No such file or directory
~~~

**Comment by Wenzel** [comment]
Hi @scudette ,

Based on the information i provided here,
do you have an idea of how we could fix the search path for Python3 ?

**Comment by scudette** [comment]
I wonder if you can just tell pip where you want to install the shared object? 

This thread has a bunch of pointers for different command line flags for pip to control some behaviours:

https://stackoverflow.com/questions/18783390/python-pip-specify-a-library-directory-and-an-include-directory
