### ISSUE TITLE
    from rekall import utils ImportError: cannot import name 'utils'

### ISSUE THREAD

**Issue by xu-xiang** [google/rekall#311]
(MyEnv) sh-3.2# rekal -h
Traceback (most recent call last):
  File "/tmp/MyEnv/bin/rekal", line 7, in <module>
    from rekall.rekal import main
  File "/tmp/MyEnv/lib/python3.6/site-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/tmp/MyEnv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/tmp/MyEnv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/tools/__init__.py", line 50, in <module>
    from rekall.plugins.tools import live_darwin
  File "/tmp/MyEnv/lib/python3.6/site-packages/rekall/plugins/tools/live_darwin.py", line 42, in <module>
    from rekall import utils
ImportError: cannot import name 'utils'

**Comment by scudette** [comment]
Ah thanks for reporting. I have no OSX machine to test with :-(. That import should be 
```
from rekall_lib import utils
```

**Comment by xu-xiang** [comment]
and this file 

/Users/xuxiang/py3env/lib/python3.6/site-packages/rekall/plugins/addrspaces/pmem.py

**Comment by scudette** [comment]
This should be fixed with https://github.com/google/rekall/commit/aba11a544af5d73363add92e88990c004578c7ec
