### ISSUE TITLE
Issues using rekall with python3

### ISSUE THREAD

**Issue by tincho9** [google/rekall#316]
On python 3.6.1 (conda env.), installing latest version from git, using pip as specified in the instructions. When importing rekall:
```
from rekall import plugins
from rekall import session
```

I get the following exception:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-bf2839256dde> in <module>()
----> 1 from rekall import plugins
      2 from rekall import session

~/anaconda/envs/rekenv/lib/python3.5/site-packages/rekall/plugins/__init__.py in <module>()
      2 # pylint: disable=unused-import
      3 
----> 4 from rekall.plugins import addrspaces
      5 from rekall.plugins import common
      6 from rekall.plugins import core

~/anaconda/envs/rekenv/lib/python3.5/site-packages/rekall/plugins/addrspaces/__init__.py in <module>()
      6 from rekall.plugins.addrspaces import crash
      7 from rekall.plugins.addrspaces import elfcore
----> 8 from rekall.plugins.addrspaces import ewf
      9 from rekall.plugins.addrspaces import lime
     10 

~/anaconda/envs/rekenv/lib/python3.5/site-packages/rekall/plugins/addrspaces/ewf.py in <module>()
     24 
     25 from rekall import addrspace
---> 26 from rekall.plugins.tools import ewf
     27 
     28 

~/anaconda/envs/rekenv/lib/python3.5/site-packages/rekall/plugins/tools/__init__.py in <module>()
     31 from rekall.plugins.tools import dynamic_profiles
     32 from rekall.plugins.tools import ewf
---> 33 from rekall.plugins.tools import ipython
     34 from rekall.plugins.tools import json_tools
     35 from rekall.plugins.tools import mspdb

~/anaconda/envs/rekenv/lib/python3.5/site-packages/rekall/plugins/tools/ipython.py in <module>()
    186 # pylint: disable=protected-access
    187 
--> 188 class RekallHelper(site._Helper):
    189     """A More useful default help function."""
    190     HELP_MESSAGE = """Welocome to Rekall Memory Forensics.

AttributeError: module 'site' has no attribute '_Helper'
```

**Comment by scudette** [comment]
That seems strange. I just tested if pure python has it and it seems to:

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site._Helper
<class 'site._Helper'>
```

Is there something unusual about your python installation?

**Comment by scudette** [comment]
I think that code is supposed to add rekall's help to the standard python's help() command. I just checked and I dont think it works anyway. I think we can just delete that class since it is not useful.

**Comment by tincho9** [comment]
regular python3 installation that comes with ubuntu 16.04

**Comment by Wenzel** [comment]
I already had this issue.
Let me see if i can reproduce it in a Dockerfile...

**Comment by Wenzel** [comment]
@tincho9 you are not alone.
I reproduced the issue on my project, but not in a Dockerfile for now.
Let me work on it a bit.
~~~
vagrant@jessie:/vagrant/nitro$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 23, in <module>
    from nitro.nitro import Nitro
  File "/vagrant/nitro/nitro/nitro.py", line 2, in <module>
    from nitro.backends import get_backend
  File "/vagrant/nitro/nitro/backends/__init__.py", line 1, in <module>
    from nitro.backends.factory import get_backend
  File "/vagrant/nitro/nitro/backends/factory.py", line 3, in <module>
    from nitro.backends.windows import WindowsBackend
  File "/vagrant/nitro/nitro/backends/windows/__init__.py", line 1, in <module>
    from .backend import WindowsBackend
  File "/vagrant/nitro/nitro/backends/windows/backend.py", line 9, in <module>
    from rekall import plugins
  File "/home/vagrant/rekall/rekall-core/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/vagrant/rekall/rekall-core/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/home/vagrant/rekall/rekall-core/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/home/vagrant/rekall/rekall-core/rekall/plugins/tools/__init__.py", line 33, in <module>
    from rekall.plugins.tools import ipython
  File "/home/vagrant/rekall/rekall-core/rekall/plugins/tools/ipython.py", line 188, in <module>
    class RekallHelper(site._Helper):
AttributeError: 'module' object has no attribute '_Helper'
~~~

**Comment by Wenzel** [comment]
And here you go !!
~~~Dockerfile
FROM debian:jessie

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y python3-dev python3-pip ncurses-dev wget unzip virtualenv git vim \
        python3-libvirt python3-cffi python3-docopt build-essential gcc libtool automake pkg-config \
        check libglib2.0-dev libvirt-dev bison flex libjson-c-dev

WORKDIR /root

RUN pip3 install ioctl-opt

# clone libvmi
RUN git clone https://github.com/KVM-VMI/libvmi -b nitro
RUN cd libvmi && ./autogen.sh && ./configure --prefix=/usr && make && make install

RUN git clone https://github.com/google/rekall
RUN pip3 install --upgrade setuptools pip wheel
RUN pip3 install --editable rekall/rekall-lib
RUN pip3 install --editable rekall/rekall-core
RUN pip3 install --editable rekall/rekall-agent
RUN pip3 install --editable rekall

# install capstone in /usr/lib
RUN cp /usr/local/lib/python3.4/dist-packages/capstone/libcapstone.so /usr/lib

# clone nitro
RUN git clone https://github.com/KVM-VMI/nitro -b rekall_python3

ENTRYPOINT ["/root/nitro/main.py"]
~~~

**Comment by scudette** [comment]
Ah I see what is happening here. Somehow when installing inside a virtual env it creates its own site.py file and this works:
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site._Helper
<class 'site._Helper'>
>>> site.__file__
'/path/to/virtualenv/lib/python3.6/site.py'
>>>
```
But when trying to run without a virtual env there is a different site.py created:
```
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site._Helper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'site' has no attribute '_Helper'
>>> site.__file__
'/usr/lib/python3.6/site.py'
```

Since we officially only support running inside a virtual env we never seen this problem. We can probably remove this code though since it obviously does not work.

**Comment by Wenzel** [comment]
Hi,

your last commit fixed the issue
https://github.com/google/rekall/commit/da3862af202fdf39abead63001d08dd8a5cd677f

Thanks !
