### ISSUE TITLE
Python3: Unsupported operand for bytes and int

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#317]
Hi Michael,

I think i found another issue on the Python3 version:

The error:
~~~
Traceback (most recent call last):
  File "/root/get_symbols.py", line 100, in <module>
    main(docopt(__doc__))
  File "/root/get_symbols.py", line 50, in main
    s.RunPlugin("ssdt", output=output)
  File "/root/rekall/rekall-core/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/root/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/root/rekall/rekall-core/rekall/plugin.py", line 776, in render
    renderer.table_row(*new_row, **row)
  File "/root/rekall/rekall-core/rekall/plugins/renderers/data_export.py", line 92, in table_row
    arg, **column_spec)
  File "/root/rekall/rekall-core/rekall/ui/json_renderer.py", line 399, in Encode
    json_safe_item = object_renderer.EncodeToJsonSafe(item, **options)
  File "/root/rekall/rekall-core/rekall/ui/json_renderer.py", line 267, in EncodeToJsonSafe
    state = self.GetState(item, **options)
  File "/root/rekall/rekall-core/rekall/plugins/renderers/json_storage.py", line 332, in GetState
    symbol=utils.SmartUnicode(item))
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 100, in SmartUnicode
    return str(string)
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 587, in __str__
    self.address, max_distance=self.max_distance)[:self.max_count]
  File "/root/rekall/rekall-core/rekall/plugins/common/address_resolver.py", line 318, in format_address
    address, max_distance=max_distance)
  File "/root/rekall/rekall-core/rekall/plugins/common/address_resolver.py", line 335, in get_nearest_constant_by_address
    if module.profile != None:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 1086, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/root/rekall/rekall-core/rekall/plugins/windows/address_resolver.py", line 182, in profile
    return self.load_profile(force=False)
  File "/root/rekall/rekall-core/rekall/plugins/windows/address_resolver.py", line 185, in load_profile
    profile_name = self.detect_profile_name()
  File "/root/rekall/rekall-core/rekall/plugins/windows/address_resolver.py", line 106, in detect_profile_name
    profile = self.detect_profile_from_session()
  File "/root/rekall/rekall-core/rekall/plugins/windows/address_resolver.py", line 57, in detect_profile_from_session
    return self.session.GetParameter("%s_profile" % self.name)
  File "/root/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/rekall/rekall-core/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/root/rekall/rekall-core/rekall/plugins/windows/gui/win32k_core.py", line 973, in calculate
    module="win32k", minimal_match=3).GuessProfiles():
  File "/root/rekall/rekall-core/rekall/plugins/windows/index.py", line 99, in GuessProfiles
    for x in self.LookupIndex():
  File "/root/rekall/rekall-core/rekall/plugins/windows/index.py", line 91, in LookupIndex
    image_base, minimal_match=self.plugin_args.minimal_match):
  File "/root/rekall/rekall-core/rekall/plugins/common/profile_index.py", line 147, in LookupIndex
    minimal_match=minimal_match):
  File "/root/rekall/rekall-core/rekall/plugins/common/profile_index.py", line 140, in IndexHits
    symbols=symbols)
  File "/root/rekall/rekall-core/rekall/plugins/common/profile_index.py", line 108, in _TestProfile
    utils.encode_string (match))
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 1138, in encode_string
    result.extend(b"\\x%02x" % c)
TypeError: unsupported operand type(s) for %: 'bytes' and 'int'
~~~

The Dockerfile
~~~Dockerfile
FROM debian:jessie

RUN apt-get update
RUN apt-get install -y python3-dev python3-pip ncurses-dev wget unzip virtualenv git vim

WORKDIR /root

RUN virtualenv -p python3 venv

RUN git clone https://github.com/google/rekall
RUN venv/bin/pip install --upgrade setuptools pip wheel
RUN venv/bin/pip install --editable rekall/rekall-lib
RUN venv/bin/pip install --editable rekall/rekall-core
RUN venv/bin/pip install --editable rekall/rekall-agent
RUN venv/bin/pip install --editable rekall

RUN venv/bin/pip install docopt

# download get_symbols.py
RUN wget https://gist.githubusercontent.com/Wenzel/c570a17c9d91cbef1b84a22a9e390550/raw/25e25d4f9c90898b2e3198a977dda3788b6a8f67/get_symbols.py

# download memory dump
RUN wget 'http://files.sempersecurus.org/dumps/cridex_memdump.zip' && unzip cridex_memdump.zip && rm cridex_memdump.zip

ENTRYPOINT ["/root/venv/bin/python3", "/root/get_symbols.py", "/root/cridex.vmem"]
~~~

the modified `get_symbols.py`, python3 compatible
~~~Python
#!/usr/bin/env python3

"""

Usage:
  symbols.py <ram_dump>

Options:
  -h --help     Show this screen.

"""

import os
import logging
from io import StringIO
import json
from collections import defaultdict

# logging.basicConfig(level=logging.DEBUG)


from docopt import docopt
from rekall import session
from rekall import plugins

def main(args):
    ram_dump = args['<ram_dump>']
    home = os.getenv('HOME')
    # we need to make sure the directory exists otherwise rekall will complain
    # when we specify it in the profile_path
    local_cache_path = os.path.join(home, '.rekall_cache')
    try:
        os.makedirs(local_cache_path)
    except OSError: # already exists
        pass

    s = session.Session(
            filename=ram_dump,
            autodetect=["rsds"],
            logger=logging.getLogger(),
            autodetect_build_local='none',
            format='data',
            profile_path=[
                local_cache_path,
                "http://profiles.rekall-forensic.com"
            ])

    symbols = {}
    output = StringIO()
    s.RunPlugin("ssdt", output=output)
    symbols['syscall_table'] = json.loads(output.getvalue())
    symbols['offsets'] = get_offsets(s)



def get_offsets(session):
    offsets = defaultdict(dict)

    offsets['KPROCESS']['DirectoryTableBase'] = session.profile.get_obj_offset('_KPROCESS',
                                                                   'DirectoryTableBase')

    offsets['EPROCESS']['ActiveProcessLinks'] = session.profile.get_obj_offset('_EPROCESS',
                                                      'ActiveProcessLinks')

    offsets['EPROCESS']['ImageFileName'] = session.profile.get_obj_offset('_EPROCESS',
                                                              'ImageFileName')

    offsets['EPROCESS']['UniqueProcessId'] = session.profile.get_obj_offset('_EPROCESS',
                                                   'UniqueProcessId')

    offsets['EPROCESS']['InheritedFromUniqueProcessId'] = \
        session.profile.get_obj_offset('_EPROCESS', 'InheritedFromUniqueProcessId')

    offsets['EPROCESS']['Wow64Process'] = \
        session.profile.get_obj_offset('_EPROCESS', 'Wow64Process')

    offsets['EPROCESS']['CreateTime'] = \
        session.profile.get_obj_offset('_EPROCESS', 'CreateTime')

    offsets['EPROCESS']['SeAuditProcessCreationInfo'] = \
        session.profile.get_obj_offset('_EPROCESS', 'SeAuditProcessCreationInfo')

    offsets['SE_AUDIT_PROCESS_CREATION_INFO']['ImageFileName'] = \
        session.profile.get_obj_offset('_SE_AUDIT_PROCESS_CREATION_INFO', 'ImageFileName')

    offsets['OBJECT_NAME_INFORMATION']['Name'] = \
        session.profile.get_obj_offset('_OBJECT_NAME_INFORMATION', 'Name')

    offsets['EPROCESS']['Peb'] = session.profile.get_obj_offset('_EPROCESS', 'Peb')

    offsets['PEB']['ProcessParameters'] = \
        session.profile.get_obj_offset('_PEB', 'ProcessParameters')

    offsets['RTL_USER_PROCESS_PARAMETERS']['CommandLine'] = \
        session.profile.get_obj_offset('_RTL_USER_PROCESS_PARAMETERS', 'CommandLine')

    return offsets

if __name__ == '__main__':
    main(docopt(__doc__))
~~~

What do you think ?

Thanks Michael !

**Comment by scudette** [comment]
This should be fixed now. Can you please give it another try?

**Comment by Wenzel** [comment]
I tried, and the bug is gone.
Thanks Michael.
