### ISSUE TITLE
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'

### ISSUE THREAD

**Issue by juju4** [google/rekall#319]
Hello,

Since a week, I have an error in the execution of my ansible role for rekall.
https://travis-ci.org/juju4/ansible-rekall/jobs/300949910#L2092

Output is different at first or second execution depending if .rekallrc exists or not

On a local kitchen/docker.
```
root@adfbdfec6f71:~# mv ~/.rekallrc ~/.rekallrc.old
root@adfbdfec6f71:~# /usr/local/share/env-rekall/bin/rekall agent_server_initialize_http /etc/rekall-server/ --base_url http://127.0.0.1:8000/ --bind_port 80
00 --client_writeback_path ~/.rekall_agent
usage: rekall [-p PROFILE] [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F FORMAT]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
              [--logging_format LOGGING_FORMAT]
              [--performance {normal,fast,thorough}] [--live LIVE]
              [--cpu_quota CPU_QUOTA] [--load_quota LOAD_QUOTA] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--highlighting_style {manni,igor,lovelace,xcode,vim,autumn,abap,vs,rrt,native,perldoc,borland,arduino,tango,emacs,friendly,monokai,paraiso-dark,colorful,murphy,bw,pastie,rainbow_dash,algol_nu,paraiso-light,trac,default,algol,fruity}]
              [--name_resolution_strategies [{Module,Symbol,Export} [{Module,Symbol,Export} ...]]]
              [--autodetect_build_local_tracked [AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
              [--pagefile [PAGEFILE [PAGEFILE ...]]]
              [--autodetect {linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux} [{linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux} ...]]
              [--autodetect_threshold AUTODETECT_THRESHOLD]
              [--autodetect_build_local {full,basic,none}]
              [--autodetect_scan_length AUTODETECT_SCAN_LENGTH]
              [--agent_configuration AGENT_CONFIGURATION] [--version] [-]
rekall: error: unrecognized arguments: agent_server_initialize_http /etc/rekall-server/ --base_url http://127.0.0.1:8000/ --bind_port 8000 --client_writeback_path /home/kitchen/.rekall_agent
root@adfbdfec6f71:~# cat ~/.rekallrc
cache_dir: .rekall_cache
repository_path: [!!python/unicode 'https://github.com/google/rekall-profiles/raw/master',
  !!python/unicode 'http://profiles.rekall-forensic.com']
root@adfbdfec6f71:~# /usr/local/share/env-rekall/bin/rekall agent_server_initialize_http /etc/rekall-server/ --base_url http://127.0.0.1:8000/ --bind_port 8000 --client_writeback_path ~/.rekall_agent
Traceback (most recent call last):
  File "/usr/local/share/env-rekall/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.1', 'console_scripts', 'rekall')()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 81, in main
    user_session = session.InteractiveSession()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py", line 1259, in __init__
    config.MergeConfigOptions(self.state, self)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/config.py", line 245, in MergeConfigOptions
    config_data = GetConfigFile(session)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/config.py", line 202, in GetConfigFile
    result = yaml.safe_load(fd) or {}
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py", line 393, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py", line 118, in construct_sequence
    for child in node.value]
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py", line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in ".rekallrc", line 2, column 19
root@adfbdfec6f71:~# rm .rekallrc
root@adfbdfec6f71:~# rekall --version
This is Rekall Version 1.7.1 (Hurricane Ridge)
{'pep440': u'1.7.1', u'rc': u'0', u'version': u'1.7.1', 'error': 'Not in a git repository.', u'codename': u'Hurricane Ridge', u'post': u'0'}
```

Didn't find an issue matching yaml.constructor.
Any ideas where does it come? or a change of syntax?

Thanks

**Comment by scudette** [comment]
I have seen this before when whatever is creating the yaml file uses
yaml.dumps() instead of yaml.safe_dump(). I think we have some utilities in
yaml_utils.py which make the dumping easier.

On 19 Nov 2017 12:37 PM, "Julien" <notifications@github.com> wrote:

Hello,

Since a week, I have an error in the execution of my ansible role for
rekall.
https://travis-ci.org/juju4/ansible-rekall/jobs/300949910#L2092

Output is different at first or second execution depending if .rekallrc
exists or not

On a local kitchen/docker.

root@adfbdfec6f71:~# mv ~/.rekallrc ~/.rekallrc.old
root@adfbdfec6f71:~# /usr/local/share/env-rekall/bin/rekall
agent_server_initialize_http /etc/rekall-server/ --base_url
http://127.0.0.1:8000/ --bind_port 80
00 --client_writeback_path ~/.rekall_agent
usage: rekall [-p PROFILE] [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F FORMAT]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
              [--logging_format LOGGING_FORMAT]
              [--performance {normal,fast,thorough}] [--live LIVE]
              [--cpu_quota CPU_QUOTA] [--load_quota LOAD_QUOTA] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--highlighting_style
{manni,igor,lovelace,xcode,vim,autumn,abap,vs,rrt,native,perldoc,borland,arduino,tango,emacs,friendly,monokai,paraiso-dark,colorful,murphy,bw,pastie,rainbow_dash,algol_nu,paraiso-light,trac,default,algol,fruity}]
              [--name_resolution_strategies [{Module,Symbol,Export}
[{Module,Symbol,Export} ...]]]
              [--autodetect_build_local_tracked
[AUTODETECT_BUILD_LOCAL_TRACKED [AUTODETECT_BUILD_LOCAL_TRACKED ...]]]
              [--pagefile [PAGEFILE [PAGEFILE ...]]]
              [--autodetect
{linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux}
[{linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux}
...]]
              [--autodetect_threshold AUTODETECT_THRESHOLD]
              [--autodetect_build_local {full,basic,none}]
              [--autodetect_scan_length AUTODETECT_SCAN_LENGTH]
              [--agent_configuration AGENT_CONFIGURATION] [--version] [-]
rekall: error: unrecognized arguments: agent_server_initialize_http
/etc/rekall-server/ --base_url http://127.0.0.1:8000/ --bind_port 8000
--client_writeback_path /home/kitchen/.rekall_agent
root@adfbdfec6f71:~# cat ~/.rekallrc
cache_dir: .rekall_cache
repository_path: [!!python/unicode
'https://github.com/google/rekall-profiles/raw/master',
  !!python/unicode 'http://profiles.rekall-forensic.com']
root@adfbdfec6f71:~# /usr/local/share/env-rekall/bin/rekall
agent_server_initialize_http /etc/rekall-server/ --base_url
http://127.0.0.1:8000/ --bind_port 8000 --client_writeback_path
~/.rekall_agent
Traceback (most recent call last):
  File "/usr/local/share/env-rekall/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.1', 'console_scripts', 'rekall')()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py",
line 81, in main
    user_session = session.InteractiveSession()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py",
line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/session.py",
line 1259, in __init__
    config.MergeConfigOptions(self.state, self)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/config.py",
line 245, in MergeConfigOptions
    config_data = GetConfigFile(session)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/config.py",
line 202, in GetConfigFile
    result = yaml.safe_load(fd) or {}
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/__init__.py",
line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/__init__.py",
line 71, in load
    return loader.get_single_data()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py",
line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py",
line 48, in construct_document
    for dummy in generator:
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py",
line 393, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py",
line 118, in construct_sequence
    for child in node.value]
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py",
line 88, in construct_object
    data = constructor(self, node)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/yaml/constructor.py",
line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor
for the tag 'tag:yaml.org,2002:python/unicode'
  in ".rekallrc", line 2, column 19
root@adfbdfec6f71:~# rm .rekallrc
root@adfbdfec6f71:~# rekall --version
This is Rekall Version 1.7.1 (Hurricane Ridge)
{'pep440': u'1.7.1', u'rc': u'0', u'version': u'1.7.1', 'error': 'Not
in a git repository.', u'codename': u'Hurricane Ridge', u'post': u'0'}

Didn't find an issue matching yaml.constructor.
Any ideas where does it come? or a change of syntax?

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/rekall/issues/319>, or mute the thread

**Comment by nssamphone** [comment]
I have  somehow the same issue, after installing rekall I have run it once with -h switch, and I could see the version info and help of switches, but when I run it for the second time I face this yaml.constructor.ConstructorError  
>rekal -h
>    Traceback (most recent call last):
>      File "/tmp/MyEnv/bin/rekal", line 11, in <module>
>        sys.exit(main())
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/rekal.py", line 81, in main
>        user_session = session.InteractiveSession()
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
>        res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 1259, in __init__
>        config.MergeConfigOptions(self.state, self)
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/config.py", line 245, in MergeConfigOptions
>        config_data = GetConfigFile(session)
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/config.py", line 202, in GetConfigFile
>        result = yaml.safe_load(fd) or {}
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
>        return load(stream, SafeLoader)
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
>        return loader.get_single_data()
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
>        return self.construct_document(node)
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
>        for dummy in generator:
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/constructor.py", line 393, in construct_yaml_seq
>        data.extend(self.construct_sequence(node))
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/constructor.py", line 118, in construct_sequence
>        for child in node.value]
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/constructor.py", line 88, in construct_object
>        data = constructor(self, node)
>      File "/tmp/MyEnv/local/lib/python2.7/site-packages/yaml/constructor.py", line 414, in construct_undefined
>        node.start_mark)
>    yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
>      in ".rekallrc", line 2, column 19

**Comment by scudette** [comment]
I was able to reproduce this. When creating the .rekallrc file for the first time under python 2.7 we dump:

```
cache_dir: .rekall_cache
repository_path: [!!python/unicode 'https://github.com/google/rekall-profiles/raw/master',
  !!python/unicode 'http://profiles.rekall-forensic.com']
```

This then breaks when reading it back in on the next run.

**Comment by jeanru** [comment]
I have the same issue and reproduce it after input: conda env create -f environment.yaml

**Comment by Sashie** [comment]
There is a way for the tags to be read and for the class to be read properly when loading

**Comment by scudette** [comment]
Are you installing the latest github version? Note the commit above which fixes this issue (Nov 2017). Is it possible that the environment is bringing in an older version?

**Comment by scudette** [comment]
You can just work around it by pasting the file by hand in ~/.rekallrc

```
cache_dir: .rekall_cache                                                                                                                                                                   
repository_path:                                                                                                                                                                        
- https://github.com/google/rekall-profiles/raw/master                                                                                                                                     
- http://profiles.rekall-forensic.com     
```
