### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by seth1002** [google/rekall#325]
i got an error when i'm analyzing a VM mem dump via plugin - inspect_heap(0xfffffa800e6e8b30) .

**************************************************
0xfa800e6e8b30 spoolsv.exe   924
Heap 1: 0x200000 (LOW_FRAG)
Backend Info:

     Segment            End        Length  Data
------------------ -------------- -------- ----
.       0x200040         0x300000 1048512
2017-11-28 13:01:08,557:CRITICAL:rekall.1:Traceback (most recent call last):
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\plugins\windows\heap_analysis.py", line 154, in render
    self.render_process_heap_info(heap, renderer)
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\plugins\windows\heap_analysis.py", line 217, in render_process_heap_info
    if entry.Flags.LAST_ENTRY:
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\plugins\overlays\basic.py", line 311, in __getattr__
    return self.v() & mask
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\plugins\overlays\basic.py", line 272, in v
    return self.target_obj.v(vm=vm)
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\obj.py", line 652, in v
    data = self.obj_vm.read(self.obj_offset, self.obj_size)
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev2-py3.6.egg\rekall\addrspace.py", line 439, in read
    return data + ZEROER.GetZeros(length - len(data))

TypeError: must be str, not bytes

**Comment by scudette** [comment]
Thanks for this bug report. This seems to be a unicode/str issue with python3.

**Comment by scudette** [comment]
Should be fixed now with https://github.com/google/rekall/commit/0378be398b3f2c464d8f6c9aaf2b48f3d52548b5

**Comment by seth1002** [comment]
thank you! bug have been fixed
