### ISSUE TITLE
a bug of dns_cache |'set' object has no attribute 'obj_offset'

### ISSUE THREAD

**Issue by seth1002** [google/rekall#328]
[1] memory.dmp 17:10:36> plugins.dns_cache
-----------------------> plugins.dns_cache()
                    Name                          record           type       data
-------------------------------------------------------------------------------
2017-11-28 17:10:37,477:CRITICAL:rekall.1:Traceback (most recent call last):faec
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev7-py3.6.egg\rekall\session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev7-py3.6.egg\rekall\plugin.py", line 761, in render
    for row in self.collect():
  File "G:\Project\Git\rekall\Dev\lib\site-packages\rekall_core-1.7.2.dev7-py3.6.egg\rekall\plugins\windows\dns.py", line 382, in collect
    if entries.obj_offset in buckets:
AttributeError: 'set' object has no attribute 'obj_offset'
-----------------------------------------------------------------------------
    380                             include_current=True):
    381
--> 382                         if entries.obj_offset in buckets:
    383                             continue
    384

AttributeError: 'set' object has no attribute 'obj_offset'

**Comment by scudette** [comment]
Should be fixed in the recent release 1.7.2rc1
