### ISSUE TITLE
netscan is broken

### ISSUE THREAD

**Issue by scudette** [google/rekall#333]
```
Traceback (most recent call last):
  File "/home/mic/Dev3/bin/rekal", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekal')()
  File "/home/mic/rekall/rekall-core/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/mic/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/mic/rekall/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/mic/rekall/rekall-core/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/home/mic/rekall/rekall-core/rekall/plugins/windows/netscan.py", line 209, in collect
    state) in self.generate_hits(run):
  File "/home/mic/rekall/rekall-core/rekall/plugins/windows/netscan.py", line 130, in generate_hits
    for pool_obj in scanner.scan(run.start, run.length):
  File "/home/mic/rekall/rekall-core/rekall/plugins/windows/common.py", line 344, in scan
    for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
  File "/home/mic/rekall/rekall-core/rekall/scan.py", line 477, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "/home/mic/rekall/rekall-core/rekall/scan.py", line 412, in check_addr
    val = check.check(buffer_as, offset)
  File "/home/mic/rekall/rekall-core/rekall/plugins/windows/common.py", line 263, in check
    buffer_as, offset + self.tag_offset)
  File "/home/mic/rekall/rekall-core/rekall/scan.py", line 181, in check
    if buffer_as.data.startswith(self.needle, buffer_offset):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by rainaashutosh** [comment]
Doesnt look broken after commit https://github.com/google/rekall/commit/bf32dcbc1291f8ff70d39d1fc64497f065013cb9 . 
However , i m still seeing blank output even though tcpip structures as well as tcpip profile pdb exists (for windows 10)

**Comment by rainaashutosh** [comment]
![image](https://user-images.githubusercontent.com/16841220/34382765-39b0fb0e-eb37-11e7-9844-c00fe7540579.png)
This happens on this version of windows 10 while doing live memory analysis

**Comment by Kirantei** [comment]
This seems to be a python3 issue. The following patch will fix it (in a way... assuming an encoding), but I think this is a more fundamental problem with people specifying str's as needles

[netscanpatch.txt](https://github.com/google/rekall/files/2405117/netscanpatch.txt)
