### ISSUE TITLE
No valid DTB specified. Try the find_dtb plugin to search for the dtb.

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#343]
Hi, I am trying to use rekall on tails (the linux distro with tor) because I have suspect to be victim of many hacking operations. I hope I am not paranoid. Anyway I have run rekall well on tails, dump the sample memory and build the profile. I know my question is a bit oftopic because tails is very hardened distro and also is on live media then could be very difficult to solve the problem. But be patient. If u can't help me, it's not a problem. I'll try to install a new distro on an other pc and put the sample memory there.

Well, my problem now is I've got the following error:

`No valid DTB specified. Try the find_dtb plugin to search for the dtb.`

The following is the whole output:

```
(venv) Persistent/venv# rekall -f tails.box -p tails-4.13.0-1-amd64.json 
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).
We can remember it for you wholesale!
This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.
See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
[1] tails.box 01:05:38> lsmod
----------------------> lsmod()
2018-01-07 01:05:39,418:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/session.py", line 921, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/obj.py", line 153, in __call__
    return self._target(*(self._args + args), **new_kwargs)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugin.py", line 888, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 424, in GetVirtualAddressSpace
    for address_space in find_dtb.address_space_hits():
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 258, in address_space_hits
    address_space = self.VerifyHit(hit)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 164, in VerifyHit
    address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 248, in VerifyHit
    return self.CreateAS(hit)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 269, in CreateAS
    profile=self.profile)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/intel.py", line 285, in __init__
    raise TypeError("No valid DTB specified. Try the find_dtb"
TypeError: No valid DTB specified. Try the find_dtb plugin to search for the dtb.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-0b273662f9f8> in <module>()
----> 1 lsmod()

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/obj.pyc in __call__(self, *args, **kwargs)
    151         new_kwargs = self._kwargs.copy()
    152         new_kwargs.update(kwargs)
--> 153         return self._target(*(self._args + args), **new_kwargs)
    154 
    155     def get_default_arguments(self):

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
    867                 self.last = plugin_obj
    868             except (Exception, KeyboardInterrupt) as e:
--> 869                 self._HandleRunPluginException(ui_renderer, e)
    870 
    871             finally:

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
    860             try:
    861                 original_plugin_obj = plugin_obj
--> 862                 plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
    863                 if not plugin_obj:
    864                     raise ValueError(

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/session.pyc in _GetPluginObj(self, plugin_obj, *args, **kwargs)
    919         # Instantiate the plugin object.
    920         kwargs["session"] = self
--> 921         return plugin_cls(*args, **kwargs)
    922 
    923     def LoadProfile(self, name, use_cache=True):

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/obj.pyc in __call__(self, *args, **kwargs)
    151         new_kwargs = self._kwargs.copy()
    152         new_kwargs.update(kwargs)
--> 153         return self._target(*(self._args + args), **new_kwargs)
    154 
    155     def get_default_arguments(self):

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall_lib/registry.pyc in __call__(cls, *args, **kwargs)
     94 
     95     def __call__(cls, *args, **kwargs):
---> 96         res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
     97         res._object_id = UniqueObjectIdMetaclass.ID  # pylint: disable=protected-access
     98         UniqueObjectIdMetaclass.ID += 1

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugin.pyc in __init__(self, *args, **kwargs)
    886         if self.kernel_address_space == None:
    887             # Try to guess the AS
--> 888             self.session.plugins.load_as().GetVirtualAddressSpace()
    889 
    890             self.kernel_address_space = self.session.kernel_address_space

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.pyc in GetVirtualAddressSpace(self, dtb)
    422             self.session.logging.debug("DTB not specified. Delegating to "
    423                                        "find_dtb.")
--> 424             for address_space in find_dtb.address_space_hits():
    425                 with self.session:
    426                     self.session.kernel_address_space = address_space

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.pyc in address_space_hits(self)
    256         """
    257         for hit in self.dtb_hits():
--> 258             address_space = self.VerifyHit(hit)
    259             if address_space is not None:
    260                 yield address_space

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/linux/common.pyc in VerifyHit(self, dtb)
    162     def VerifyHit(self, dtb):
    163         """Returns a valid address_space if the dtb is valid."""
--> 164         address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
    165         if address_space:
    166             # Try to verify the profile by checking the linux_proc_banner.

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.pyc in VerifyHit(self, hit)
    246     def VerifyHit(self, hit):
    247         """Verify the hit for correctness, yielding an address space."""
--> 248         return self.CreateAS(hit)
    249 
    250     def address_space_hits(self):

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/core.pyc in CreateAS(self, dtb)
    267                 base=self.physical_address_space,
    268                 dtb=dtb, session=self.session,
--> 269                 profile=self.profile)
    270         except IOError:
    271             return None

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall_lib/registry.pyc in __call__(cls, *args, **kwargs)
     94 
     95     def __call__(cls, *args, **kwargs):
---> 96         res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
     97         res._object_id = UniqueObjectIdMetaclass.ID  # pylint: disable=protected-access
     98         UniqueObjectIdMetaclass.ID += 1

/home/amnesia/Persistent/venv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/intel.pyc in __init__(self, name, dtb, **kwargs)
    283 
    284         if not self.dtb != None:
--> 285             raise TypeError("No valid DTB specified. Try the find_dtb"
    286                             " plugin to search for the dtb.")
    287         self.name = (name or 'Kernel AS') + "@%#x" % self.dtb

TypeError: No valid DTB specified. Try the find_dtb plugin to search for the dtb.
[1] tails.box 01:05:42> 
```

**Comment by scudette** [comment]
What kind of image is this?

Note that for recent kernels there is KASLR and we need to calculate the kernel slide. Older versions of Rekall would invoke a scan for the KASLR but this tended to degenerate into a very expensive operation on live systems.

We currently rely on the presences of /proc/iomaps to determine the kernel slide efficiently and do not bother to scan for it. This means that it works well on live systems, and AFF4 images (which also acquire this) but does not work on flat files.

Maybe we can add a plugin to perform the kernel slide scan on demand.

**Comment by fpusersuggest** [comment]
Hi, thank you for the quick answer.
The image is aff4. The kernel is the following: 

`(venv) root@amnesia:/live/persistence/TailsData_unlocked/Persistent/venv# uname -a
Linux amnesia 4.13.0-1-amd64 #1 SMP Debian 4.13.10-1 (2017-10-30) x86_64 GNU/Linux
`
As I read on wikipedia this kernel version should not have KASLR enabled (melted)
The file /proc/iomaps does not exist on tails.

**Comment by fpusersuggest** [comment]
I close the bug because I have upgraded tails to the new version with kernel  4.14.
