### ISSUE TITLE
segfault 

### ISSUE THREAD

**Issue by whohoho** [google/rekall#345]
```

#rekal.py --verbose --repository_path ../../ --profile ./debian_4.9.0-4-amd64.json --live Memory --autodetect rsds

2018-01-09 01:32:56,816:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-01-09 01:32:56,819:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-01-09 01:32:56,820:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-01-09 01:32:56,821:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-01-09 01:32:56,822:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-01-09 01:32:56,822:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-01-09 01:32:56,822:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-01-09 01:32:56,823:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-01-09 01:32:56,827:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
2018-01-09 01:32:56,827:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-01-09 01:32:56,830:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-01-09 01:32:56,830:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-01-09 01:32:56,831:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-01-09 01:32:56,831:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-01-09 01:32:56,856:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
2018-01-09 01:32:56,866:DEBUG:rekall.1:Succeeded instantiating KCoreAddressSpace
2018-01-09 01:32:56,867:DEBUG:rekall.1:Voting round with base: KCoreAddressSpace
2018-01-09 01:32:56,868:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-01-09 01:32:56,868:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-01-09 01:32:56,868:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-01-09 01:32:56,869:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-01-09 01:32:56,869:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-01-09 01:32:56,869:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-01-09 01:32:56,870:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-01-09 01:32:56,873:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2018-01-09 01:32:56,873:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-01-09 01:32:56,875:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-01-09 01:32:56,875:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-01-09 01:32:56,876:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-01-09 01:32:56,877:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-01-09 01:32:56,877:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-01-09 01:32:56,878:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-01-09 01:32:56,878:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-01-09 01:32:56,878:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-01-09 01:32:56,880:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-01-09 01:32:56,880:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-01-09 01:32:56,881:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-01-09 01:32:56,881:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-01-09 01:32:56,881:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-01-09 01:32:56,882:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-01-09 01:32:56,883:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-01-09 01:32:56,884:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-01-09 01:32:56,884:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-01-09 01:32:56,884:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-01-09 01:32:56,885:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-01-09 01:32:56,885:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2018-01-09 01:32:56,889:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-01-09 01:32:56,889:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2018-01-09 01:32:56,889:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-01-09 01:32:56,890:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2018-01-09 01:32:56,891:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-01-09 01:32:56,891:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2018-01-09 01:32:56,892:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-01-09 01:32:56,892:INFO:rekall.1:Autodetected physical address space KCoreAddressSpace
2018-01-09 01:32:56,899:DEBUG:rekall.1:Logging level set to 10
2018-01-09 01:32:56,901:DEBUG:rekall.1:Opened local file /root/src/intr/rekall/rekall-core/debian_4.9.0-4-amd64.json

2018-01-09 01:32:59,309:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': './debian_4.9.0-4-amd64.json'})

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] Live(/proc/kcore) 01:33:00>
[1] Live(/proc/kcore) 01:33:24> dis
------------------------------> dis()
2018-01-09 01:33:24,804:DEBUG:rekall.1:Running plugin (dis) with args (()) kwargs ({})
2018-01-09 01:33:24,811:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-01-09 01:33:24,812:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
2018-01-09 01:33:25,215:DEBUG:rekall.1:Found /proc/kallsyms of size: 4574451
2018-01-09 01:33:25,264:DEBUG:rekall.1:Calculating page offset...
2018-01-09 01:33:25,265:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
2018-01-09 01:33:25,273:DEBUG:rekall.1:Page offset is ffff80000000
2018-01-09 01:33:25,275:DEBUG:rekall.1:Found paravirtualization type Xen
2018-01-09 01:33:25,286:DEBUG:rekall.1:Failed to verify dtb @ 0x1c07000
2018-01-09 01:33:25,286:INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
      address             rel              opcode                      instruction                comment
-------------------- -------------- -------------------- ---------------------------------------- -------


(gdb) bt
#0  _Py_CheckFunctionResult (func=func@entry=0x0, result=result@entry=0x7fa1d03863c8, where=where@entry=0x68c290 "PyEval_EvalFrameEx") at ../Objects/abstract.c:2193
#1  0x0000000000550b12 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3725
#2  0x000000000054ea78 in PyEval_EvalFrameEx (throwflag=0, f=0x1bf2f88) at ../Python/ceval.c:753
#3  _PyFunction_FastCall (co=co@entry=0x7fa2118f1810, args=<optimized out>, args@entry=0x7ffd27340210, nargs=nargs@entry=2, globals=globals@entry=0x7fa2118e7e58)
    at ../Python/ceval.c:4906
#4  0x0000000000558882 in _PyFunction_FastCallDict (func=func@entry=0x7fa2107018c8, args=args@entry=0x7ffd27340210, nargs=nargs@entry=2, kwargs=kwargs@entry=0x0)
    at ../Python/ceval.c:5008
#5  0x0000000000459fb1 in _PyObject_FastCallDict (kwargs=0x0, nargs=2, args=0x7ffd27340210, func=0x7fa2107018c8) at ../Objects/abstract.c:2310
#6  _PyObject_Call_Prepend (func=0x7fa2107018c8, obj=<optimized out>, args=0x7fa1f025d748, kwargs=0x0) at ../Objects/abstract.c:2373
#7  0x0000000000459c33 in _PyObject_FastCallDict (func=0x7fa1f02d4848, args=0x7ffd27340310, nargs=1, kwargs=0x0) at ../Objects/abstract.c:2331
#8  0x000000000045b552 in PyObject_CallFunctionObjArgs (callable=callable@entry=0x7fa1f02d4848) at ../Objects/abstract.c:2827
#9  0x00000000004e3605 in call_attribute (name=0x7fa1d0357330, attr=0x7fa1f02d4848, self=0x7fa1d03863c8) at ../Objects/typeobject.c:6230
#10 slot_tp_getattr_hook (self=0x7fa1d03863c8, name=0x7fa1d0357330) at ../Objects/typeobject.c:6272
#11 0x00000000004c812d in PyObject_GetAttr (name=0x7fa1d0357330, v=0x7fa1d03863c8) at ../Objects/object.c:891
#12 PyObject_GetAttrString (v=0x7fa1d03863c8, name=<optimized out>) at ../Objects/object.c:791
#13 0x00007fa2131e16dc in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1685
#14 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#15 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#16 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#17 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#18 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#19 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#20 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#21 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#22 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#23 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#24 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#25 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#26 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#27 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#28 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#29 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#30 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#31 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#32 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#33 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#34 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#35 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
#36 0x00007fa2131e16f3 in c_char_p_from_param (type=type@entry=0xfec668, value=value@entry=0x7fa1d03863c8) at ./Modules/_ctypes/_ctypes.c:1687
```
And so on....

**Comment by scudette** [comment]
Thanks for reporting !
