### ISSUE TITLE
I can't do something with vmem dump of Windows 10

### ISSUE THREAD

**Issue by normaliok** [google/rekall#348]
Hello to all. I've got a problem with a vmem dump of Windows 10 RAM. When I try to use any rekall command (imageinfo, pslist etc) I get same error:

$ rekall -f ./Inside.vmem imageinfo
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.1', 'console_scripts', 'rekall')()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall_lib/utils.py", line 1079, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 1060, in profile
    res = self.GetParameter("profile_obj")
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 766, in GetParameter
    result = self._RunParameterHook(item)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 801, in _RunParameterHook
    result = hook.calculate()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/vmem.py", line 70, in __init__
    self.add_run(v * 0x1000, p * 0x1000, l * 0x1000)
TypeError: unsupported operand type(s) for *: '_VMWARE_TAG' and 'int'

I found a message with kind of solution - use vmem file with vmss, but it helped me only with volatility, not with rekall. Volatility works fine with vmem+vmss.
Here is the link to my dump:
https://drive.google.com/drive/folders/19UOhQKV8Oq5kzX1CXPvJ5qxL43SEZZT3?usp=sharing

**Comment by scudette** [comment]
Thanks for sharing the image - this helped a lot. Note that since this image is so large you need to tell Rekall to scan more of it before autodetection will work:

```
rekall -f Inside.vmem  --autodetect_scan_length 3G pslist
```
