### ISSUE TITLE
Rekall 1.7.3.dev6 ======> UnicodeEncodeError: 'ascii' codec can't encode character u'\u03ff' in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by winnotor** [google/rekall#349]
When I try to request. For exemple pslist() 

There's this error 

UnicodeEncodeError: 'ascii' codec can't encode character u'\u03ff' in position 0: ordinal not in range(128)

=======

My Rekall Release is 
===========
rekall (1.7.3.dev6, /home/xxxx/rekallEnv/rekall)
rekall-agent (1.7.3.dev6, /home/xxxx/rekallEnv/rekall/rekall-agent)
rekall-capstone (3.0.5.post2)
rekall-core (1.7.3.dev6, /home/xxxx/rekallEnv/rekall/rekall-core)
rekall-efilter (1.6.0)
rekall-lib (1.7.2.dev6, /home/xxxx/rekallEnv/rekall/rekall-lib)
rekall-yara (3.6.3.1)

**Comment by scudette** [comment]
Could you please attach the full traceback with the -v flag? Are you using
python 2.7 or 3.6?

On 17 Jan 2018 5:30 AM, "winnotor" <notifications@github.com> wrote:

When I try to request. For exemple pslist()

There's this error

UnicodeEncodeError: 'ascii' codec can't encode character u'\u03ff' in
position 0: ordinal not in range(128)

=======
My Rekall Release is

rekall (1.7.3.dev6, /home/xxxx/rekallEnv/rekall)
rekall-agent (1.7.3.dev6, /home/xxxx/rekallEnv/rekall/rekall-agent)
rekall-capstone (3.0.5.post2)
rekall-core (1.7.3.dev6, /home/xxxx/rekallEnv/rekall/rekall-core)
rekall-efilter (1.6.0)
rekall-lib (1.7.2.dev6, /home/xxxx/rekallEnv/rekall/rekall-lib)
rekall-yara (3.6.3.1)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/rekall/issues/349>, or mute the thread

**Comment by winnotor** [comment]
Hi, I give you 
the release of python 
---------------------------------- 
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
---------------------------------- 

2018-01-18 15:53:44,026:DEBUG:rekall.1:Logging level set to 10
2018-01-18 15:53:44,026:DEBUG:rekall.1:Opened local file /mnt/memory/profile_volatility-4.4.0-53-generic.zip.json
2018-01-18 15:53:44,627:DEBUG:rekall.1:Voting round with base: None
2018-01-18 15:53:44,627:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-01-18 15:53:44,627:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-01-18 15:53:44,627:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-01-18 15:53:44,627:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-01-18 15:53:44,627:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-01-18 15:53:44,627:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-01-18 15:53:44,628:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-01-18 15:53:44,628:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-01-18 15:53:44,628:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-01-18 15:53:44,631:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-01-18 15:53:44,631:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-01-18 15:53:44,631:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-01-18 15:53:44,631:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-01-18 15:53:44,631:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-01-18 15:53:44,631:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-01-18 15:53:44,632:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-01-18 15:53:44,632:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-01-18 15:53:44,632:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-01-18 15:53:44,632:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-01-18 15:53:44,632:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-01-18 15:53:44,632:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-01-18 15:53:44,632:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-01-18 15:53:44,632:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-01-18 15:53:44,635:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-01-18 15:53:44,635:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-01-18 15:53:44,635:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at memory.raw_info
2018-01-18 15:53:44,635:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-01-18 15:53:44,635:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-01-18 15:53:44,635:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-01-18 15:53:44,635:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-01-18 15:53:44,635:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-01-18 15:53:44,635:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-01-18 15:53:44,637:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45
2018-01-18 15:53:44,637:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-01-18 15:53:44,637:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-01-18 15:53:44,637:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-01-18 15:53:44,637:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-01-18 15:53:44,637:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-01-18 15:53:44,637:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-01-18 15:53:44,637:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-01-18 15:53:44,637:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-01-18 15:53:44,637:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-01-18 15:53:44,637:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-01-18 15:53:44,637:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-01-18 15:53:44,638:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-01-18 15:53:44,638:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-01-18 15:53:44,638:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-01-18 15:53:44,638:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-01-18 15:53:44,638:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-01-18 15:53:44,638:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-01-18 15:53:44,639:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace
2018-01-18 15:53:44,639:DEBUG:rekall.1:Voting round with base: LimeAddressSpace
2018-01-18 15:53:44,639:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-01-18 15:53:44,639:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-01-18 15:53:44,639:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-01-18 15:53:44,640:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0 
2018-01-18 15:53:44,640:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-01-18 15:53:44,640:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-01-18 15:53:44,640:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-01-18 15:53:44,640:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-01-18 15:53:44,641:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-01-18 15:53:44,641:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-01-18 15:53:44,641:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-01-18 15:53:44,641:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-01-18 15:53:44,641:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-01-18 15:53:44,641:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-01-18 15:53:44,641:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-01-18 15:53:44,641:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-01-18 15:53:44,641:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-01-18 15:53:44,641:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-01-18 15:53:44,641:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-01-18 15:53:44,641:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-01-18 15:53:44,642:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-01-18 15:53:44,642:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-01-18 15:53:44,642:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-01-18 15:53:44,642:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-01-18 15:53:44,642:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-01-18 15:53:44,642:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-01-18 15:53:44,642:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-01-18 15:53:44,642:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-01-18 15:53:44,642:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-01-18 15:53:44,642:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-01-18 15:53:44,642:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-01-18 15:53:44,645:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-01-18 15:53:44,645:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-01-18 15:53:44,645:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-01-18 15:53:44,645:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-01-18 15:53:44,645:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-01-18 15:53:44,645:INFO:rekall.1:Autodetected physical address space LimeAddressSpace
2018-01-18 15:53:44,647:DEBUG:rekall.1:Opened local file /home/XXX/.rekall_cache/sessions/v1.0/sessions/index.gz
2018-01-18 15:53:44,710:DEBUG:rekall.1:Decoded in 0.0615050792694 sec.
Traceback (most recent call last):
  File "/home/XXX/rekallEnv/bin/rekal.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/rekal.py", line 114, in <module>
    main()
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and 
  File "/home/XXX/rekallEnv/rekall/rekall-lib/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    res = self.GetParameter("profile_obj")
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/plugins/guess_profile.py", line 747, in calculate
    self.session.physical_address_space)
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/cache.py", line 299, in DetectImage
    if item.Test(address_space):
  File "/home/XXX/rekallEnv/rekall/rekall-core/rekall/cache.py", line 320, in Test
    expected = utils.SmartStr(expected)
  File "/home/XXX/rekallEnv/rekall/rekall-lib/rekall_lib/utils.py", line 89, in SmartStr
    return str(string).encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03ff' in position 0: ordinal not in range(128)


Thank's

**Comment by scudette** [comment]
This should be fixed by 17e500326a21a9bbab52766e89bcb5290c15740b

Thanks for reporting :-).
