### ISSUE TITLE
Installation on Win7SP1 on Python 3.6.4x64 doesn't work

### ISSUE THREAD

**Issue by truekonrads** [google/rekall#359]
Hi,

Following instructions on Win7 64 bit fails as of 05/02/2018

```
C:\Tools>C:\Tools\Python36\scripts\virtualenv.exe rekall
Using base prefix 'c:\\tools\\python36'
New python executable in C:\Tools\rekall\Scripts\python.exe
Installing setuptools, pip, wheel...done.

C:\Tools>cd rekall

C:\Tools\rekall>Scripts\activate

(rekall) C:\Tools\rekall>pip install --upgrade setuptools pip wheel
Requirement already up-to-date: setuptools in c:\tools\rekall\lib\site-packages
Requirement already up-to-date: pip in c:\tools\rekall\lib\site-packages
Requirement already up-to-date: wheel in c:\tools\rekall\lib\site-packages

(rekall) C:\Tools\rekall>pip install rekall-agent rekall
Collecting rekall-agent
  Using cached rekall_agent-1.7.1.zip
Collecting rekall
  Using cached rekall-1.7.1.zip
Collecting future (from rekall-agent)
  Using cached future-0.16.0.tar.gz
Collecting rekall-lib<1.8,>=1.7.0rc1 (from rekall-agent)
  Using cached rekall_lib-1.7.2rc1.zip
Collecting sseclient==0.0.18 (from rekall-agent)
  Using cached sseclient-0.0.18.tar.gz
Collecting rekall-core<1.8,>=1.7.0rc1 (from rekall-agent)
  Using cached rekall-core-1.7.2rc1.zip
Collecting requests==2.18.1 (from rekall-agent)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting httplib2==0.9.2 (from rekall-agent)
  Using cached httplib2-0.9.2.zip
Collecting oauth2client==3.0.0 (from rekall-agent)
  Using cached oauth2client-3.0.0.tar.gz
Collecting filelock==2.0.6 (from rekall-agent)
  Using cached filelock-2.0.6.tar.gz
Collecting pathlib==1.0.1 (from rekall-agent)
  Using cached pathlib-1.0.1.tar.gz
Collecting portpicker==1.1.1 (from rekall-agent)
  Using cached portpicker-1.1.1.tar.gz
Collecting ipython<7.0,>=5.0.0 (from rekall)
  Downloading ipython-6.2.1-py3-none-any.whl (745kB)
    100% |████████████████████████████████| 747kB 437kB/s
Collecting pyreadline>=2.0 (from rekall)
  Using cached pyreadline-2.1.zip
Collecting arrow==0.10.0 (from rekall-lib<1.8,>=1.7.0rc1->rekall-agent)
  Using cached arrow-0.10.0.tar.gz
Collecting sortedcontainers==1.5.7 (from rekall-lib<1.8,>=1.7.0rc1->rekall-agent
)
  Using cached sortedcontainers-1.5.7-py2.py3-none-any.whl
Collecting six (from sseclient==0.0.18->rekall-agent)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 820kB/s
Collecting acora==2.0 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached acora-2.0.tar.gz
Collecting artifacts==20170909 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached artifacts-20170909.tar.gz
Collecting intervaltree==2.1.0 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached intervaltree-2.1.0.tar.gz
Collecting ipaddr==2.2.0 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached ipaddr-2.2.0.tar.gz
Collecting parsedatetime==2.4 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Downloading parsedatetime-2.4.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 1.3MB/s
Collecting psutil<6.0,>=5.0 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Downloading psutil-5.4.3-cp36-cp36m-win_amd64.whl (226kB)
    100% |████████████████████████████████| 235kB 1.1MB/s
Collecting pyaff4<0.30,>=0.26 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached pyaff4-0.26.post6.zip
Collecting pycryptodome==3.4.7 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Downloading pycryptodome-3.4.7-cp36-cp36m-win_amd64.whl (7.5MB)
    100% |████████████████████████████████| 7.5MB 53kB/s
Collecting pyelftools==0.24 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached pyelftools-0.24.tar.gz
Collecting pyparsing==2.1.5 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached pyparsing-2.1.5-py2.py3-none-any.whl
Collecting python-dateutil==2.6.1 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent
)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pytsk3==20170802 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached pytsk3-20170802.tar.gz
Collecting pytz==2017.3 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting rekall-capstone==3.0.5.post2 (from rekall-core<1.8,>=1.7.0rc1->rekall
-agent)
  Using cached rekall-capstone-3.0.5.post2.zip
Collecting rekall-efilter<1.7,>=1.6 (from rekall-core<1.8,>=1.7.0rc1->rekall-age
nt)
  Downloading rekall_efilter-1.6.0-py3-none-any.whl (101kB)
    100% |████████████████████████████████| 102kB 205kB/s
Collecting rekall-yara==3.6.3.1 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Using cached rekall_yara-3.6.3.1.tar.gz
Collecting pypiwin32==220 (from rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Downloading pypiwin32-220-cp36-none-win_amd64.whl (9.0MB)
    100% |████████████████████████████████| 9.0MB 45kB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.1->rekall-agent)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.3MB/s
Collecting idna<2.6,>=2.5 (from requests==2.18.1->rekall-agent)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 2.0MB/s
Collecting urllib3<1.22,>=1.21.1 (from requests==2.18.1->rekall-agent)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
    100% |████████████████████████████████| 133kB 1.3MB/s
Collecting certifi>=2017.4.17 (from requests==2.18.1->rekall-agent)
  Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 1.1MB/s
Collecting pyasn1>=0.1.7 (from oauth2client==3.0.0->rekall-agent)
  Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 1.5MB/s
Collecting pyasn1-modules>=0.0.5 (from oauth2client==3.0.0->rekall-agent)
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 911kB/s
Collecting rsa>=3.1.4 (from oauth2client==3.0.0->rekall-agent)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 1.6MB/s
Collecting decorator (from ipython<7.0,>=5.0.0->rekall)
  Downloading decorator-4.2.1-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from ipython<7.0,>=5.0.0->rekall)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython<7.0,>=5.0.0->rekall)
  Using cached simplegeneric-0.8.1.zip
Requirement already satisfied: setuptools>=18.5 in c:\tools\rekall\lib\site-pack
ages (from ipython<7.0,>=5.0.0->rekall)
Collecting jedi>=0.10 (from ipython<7.0,>=5.0.0->rekall)
  Downloading jedi-0.11.1-py2.py3-none-any.whl (250kB)
    100% |████████████████████████████████| 256kB 1.1MB/s
Collecting traitlets>=4.2 (from ipython<7.0,>=5.0.0->rekall)
  Using cached traitlets-4.3.2-py2.py3-none-any.whl
Collecting pickleshare (from ipython<7.0,>=5.0.0->rekall)
  Using cached pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pygments (from ipython<7.0,>=5.0.0->rekall)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython<7.0,>=5.0.0->rekall)
  Downloading prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
    100% |████████████████████████████████| 256kB 1.3MB/s
Collecting aff4-snappy==0.5.1 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0r
c1->rekall-agent)
  Downloading aff4-snappy-0.5.1.zip (64kB)
    100% |████████████████████████████████| 71kB 574kB/s
Collecting rdflib[sparql]==4.2.2 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7
.0rc1->rekall-agent)
  Downloading rdflib-4.2.2-py3-none-any.whl (344kB)
    100% |████████████████████████████████| 348kB 729kB/s
Collecting pyblake2==0.9.3 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1-
>rekall-agent)
  Downloading pyblake2-0.9.3.tar.gz (130kB)
    100% |████████████████████████████████| 133kB 547kB/s
Collecting expiringdict==1.1.4 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0
rc1->rekall-agent)
  Downloading expiringdict-1.1.4.tar.gz
Collecting html5lib (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall
-agent)
  Downloading html5lib-1.0.1-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 504kB/s
Collecting parso==0.1.1 (from jedi>=0.10->ipython<7.0,>=5.0.0->rekall)
  Downloading parso-0.1.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 1.5MB/s
Collecting ipython-genutils (from traitlets>=4.2->ipython<7.0,>=5.0.0->rekall)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython<7.0,>=5.0.0->reka
ll)
  Using cached wcwidth-0.1.7-py2.py3-none-any.whl
Collecting isodate (from rdflib[sparql]==4.2.2->pyaff4<0.30,>=0.26->rekall-core<
1.8,>=1.7.0rc1->rekall-agent)
  Downloading isodate-0.6.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 1.6MB/s
Collecting SPARQLWrapper; extra == "sparql" (from rdflib[sparql]==4.2.2->pyaff4<
0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall-agent)
  Downloading SPARQLWrapper-1.8.0.zip
Collecting webencodings (from html5lib->pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.
7.0rc1->rekall-agent)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl
Building wheels for collected packages: rekall-agent, rekall, future, rekall-lib
, sseclient, rekall-core, httplib2, oauth2client, filelock, pathlib, portpicker,
 pyreadline, arrow, PyYAML, acora, artifacts, intervaltree, ipaddr, parsedatetim
e, pyaff4, pyelftools, pytsk3, rekall-capstone, rekall-yara, simplegeneric, aff4
-snappy, pyblake2, expiringdict, SPARQLWrapper
  Running setup.py bdist_wheel for rekall-agent ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\1a\98\e
6\2b60fcfeb20cf3c46d3bf1f2c556d51cf07f7e3e3837c282d1
  Running setup.py bdist_wheel for rekall ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\1c\e8\b
c\3a09478524a9f3203fea9bf42b8d148c8a0c58a3f3c237de88
  Running setup.py bdist_wheel for future ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\c2\50\7
c\0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
  Running setup.py bdist_wheel for rekall-lib ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\9e\99\a
b\afbeb0d7222189c942fadc1ccb96f41f67b21d64af2defc0a7
  Running setup.py bdist_wheel for sseclient ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\f7\03\9
7\65ea06e608e033b2cf09afbd233f0be203710c463348b45fed
  Running setup.py bdist_wheel for rekall-core ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\65\ab\a
3\a543e74769cb1d94cbcf8861138a487adba8c6e5f20282ebdd
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\c7\67\6
0\e0be8ccfc1e08f8ff1f50d99ea5378e204580ea77b0169fb55
  Running setup.py bdist_wheel for oauth2client ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\b3\44\e
9\e56c5a2ca8869305f38254df012fb16b2807eb9d5d55291e8b
  Running setup.py bdist_wheel for filelock ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\97\9b\c
0\47c42b4f38b378a65671364fb62ae7822b68b13f8048221d07
  Running setup.py bdist_wheel for pathlib ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\2a\23\a
5\d8803db5d631e9f391fe6defe982a238bf5483062eeb34e841
  Running setup.py bdist_wheel for portpicker ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\ef\1c\c
3\9299e362e2df8b668faf414056577b83e6cfb6486e7afb41c2
  Running setup.py bdist_wheel for pyreadline ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\9a\c7\4
5\fd424eb3d7875d7a61221accd593e17c7953ed5ece5ee60be9
  Running setup.py bdist_wheel for arrow ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\f0\4d\9
b\692f17c2b531f0435ec1a73d6f936a4c0c252f23b66d5755e6
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\2c\f7\7
9\13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for acora ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\04\e9\8
6\a8f8d21bfc3ccca1152fc55f1e855775f717a43aaa1bf6a089
  Running setup.py bdist_wheel for artifacts ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\a2\24\8
f\6968e744a211b52cc39c5130a14b6a34696346ce2de8e02e52
  Running setup.py bdist_wheel for intervaltree ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\89\40\0
1\fa05b5a8202a472fb143815e7589fdf74369e710ca675cad11
  Running setup.py bdist_wheel for ipaddr ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\3a\75\e
f\8677a26e72d7fee90f46b1cb9d8cfdc0ffe9c738dfd22a54e5
  Running setup.py bdist_wheel for parsedatetime ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\c8\d7\9
6\ff02570dfadafc0aaa487becc1579c020f66627c4236330981
  Running setup.py bdist_wheel for pyaff4 ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\2b\a2\4
0\b941bf61faa6ed359708dc8153ad5dcc8e165f70fba6c49d7c
  Running setup.py bdist_wheel for pyelftools ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\f0\bd\5
e\ced1af292575c94420c85843a251b0c4a43546e68ff801134c
  Running setup.py bdist_wheel for pytsk3 ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\90\84\2
d\1d44f75ffe9b77866f8314848bf508ea6d75d6d4401c278664
  Running setup.py bdist_wheel for rekall-capstone ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\2d\30\d
f\e483a778316a7356b9818664f9e2bccc2976c30ed877e666dd
  Running setup.py bdist_wheel for rekall-yara ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\b2\d5\d
9\ebb8202affc862280ea765e667972f9eb5183c1e700a205ffb
  Running setup.py bdist_wheel for simplegeneric ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\7b\31\0
8\c85e74c84188cbec6a6827beec4d640f2bd78ae003dc1ec09d
  Running setup.py bdist_wheel for aff4-snappy ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\df\a8\3
4\475acdae008f440ce65a4710014655b1584cd154da8a1ea44d
  Running setup.py bdist_wheel for pyblake2 ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\75\e2\6
9\ae61234d3306f5c622efed7f1db5d12271d3bc95dca41176fe
  Running setup.py bdist_wheel for expiringdict ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\46\3d\0
5\362cb33e12d1373bfabb006be7478c380f1ee74dfc1ed703f6
  Running setup.py bdist_wheel for SPARQLWrapper ... done
  Stored in directory: C:\Users\buggerall\AppData\Local\pip\Cache\wheels\3c\b6\3
6\90a0877c0a7ac2933a16c446b535af632831b3fd692e1910fe
Successfully built rekall-agent rekall future rekall-lib sseclient rekall-core h
ttplib2 oauth2client filelock pathlib portpicker pyreadline arrow PyYAML acora a
rtifacts intervaltree ipaddr parsedatetime pyaff4 pyelftools pytsk3 rekall-capst
one rekall-yara simplegeneric aff4-snappy pyblake2 expiringdict SPARQLWrapper
Installing collected packages: future, six, python-dateutil, arrow, sortedcontai
ners, rekall-lib, chardet, idna, urllib3, certifi, requests, sseclient, PyYAML,
acora, artifacts, intervaltree, ipaddr, parsedatetime, psutil, aff4-snappy, isod
ate, pyparsing, SPARQLWrapper, rdflib, pyblake2, expiringdict, webencodings, htm
l5lib, pyaff4, pycryptodome, pyelftools, pytsk3, pytz, rekall-capstone, rekall-e
filter, rekall-yara, pypiwin32, rekall-core, httplib2, pyasn1, pyasn1-modules, r
sa, oauth2client, filelock, pathlib, portpicker, rekall-agent, decorator, colora
ma, simplegeneric, parso, jedi, ipython-genutils, traitlets, pickleshare, pygmen
ts, wcwidth, prompt-toolkit, ipython, pyreadline, rekall
Successfully installed PyYAML-3.12 SPARQLWrapper-1.8.0 acora-2.0 aff4-snappy-0.5
.1 arrow-0.10.0 artifacts-20170909 certifi-2018.1.18 chardet-3.0.4 colorama-0.3.
9 decorator-4.2.1 expiringdict-1.1.4 filelock-2.0.6 future-0.16.0 html5lib-1.0.1
 httplib2-0.9.2 idna-2.5 intervaltree-2.1.0 ipaddr-2.2.0 ipython-6.2.1 ipython-g
enutils-0.2.0 isodate-0.6.0 jedi-0.11.1 oauth2client-3.0.0 parsedatetime-2.4 par
so-0.1.1 pathlib-1.0.1 pickleshare-0.7.4 portpicker-1.1.1 prompt-toolkit-1.0.15
psutil-5.4.3 pyaff4-0.26.post6 pyasn1-0.4.2 pyasn1-modules-0.2.1 pyblake2-0.9.3
pycryptodome-3.4.7 pyelftools-0.24 pygments-2.2.0 pyparsing-2.1.5 pypiwin32-220
pyreadline-2.1 python-dateutil-2.6.1 pytsk3-20170802 pytz-2017.3 rdflib-4.2.2 re
kall-1.7.1 rekall-agent-1.7.1 rekall-capstone-3.0.5.post2 rekall-core-1.7.2rc1 r
ekall-efilter-1.6.0 rekall-lib-1.7.2rc1 rekall-yara-3.6.3.1 requests-2.18.1 rsa-
3.4.2 simplegeneric-0.8.1 six-1.11.0 sortedcontainers-1.5.7 sseclient-0.0.18 tra
itlets-4.3.2 urllib3-1.21.1 wcwidth-0.1.7 webencodings-0.5.1

(rekall) C:\Tools\rekall>rekall
Traceback (most recent call last):
  File "c:\tools\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\rekall\Scripts\rekall.exe\__main__.py", line 5, in <module>
  File "c:\tools\rekall\lib\site-packages\rekall\rekal.py", line 32, in <module>

    from rekall import args
  File "c:\tools\rekall\lib\site-packages\rekall\args.py", line 38, in <module>
    from rekall import config
  File "c:\tools\rekall\lib\site-packages\rekall\config.py", line 45, in <module
>
    from rekall_lib import yaml_utils
  File "c:\tools\rekall\lib\site-packages\rekall_lib\__init__.py", line 1, in <m
odule>
    from rekall_lib import crypto
  File "c:\tools\rekall\lib\site-packages\rekall_lib\crypto.py", line 13, in <mo
dule>
    from Crypto.PublicKey import RSA
  File "c:\tools\rekall\lib\site-packages\Crypto\PublicKey\RSA.py", line 42, in
<module>
    from Crypto.Math.Numbers import Integer
  File "c:\tools\rekall\lib\site-packages\Crypto\Math\Numbers.py", line 42, in <
module>
    from Crypto.Math._Numbers_gmp import Integer
  File "c:\tools\rekall\lib\site-packages\Crypto\Math\_Numbers_gmp.py", line 155
, in <module>
    _gmp.mpz_init = lib.__gmpz_init
  File "c:\tools\python36\Lib\ctypes\__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "c:\tools\python36\Lib\ctypes\__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function '__gmpz_init' not found

(rekall) C:\Tools\rekall>python --version
Python 3.6.4

```

**Comment by scudette** [comment]
This looks strange - everything builds ok but it cant run because it is trying to load a different library.
It might be similar to https://stackoverflow.com/questions/10938274/building-pycrypto-with-fastmath-gmp-or-mpir-via-pip-on-windows

Are you building using the MS visual studio for python? The python you are using is not installed in the usual spot (normally it is in c:\Program Files\Python36  - it is the standard python from python.org?

With the standard python from python.org and a fresh virtualenv on Windows 10 I can not replicate this problem - it all works fine:

```
[1] Default session 23:53:14> import sys
                         ...: sys.version
                         ...:
Out<23:53:14> '3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]'
```

**Comment by scudette** [comment]
So this does not look like a Rekall bug then? I will close this issue.
