### ISSUE TITLE
WARNING:rekall.1:UserAndGroups has no offset in object _ TOKEN. Check that vtypes has a concrete definition for it. | KeyError: 'pslist'

### ISSUE THREAD

**Issue by truekonrads** [google/rekall#360]
Image parsing fails:

```
(rekall) C:\Tools\rekall>rekall --version
This is Rekall Version 1.7.2.rc1 (Hurricane Ridge)
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.2', 'err
or': 'Not in a git repository.', 'pep440': '1.7.2.rc1'}
```

```
 Found possible _EPROCESS @ 0x256BF4 (In process csrss.exe      ) (DTB: 0x9B8747

 Found possible _EPROCESS @ 0x5A2FB1C (In process svchost.exe    ) (DTB: 0xFFFFE

 Found possible _EPROCESS @ 0x8DBAF9C (In process System         ) (DTB: 0xCD836

 Found possible _EPROCESS @ 0xF8F2586 (In process svchost.exe    ) (DTB: 0x4553)

 Found possible _EPROCESS @ 0x11DD3D1C (In process lsass.exe      ) (DTB: 0x6400

 Found possible _EPROCESS @ 0x1D477FD0 (In process cmd.exe        ) (DTB: 0x32B4

 Found possible _EPROCESS @ 0x2C7EE5A5 (In process svchost.exe    ) (DTB: 0x681)

 Found possible _EPROCESS @ 0x2DAF64FA (In process cmd.exe        ) (DTB: 0x8B41

 Found possible _EPROCESS @ 0x3114C35C (In process svchost.exe    ) (DTB: 0xFFFF

 Found possible _EPROCESS @ 0x43ED2B1C (In process cmd.exe        ) (DTB: 0xFFFF

 Found possible _EPROCESS @ 0x49EDC368 (In process cmd.exe        ) (DTB: 0xDAEB

 Found possible _EPROCESS @ 0x5337AAD0 (In process System         ) (DTB: 0x6635

 Found possible _EPROCESS @ 0x58445D24 (In process lsass.exe      ) (DTB: 0x6174

 Found possible _EPROCESS @ 0x5DEC3368 (In process cmd.exe        ) (DTB: 0xDAEB

 Found possible _EPROCESS @ 0x6D5C235C (In process csrss.exe      ) (DTB: 0xFFFF

 Found possible _EPROCESS @ 0x747C435C (In process svchost.exe    ) (DTB: 0xFFFF

 nt/GUID/14F98231AC784310A6BE9BC23B9A00E62 matched offset 0x351ec6+0xf800ad0b000

 nt/GUID/31E5E162F4AB471D887D8D1D10C0BFDF2 matched offset 0x25e52e+0xf800ad0b000

 nt/GUID/570007312A1C4EB491654DB1C1F0EA462 matched offset 0x252e66+0xf800ad0b000

 nt/GUID/74C4481DAB054EFFAB512D78D875147B2 matched offset 0x4ba3bf+0xf800ad0b000

 nt/GUID/966DF78E558F483199141B029DF5A9D51 matched offset 0x13e2f+0xf800ad0b0000

 nt/GUID/ABC202FD1EF6402288058D62F84F98B82 matched offset 0x2a195+0xf800ad0b0000

 nt/GUID/BC53472E009844A7A44CA9F7B403EF5B2 matched offset 0x217be0+0xf800ad0b000

 nt/GUID/CABD6868CA4A451D87651F0293CDC91A2 matched offset 0x2c6885+0xf800ad0b000

 nt/GUID/E0515BF0C2FC4134B26FE3C4B2C11B151 matched offset 0x3b725f+0xf800ad0b000

 nt/GUID/EF1817461B764CE097ED8718088681722 matched offset 0x2a335+0xf800ad0b0000

 nt/GUID/FDB83BA019284E92B15D62BA74910CE32 matched offset 0x2cd7fd+0xf800ad0b000

 nt/GUID/0D7763D351E54F68831519826DF579871 matched offset 0x2ed84f+0xf800ad0d000

 nt/GUID/201C9B6067DB4EA89E329FCB9792B3E71 matched offset 0x87ddbf+0xf800ad0d000

 nt/GUID/3359F0DB46004F91B2C7651697A792821 matched offset 0x20678f+0xf800ad0d000

 nt/GUID/47A5AC97343A4A7ABF14EFD9E99337722 matched offset 0x238fd+0xf800ad0d0000

 nt/GUID/5A50E2594F3E433ABAE37E3692A3CCE61 matched offset 0x83608+0xf800ad0d0000

 nt/GUID/6D214F525D704F65B2EA7DAC16BFE92C2 matched offset 0x21b04+0xf800ad0d0000

 nt/GUID/80A87123E83C40579E8319E5DB7B523C1 matched offset 0x19aa5b+0xf800ad0d000

 nt/GUID/948B7C2248CF4DEF871D3A06EE841BB82 matched offset 0x1b6c9e+0xf800ad0d000

 nt/GUID/A52153FF9F4D473EA2611B78F6F432422 matched offset 0x261e7+0xf800ad0d0000

 nt/GUID/BB882B07EC4F4B4EA29C61FE55012B962 matched offset 0x1b2bff+0xf800ad0d000

 nt/GUID/CB8EC0E66F7049FBAB2FAAB2D250127C2 matched offset 0xa26ff+0xf800ad0d0000

 nt/GUID/DE1ABD60DEDE4897A247282012E3EBD52 matched offset 0x9eaf+0xf800ad0d0000=

 nt/GUID/F1444F12AB8C466AB566BD474F89AF432 matched offset 0x21b04+0xf800ad0d0000

 nt/GUID/0292FE5A651143BFA48A2B8936D760B41 matched offset 0x620ae7+0xf800ad0f000

 nt/GUID/129B357411274E659853EBBD8CAEF8D22 matched offset 0x2a9348+0xf800ad0f000

 nt/GUID/2453972BBBF845E5845761C90A8B033C2 matched offset 0x2cc589+0xf800ad0f000

 nt/GUID/36F9BFB2A9B64E0D843543A6627E1BD12 matched offset 0x2cc7f9+0xf800ad0f000

 nt/GUID/541CCFD590254FF4963601267A2273E51 matched offset 0x49dff+0xf800ad0f0000

 nt/GUID/68D5AC8660F948B3B085D81007A3DCFC2 matched offset 0x3ccaaf+0xf800ad0f000

 nt/GUID/7BF6A15024324E9A90E26C4269114DD31 matched offset 0x1849f+0xf800ad0f0000

 nt/GUID/956A3749CE1043B3BB09558738F967E52 matched offset 0x57066b+0xf800ad0f000

 nt/GUID/AA1C6DFE1C9F4E858ACC76B54F42BEE61 matched offset 0x508b6f+0xf800ad0f000

 nt/GUID/C341B582E5464175BCBF5C48026A44541 matched offset 0x1849f+0xf800ad0f0000

 nt/GUID/D534C5029E0343E2874B39A1EA292BBE2 matched offset 0x2cc197+0xf800ad0f000

 nt/GUID/E1D666E6F2EB4BACB8AFFA3B98023CE42 matched offset 0x2cd33f+0xf800ad0f000

 nt/GUID/F6E0CFE308024593B1A73A12500E54A31 matched offset 0x48b5b+0xf800ad0f0000

 nt/GUID/05A6F49C5DD848FF983459421A78F1232 matched offset 0x345ccf+0xf800ad1b000

 nt/GUID/197D68CCA15544668586B96559C879CD2 matched offset 0x4134ef+0xf800ad1b000

 nt/GUID/2C39F687423840E793308F28C4FDE0CD2 matched offset 0x3053df+0xf800ad1b000

 nt/GUID/3E66FC25B7D24AA1941B998B342CED771 matched offset 0xe0721+0xf800ad1b0000

 nt/GUID/4DF2BCF20E1F4195AB47EBFC338639D61 matched offset 0x5df27f+0xf800ad1b000

 nt/GUID/5E22546695474BAFAE2A8BE520A14B022 matched offset 0x18f8f+0xf800ad1b0000
2018-02-05 12:21:55,607:WARNING:rekall.1:UserAndGroups has no offset in object _
TOKEN. Check that vtypes has a concrete definition for it.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
c:\tools\rekall\lib\site-packages\rekall\session.py in __getitem__(self, item)
   1175         try:
-> 1176             return super(DynamicNameSpace, self).__getitem__(item)
   1177         except KeyError:

KeyError: 'pslist'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
c:\tools\rekall\lib\site-packages\rekall_lib\utils.py in __get__(self, *args, **
kwargs)
   1090         try:
-> 1091             return super(safe_property, self).__get__(*args, **kwargs)
   1092         except AttributeError as e:

c:\tools\rekall\lib\site-packages\rekall\session.py in profile(self)
   1061
-> 1062         res = self.GetParameter("profile_obj")
   1063         return res

c:\tools\rekall\lib\site-packages\rekall\session.py in GetParameter(self, item,
default, cached)
    767         try:
--> 768             result = self._RunParameterHook(item)
    769             if result is not None:

c:\tools\rekall\lib\site-packages\rekall\session.py in _RunParameterHook(self, n
ame)
    802                     hook = cls(session=self)
--> 803                     result = hook.calculate()
    804

c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py in calculate(s
elf)
    760         if not profile_obj:
--> 761             profile_obj = self.ScanProfiles()
    762             if not profile_obj:

c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py in ScanProfile
s(self)
    628             self.session.SetCache("execution_phase", "ProfileAutodetect"
)
--> 629             return self._ScanProfiles()
    630         finally:

c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py in _ScanProfil
es(self)
    686             for method in needle_lookup[hit]:
--> 687                 profile = method.DetectFromHit(hit, offset, address_spac
e)
    688                 if profile:

c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py in DetectFromH
it(self, hit, filename_offset, address_space)
    285                         profile_obj)
--> 286                     if self.VerifyProfile(profile_obj):
    287                         return profile_obj

c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py in VerifyProfi
le(self, profile_name)
     74         if profile != None:
---> 75             return self._ApplyFindDTB(self.find_dtb_impl, profile)
     76

c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py in _ApplyFindD
TB(self, find_dtb_cls, profile)
     89             # Verify the DTB to make sure it is correct.
---> 90             if not find_dtb_plugin.VerifyHit(dtb):
     91                 return

c:\tools\rekall\lib\site-packages\rekall\plugins\windows\common.py in VerifyHit(
self, dtb)
    196
--> 197         return self.CreateAS(dtb)
    198

c:\tools\rekall\lib\site-packages\rekall\plugins\core.py in CreateAS(self, dtb)
    268                 dtb=dtb, session=self.session,
--> 269                 profile=self.profile)
    270         except IOError:

c:\tools\rekall\lib\site-packages\rekall_lib\registry.py in __call__(cls, *args,
 **kwargs)
     95     def __call__(cls, *args, **kwargs):
---> 96         res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwar
gs)
     97         res._object_id = UniqueObjectIdMetaclass.ID  # pylint: disable=p
rotected-access

c:\tools\rekall\lib\site-packages\rekall\plugins\windows\pagefile.py in __init__
(self, **kwargs)
    371         pte = self.session.profile._MMPTE()
--> 372         self.prototype_mask = pte.u.Proto.Prototype.mask
    373         self.transition_mask = pte.u.Trans.Transition.mask

c:\tools\rekall\lib\site-packages\rekall\obj.py in __getattr__(self, attr)
   1459         if result == None:
-> 1460             raise AttributeError(attr)
   1461

AttributeError: u

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
c:\tools\rekall\lib\site-packages\IPython\core\prefilter.py in prefilter_lines(s
elf, lines, continue_prompt)
    333                              for lnum, line in enumerate(llines) ])
    334         else:
--> 335             out = self.prefilter_line(llines[0], continue_prompt)
    336
    337         return out

c:\tools\rekall\lib\site-packages\IPython\core\prefilter.py in prefilter_line(se
lf, line, continue_prompt)
    308             return normal_handler.handle(line_info)
    309
--> 310         prefiltered = self.prefilter_line_info(line_info)
    311         # print "prefiltered line: %r" % prefiltered
    312         return prefiltered

c:\tools\rekall\lib\site-packages\IPython\core\prefilter.py in prefilter_line_in
fo(self, line_info)
    250         """
    251         # print "prefilter_line_info: ", line_info
--> 252         handler = self.find_handler(line_info)
    253         return handler.handle(line_info)
    254

c:\tools\rekall\lib\site-packages\IPython\core\prefilter.py in find_handler(self
, line_info)
    257         for checker in self.checkers:
    258             if checker.enabled:
--> 259                 handler = checker.check(line_info)
    260                 if handler:
    261                     return handler

c:\tools\rekall\lib\site-packages\IPython\core\prefilter.py in check(self, line_
info)
    413
    414     def check(self, line_info):
--> 415         obj = self.shell.user_ns.get(line_info.ifun)
    416         if isinstance(obj, Macro):
    417             return self.prefilter_manager.get_handler_by_name('macro')

c:\tools\rekall\lib\site-packages\rekall\session.py in get(self, item, default)
   1183     def get(self, item, default=None):
   1184         try:
-> 1185             return self[item]
   1186         except KeyError:
   1187             return default

c:\tools\rekall\lib\site-packages\rekall\session.py in __getitem__(self, item)
   1176             return super(DynamicNameSpace, self).__getitem__(item)
   1177         except KeyError:
-> 1178             if getattr(self["session"].plugins, item):
   1179                 return self._prepare_runner(item)
   1180

c:\tools\rekall\lib\site-packages\rekall\session.py in __getattr__(self, name)
    153         pslist_plugin = plugins.pslist()
    154         """
--> 155         plugin_cls = self.GetPluginClass(name)
    156         if plugin_cls == None:
    157             return plugin_cls

c:\tools\rekall\lib\site-packages\rekall\session.py in GetPluginClass(self, name
)
    133         """
    134         # Try to see if the requested plugin is active right now.
--> 135         metadata = self.plugin_db.GetActivePlugin(name)
    136         if metadata == None:
    137             return metadata

c:\tools\rekall\lib\site-packages\rekall\plugin.py in GetActivePlugin(self, plug
in_name)
    980         for command_metadata in self.db.get(plugin_name, []):
    981             plugin_cls = command_metadata.plugin_cls
--> 982             if plugin_cls.is_active(self.session):
    983                 results.append(command_metadata)
    984

c:\tools\rekall\lib\site-packages\rekall\plugin.py in is_active(cls, session)
    438
    439         else:
--> 440             return super(ProfileCommand, cls).is_active(session)
    441
    442     def __init__(self, profile=None, **kwargs):

c:\tools\rekall\lib\site-packages\rekall\plugin.py in is_active(cls, session)
    225
    226             if isinstance(mode, basestring):
--> 227                 if not session.GetParameter(mode):
    228                     return False
    229

c:\tools\rekall\lib\site-packages\rekall\session.py in GetParameter(self, item,
default, cached)
    766         # can get if from a hook.
    767         try:
--> 768             result = self._RunParameterHook(item)
    769             if result is not None:
    770                 return result

c:\tools\rekall\lib\site-packages\rekall\session.py in _RunParameterHook(self, n
ame)
    801                     self._hook_locks.add(name)
    802                     hook = cls(session=self)
--> 803                     result = hook.calculate()
    804
    805                     # Cache the output from the hook directly.

c:\tools\rekall\lib\site-packages\rekall\plugins\modes.py in calculate(self)
    113
    114     def calculate(self):
--> 115         if self.session.profile:
    116             return self.session.GetParameter("live_mode") == "API"
    117

c:\tools\rekall\lib\site-packages\rekall_lib\utils.py in __get__(self, *args, **
kwargs)
   1095             # Retain the original backtrace but re-raise a RuntimeError
to
   1096             # prevent the property from calling __getattr__.
-> 1097             raise RuntimeError(message, sys.exc_info()[2])
   1098
   1099

RuntimeError: ('AttributeError raised: u', <traceback object at 0x0000000005B4DE
08>)
[1] drg-first2017.ram 12:22:41>
[1] drg-first2017.ram 12:22:42>
[1] drg-first2017.ram 12:22:43> quit
I've been trying to tell you, someone has erased his memory.

2018-02-05 12:22:43,070:WARNING:rekall.1:SystemTime has no offset in object _KUS
ER_SHARED_DATA. Check that vtypes has a concrete definition for it.
2018-02-05 12:22:43,070:WARNING:rekall.1:SystemExpirationDate has no offset in o
bject _KUSER_SHARED_DATA. Check that vtypes has a concrete definition for it.
2018-02-05 12:22:43,070:WARNING:rekall.1:NtSystemRoot has no offset in object _K
USER_SHARED_DATA. Check that vtypes has a concrete definition for it.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\tools\python36\Lib\runpy.py in _run_module_as_main(mod_name, alter_argv)
    191         sys.argv[0] = mod_spec.origin
    192     return _run_code(code, main_globals, None,
--> 193                      "__main__", mod_spec)
    194
    195 def run_module(mod_name, init_globals=None,

c:\tools\python36\Lib\runpy.py in _run_code(code, run_globals, init_globals, mod
_name, mod_spec, pkg_name, script_name)
     83                        __package__ = pkg_name,
     84                        __spec__ = mod_spec)
---> 85     exec(code, run_globals)
     86     return run_globals
     87

C:\Tools\rekall\Scripts\rekall.exe\__main__.py in <module>()
      7 if __name__ == '__main__':
      8     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
----> 9     sys.exit(main())

c:\tools\rekall\lib\site-packages\rekall\rekal.py in main(argv)
    109         raise
    110     finally:
--> 111         user_session.Flush()
    112
    113 if __name__ == '__main__':

c:\tools\rekall\lib\site-packages\rekall\session.py in Flush(self)
   1130         """
   1131         for _, hook, args in self._flush_hooks:
-> 1132             hook(*args)
   1133
   1134

c:\tools\rekall\lib\site-packages\rekall\cache.py in Flush(self)
    273         """Write out all dirty items at once."""
    274         if self.fingerprint is None and self.session.HasParameter("profi
le"):
--> 275             self.SetFingerprint(self.session.GetParameter("image_fingerp
rint"))
    276
    277         if self.name and self.io_manager:

c:\tools\rekall\lib\site-packages\rekall\session.py in GetParameter(self, item,
default, cached)
    766         # can get if from a hook.
    767         try:
--> 768             result = self._RunParameterHook(item)
    769             if result is not None:
    770                 return result

c:\tools\rekall\lib\site-packages\rekall\session.py in _RunParameterHook(self, n
ame)
    801                     self._hook_locks.add(name)
    802                     hook = cls(session=self)
--> 803                     result = hook.calculate()
    804
    805                     # Cache the output from the hook directly.

c:\tools\rekall\lib\site-packages\rekall\plugins\windows\misc.py in calculate(se
lf)
    359
    360         system_time_offset = address_space.vtop(
--> 361             kuser_shared.SystemTime.obj_offset)
    362
    363         result.append((system_time_offset, phys_as.read(system_time_offs
et, 8)))

c:\tools\rekall\lib\site-packages\rekall\obj.py in __getattr__(self, attr)
   1458         result = self.m(attr)
   1459         if result == None:
-> 1460             raise AttributeError(attr)
   1461
   1462         return result

AttributeError: SystemTime
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 768, in GetPa
rameter
    result = self._RunParameterHook(item)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 803, in _RunP
arameterHook
    result = hook.calculate()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\windows\misc.py", line
361, in calculate
    kuser_shared.SystemTime.obj_offset)
  File "c:\tools\rekall\lib\site-packages\rekall\obj.py", line 1460, in __getatt
r__
    raise AttributeError(attr)
AttributeError: SystemTime

(rekall) C:\Tools\rekall\Scripts>rekall -f C:\Users\buggerall\Desktop\drg-first2
017.ram pslist
 nt/GUID/008BC13AC87A48BD99BDE6874AA0FC0A2 matched offset 0x11599+0xf800aca00000

 nt/GUID/0C68CEE0701341389A5C76A21320FFCC1 matched offset 0x2eff+0xf800aca00000=

Traceback (most recent call last):
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\addrspaces\intel.py", l
ine 311, in vtop
    return self._tlb.Get(vaddr)
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 76, in Get
    result = self.page_cache.Get(vaddr & self.PAGE_MASK)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 147, in New
Function
    return f(self, *args, **kw)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 336, in Get

    raise KeyError(key)
KeyError: 272681781424128

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\addrspaces\intel.py", l
ine 581, in read_pte
    return self._cache.Get(addr)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 147, in New
Function
    return f(self, *args, **kw)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 336, in Get

    raise KeyError(key)
KeyError: 7609336

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 519, in rea
d_partial
    data = self._cache.Get(chunk_number)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 147, in New
Function
    return f(self, *args, **kw)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 336, in Get

    raise KeyError(key)
KeyError: 1857

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\tools\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\rekall\Scripts\rekall.exe\__main__.py", line 9, in <module>
  File "c:\tools\rekall\lib\site-packages\rekall\rekal.py", line 98, in main
    user_session=user_session)
  File "c:\tools\rekall\lib\site-packages\rekall\args.py", line 432, in parse_ar
gs
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 142, in Metad
ata
    return self.plugin_db.GetActivePlugin(name)
  File "c:\tools\rekall\lib\site-packages\rekall\plugin.py", line 982, in GetAct
ivePlugin
    if plugin_cls.is_active(self.session):
  File "c:\tools\rekall\lib\site-packages\rekall\plugin.py", line 440, in is_act
ive
    return super(ProfileCommand, cls).is_active(session)
  File "c:\tools\rekall\lib\site-packages\rekall\plugin.py", line 227, in is_act
ive
    if not session.GetParameter(mode):
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 768, in GetPa
rameter
    result = self._RunParameterHook(item)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 803, in _RunP
arameterHook
    result = hook.calculate()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\modes.py", line 115, in
 calculate
    if self.session.profile:
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 1091, in __
get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 1062, in prof
ile
    res = self.GetParameter("profile_obj")
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 768, in GetPa
rameter
    result = self._RunParameterHook(item)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 803, in _RunP
arameterHook
    result = hook.calculate()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 761, in calculate
    profile_obj = self.ScanProfiles()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 629, in ScanProfiles
    return self._ScanProfiles()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 687, in _ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 280, in DetectFromHit
    kernel_base, test_as)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 235, in _match_profile_for_kernel_base
    kernel_base, address_space=test_as):
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\common\profile_index.py
", line 147, in LookupIndex
    minimal_match=minimal_match):
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\common\profile_index.py
", line 140, in IndexHits
    symbols=symbols)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\common\profile_index.py
", line 96, in _TestProfile
    if address_space.vtop(offset_to_check) == None:
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\addrspaces\intel.py", l
ine 316, in vtop
    aligned_vaddr, PhysicalAddressDescriptorCollector(self.session))
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\addrspaces\amd64.py", l
ine 119, in describe_vtop
    self._describe_pde(collection, pde_addr, vaddr)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\addrspaces\intel.py", l
ine 556, in _describe_pde
    pte_value = self.read_pte(pte_addr)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\addrspaces\intel.py", l
ine 583, in read_pte
    string = self.base.read(addr, 8)
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 488, in rea
d
    data = self.read_partial(addr, length)
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 523, in rea
d_partial
    chunk_number * self.CHUNK_SIZE, self.CHUNK_SIZE)
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 501, in cac
hed_read_partial
    return super(CachingAddressSpaceMixIn, self).read(addr, length)
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 589, in rea
d
    buf = self._read_chunk(addr, length)
  File "c:\tools\rekall\lib\site-packages\rekall\addrspace.py", line 652, in _re
ad_chunk
    start, end, run = self.runs.get_containing_range(addr)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 848, in get
_containing_range
    tmp, data = self.collection.get_value_smaller_than((address + 1, address + 1
))
KeyboardInterrupt

(rekall) C:\Tools\rekall\Scripts>rekall -f C:\Users\buggerall\Desktop\drg-first2
017.ram pslist

(rekall) C:\Tools\rekall\Scripts>rekall -f C:\Users\buggerall\Desktop\drg-first2
017.ram >..\drg-first2017.ram.pslist.txt




2018-02-05 12:29:48,281:ERROR:root:Aborted


(rekall) C:\Tools\rekall\Scripts>rekall -f C:\Users\buggerall\Desktop\drg-first2
017.ram pslist >..\drg-first2017.ram.pslist.txt
2018-02-05 12:31:50,599:WARNING:rekall.1:UserAndGroups has no offset in object _
TOKEN. Check that vtypes has a concrete definition for it.
Traceback (most recent call last):
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 1091, in __
get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 1062, in prof
ile
    res = self.GetParameter("profile_obj")
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 768, in GetPa
rameter
    result = self._RunParameterHook(item)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 803, in _RunP
arameterHook
    result = hook.calculate()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 761, in calculate
    profile_obj = self.ScanProfiles()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 629, in ScanProfiles
    return self._ScanProfiles()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 687, in _ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 286, in DetectFromHit
    if self.VerifyProfile(profile_obj):
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 75, in VerifyProfile
    return self._ApplyFindDTB(self.find_dtb_impl, profile)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\guess_profile.py", line
 90, in _ApplyFindDTB
    if not find_dtb_plugin.VerifyHit(dtb):
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\windows\common.py", lin
e 197, in VerifyHit
    return self.CreateAS(dtb)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\core.py", line 269, in
CreateAS
    profile=self.profile)
  File "c:\tools\rekall\lib\site-packages\rekall_lib\registry.py", line 96, in _
_call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\windows\pagefile.py", l
ine 372, in __init__
    self.prototype_mask = pte.u.Proto.Prototype.mask
  File "c:\tools\rekall\lib\site-packages\rekall\obj.py", line 1460, in __getatt
r__
    raise AttributeError(attr)
AttributeError: u

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\tools\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Tools\rekall\Scripts\rekall.exe\__main__.py", line 9, in <module>
  File "c:\tools\rekall\lib\site-packages\rekall\rekal.py", line 98, in main
    user_session=user_session)
  File "c:\tools\rekall\lib\site-packages\rekall\args.py", line 432, in parse_ar
gs
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 142, in Metad
ata
    return self.plugin_db.GetActivePlugin(name)
  File "c:\tools\rekall\lib\site-packages\rekall\plugin.py", line 982, in GetAct
ivePlugin
    if plugin_cls.is_active(self.session):
  File "c:\tools\rekall\lib\site-packages\rekall\plugin.py", line 440, in is_act
ive
    return super(ProfileCommand, cls).is_active(session)
  File "c:\tools\rekall\lib\site-packages\rekall\plugin.py", line 227, in is_act
ive
    if not session.GetParameter(mode):
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 768, in GetPa
rameter
    result = self._RunParameterHook(item)
  File "c:\tools\rekall\lib\site-packages\rekall\session.py", line 803, in _RunP
arameterHook
    result = hook.calculate()
  File "c:\tools\rekall\lib\site-packages\rekall\plugins\modes.py", line 115, in
 calculate
    if self.session.profile:
  File "c:\tools\rekall\lib\site-packages\rekall_lib\utils.py", line 1097, in __
get__
    raise RuntimeError(message, sys.exc_info()[2])
RuntimeError: ('AttributeError raised: u', <traceback object at 0x0000000005B7A2
48>)
```

**Comment by scudette** [comment]
This is likely due to an incorrect profile. It is hard to tell from the above which profile it is trying to actually use but 5E22546695474BAFAE2A8BE520A14B022 seems to have the correct fields in it so it should not raise exceptions. Can you please share the image (you can send me a private message to support@rekall-innovations.com) ?

**Comment by truekonrads** [comment]
Bump....
