### ISSUE TITLE
Web-GUI Installation Issue

### ISSUE THREAD

**Issue by vnc2017** [google/rekall#366]
Hi Michael,

Need to run Web GUI for collaborating my work with team mates.

I am on latest Windows 10 OS.
Installed the latest Rekall using the installer Rekall_1.7.2.p1_Hurricane.Ridge_x64.exe

C:\Program Files (x86)\Tanium\Tanium Client\Tools\IR\Rekall>rekal.exe -v
2018-02-13 17:26:19,395:DEBUG:rekall.1:Logging level set to 10
2018-02-13 17:26:19,398:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': None})

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] Default session 17:26:25> webconsole?
Object `webconsole` not found.

===========
Since I did not find any instructions on how to run webconsole searched on google and found the below link 

https://groups.google.com/forum/#!msg/rekall-discuss/65Ye7TYZoA8/8rTqpeqqAwAJ

I tried to install the webgui using pip but got errors as below

C:\WINDOWS\system32>pip install rekall-gui
Collecting rekall-gui
  Downloading rekall_gui-1.5.0.post4.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.0MB 439kB/s
Collecting rekall-core<1.6,>=1.5.0 (from rekall-gui)
  Downloading rekall-core-1.5.3.post1.zip (1.1MB)
    100% |████████████████████████████████| 1.1MB 638kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\vnayak\AppData\Local\Temp\pip-build-l8wl9_7c\rekall-core\setup.py", line 36
        exec open("rekall/_version.py").read() in ENV
                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\vnc2017\AppData\Local\Temp\pip-build-l8wl9_7c\rekall-core\

Could you please give pointers on how to rectify this issue ?

Also appreciate if you have instructions to run webgui on mac/linux platforms too.

Thanks.

**Comment by scudette** [comment]
The web GUI has been deprecated for a long time :-(. This is why it is not included with the latest binary builds. 
I dont think the last release (which is super old) is python3 compatible either (this is why installing it fails). Sorry there was just no interest in it to warrant further development. 

We should probably delete it from the repo.

**Comment by vnc2017** [comment]
Thanks Michael for confirming.
