### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#367]
Hi Michael,

I just had a bug when trying to use rekall on a memory dump:

~~~
$ rekall -f xenwin7 pslist
2018-02-22 04:13:07,900:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/usr/local/lib/python3.5/dist-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/usr/local/lib/python3.5/dist-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.5/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rekall/plugins/addrspaces/elfcore.py", line 214, in __init__
    first_run = self.runs[0][2]
  File "/usr/local/lib/python3.5/dist-packages/rekall_lib/utils.py", line 866, in __getitem__
    key = self.collection.iloc[item]
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sorteddict.py", line 30, in __getitem__
    return self._dict._list[index]
  File "/usr/local/lib/python3.5/dist-packages/sortedcontainers/sortedlist.py", line 629, in __getitem__
    raise IndexError('list index out of range')
IndexError: list index out of range
~~~

More details
~~~
...
/usr/local/lib/python3.5/dist-packages/rekall_lib/utils.py in __getitem__(self, item)
    864 
    865     def __getitem__(self, item):
--> 866         key = self.collection.iloc[item]
    867         return key[0], key[1], self.collection[key]
    868 

/usr/local/lib/python3.5/dist-packages/sortedcontainers/sorteddict.py in __getitem__(self, index)
     28         *index*.
     29         """
---> 30         return self._dict._list[index]
     31     def __delitem__(self, index):
     32         """

/usr/local/lib/python3.5/dist-packages/sortedcontainers/sortedlist.py in __getitem__(self, idx)
    627                     return _lists[-1][-1]
    628             else:
--> 629                 raise IndexError('list index out of range')
    630 
    631             if 0 <= idx < len(_lists[0]):

IndexError: list index out of range
~~~

My  dump is 2G.

Is it a bug in `sortedcontainers` ?

Thanks !

**Comment by scudette** [comment]
No it is most likely that self.runs is an empty list. This contains the list of ELF runs in a kcore file. I am a bit surprised that Rekall thinks this image is an ELF file? Does the file start with the ELF header? 

We probably should reject the image in a more obvious way (maybe complain if there are no valid memory ranges in that file).

**Comment by Wenzel** [comment]
Yes, that dump looks has an ELF header:
~~~
$ file xenwin7.dump
xenwin7.dump: ELF 64-bit LSB core file x86-64, version 1
~~~

I dumpped it from Xen using
~~~
$ sudo xl dump-core xenwin7 xenwin7.dump
~~~

But it should be raw memory dump anyway ??? :thinking:

**Comment by smaresca** [comment]
ELF output from Xen's xl dump-core is expected to be in ELF format (like
Linux core dumps) marked by e_type=ET_CORE.

See old but still valid documentation here
https://xenbits.xen.org/docs/4.8-testing/misc/dump-core-format.txt

**Comment by scudette** [comment]
Strangely this dump does not have any program headers:

```
⟫ readelf -e xenwin7.dump
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 01 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       1
  Type:                              CORE (Core file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          64 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         0
  Size of section headers:           64 (bytes)
  Number of section headers:         7
  Section header string table index: 1

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .shstrtab         STRTAB           0000000000000000  7d435250
       0000000000000048  0000000000000000           0     0     0
  [ 2] .note.Xen         NOTE             0000000000000000  00000200
       0000000000000568  0000000000000000           0     0     0
  [ 3] .xen_prstatus     PROGBITS         0000000000000000  00000768
       0000000000001430  0000000000001430           0     0     8
  [ 4] .xen_shared_info  PROGBITS         0000000000000000  00001b98
       0000000000001000  0000000000001000           0     0     8
  [ 5] .xen_pages        PROGBITS         0000000000000000  00003000
       000000007d04a000  0000000000001000           0     0     4096
  [ 6] .xen_pfn          PROGBITS         0000000000000000  7d04d000
       00000000003e8250  0000000000000008           0     0     8
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

There are no program headers in this file.
```

According to the documentation:

> The usual process core file includes program headers and no section header.
> On the other hand the xen dump-core file includes no program headers and
> some sections because of its peculiar requirements.

So I dont think we know how to parse these kind of images. We should add support.
