### ISSUE TITLE
IndexError: list index out of range (from 32bit kernel)

### ISSUE THREAD

**Issue by fpusersuggest** [google/rekall#369]
Hi, I have the error written in the subject. I don't think it is a duplicated bug.
I am on lxle (from ubuntu 16.04) with a 32 bit kernel.

```
user@BOX:~$ uname -a
Linux BOX 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:22:43 UTC 2018 i686 i686 i686 GNU/Linux
user@tBOX:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="LXLE Eclectica 16.04.3 32-bit Edition"

```

and the following is the error from **rekall aff4acquire b.aff4**:

```
2018-02-24 14:43:41,973:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 603, in collect
    with self.session.plugins.live():
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/tools/live_linux.py", line 96, in __enter__
    self.live()
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/tools/live_linux.py", line 77, in live
    load_as.GuessAddressSpace(base_as=base_as))
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/elfcore.py", line 214, in __init__
    first_run = self.runs[0][2]
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall_lib/utils.py", line 866, in __getitem__
    key = self.collection.iloc[item]
  File "/home/user/venv3/local/lib/python2.7/site-packages/sortedcontainers/sorteddict.py", line 30, in __getitem__
    return self._dict._list[index]
  File "/home/user/venv3/local/lib/python2.7/site-packages/sortedcontainers/sortedlist.py", line 629, in __getitem__
    raise IndexError('list index out of range')
IndexError: list index out of range

2018-02-24 14:43:41,974:CRITICAL:root:list index out of range. Try --debug for more information.
Traceback (most recent call last):
  File "/home/user/venv3/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/tools/aff4acquire.py", line 603, in collect
    with self.session.plugins.live():
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/tools/live_linux.py", line 96, in __enter__
    self.live()
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/tools/live_linux.py", line 77, in live
    load_as.GuessAddressSpace(base_as=base_as))
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/elfcore.py", line 214, in __init__
    first_run = self.runs[0][2]
  File "/home/user/venv3/local/lib/python2.7/site-packages/rekall_lib/utils.py", line 866, in __getitem__
    key = self.collection.iloc[item]
  File "/home/user/venv3/local/lib/python2.7/site-packages/sortedcontainers/sorteddict.py", line 30, in __getitem__
    return self._dict._list[index]
  File "/home/user/venv3/local/lib/python2.7/site-packages/sortedcontainers/sortedlist.py", line 629, in __getitem__
    raise IndexError('list index out of range')
IndexError: list index out of range 
```

**Comment by fpusersuggest** [comment]
Contrary I've written looks a duplicated bug.

**Comment by scudette** [comment]
Did you verify that the fix for #367 also fixes this one?

**Comment by grassy** [comment]
I also have this problem. I try to acquire memory at 32bit kernel with python2.7.15.

**Comment by scudette** [comment]
Did you say you had a 32 bit kernel? You can't acquire memory from
/process/kcore on 32 bit kernels because the address space is too small to
map the physical memory. Your best bet is to compile pmem or lime.

We probably should have a better error message though.

**Comment by scudette** [comment]
Yes as I said, the error occurs here:
https://github.com/google/rekall/blob/v1.7.1/rekall-core/rekall/plugins/addrspaces/elfcore.py#L214

```
            first_run = self.runs[0][2]
```

and it raises IndexError because the runs list is empty. On i686 kernels (32 bit) the /proc/kcore does not export the physical memory because the address space is not large enough so this technique can not work. You would need to compile pmem or lime to access memory of such a system.
