### ISSUE TITLE
ImportError: No module named win32service while giving rekall command

### ISSUE THREAD

**Issue by ballanaveenchand** [google/rekall#373]
C:\Users\CHANDU'S>.\dev\Scripts\activate

(dev) C:\Users\CHANDU'S>rekall
Traceback (most recent call last):
  File "C:\Users\CHANDU'S\dev\Scripts\rekall-script.py", line 11, in <module>
    load_entry_point('rekall-core==1.5.3', 'console_scripts', 'rekall')()
  File "C:\Users\CHANDU'S\dev\lib\site-packages\pkg_resources\__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\CHANDU'S\dev\lib\site-packages\pkg_resources\__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "C:\Users\CHANDU'S\dev\lib\site-packages\pkg_resources\__init__.py", line 2408, in load
    return self.resolve()
  File "C:\Users\CHANDU'S\dev\lib\site-packages\pkg_resources\__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_core-1.5.3-py2.7.egg\rekall\rekal.py", line 39, in <module>
    entry_point.load()
  File "C:\Users\CHANDU'S\dev\lib\site-packages\pkg_resources\__init__.py", line 2408, in load
    return self.resolve()
  File "C:\Users\CHANDU'S\dev\lib\site-packages\pkg_resources\__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_gui\plugins\webconsole_plugin.py", line 41, in <module>
    from rekall.plugins.renderers import data_export
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_core-1.5.3-py2.7.egg\rekall\plugins\__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_core-1.5.3-py2.7.egg\rekall\plugins\addrspaces\__init__.py", line 10, in <module>
    from rekall.plugins.addrspaces import ewf
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_core-1.5.3-py2.7.egg\rekall\plugins\addrspaces\ewf.py", line 27, in <module>
    from rekall.plugins.tools import ewf
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_core-1.5.3-py2.7.egg\rekall\plugins\tools\__init__.py", line 48, in <module>
    from rekall.plugins.tools import live_windows
  File "C:\Users\CHANDU'S\dev\lib\site-packages\rekall_core-1.5.3-py2.7.egg\rekall\plugins\tools\live_windows.py", line 37, in <module>
    import win32service
ImportError: No module named win32service

I am new to use this software I was strucked at this point .... please help me to move forward

**Comment by scudette** [comment]
How did you install rekall? It looks like you are missing some dependencies
which should be automatically installed with pip (specifically pypiwin32).

**Comment by ballanaveenchand** [comment]
These are the steps i have followed to install from the link https://holdmybeersecurity.com/2017/07/29/rekall-memory-analysis-framework-for-windows-linux-and-mac-osx/

Download and Install Python 2.7
Download and Install Microsoft Visual C++ Compiler for Python 2.7
Open Cpommand prompt
cd C:\Python27\Scripts
.\pip.exe install virtualenv
virtualenv.exe C:\Users\<username>\dev
cd C:\Users\<username>
.\dev\Scripts\activate.ps1
If it fails due to the Execution-Policy run “Set-ExecutionPolicy RemoteSigned” as an Administrator
pip install setuptools pip wheel
pip install rekall-agent rekall

**Comment by scudette** [comment]
Can you please see if pypiwin32 is installed:

pip freeze | grep pypiwin32

what if you install it manually: pip install pypiwin32

**Comment by ballanaveenchand** [comment]
These commands are giving the following output:

(dev) C:\Users\CHANDU'S>pip freeze | grep pypiwin32
'grep' is not recognized as an internal or external command,
operable program or batch file.

(dev) C:\Users\CHANDU'S>pip install pypiwin32
Requirement already satisfied: pypiwin32 in c:\users\chandu's\dev\lib\site-packages\pypiwin32-219-py2.7-win32.egg

**Comment by ballanaveenchand** [comment]
Hi .... Thanks for your valuable response 
 
I have solved the issue .... up to now i have used Python 2.7 and Python compiler for Python 2.7 and now i have updated it to Python 3.6 and Visual C++ Build Tools 2017 so that i could come over this issue ..... It's working good for me.

I am closing this issue .
