### ISSUE TITLE
"RuntimeError: RebuildM2PMapping recursed... aborting. " error on AWS memory dump

### ISSUE THREAD

**Issue by vegardvaage** [google/rekall#383]
I have created a memory dump of a Ubuntu 3.13.0.24 server running on a m3.xlarge server with on Amazon AWS. Rekall version is 1.7.2.rc1 (Hurricane Ridge). 

Based on the below output Rekall selects the correct profile, but fails. I suspect that this may be related to running on AWS infrastructure, but does anyone have an idea what would cause this? The memory dump was created by Lime via the [MargaritaShotgun](https://github.com/ThreatResponse/margaritashotgun/) tool. 

```
rekall  -f 10.140.11.248.dump -v pslist
2018-03-16 11:16:11,888:INFO:rekall.1:Cache directory is not specified or invalid. Switching to memory cache.
2018-03-16 11:16:11,890:DEBUG:rekall.1:Logging level set to 10
2018-03-16 11:16:11,890:INFO:rekall.1:Cache directory is not specified or invalid. Switching to memory cache.
2018-03-16 11:16:11,890:DEBUG:rekall.1:Voting round with base: None
2018-03-16 11:16:11,890:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-03-16 11:16:11,890:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-03-16 11:16:11,890:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-03-16 11:16:11,890:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-03-16 11:16:11,890:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-03-16 11:16:11,891:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-03-16 11:16:11,891:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-03-16 11:16:11,891:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-03-16 11:16:11,891:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-03-16 11:16:11,891:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-03-16 11:16:11,891:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-03-16 11:16:11,891:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-03-16 11:16:11,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-03-16 11:16:11,892:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-03-16 11:16:11,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-03-16 11:16:11,892:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-03-16 11:16:11,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-03-16 11:16:11,892:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-03-16 11:16:11,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-03-16 11:16:11,892:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-03-16 11:16:11,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-03-16 11:16:11,892:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-03-16 11:16:11,892:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-03-16 11:16:11,894:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-03-16 11:16:11,894:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-03-16 11:16:11,894:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at 10.140.11.248.dump_info
2018-03-16 11:16:11,894:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-03-16 11:16:11,894:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-03-16 11:16:11,894:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-03-16 11:16:11,894:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-03-16 11:16:11,894:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-03-16 11:16:11,894:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-03-16 11:16:11,895:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4c694d45
2018-03-16 11:16:11,895:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-03-16 11:16:11,895:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-03-16 11:16:11,895:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-03-16 11:16:11,895:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-03-16 11:16:11,895:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-03-16 11:16:11,895:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-03-16 11:16:11,895:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-03-16 11:16:11,895:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-03-16 11:16:11,895:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-03-16 11:16:11,896:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-03-16 11:16:11,896:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-03-16 11:16:11,896:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-03-16 11:16:11,896:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-03-16 11:16:11,896:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-03-16 11:16:11,896:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-03-16 11:16:11,896:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-03-16 11:16:11,896:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-03-16 11:16:11,897:DEBUG:rekall.1:Succeeded instantiating LimeAddressSpace
2018-03-16 11:16:11,897:DEBUG:rekall.1:Voting round with base: LimeAddressSpace
2018-03-16 11:16:11,897:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-03-16 11:16:11,897:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-03-16 11:16:11,897:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-03-16 11:16:11,898:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2018-03-16 11:16:11,898:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-03-16 11:16:11,898:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-03-16 11:16:11,898:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-03-16 11:16:11,898:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-03-16 11:16:11,898:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-03-16 11:16:11,898:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-03-16 11:16:11,898:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-03-16 11:16:11,898:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-03-16 11:16:11,898:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-03-16 11:16:11,899:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2018-03-16 11:16:11,899:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-03-16 11:16:11,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2018-03-16 11:16:11,900:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-03-16 11:16:11,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2018-03-16 11:16:11,900:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-03-16 11:16:11,900:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2018-03-16 11:16:11,900:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-03-16 11:16:11,900:INFO:rekall.1:Autodetected physical address space LimeAddressSpace
2018-03-16 11:16:11,900:INFO:rekall.1:Cache directory is not specified or invalid. Switching to memory cache.
2018-03-16 11:16:11,900:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,tsk,osx,pe,windows_kernel_file,rsds,ntfs,linux
2018-03-16 11:16:12,649:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2018-03-16 11:16:13,418:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/Linux/index.gz
2018-03-16 11:16:13,450:DEBUG:rekall.1:Adding Linux/index to local cache.
2018-03-16 11:16:13,451:INFO:rekall.1:Loaded profile Linux/index from Local Cache - (in 0.764472961426 sec)
2018-03-16 11:16:14,131:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/eprocess_index.gz
2018-03-16 11:16:14,178:DEBUG:rekall.1:Adding nt/eprocess_index to local cache.
2018-03-16 11:16:14,181:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache - (in 0.729880094528 sec)
2018-03-16 11:16:14,822:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/nt/index.gz
2018-03-16 11:16:14,954:DEBUG:rekall.1:Adding nt/index to local cache.
2018-03-16 11:16:14,955:INFO:rekall.1:Loaded profile nt/index from Local Cache - (in 0.773448944092 sec)
2018-03-16 11:16:15,558:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/OSX/index.gz
2018-03-16 11:16:15,559:DEBUG:rekall.1:Adding OSX/index to local cache.
2018-03-16 11:16:15,559:INFO:rekall.1:Loaded profile OSX/index from Local Cache - (in 0.604033231735 sec)
2018-03-16 11:16:16,388:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/pe.gz
2018-03-16 11:16:16,393:DEBUG:rekall.1:Adding pe to local cache.
2018-03-16 11:16:16,396:INFO:rekall.1:Loaded profile pe from Local Cache - (in 0.837331056595 sec)
2018-03-16 11:16:16,397:DEBUG:rekall.1:Trying method pe, offset 0
2018-03-16 11:16:16,398:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2018-03-16 11:16:16,398:DEBUG:rekall.1:Trying method rsds, offset 0
2018-03-16 11:16:16,398:DEBUG:rekall.1:Trying method linux_index, offset 0
2018-03-16 11:16:16,398:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2018-03-16 11:16:16,398:DEBUG:rekall.1:Trying method nt_index, offset 0
2018-03-16 11:16:16,399:DEBUG:rekall.1:Trying method tsk, offset 0
2018-03-16 11:16:16,399:DEBUG:rekall.1:Trying method ntfs, offset 0
2018-03-16 11:16:16,959:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/ntfs.gz
2018-03-16 11:16:16,959:DEBUG:rekall.1:Adding ntfs to local cache.
2018-03-16 11:16:16,960:INFO:rekall.1:Loaded profile ntfs from Local Cache - (in 0.560845851898 sec)
2018-03-16 11:16:18,225:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/Ubuntu/3.13.0-24-generic.gz
2018-03-16 11:16:18,502:DEBUG:rekall.1:Adding Ubuntu/3.13.0-24-generic to local cache.
2018-03-16 11:16:18,852:INFO:rekall.1:Loaded profile Ubuntu/3.13.0-24-generic from Local Cache - (in 1.69957399368 sec)
2018-03-16 11:16:18,852:INFO:rekall.1:Detected Ubuntu/3.13.0-24-generic: Linux version 3.13.0-24-generic
2018-03-16 11:16:18,852:DEBUG:rekall.1:Calculating page offset...
2018-03-16 11:16:18,853:DEBUG:rekall.1:Page offset is ffff80000000
2018-03-16 11:16:18,853:INFO:rekall.1:Found slide 0x0
2018-03-16 11:16:18,853:DEBUG:rekall.1:Detected paravirtualized XEN guest
2018-03-16 11:16:18,854:DEBUG:rekall.1:Rebuilding the machine to physical mapping...
2018-03-16 11:16:18,854:DEBUG:rekall.1:p2m_top = 0xffff81fde000
2018-03-16 11:16:18,855:DEBUG:rekall.1:p2m_missing = 0xffff81fdc000
2018-03-16 11:16:18,855:DEBUG:rekall.1:p2m_mid_missing = 0xffff81fdd000
2018-03-16 11:16:18,855:DEBUG:rekall.1:p2m_identity = 0xffff81fdf000
2018-03-16 11:16:18,855:DEBUG:rekall.1:XENFEAT_auto_translated_physmap = 0
2018-03-16 11:16:18,856:DEBUG:rekall.1:p2m_top[0] = 0xffff81fe0000
2018-03-16 11:16:18,856:DEBUG:rekall.1:p2m_top[0][0] = 0x88039a097000
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.2rc1', 'console_scripts', 'rekall')()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 761, in calculate
    profile_obj = self.ScanProfiles()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 629, in ScanProfiles
    return self._ScanProfiles()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 687, in _ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 553, in DetectFromHit
    verified_profile = self.VerifyProfile(profile)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 75, in VerifyProfile
    return self._ApplyFindDTB(self.find_dtb_impl, profile)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 99, in _ApplyFindDTB
    for address_space in find_dtb_plugin.address_space_hits():
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 258, in address_space_hits
    address_space = self.VerifyHit(hit)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 164, in VerifyHit
    address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 248, in VerifyHit
    return self.CreateAS(hit)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 269, in CreateAS
    profile=self.profile)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 368, in __init__
    self._RebuildM2PMapping()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 527, in _RebuildM2PMapping
    for p2m in self._ReadP2M(p2m_mid_entry, self.P2M_PER_PAGE):
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 401, in _ReadP2M
    self.read(offset, 0x1000))):
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 589, in read
    buf = self._read_chunk(addr, length)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 550, in _read_chunk
    paddr = self.vtop(vaddr)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 617, in vtop
    return super(XenParaVirtAMD64PagedMemory, self).vtop(vaddr)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/intel.py", line 316, in vtop
    aligned_vaddr, PhysicalAddressDescriptorCollector(self.session))
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 79, in describe_vtop
    pml4e_value = self.read_pte(pml4e_addr, collection=collection)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 584, in read_pte
    pfn = self.m2p(mfn)
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 574, in m2p
    self._RebuildM2PMapping()
  File "/opt/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 429, in _RebuildM2PMapping
    raise RuntimeError("RebuildM2PMapping recursed... aborting.")
RuntimeError: RebuildM2PMapping recursed... aborting.
```

**Comment by scudette** [comment]
I think AWS are running a Xen paravitualized based kernel. This is
problematic because without access to the hypervisor we can not reliably
build the machine to physical map. Although I have not verified recently
this never used to work because we dont have the required information from
within the guest memory itself.

I think we need a better error message here - it is not clear why this
failed from the error message. I think AWS images taken from the guest are
not generally supported by Rekall.

Thanks
Michael
