### ISSUE TITLE
More of the same missing pdb files using rekall fetch_pdb

### ISSUE THREAD

**Issue by 82d28a** [google/rekall#385]
rekall fetch_pdb ntkrpamp 3844dbb920174967be7aa4a2c20430fa2
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pd2018-03-16 17:03:20,341:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/plugins/tools/mspdb.py", line 159, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/plugins/tools/mspdb.py", line 248, in FetchPDBFile
    url, pdb_filename, guid, basename)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/plugins/tools/mspdb.py", line 172, in DownloadCompressedPDBFile
    url_handler = urllib.request.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 171, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 500, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 612, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 538, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 620, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2018-03-16 17:03:20,342:CRITICAL:root:HTTP Error 404: Not Found. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.7.2rc1', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/plugins/tools/mspdb.py", line 159, in render
    pdb_file_data = self.FetchPDBFile()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/plugins/tools/mspdb.py", line 248, in FetchPDBFile
    url, pdb_filename, guid, basename)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.2rc1-py2.7.egg/rekall/plugins/tools/mspdb.py", line 172, in DownloadCompressedPDBFile
    url_handler = urllib.request.urlopen(request)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 171, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 500, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 612, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 538, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/future-0.16.0-py2.7.egg/future/backports/urllib/request.py", line 620, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
future.backports.urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by 82d28a** [comment]
I see the has is listed in https://github.com/google/rekall-profiles/blob/gh-pages/v1.0/src/nt/guids.yaml
