### ISSUE TITLE
Error running rekal after installation via windows binaries

### ISSUE THREAD

**Issue by waydaws** [google/rekall#387]
After installing from binaries on windows (Rekall_1.7.2.p1_Hurricane.Ridge_x64.exe), I get the following error when I try to run it. 

C:\>rekal
Traceback (most recent call last):
  File "rekal.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "rekall-core\rekall\rekal.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "rekall-core\rekall\args.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "rekall-core\rekall\config.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "rekall-lib\rekall_lib\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "rekall-lib\rekall_lib\crypto.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\Crypto\PublicKey\RSA.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\Crypto\Math\Numbers.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\Crypto\Math\_Numbers_gmp.py", line 155, in <module>
  File "ctypes\__init__.py", line 361, in __getattr__
  File "ctypes\__init__.py", line 366, in __getitem__
AttributeError: function '__gmpz_init' not found
[123704] Failed to execute script rekal

**Comment by waydaws** [comment]
I'm not sure why it's trying to to access files in non-existent path, like "File "c:\users\test\dev36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", or whether that's the reason for the error.

**Comment by scudette** [comment]
This seems a duplicate of #359

**Comment by waydaws** [comment]
Yes, it was that gmp.dll was in my path.  I had openssl's bin directory in my path, which has gmp.dll in it.
