### ISSUE TITLE
RuntimeError: RebuildM2PMapping recursed... aborting

### ISSUE THREAD

**Issue by grassy** [google/rekall#388]
I use "rekal aff4acquire /path/image.aff4" to acquire memory for centos7, and make profile with the linux tool.
but when I run './rekal -v -p ./rekal-profile/3.10.0-693.21.1.el7.x86_64 -f ./centos.aff4 pslist', the error occur. 

Rekal version: rekal --version
This is Rekall Version 1.7.2.rc1 (Hurricane Ridge)
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.2', 'error': 'Not in a git repository.', 'pep440': '1.7.2.rc1'}

Output like below:

2018-03-26 18:01:49,155:DEBUG:rekall.1:Logging level set to 10
2018-03-26 18:01:49,157:DEBUG:rekall.1:Opened local file /Users/zhangmeimei/Documents/profiles/Centos/7.3/x86_64/3.10.0-693.21.1.el7.x86_64
2018-03-26 18:01:49,687:DEBUG:rekall.1:Voting round with base: None
2018-03-26 18:01:49,687:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-03-26 18:01:49,688:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-03-26 18:01:49,688:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-03-26 18:01:49,688:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-03-26 18:01:49,688:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-03-26 18:01:49,689:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-03-26 18:01:49,689:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-03-26 18:01:49,689:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-03-26 18:01:49,689:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-03-26 18:01:49,690:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-03-26 18:01:49,690:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-03-26 18:01:49,690:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-03-26 18:01:49,690:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-03-26 18:01:49,690:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-03-26 18:01:49,690:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-03-26 18:01:49,690:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-03-26 18:01:49,691:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-03-26 18:01:49,691:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-03-26 18:01:49,691:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-03-26 18:01:49,691:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-03-26 18:01:49,691:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-03-26 18:01:49,691:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-03-26 18:01:49,692:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-03-26 18:01:49,717:INFO:rekall.1:Added aff4://bbd102a2-5946-4ee1-ab17-8908309dede7/PhysicalMemory as physical memory
2018-03-26 18:01:49,718:DEBUG:rekall.1:Succeeded instantiating AFF4AddressSpace
2018-03-26 18:01:49,719:DEBUG:rekall.1:Voting round with base: AFF4AddressSpace
2018-03-26 18:01:49,719:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-03-26 18:01:49,719:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-03-26 18:01:49,719:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-03-26 18:01:49,727:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-03-26 18:01:49,727:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-03-26 18:01:49,728:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-03-26 18:01:49,728:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-03-26 18:01:49,730:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x0
2018-03-26 18:01:49,730:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-03-26 18:01:49,731:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-03-26 18:01:49,731:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-03-26 18:01:49,731:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-03-26 18:01:49,731:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-03-26 18:01:49,731:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-03-26 18:01:49,731:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-03-26 18:01:49,732:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-03-26 18:01:49,732:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-03-26 18:01:49,732:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-03-26 18:01:49,732:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-03-26 18:01:49,732:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-03-26 18:01:49,732:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-03-26 18:01:49,733:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-03-26 18:01:49,733:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-03-26 18:01:49,734:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-03-26 18:01:49,734:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-03-26 18:01:49,734:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-03-26 18:01:49,734:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-03-26 18:01:49,734:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-03-26 18:01:49,734:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-03-26 18:01:49,736:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-03-26 18:01:49,736:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-03-26 18:01:49,736:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-03-26 18:01:49,736:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-03-26 18:01:49,737:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-03-26 18:01:49,737:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-03-26 18:01:49,737:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-03-26 18:01:49,737:INFO:rekall.1:Autodetected physical address space AFF4AddressSpace
2018-03-26 18:01:49,758:DEBUG:rekall.1:Opened local file /Users/zhangmeimei/.rekall_cache/sessions/v1.0/sessions/index.gz
2018-03-26 18:01:49,767:DEBUG:rekall.1:Decoded in 0.00773930549621582 sec.
2018-03-26 18:01:49,775:DEBUG:rekall.1:Opened local file /Users/zhangmeimei/Documents/profiles/Centos/7.3/x86_64/3.10.0-693.21.1.el7.x86_64
2018-03-26 18:01:50,338:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': '/Users/zhangmeimei/Documents/profiles/Centos/7.3/x86_64/3.10.0-693.21.1.el7.x86_64', 'pids': None, 'proc_regex': None, 'task': None, 'method': ['InitTask'], 'verbosity': 1})
2018-03-26 18:01:50,339:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-03-26 18:01:50,362:DEBUG:rekall.1:Found /proc/kallsyms of size: 4416859
2018-03-26 18:01:50,382:DEBUG:rekall.1:Calculating page offset...
2018-03-26 18:01:50,383:DEBUG:rekall.1:Page offset is ffff80000000
2018-03-26 18:01:50,393:DEBUG:rekall.1:Detected paravirtualized XEN guest
2018-03-26 18:01:50,394:DEBUG:rekall.1:Rebuilding the machine to physical mapping...
2018-03-26 18:01:50,395:DEBUG:rekall.1:p2m_top = 0x0
2018-03-26 18:01:50,405:DEBUG:rekall.1:p2m_missing = 0x0
2018-03-26 18:01:50,405:DEBUG:rekall.1:p2m_mid_missing = 0x0
2018-03-26 18:01:50,406:DEBUG:rekall.1:p2m_identity = 0x0
2018-03-26 18:01:50,406:DEBUG:rekall.1:XENFEAT_auto_translated_physmap = 0
2018-03-26 18:01:50,419:CRITICAL:rekall.1:Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/intel.py", line 311, in vtop
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 76, in Get
  File "venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 147, in NewFunction
  File "venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 336, in Get
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 862, in RunPlugin
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 921, in _GetPluginObj
  File "venv/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
  File "venv/lib/python3.6/site-packages/rekall/plugin.py", line 888, in __init__
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 424, in GetVirtualAddressSpace
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 258, in address_space_hits
  File "venv/lib/python3.6/site-packages/rekall/plugins/linux/common.py", line 164, in VerifyHit
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 248, in VerifyHit
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 269, in CreateAS
  File "venv/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 368, in __init__
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 469, in _RebuildM2PMapping
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 401, in _ReadP2M
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 589, in read
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 550, in _read_chunk
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 617, in vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/intel.py", line 316, in vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 79, in describe_vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 584, in read_pte
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 574, in m2p
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 429, in _RebuildM2PMapping
RuntimeError: RebuildM2PMapping recursed... aborting.

2018-03-26 18:01:50,420:CRITICAL:root:RebuildM2PMapping recursed... aborting.. Try --debug for more information.
2018-03-26 18:01:50,421:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-03-26 18:01:50,421:DEBUG:rekall.1:Detected paravirtualized XEN guest
2018-03-26 18:01:50,422:DEBUG:rekall.1:Rebuilding the machine to physical mapping...
2018-03-26 18:01:50,423:DEBUG:rekall.1:p2m_top = 0x0
2018-03-26 18:01:50,423:DEBUG:rekall.1:p2m_missing = 0x0
2018-03-26 18:01:50,424:DEBUG:rekall.1:p2m_mid_missing = 0x0
2018-03-26 18:01:50,424:DEBUG:rekall.1:p2m_identity = 0x0
2018-03-26 18:01:50,426:DEBUG:rekall.1:XENFEAT_auto_translated_physmap = 0
2018-03-26 18:01:50,431:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-03-26 18:01:50,432:DEBUG:rekall.1:Detected paravirtualized XEN guest
2018-03-26 18:01:50,433:DEBUG:rekall.1:Rebuilding the machine to physical mapping...
2018-03-26 18:01:50,434:DEBUG:rekall.1:p2m_top = 0x0
2018-03-26 18:01:50,434:DEBUG:rekall.1:p2m_missing = 0x0
2018-03-26 18:01:50,434:DEBUG:rekall.1:p2m_mid_missing = 0x0
2018-03-26 18:01:50,435:DEBUG:rekall.1:p2m_identity = 0x0
2018-03-26 18:01:50,435:DEBUG:rekall.1:XENFEAT_auto_translated_physmap = 0
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/intel.py", line 311, in vtop
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 76, in Get
  File "venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 147, in NewFunction
  File "venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 336, in Get
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/rekall/rekal.py", line 104, in main
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 869, in RunPlugin
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 862, in RunPlugin
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 921, in _GetPluginObj
  File "venv/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
  File "venv/lib/python3.6/site-packages/rekall/plugin.py", line 888, in __init__
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 424, in GetVirtualAddressSpace
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 258, in address_space_hits
  File "venv/lib/python3.6/site-packages/rekall/plugins/linux/common.py", line 164, in VerifyHit
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 248, in VerifyHit
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 269, in CreateAS
  File "venv/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 368, in __init__
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 469, in _RebuildM2PMapping
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 401, in _ReadP2M
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 589, in read
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 550, in _read_chunk
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 617, in vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/intel.py", line 316, in vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 79, in describe_vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 584, in read_pte
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 574, in m2p
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 429, in _RebuildM2PMapping
RuntimeError: RebuildM2PMapping recursed... aborting.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/intel.py", line 311, in vtop
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 76, in Get
  File "venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 147, in NewFunction
  File "venv/lib/python3.6/site-packages/rekall_lib/utils.py", line 336, in Get
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/installers/rekal.py", line 11, in <module>
  File "venv/lib/python3.6/site-packages/rekall/rekal.py", line 111, in main
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 1132, in Flush
  File "venv/lib/python3.6/site-packages/rekall/cache.py", line 275, in Flush
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 768, in GetParameter
  File "venv/lib/python3.6/site-packages/rekall/session.py", line 803, in _RunParameterHook
  File "venv/lib/python3.6/site-packages/rekall/plugins/linux/misc.py", line 96, in calculate
  File "venv/lib/python3.6/site-packages/rekall/obj.py", line 153, in __call__
  File "venv/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
  File "venv/lib/python3.6/site-packages/rekall/plugin.py", line 888, in __init__
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 424, in GetVirtualAddressSpace
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 258, in address_space_hits
  File "venv/lib/python3.6/site-packages/rekall/plugins/linux/common.py", line 164, in VerifyHit
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 248, in VerifyHit
  File "venv/lib/python3.6/site-packages/rekall/plugins/core.py", line 269, in CreateAS
  File "venv/lib/python3.6/site-packages/rekall_lib/registry.py", line 96, in __call__
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 368, in __init__
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 469, in _RebuildM2PMapping
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 401, in _ReadP2M
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 589, in read
  File "venv/lib/python3.6/site-packages/rekall/addrspace.py", line 550, in _read_chunk
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 617, in vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/intel.py", line 316, in vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 79, in describe_vtop
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 584, in read_pte
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 574, in m2p
  File "venv/lib/python3.6/site-packages/rekall/plugins/addrspaces/amd64.py", line 429, in _RebuildM2PMapping
RuntimeError: RebuildM2PMapping recursed... aborting.
[16704] Failed to execute script rekal

Thanks

**Comment by scudette** [comment]
It looks like you are trying to acquire a paravirtualized host. On some
environments like AWS this is not possible because the machine to physical
mapping section is not available inside the virtualized host. This is why
it fails when it tries to analyze the image in building the M2P mapping
(RebuildM2PMapping function).

I have not looked at this for a while but unless things have changed, there
is no way to make it work because the mapping is not accessible.

Thanks
Michael.

**Comment by scudette** [comment]
Maybe its a bug then? I would appreciate if you could share such an image with me (support@rekall-forensics.com). Thanks :-).

**Comment by grassy** [comment]
I has sent the images and profiles to your mail.

**Comment by vegardvaage** [comment]
Any updates on this? 

#383 is the same issue from the sound of it - AWS forensics is becoming more and more important, so if there's anything I can do to provide sample images beyond what @grassy sent please let me know.
