### ISSUE TITLE
Yara constructor error in Rekall

### ISSUE THREAD

**Issue by JohnPeng47** [google/rekall#394]
Hi just installed the latest version of Rekall from, ran, and got hit with this error below. Googling, it seems very similar to issue #319, but supposedly that was fixed with the #323 merge? 

```
john@john-GL62M-7RDX:~/rekall/rekall-core$ rekall -h
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 9, in <module>
    load_entry_point('rekall-core==1.7.3.dev20', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev20-py2.7.egg/rekall/rekal.py", line 81, in main
    user_session = session.InteractiveSession()
  File "/usr/local/lib/python2.7/dist-packages/rekall_lib-1.7.2rc1-py2.7.egg/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev20-py2.7.egg/rekall/session.py", line 1266, in __init__
    config.MergeConfigOptions(self.state, self)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev20-py2.7.egg/rekall/config.py", line 245, in MergeConfigOptions
    config_data = GetConfigFile(session)
  File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev20-py2.7.egg/rekall/config.py", line 202, in GetConfigFile
    result = yaml_utils.decode(fd.read(1000*1000*10)) or {}
  File "/usr/local/lib/python2.7/dist-packages/rekall_lib-1.7.2rc1-py2.7.egg/rekall_lib/yaml_utils.py", line 57, in decode
    return yaml.safe_load(utils.SmartUnicode(data)) or OrderedYamlDict()
  File "build/bdist.linux-x86_64/egg/yaml/__init__.py", line 93, in safe_load
  File "build/bdist.linux-x86_64/egg/yaml/__init__.py", line 71, in load
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 39, in get_single_data
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 48, in construct_document
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 393, in construct_yaml_seq
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 118, in construct_sequence
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 88, in construct_object
  File "build/bdist.linux-x86_64/egg/yaml/constructor.py", line 414, in construct_undefined
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "<unicode string>", line 2, column 19:
    repository_path: [!!python/unicode 'https://github ...
```

**Comment by scudette** [comment]
If you remove ~/.rekallrc and re-run rekall -h does it re-create the corrupted file?
