### ISSUE TITLE
Runtimeerror: Unable to find a valid profile for this image

### ISSUE THREAD

**Issue by buekera** [google/rekall#395]
I'm facing an error when trying to execute rekall as follows:
```bash
rekall -f vmi://kvm/win10
```

As result I'm getting this after a few seconds:
```bash
ERROR:root:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "./rekall_offset_finder.py", line 116, in <module>
    config = extract_offsets(domain, url)
  File "./rekall_offset_finder.py", line 37, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 916, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/guess_profile.py", line 765, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
```

Host:
Arch Linux x64 Kernel 4.15.13
Latest Rekall version

Guest:
Windows 10 x64
GUID 481F0DAABA6C4F02B456FAD74941C2A41
PDB ntkrnlmp.pdb

If further information is needed just let me know.

**Comment by scudette** [comment]
Does it run on a memory image? Is this an vmi problem or just a profile autodetection issue? Can you please run again with the --verbose flag?

**Comment by smaresca** [comment]
no, I'm afraid libvmi provides access to memory and registers only.

**Comment by buekera** [comment]
> How large is the image?

I do live scanning on a machine with 4GB of memory.

> Does it work if you increase the autodetect scan length?

I don't know how to increase autodetect scan length.

>  Does running version scan pick up the right guid?

No. It is picked up correcty when I run rekall against a memory dump of said vm though.

**Comment by scudette** [comment]
You can increase the autodetect scan length using the flag --autodetect_scan_length . Try to set it to 4Gb to ensure all the image is scanned (I think it is 1Gb by default).

You can check if the GUID exists in the image by running the version_scan plugin:
```
rekal -v -f  vmi://kvm/win10 version_scan --name_regex krnl
```

Should be something like:
```
   offset                   guid                             pdb              
-------------- --------------------------------- ------------------------------
     0x27bbd8c F8E2A8B5C9B74BF4A6E4A48F180099942 ntkrnlmp.pdb                  
```
