### ISSUE TITLE
TypeError: Struct() when running any plugins

### ISSUE THREAD

**Issue by echin20** [google/rekall#399]
I get the following error when I attempt to run any plugins from Rekall. I tried a simple plugin like imageinfo

Rekall version: 1.7.2.rc1
OS: CentOS Linux release 7.4.1708 
Python verion: Python 2.7.5
Memory Image OS: Win7SP1x86
command line: any plugins

2018-05-09 08:01:05,017:DEBUG:rekall.1:Logging level set to 10
2018-05-09 08:01:05,018:DEBUG:rekall.1:Voting round with base: None
2018-05-09 08:01:05,018:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-05-09 08:01:05,019:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-05-09 08:01:05,019:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-05-09 08:01:05,019:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-05-09 08:01:05,019:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-05-09 08:01:05,019:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-05-09 08:01:05,019:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-05-09 08:01:05,019:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-05-09 08:01:05,019:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-05-09 08:01:05,020:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-05-09 08:01:05,020:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-05-09 08:01:05,021:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-05-09 08:01:05,021:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-05-09 08:01:05,021:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-05-09 08:01:05,021:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-05-09 08:01:05,021:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-05-09 08:01:05,021:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-05-09 08:01:05,021:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-05-09 08:01:05,021:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-05-09 08:01:05,022:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-05-09 08:01:05,022:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-05-09 08:01:05,022:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-05-09 08:01:05,022:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-05-09 08:01:05,024:INFO:rekall.1:Error: Struct() argument 1 must be string, not unicode
Traceback (most recent call last):
  File "/home//venv/rekall/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.py", line 133, in __init__
    volume_path, stream_path = self._LocateAFF4Volume(path)
  File "/home//venv/rekall/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.py", line 170, in _LocateAFF4Volume
    self.resolver, volume_urn) as volume:
  File "/home//venv/rekall/lib/python2.7/site-packages/pyaff4/zip.py", line 665, in NewZipFile
    return resolver.AFF4FactoryOpen(result.urn)
  File "/home//venv/rekall/lib/python2.7/site-packages/pyaff4/data_store.py", line 384, in AFF4FactoryOpen
    obj.LoadFromURN()
  File "/home//venv/rekall/lib/python2.7/site-packages/pyaff4/zip.py", line 725, in LoadFromURN
    self.parse_cd(self.backing_store_urn)
  File "/home//venv/rekall/lib/python2.7/site-packages/pyaff4/zip.py", line 490, in parse_cd
    end_cd, buffer_offset = EndCentralDirectory.FromBuffer(buffer)
  File "/home//venv/rekall/lib/python2.7/site-packages/pyaff4/zip.py", line 71, in FromBuffer
    if len(buffer) > cls.sizeof():
  File "/home//venv/rekall/lib/python2.7/site-packages/pyaff4/struct_parser.py", line 46, in sizeof
    return struct.calcsize(cls._format_string)
TypeError: Struct() argument 1 must be string, not unicode

**Comment by scudette** [comment]
Python 2.7.5 is really ancient and we dont support it. The current 2.7 python is 2.7.15 but probably anything after 2.7.10 will be ok. Officially Rekall supports python > 3.5 but 2.7 is technically still supported.

**Comment by echin20** [comment]
Thanks, I tried at least a semi newer version of Python and I didn't get that error anymore.
