### ISSUE TITLE
_EPROCESS.ThreadListHead not valid with Rekall master

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#407]
Hi,

I have an issue with the latest Rekall from git master:
~~~
$ rekall -f <memdump> -v pslist
2018-05-22 12:05:29,982:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/nt/GUID/3844DBB920174967BE7AA4A2C20430FA2.gz
2018-05-22 12:05:30,203:INFO:rekall.1:Loaded profile nt/GUID/3844DBB920174967BE7AA4A2C20430FA2 from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.22065114975 sec)
2018-05-22 12:05:30,371:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/nt/eprocess_index.gz
2018-05-22 12:05:30,399:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.0279598236084 sec)
2018-05-22 12:05:31,748:DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.C004)               
2018-05-22 12:05:39,239:ERROR:rekall.1:No profiles match this image. Try specifying manually.
Traceback (most recent call last):                 
  File "/home/tarrma/tmp/venv-rekall-master/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/tarrma/fsecure/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugins/guess_profile.py", line 765, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
~~~

Error is **_EPROCESS.ThreadListHead not valid**.

This is a bug introduced by the latest commits on Rekall, because I can't reproduce with the release version available via pip (`1.7.2.rc1 (Hurricane Ridge)`)

Can you confirm ?

Thanks !

**Comment by scudette** [comment]
This message just means that it can not verify the profile by walking the _EPROCESS.ThreadListHead member. There may have been a bug introduced. I think there was some change to the address space auto detection - what is the address space detected as? What was the image format? Can you please attach the full address selection debug messages?

**Comment by Wenzel** [comment]
Hi @scudette ,

> What was the image format? 
~~~
/home/tarrma/fsecure/kvm-vmi/nitro/debug/win7.raw: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style
~~~



>  what is the address space detected as?
> Can you please attach the full address selection debug messages?

Here is the full log:
~~~
2018-05-22 16:28:12,214:DEBUG:rekall.1:Logging level set to 10
2018-05-22 16:28:12,217:DEBUG:rekall.1:Voting round with base: None
2018-05-22 16:28:12,217:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-05-22 16:28:12,218:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-05-22 16:28:12,218:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-05-22 16:28:12,218:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-05-22 16:28:12,218:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-05-22 16:28:12,219:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-05-22 16:28:12,219:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-05-22 16:28:12,220:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-05-22 16:28:12,220:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-05-22 16:28:12,220:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-05-22 16:28:12,220:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-05-22 16:28:12,220:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-05-22 16:28:12,220:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-05-22 16:28:12,221:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-05-22 16:28:12,221:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-05-22 16:28:12,221:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-05-22 16:28:12,221:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-05-22 16:28:12,221:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-05-22 16:28:12,221:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-05-22 16:28:12,221:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Must stack on another address space
2018-05-22 16:28:12,221:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-05-22 16:28:12,221:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-05-22 16:28:12,221:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-05-22 16:28:12,221:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-05-22 16:28:12,222:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-05-22 16:28:12,222:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
2018-05-22 16:28:12,222:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-05-22 16:28:12,224:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-05-22 16:28:12,224:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-05-22 16:28:12,224:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /home/tarrma/fsecure/kvm-vmi/nitro/debug/win7.raw_info
2018-05-22 16:28:12,224:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-05-22 16:28:12,224:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-05-22 16:28:12,225:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-05-22 16:28:12,225:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-05-22 16:28:12,225:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-05-22 16:28:12,225:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-05-22 16:28:12,226:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-05-22 16:28:12,226:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-05-22 16:28:12,228:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
2018-05-22 16:28:12,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-05-22 16:28:12,228:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-05-22 16:28:12,228:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-05-22 16:28:12,229:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-05-22 16:28:12,229:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-05-22 16:28:12,229:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-05-22 16:28:12,229:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-05-22 16:28:12,229:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-05-22 16:28:12,229:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-05-22 16:28:12,230:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-05-22 16:28:12,230:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-05-22 16:28:12,230:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-05-22 16:28:12,230:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-05-22 16:28:12,232:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Image does not contain Xen note.
2018-05-22 16:28:12,232:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-05-22 16:28:12,232:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-05-22 16:28:12,233:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-05-22 16:28:12,233:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-05-22 16:28:12,233:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-05-22 16:28:12,233:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
2018-05-22 16:28:12,233:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-05-22 16:28:12,234:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-05-22 16:28:12,234:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-05-22 16:28:12,234:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-05-22 16:28:12,234:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-05-22 16:28:12,234:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-05-22 16:28:12,234:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-05-22 16:28:12,236:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-05-22 16:28:12,236:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-05-22 16:28:12,236:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-05-22 16:28:12,236:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-05-22 16:28:12,236:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-05-22 16:28:12,236:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-05-22 16:28:12,237:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-05-22 16:28:12,237:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2018-05-22 16:28:12,238:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/sessions/v1.0/sessions/index.gz
2018-05-22 16:28:12,240:DEBUG:rekall.1:Decoded in 0.0022432804107666016 sec.
2018-05-22 16:28:12,241:DEBUG:rekall.1:Will detect profile using these Detectors: rsds,pe,windows_kernel_file,linux_index,osx
2018-05-22 16:28:12,937:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2018-05-22 16:28:13,209:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/inventory.gz
2018-05-22 16:28:13,303:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2018-05-22 16:28:13,567:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/inventory.gz
2018-05-22 16:28:13,568:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/pe.gz
2018-05-22 16:28:13,576:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.008356332778930664 sec)
2018-05-22 16:28:13,577:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/Linux/index.gz
2018-05-22 16:28:13,590:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.013515472412109375 sec)
2018-05-22 16:28:13,591:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/OSX/index.gz
2018-05-22 16:28:13,591:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.0009980201721191406 sec)
2018-05-22 16:28:13,592:DEBUG:rekall.1:Trying method pe, offset 0
2018-05-22 16:28:13,594:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2018-05-22 16:28:13,594:DEBUG:rekall.1:Trying method rsds, offset 0
2018-05-22 16:28:13,594:DEBUG:rekall.1:Trying method linux_index, offset 0
2018-05-22 16:28:13,594:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2018-05-22 16:28:13,825:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/nt/GUID/3844DBB920174967BE7AA4A2C20430FA2.gz
2018-05-22 16:28:13,998:INFO:rekall.1:Loaded profile nt/GUID/3844DBB920174967BE7AA4A2C20430FA2 from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.17316269874572754 sec)
2018-05-22 16:28:14,168:DEBUG:rekall.1:Opened local file /home/tarrma/.rekall_cache/v1.0/nt/eprocess_index.gz
2018-05-22 16:28:14,186:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/tarrma/.rekall_cache (in 0.017969608306884766 sec)
2018-05-22 16:28:15,313:DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.C004) 
2018-05-22 16:28:22,080:ERROR:rekall.1:No profiles match this image. Try specifying manually. 
Traceback (most recent call last):                 
  File "/home/tarrma/fsecure/venv-rekall/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/tarrma/fsecure/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/tarrma/fsecure/rekall/rekall-core/rekall/plugins/guess_profile.py", line 765, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
~~~

~~~
$ rekall --version
This is Rekall Version 1.7.3.dev21 (Hurricane Ridge)
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.3', 'revisionid': b'6e55eee2388a607191993b08c25f988751f61927', 'dirty': False, 'dev': 21, 'pep440': '1.7.3.dev21'}
~~~

Thanks !

**Comment by scudette** [comment]
Ah this must be the problem - it is an ELF image but it is detected as a flat image:

2018-05-22 16:28:12,230:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-05-22 16:28:12,230:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore

This might be the problem: https://github.com/google/rekall/blob/master/rekall-core/rekall/plugins/addrspaces/elfcore.py#L70

This was introduced by https://github.com/google/rekall/pull/389  which was trying to solve the issue where elf images were mistaken to be kcore images.  I think there was a typo in that PR it should be:

```
       super(Elf64CoreDump, self).__init__(**kwargs)
+         self.as_assert("kcore" not in self.session.GetParameter(
+         "filename", ""), "Not kcore")
```

It is very confusing because the as_assert() has the opposite logic to what one expects so its easy to get the wrong sense. Maybe we need to deprecate the self.as_assert() and just do it with a simple if statement.
