### ISSUE TITLE
UnicodeDecodeError: 'utf-8' error

### ISSUE THREAD

**Issue by echin20** [google/rekall#408]
I was trying out the automating Rekall feature and I was getting some errors trying to load an image as an object. As a sanity check I was able to load the same image with the filename path in the session, but I am having trouble doing it this way. 

rekall: 1.7.2.rc1
OS: Centos 7
python: 3.6.3
Mem OS: 7601.win7sp1_gdr.130708-1532

``
import logging
from rekall import plugins
from rekall import session
from rekall.plugins.addrspaces import standard

logging.getLogger().setLevel(logging.DEBUG)

s = session.Session(
    autodetect=["rsds"],
    logger=logging.getLogger(),
    profile_path=[
        "/home/user/venv/rekall/rekall-profiles/"
    ])

with s:
    s.physical_address_space = standard.FDAddressSpace(fhandle=open("/home/user/memory_image_sample/windows/sample001.bin"), session=s)

print (s.plugins.pslist(method="PsActiveProcessHead"))
``

I don't know if this is recommend, but I tried it this way too. 

``
foo = open("/home/user/memory_image_sample/windows/sample002.bin")
with s:
    s.physical_address_space = standard.FDAddressSpace(fhandle=foo, session=s)
``
	
Either way, I still get the same error message. 
DEBUG:root:Will detect profile using these Detectors: rsds
DEBUG:root:Opened local file /home/user/venv/rekall/rekall-profiles/v1.0/inventory.gz
DEBUG:root:Opened local file /home/user/venv/rekall/rekall-profiles/v1.0/pe.gz
DEBUG:root:Adding pe to local cache.
INFO:root:Loaded profile pe from Local Cache - (in 0.008483171463012695 sec)
DEBUG:root:Trying method rsds, offset 0
Traceback (most recent call last):
  File "object.py", line 20, in <module>
    print (s.plugins.pslist(method="PsActiveProcessHead"))
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 761, in calculate
    profile_obj = self.ScanProfiles()
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 629, in ScanProfiles
    return self._ScanProfiles()
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 665, in _ScanProfiles
    profile = method.DetectFromHit(None, offset, address_space)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 382, in DetectFromHit
    return self._test_rsds(rsds)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/guess_profile.py", line 386, in _test_rsds
    str(rsds.Filename) in self.KERNEL_NAMES):
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/overlays/basic.py", line 134, in __str__
    return self.__bytes__().decode("utf8", "replace")
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/overlays/basic.py", line 129, in __bytes__
    return self.v().rstrip(b"\x00")
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/overlays/basic.py", line 101, in v
    data = vm.read(self.obj_offset, length)
  File "/home/user/venv/rekall/lib/python3.6/site-packages/rekall/plugins/addrspaces/standard.py", line 77, in read
    data = self.fhandle.read(length)
  File "/home/user/venv/rekall/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 3: invalid continuation byte

**Comment by scudette** [comment]
You need to open your file in binary mode:

```
standard.FDAddressSpace(fhandle=open("/home/user/memory_image_sample/windows/sample001.bin", "rb"), session=s)
```

**Comment by echin20** [comment]
That was it, missed that part. Thanks!
