### ISSUE TITLE
Windows 10 pslist fails "Unable to find a valid profile for this image"

### ISSUE THREAD

**Issue by enjhnsn2** [google/rekall#412]
Hello, I am having trouble getting the basic pslist to run on a windows 10 image. The command I use is:

`rekall -v -f win10_new.raw pslist --autodetect_scan_length 200000000000`

image details:
`win10_new.raw: data`

rekall version:
`{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.3', 'revisionid': b'5132170b32895385872ddb35296dcdf6bc1d2512', 'dirty': False, 'dev': 22, 'pep440': '1.7.3.dev22'}`

Thank you for your time.

```
2018-06-01 11:27:23,560:DEBUG:rekall.1:Logging level set to 10
2018-06-01 11:27:23,561:DEBUG:rekall.1:Voting round with base: None
2018-06-01 11:27:23,562:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-06-01 11:27:23,562:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-06-01 11:27:23,563:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-06-01 11:27:23,563:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-06-01 11:27:23,563:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-06-01 11:27:23,563:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-06-01 11:27:23,563:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-06-01 11:27:23,564:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-06-01 11:27:23,564:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-06-01 11:27:23,564:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-06-01 11:27:23,564:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-06-01 11:27:23,564:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-06-01 11:27:23,564:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-06-01 11:27:23,565:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-06-01 11:27:23,565:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-06-01 11:27:23,565:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-06-01 11:27:23,565:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-06-01 11:27:23,565:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-06-01 11:27:23,565:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-06-01 11:27:23,565:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Must stack on another address space
2018-06-01 11:27:23,565:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-06-01 11:27:23,565:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-06-01 11:27:23,566:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-06-01 11:27:23,566:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-06-01 11:27:23,566:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-06-01 11:27:23,566:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: URL scheme must be vmi://
2018-06-01 11:27:23,566:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-06-01 11:27:23,567:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-06-01 11:27:23,567:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-06-01 11:27:23,568:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at win10_new.raw_info
2018-06-01 11:27:23,568:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-06-01 11:27:23,568:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-06-01 11:27:23,568:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-06-01 11:27:23,568:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-06-01 11:27:23,569:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-06-01 11:27:23,569:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-06-01 11:27:23,569:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-06-01 11:27:23,569:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-06-01 11:27:23,570:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xff53
2018-06-01 11:27:23,570:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-06-01 11:27:23,570:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-06-01 11:27:23,570:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-06-01 11:27:23,570:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-06-01 11:27:23,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-06-01 11:27:23,571:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Not kcore
2018-06-01 11:27:23,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-06-01 11:27:23,571:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-06-01 11:27:23,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-06-01 11:27:23,571:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-06-01 11:27:23,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-06-01 11:27:23,571:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Not kcore
2018-06-01 11:27:23,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-06-01 11:27:23,571:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Header signature invalid
2018-06-01 11:27:23,571:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-06-01 11:27:23,571:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-06-01 11:27:23,572:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-06-01 11:27:23,572:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-06-01 11:27:23,572:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-06-01 11:27:23,573:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: must be first Address Space
2018-06-01 11:27:23,573:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-06-01 11:27:23,574:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-06-01 11:27:23,574:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-06-01 11:27:23,574:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-06-01 11:27:23,575:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-06-01 11:27:23,575:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-06-01 11:27:23,575:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
2018-06-01 11:27:23,576:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-06-01 11:27:23,576:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
2018-06-01 11:27:23,576:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-06-01 11:27:23,576:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
2018-06-01 11:27:23,576:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-06-01 11:27:23,577:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
2018-06-01 11:27:23,577:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-06-01 11:27:23,577:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2018-06-01 11:27:23,578:DEBUG:rekall.1:Will detect profile using these Detectors: rsds,pe,windows_kernel_file,linux_index,osx
2018-06-01 11:27:23,578:DEBUG:rekall.1:Opened local file /home/rekall/rekall-profiles/v1.0/inventory.gz
2018-06-01 11:27:23,591:DEBUG:rekall.1:Opened local file /home/.rekall_cache/v1.0/inventory.gz
2018-06-01 11:27:23,592:DEBUG:rekall.1:Opened local file /home/.rekall_cache/v1.0/pe.gz
2018-06-01 11:27:23,599:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/.rekall_cache (in 0.006900310516357422 sec)
2018-06-01 11:27:23,600:DEBUG:rekall.1:Opened local file /home/.rekall_cache/v1.0/Linux/index.gz
2018-06-01 11:27:23,608:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:/home/.rekall_cache (in 0.008710145950317383 sec)
2018-06-01 11:27:23,609:DEBUG:rekall.1:Opened local file /home/.rekall_cache/v1.0/OSX/index.gz
2018-06-01 11:27:23,610:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:/home/.rekall_cache (in 0.0011820793151855469 sec)
2018-06-01 11:27:23,610:DEBUG:rekall.1:Trying method pe, offset 0
2018-06-01 11:27:23,612:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2018-06-01 11:27:23,613:DEBUG:rekall.1:Trying method rsds, offset 0
2018-06-01 11:27:23,613:DEBUG:rekall.1:Trying method linux_index, offset 0
2018-06-01 11:27:23,613:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2018-06-01 11:27:23,827:DEBUG:rekall.1:Remote does not have file nt/GUID/039281E5F80D4711858194C121C9D89D1.
2018-06-01 11:27:23,827:DEBUG:rekall.1:Opened local file /home/.rekall_cache/v1.0/nt/GUID/039281E5F80D4711858194C121C9D89D1.gz
2018-06-01 11:27:24,175:INFO:rekall.1:Loaded profile nt/GUID/039281E5F80D4711858194C121C9D89D1 from Local Cache Directory:/home/.rekall_cache (in 0.34862351417541504 sec)
2018-06-01 11:27:29,861:DEBUG:rekall.1:Opened local file /home/.rekall_cache/v1.0/nt/eprocess_index.gz
2018-06-01 11:27:29,877:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/.rekall_cache (in 0.016129255294799805 sec)
2018-06-01 11:27:29,881:DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.
2018-06-01 11:27:30,755:DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.002AA)              
2018-06-01 11:27:31,114:DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.830002)      
2018-06-01 11:27:31,517:DEBUG:rekall.1:_EPROCESS.ThreadListHead not valid.            
2018-06-01 11:27:42,685:ERROR:rekall.1:No profiles match this image. Try specifying manually. 
Traceback (most recent call last):                 
  File "/home/rekall/venv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/rekall/rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/home/rekall/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/home/rekall/rekall/rekall-core/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/rekall/rekall/rekall-core/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/home/rekall/rekall/rekall-core/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/rekall/rekall/rekall-core/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/rekall/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/rekall/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/rekall/rekall/rekall-core/rekall/plugins/guess_profile.py", line 765, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
```

**Comment by scudette** [comment]
This just says that profile auto-detection failed to verify the profile. We verify the DTB by trying to reflect through the ThreadListHead linked list and this is not working. It could happen, e.g. because the page is not resident or due to smear.

Generally RAW images are harder to load because we need to guess a lot of parameters which should have been collected during acquisition. I would suggest that you force a dtb value using e.g. psscan and  make sure the profile is correct using the version_scan plugin.

I am actually starting to question if it makes sense for Rekall to guess all the required parameters at the time of loading the image. This makes it hard to tell if the problem is in actual memory analysis (which is reliable and repeatable) or with guessing the parameters (like profile and DTB) which is non-deterministic since it is just a guess which could go wrong if pages are non resident or some other smear issues. 

Maybe in future we need to separate this into two stages. For example, Rekall might require a spec file which specifies the DTB or profile to be explicitly given. If the image was acquired properly these details would be recorded from the image itself, but if someone wants to use a raw file they need to create such a spec file (perhaps with the use of guessing plugins). This approach makes it clear that the issue is in guessing and not in the analysis itself.

The down side of this is that raw images will not be automatically loadable without specifying the parameters in the spec file - so that is one additional step for the analyst to guess values which they did not record at the time of acquisition.

**Comment by enjhnsn2** [comment]
@scudette 
Huh, so now it inexplicably *sort of* works with pslist when I use vmi, but psscan and all other commands still get "no profile found". 
```
2018-06-06 05:46:47,845:INFO:rekall.1:Detected ntkrnlmp.pdb with GUID 039281E5F80D4711858194C121C9D89D1
2018-06-06 05:46:47,845:DEBUG:rekall.1:Detection method rsds worked at offset 0x22ba71e8
2018-06-06 05:46:47,847:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': None, 'eprocess': <rekall.plugin.Sentinel object at 0x7f00b77e49b0>, 'pids': <rekall.plugin.Sentinel object at 0x7f00b77e49e8>, 'proc_regex': None, 'method': ['PsActiveProcessHead', 'CSRSS', 'PspCidTable', 'Sessions', 'Handles'], 'verbosity': 1})
2018-06-06 05:46:47,850:DEBUG:rekall.1:Listed 0 processes using PsActiveProcessHead
2018-06-06 05:46:47,850:DEBUG:rekall.1:Listed 0 processes using CSRSS
2018-06-06 05:46:47,850:DEBUG:rekall.1:Listed 0 processes using PspCidTable
2018-06-06 05:46:47,850:DEBUG:rekall.1:Listed 0 processes using Sessions
2018-06-06 05:46:47,851:DEBUG:rekall.1:Listed 0 processes using Handles
--  _EPROCESS            name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
-------------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
```
Perhaps I don't understand what your saying, but psscan fails with the same error
