### ISSUE TITLE
Error aff4export

### ISSUE THREAD

**Issue by beleka** [google/rekall#417]
Hello, i'm trying to use rekall to extract the raw RAM from aff4r file. When i use aff4ls i get this error:

Using rekall or rekal aff4ls memory.aff4r
________________________________________________________________________

   Size         Type                         Original Name                    URN
---------- --------------- -------------------------------------------------- ---
2018-06-07 10:24:00,273:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/root/rekall-master/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/root/rekall-master/rekall-core/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/root/rekall-master/rekall-core/rekall/plugins/tools/aff4acquire.py", line 779, in collect
    volume_urn = rdfvalue.URN(self.plugin_args.volume)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4/rdfvalue.py", line 57, in __init__
    self.Set(initializer)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4/rdfvalue.py", line 258, in Set
    utils.AssertUnicode(data)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4/utils.py", line 69, in AssertUnicode
    raise RuntimeError("String must be unicode.")
RuntimeError: String must be unicode.

2018-06-07 10:24:00,273:CRITICAL:root:String must be unicode.. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/root/rekall-master/rekall-core/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/root/rekall-master/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/root/rekall-master/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/root/rekall-master/rekall-core/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/root/rekall-master/rekall-core/rekall/plugins/tools/aff4acquire.py", line 779, in collect
    volume_urn = rdfvalue.URN(self.plugin_args.volume)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4/rdfvalue.py", line 57, in __init__
    self.Set(initializer)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4/rdfvalue.py", line 258, in Set
    utils.AssertUnicode(data)
  File "/usr/local/lib/python2.7/dist-packages/pyaff4/utils.py", line 69, in AssertUnicode
    raise RuntimeError("String must be unicode.")
RuntimeError: String must be unicode.

_________________________________________________________________________

And if i use rekall aff4export -D "Path to output folder" "Path to aff4r file" i get 2 kind of errors:

- If i don't add the -D option, i get an error from not defining the folder.

- If i use the -D modifier, i get the next error:

__________________________________________________________________________

rekall: error: unrecognized arguments: --dump-dir ~//memoria.aff4
__________________________________________________________________________

I hope you can help me and thank you for your time. I'm using the last git repository version on an Ubuntu 16.04

**Comment by beleka** [comment]
Solved, i copied the format from another issue answer and it was mistaked, you have to define the --dump_dir after the aff4 path, or it takes the aff4 path as a command. Sorry for the issue oppened.
