### ISSUE TITLE
Creating Profile for CentOS 7 3.10.0-862.6.3.el7.x86_64

### ISSUE THREAD

**Issue by koppensb** [google/rekall#427]
At trying to create a profile for a CentOS machine, I get following compiler error:
make -C /cases/test/usr/src/kernels/3.10.0-862.6.3.el7.x86_64/ CONFIG_DEBUG_INFO=y M=`pwd` modules
make[1]: Entering directory '/cases/test/usr/src/kernels/3.10.0-862.6.3.el7.x86_64'
  CC [M]  /cases/test/profile/module.o
/cases/test/profile/module.c:538:9: error: unknown type name ‘cycle_t’
         cycle_t                 cycle_interval;
         ^
/cases/test/profile/module.c:540:9: error: unknown type name ‘cycle_t’
         cycle_t                 cycle_last;
         ^
scripts/Makefile.build:347: recipe for target '/cases/test/profile/module.o' failed
make[2]: *** [/cases/test/profile/module.o] Error 1
Makefile:1312: recipe for target '_module_/cases/test/profile' failed
make[1]: *** [_module_/cases/test/profile] Error 2
make[1]: Leaving directory '/cases/test/usr/src/kernels/3.10.0-862.6.3.el7.x86_64'
Makefile:25: recipe for target 'dwarf' failed
make: *** [dwarf] Error 2

I have looked into the module.c and as far as I understand there is a variable named cycle_t which is only created if the kernelversion is greater then 4 something.
<snip>
#if LINUX_VERSION_CODE > KERNEL_VERSION(4, 9, 54)
#define cycle_t u64
#endif
</snap>

But this variable is used at a position where the kernelversion only has to be greater then 3 something
<snip>
#elif LINUX_VERSION_CODE >= KERNEL_VERSION(3,17,0)
struct tk_read_base {
        struct clocksource      *clock;
        cycle_t                 (*read)(struct clocksource *cs);
        cycle_t                 mask;
        cycle_t                 cycle_last;
        u32                     mult;
        u32                     shift;
        u64                     xtime_nsec;
        ktime_t                 base_mono;
};
</snap>

As delete the if around the #define cycle_t u64 the compile process worked and the profile was useable.

Maybe somebody with better programming skills can fix this problem

**Comment by McFlip** [comment]
I have the same issue with RHEL 7.5.

**Comment by koppensb** [comment]
I have seen your post about beeing not able to parse the vmem file. I never found a way to parse snapshot files so I mostly take the memory images from inside the vm.

**Comment by McFlip** [comment]
I think the problem was with parsing the profile, not the vmem file. I'll try using LiME just to double check.

Side note, I realized immediately after I created #444 that I compiled a profile on a later kernel version than the version the snapshot had. I created a new snapshot but still didn't work. Just thought I'd preemptively mention that.

**Comment by koppensb** [comment]
I tested now with a vmem file of a CentOS 7.5 VM. If I take the memdump with linpmem inside the VM everything works fine. If I use the vmem file I get this.

2018-10-05 06:14:50,030:DEBUG:rekall.1:Logging level set to 10
2018-10-05 06:14:50,030:DEBUG:rekall.1:Opened local file /cases/test/memdump/3.10.0-862.el7.x86_64.json
2018-10-05 06:14:50,607:DEBUG:rekall.1:Voting round with base: None
2018-10-05 06:14:50,607:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-10-05 06:14:50,608:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-10-05 06:14:50,608:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-10-05 06:14:50,608:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-10-05 06:14:50,608:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-10-05 06:14:50,608:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-10-05 06:14:50,608:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-10-05 06:14:50,608:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-10-05 06:14:50,608:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-10-05 06:14:50,609:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-10-05 06:14:50,609:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-10-05 06:14:50,609:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-10-05 06:14:50,609:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-10-05 06:14:50,609:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-10-05 06:14:50,609:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-10-05 06:14:50,610:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-10-05 06:14:50,610:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-10-05 06:14:50,610:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-10-05 06:14:50,610:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-10-05 06:14:50,610:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-10-05 06:14:50,610:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-10-05 06:14:50,610:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-10-05 06:14:50,610:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-10-05 06:14:50,612:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-10-05 06:14:50,612:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-10-05 06:14:50,612:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at CentOS-Snapshot1.vmem_info
2018-10-05 06:14:50,613:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-10-05 06:14:50,613:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-10-05 06:14:50,613:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-10-05 06:14:50,613:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-10-05 06:14:50,613:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-10-05 06:14:50,613:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-10-05 06:14:50,614:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53
2018-10-05 06:14:50,615:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-10-05 06:14:50,615:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-10-05 06:14:50,615:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-10-05 06:14:50,615:DEBUG:rekall.1:Failed instantiating VMemAddressSpace:
2018-10-05 06:14:50,615:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-10-05 06:14:50,615:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-10-05 06:14:50,616:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-10-05 06:14:50,616:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-10-05 06:14:50,616:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-10-05 06:14:50,616:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-10-05 06:14:50,616:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-10-05 06:14:50,616:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-10-05 06:14:50,616:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-10-05 06:14:50,616:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-10-05 06:14:50,617:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-10-05 06:14:50,617:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-10-05 06:14:50,617:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-10-05 06:14:50,617:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-10-05 06:14:50,617:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-10-05 06:14:50,617:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-10-05 06:14:50,617:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-10-05 06:14:50,618:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-10-05 06:14:50,618:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-10-05 06:14:50,618:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-10-05 06:14:50,618:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2018-10-05 06:14:50,618:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-10-05 06:14:50,618:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2018-10-05 06:14:50,619:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-10-05 06:14:50,619:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2018-10-05 06:14:50,619:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-10-05 06:14:50,619:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2018-10-05 06:14:50,619:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-10-05 06:14:50,619:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2018-10-05 06:14:50,620:DEBUG:rekall.1:Opened local file /home/koppensb/.rekall_cache/sessions/v1.0/sessions/index.gz
2018-10-05 06:14:50,640:DEBUG:rekall.1:Decoded in 0.0199611186981 sec.
2018-10-05 06:14:50,641:DEBUG:rekall.1:Opened local file /cases/test/memdump/3.10.0-862.el7.x86_64.json
2018-10-05 06:14:51,208:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': '3.10.0-862.el7.x86_64.json', 'proc_regex': None, 'task': None, 'verbosity': 1, 'pids': None, 'method': ['InitTask']})
2018-10-05 06:14:51,209:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-10-05 06:14:51,209:DEBUG:rekall.1:Calculating page offset...
2018-10-05 06:14:51,210:DEBUG:rekall.1:Page offset is ffff80000000
2018-10-05 06:14:51,211:DEBUG:rekall.1:Failed to verify dtb @ 0x1c0e000
2018-10-05 06:14:51,211:INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
2018-10-05 06:14:51,211:CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
2018-10-05 06:14:51,212:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-10-05 06:14:51,213:DEBUG:rekall.1:Failed to verify dtb @ 0x1c0e000
2018-10-05 06:14:51,213:INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
2018-10-05 06:14:51,215:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-10-05 06:14:51,216:DEBUG:rekall.1:Failed to verify dtb @ 0x1c0e000
2018-10-05 06:14:51,216:INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rekall/rekal.py", line 111, in main
    user_session.Flush()
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 1132, in Flush
    hook(*args)
  File "/usr/local/lib/python2.7/dist-packages/rekall/cache.py", line 275, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/linux/misc.py", line 96, in calculate
    for task in self.session.plugins.pslist().filter_processes():
  File "/usr/local/lib/python2.7/dist-packages/rekall/obj.py", line 153, in __call__
    return self._target(*(self._args + args), **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugin.py", line 888, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/core.py", line 445, in GetVirtualAddressSpace
    "A DTB value was found but failed to verify. "
rekall.plugin.PluginError: A DTB value was found but failed to verify. See logging messages for more information.

**Comment by scudette** [comment]
Right - it does not recognize it as a vmem file:
2018-10-05 06:14:50,614:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53

Can you please share this or a similar image with me support@rekall-forensics.com

**Comment by koppensb** [comment]
I found a discussion about vmem from 2015 (https://groups.google.com/forum/#!topic/rekall-discuss/Dwo-s8Ks0Ec) so I tried to suspend the vm and use this vmem und vmss. I also tried to rename the vmem file to raw, but I got the same error.

**Comment by koppensb** [comment]
Yes I will share the Image. Would a link to onedrive be ok?

**Comment by scudette** [comment]
Yeah thanks. It is possible that the vmem file format has changed somewhat. I dont use vmware so I have no reference images.
