### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#428]
When analyzing a memory dump obtain from libvirt API with the latest `rekall`, it fails with the following error:
~~~
2018-07-10 15:32:26,788:DEBUG:rekall.1:Logging level set to 10
2018-07-10 15:32:26,790:DEBUG:rekall.1:Voting round with base: None
2018-07-10 15:32:26,790:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-07-10 15:32:26,791:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-07-10 15:32:26,791:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-07-10 15:32:26,791:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-07-10 15:32:26,791:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-07-10 15:32:26,791:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-07-10 15:32:26,791:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-07-10 15:32:26,792:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-07-10 15:32:26,792:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-07-10 15:32:26,793:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-07-10 15:32:26,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-07-10 15:32:26,793:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-07-10 15:32:26,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
2018-07-10 15:32:26,793:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-07-10 15:32:26,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
2018-07-10 15:32:26,793:DEBUG:rekall.1:Failed instantiating XenElf64CoreDump: Must stack on another address space
2018-07-10 15:32:26,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
2018-07-10 15:32:26,793:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-07-10 15:32:26,793:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
2018-07-10 15:32:26,794:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-07-10 15:32:26,794:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
2018-07-10 15:32:26,794:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-07-10 15:32:26,794:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
2018-07-10 15:32:26,794:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-07-10 15:32:26,794:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
2018-07-10 15:32:26,795:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-07-10 15:32:26,795:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
2018-07-10 15:32:26,796:DEBUG:rekall.1:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
2018-07-10 15:32:26,796:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
2018-07-10 15:32:26,796:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /root/winxp.dump_info
2018-07-10 15:32:26,796:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
2018-07-10 15:32:26,796:DEBUG:rekall.1:Succeeded instantiating FileAddressSpace
2018-07-10 15:32:26,796:DEBUG:rekall.1:Voting round with base: FileAddressSpace
2018-07-10 15:32:26,797:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
2018-07-10 15:32:26,798:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
2018-07-10 15:32:26,798:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
2018-07-10 15:32:26,798:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-07-10 15:32:26,798:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
2018-07-10 15:32:26,798:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-07-10 15:32:26,798:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
2018-07-10 15:32:26,798:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-07-10 15:32:26,799:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
2018-07-10 15:32:26,799:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-07-10 15:32:26,799:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
2018-07-10 15:32:26,803:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
2018-07-10 15:32:26,810:INFO:rekall.1:Error: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
...
...
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/_collections_abc.py", line 695, in __iter__
    for key in self._mapping:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 796, in __iter__
    return iter(list(self.values()))
  File "/root/venv/lib/python3.5/site-packages/sortedcontainers/sorteddict.py", line 358, in values
    return SortedValuesView(self)
RecursionError: maximum recursion depth exceeded while calling a Python object
~~~

By looking closely at the memory dump, I noticed that it had the `ELF` format.
~~~
$ file winxp.raw
winxp.raw: ELF 64-bit LSB core file Intel 80386, version 1 (SYSV), SVR4-style
~~~
So i concluded that libvirt changed it's memory dumps from `raw` to `ELF.`

Moreover, support for this format was added in this PR: https://github.com/google/rekall/commit/629e4093b22c539d8d1f00e18da947edd3477a86

However the PR was opened to add support for Xen memory dumps.
Is it supposed to support libvirt `ELF` memory dumps as well ?

I added a `Dockerfile` to reproduce the bug:
~~~Dockerfile
FROM debian:stretch

RUN apt-get update
RUN apt-get install -y python3-dev python3-pip ncurses-dev wget unzip virtualenv git vim

WORKDIR /root

RUN virtualenv -p python3 venv

RUN git clone https://github.com/google/rekall
RUN venv/bin/pip install --upgrade setuptools pip wheel
RUN venv/bin/pip install --editable rekall/rekall-lib
RUN venv/bin/pip install --editable rekall/rekall-core
RUN venv/bin/pip install --editable rekall/rekall-agent
RUN venv/bin/pip install --editable rekall

RUN venv/bin/pip install docopt

# download memory dump
RUN wget -q 'https://www.dropbox.com/s/rrbd896wwcl8puc/winxp.raw?dl=1' -O /root/winxp.dump

ENTRYPOINT ["/root/venv/bin/rekall", "-f", "/root/winxp.dump", "pslist", "-v"]
~~~

Thanks.

**Comment by Wenzel** [comment]
Using `Rekall Version 1.7.2.rc1 (Hurricane Ridge)` from `pip` it works:
~~~
rekall -f winxp.raw pslist
2018-07-10 18:35:44,722:WARNING:rekall.1:Unable to determine file size, assuming file is volatile.
_EPROCESS          name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
---------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
0x865c49c8 System                   4      0           53          380          - False  -                        -                       
0x8639f880 smss.exe               320      4            3           19          - False  2018-07-10 23:11:58Z     -                       
0x86455650 alg.exe                332    540            6          105          0 False  2018-07-10 23:12:15Z     -                       
0x863a6da0 wscntfy.exe            448    816            1           31          0 False  2018-07-10 23:12:16Z     -                       
0x863a9318 csrss.exe              472    320            9          307          0 False  2018-07-10 23:11:59Z     -                       
0x863ab230 winlogon.exe           496    320           18          589          0 False  2018-07-10 23:11:59Z     -                       
0x863bab10 services.exe           540    496           17          374          0 False  2018-07-10 23:11:59Z     -                       
0x863bf880 lsass.exe              552    496           19          340          0 False  2018-07-10 23:11:59Z     -                       
0x864dd780 svchost.exe            704    540           16          206          0 False  2018-07-10 23:12:00Z     -                       
0x864105d8 svchost.exe            752    540            9          251          0 False  2018-07-10 23:12:00Z     -                       
0x86489da0 svchost.exe            816    540           57         1113          0 False  2018-07-10 23:12:00Z     -                       
0x8622a7a8 svchost.exe            864    540            4           57          0 False  2018-07-10 23:12:00Z     -                       
0x863ff838 svchost.exe            992    540           11          178          0 False  2018-07-10 23:12:02Z     -                       
0x86101798 rundll32.exe          1168    540            2           89          0 False  2018-07-10 23:12:24Z     -                       
0x864734d8 explorer.exe          1252   1212           11          294          0 False  2018-07-10 23:12:02Z     -                       
0x861d17b8 spoolsv.exe           1388    540           10          117          0 False  2018-07-10 23:12:03Z     -                       
0x86428da0 svchost.exe           1504    540            4          105          0 False  2018-07-10 23:12:11Z     -                       
0x864023c0 svchost.exe           1580    540            8           92          0 False  2018-07-10 23:12:11Z     -                       
0x86194da0 svchost.exe           1720    540            7          161          0 False  2018-07-10 23:12:11Z     -                       
0x8618ba00 wuauclt.exe           1856    816            4          107          0 False  2018-07-10 23:13:15Z     -  
~~~

So a bug has been introduced since then.
