### ISSUE TITLE
Any way to analyze newer linux kernel versions than 3.10?

### ISSUE THREAD

**Issue by jpoling-dswrx** [google/rekall#43]
Would be very interested in any methods to allow analysis of newer kernel versions, specifically 3.13.0-* x64 kernels/architectures.

**Comment by parkisan** [comment]
Hey jpoling, what isn't working for you? Which plugin?

Have you recreated your profile? I recently made changes to the way we generate profiles for Linux as some parts were wrong before.

**Comment by jpoling-dswrx** [comment]
Thanks for the response, parkisan. No plugins work as it seems to think the profile isn't valid.

We've made the profiles by doing the following:
1) git clone of rekall onto the system
2) cd into rekall/tools/linux
3) issue 'sudo make profile'
4) copy profile.zip into ~/rekall_profiles/v1.0/ (had to make that v1.0 directory as it wouldn't find the profile otherwise, for whatever reason)
5) rekal --profile profile.zip --profile_path ~/rekall_profiles -v -f image.raw pslist

However, it apparently can't find the appropriate address space using that profile.

Any ideas/suggestions?

**Comment by scudette** [comment]
You need to convert the zip file into a Json profile. See the readme file
in the tools/linux  directory at step 2.
Am 16.01.2015 20:40 schrieb "jpoling-dswrx" <notifications@github.com>:

**Comment by jpoling-dswrx** [comment]
> rekal convert_profile rekall-1.2.1/tools/linux/3.13.0-36-generic.zip rekall_profiles/v1.0/Ubuntu_12.04_3.13.0-36-generic_x64.zip
ERROR:root:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rekall/session.py", line 602, in _RunPlugin
    plugin_obj.render(ui_renderer)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/profile_tool.py", line 407, in render
    self.ConvertProfile(input, output)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/profile_tool.py", line 380, in ConvertProfile
    converter(input, output, session=self.session).Convert()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/profile_tool.py", line 239, in Convert
    session=self.session)
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/overlays/linux/dwarfparser.py", line 399, in __init__
    self.compile()
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/overlays/linux/dwarfparser.py", line 435, in compile
    attr, die, section_offset)))
  File "/usr/local/lib/python2.7/dist-packages/elftools/dwarf/descriptions.py", line 38, in describe_attr_value
    extra_info = extra_info_func(attr, die, section_offset)
  File "/usr/local/lib/python2.7/dist-packages/elftools/dwarf/descriptions.py", line 388, in _location_list_extra
    return describe_DWARF_expr(attr.value, die.cu.structs)
  File "/usr/local/lib/python2.7/dist-packages/elftools/dwarf/descriptions.py", line 149, in describe_DWARF_expr
    dwarf_expr_dumper.process_expr(expr)
  File "/usr/local/lib/python2.7/dist-packages/elftools/dwarf/dwarf_expr.py", line 119, in process_expr
    self.stream = BytesIO(bytelist2string(expr))
  File "/usr/local/lib/python2.7/dist-packages/elftools/common/utils.py", line 19, in bytelist2string
    return b''.join(int2byte(b) for b in bytelist)
TypeError: 'int' object is not iterable

ERROR:root:'int' object is not iterable. Try --debug for more information.

**Comment by scudette** [comment]
There seems to be a problem with pyelftool's parsing of the dwarf debugging. Can you please share the zip file rekall-1.2.1/tools/linux/3.13.0-36-generic.zip either to this issue or you can just email it to me.

BTW you do not need to place the profile in the repository after you generate it. You can just point rekall to it using the --profile flag:

```
$rekal convert_profile profile.zip profile.json
$rekal -v --profile profile.json myimage.E01

**Comment by scudette** [comment]
Just to make sure, we need to use pyelftools >= 0.22 (current version in pip is 0.23). So it is worth checking that you have the latest.

**Comment by jpoling-dswrx** [comment]
How would I go about uploading it to this issue or emailing to you?

I didn't think I was uploading it to the repo, just pointing it to the local profile directory location and name where I'd put it (unless I'm doing something wrong).

What's the easiest way to find out which pyelftools version I'm using? I git cloned rekall today, would it not have the latest version?

**Comment by jpoling-dswrx** [comment]
Profile .zip sent to your Google email address.

**Comment by scudette** [comment]
Rekall is now tested with all the latest kernel versions and should work. Please re-open if you still have issues.
