### ISSUE TITLE
Windows 2008 R2 Standard SP1 no profile found

### ISSUE THREAD

**Issue by JustMyGithub** [google/rekall#434]
I have a VMWare-Snapshot (.vmsn) of a Windows 2008 R2 Standard SP1 system. Rekall cannot detect a valid PROFILE. I noticed using -v that quite some profiles are ignored because they are not listed in the inventory.

I tried fixing this by setting a large value for autodetect:
` --autodetect_scan_length 1000000000000`

I even converted the vmsn using

`vmss2core-sb-8456865 -W INPUT.vmsn OUTPUT.dmp`
(well, output name wa ignored und memory.dmp was created instead)

with the same result (no profile found). 

I would try the -p PROFILENAME command, but I could not find a list of valid PROFILENAME values?!

thanks for help

**Comment by JustMyGithub** [comment]
```
C:\WINDOWS\system32>"C:\Program Files\Rekall\rekal.exe" --profile ./ntkrnlmp.json -f "D:\%PATH%.vmsn" --autodetect rsds -v imageinfo
2018-08-21 12:39:24,681:DEBUG:rekall.1:Logging level set to 10
2018-08-21 12:39:24,681:DEBUG:rekall.1:Opened local file C:\WINDOWS\system32\ntkrnlmp.json
2018-08-21 12:39:24,837:DEBUG:rekall.1:Voting round with base: None
2018-08-21 12:39:24,837:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Filename does not look like a device.
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Succeeded instantiating Win32FileAddressSpace
2018-08-21 12:39:24,853:DEBUG:rekall.1:Voting round with base: Win32FileAddressSpace
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-08-21 12:39:24,853:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-08-21 12:39:24,853:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-08-21 12:39:24,869:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-08-21 12:39:24,869:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-08-21 12:39:24,900:DEBUG:rekall.1:Succeeded instantiating VMSSAddressSpace
2018-08-21 12:39:24,900:DEBUG:rekall.1:Voting round with base: VMSSAddressSpace
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'>
2018-08-21 12:39:24,915:DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Must be first Address Space
2018-08-21 12:39:24,915:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2018-08-21 12:39:24,931:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2018-08-21 12:39:24,931:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
2018-08-21 12:39:24,931:DEBUG:rekall.1:Failed instantiating Win32FileAddressSpace: Must be first Address Space
2018-08-21 12:39:24,947:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2018-08-21 12:39:24,947:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2018-08-21 12:39:24,947:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2018-08-21 12:39:24,947:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2018-08-21 12:39:24,947:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2018-08-21 12:39:24,947:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2018-08-21 12:39:24,947:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2018-08-21 12:39:24,947:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2018-08-21 12:39:24,947:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2018-08-21 12:39:24,947:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2018-08-21 12:39:24,947:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2018-08-21 12:39:24,947:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2018-08-21 12:39:24,947:INFO:rekall.1:Autodetected physical address space VMSSAddressSpace
2018-08-21 12:39:24,962:DEBUG:rekall.1:Opened local file C:\WINDOWS\system32\ntkrnlmp.json
2018-08-21 12:39:25,087:DEBUG:rekall.1:Running plugin (imageinfo) with args (()) kwargs ({'profile': './ntkrnlmp.json', 'verbosity': 1})
2018-08-21 12:39:25,103:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2018-08-21 12:39:25,212:DEBUG:rekall.1:Opened local file C:\Users\user\rekall-profiles\v1.0\inventory.gz
2018-08-21 12:39:25,228:DEBUG:rekall.1:Opened local file C:\Users\user\.rekall_cache\v1.0\inventory.gz
2018-08-21 12:39:25,228:DEBUG:rekall.1:Opened local file C:\Users\user\rekall-Profiles\v1.0\inventory.gz
2018-08-21 12:39:25,228:DEBUG:rekall.1:Opened local file C:\Users\user\.rekall_cache\v1.0\inventory.gz
2018-08-21 12:39:25,228:DEBUG:rekall.1:Opened local file C:\Users\user\.rekall_cache\v1.0\nt\eprocess_index.gz
2018-08-21 12:39:25,244:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\user\.rekall_cache (in 0.015626192092895508 sec)
2018-08-21 12:43:22,263:INFO:rekall.1:A DTB value was found but failed to verify. Some troubleshooting steps to consider: (1) Is the profile correct? (2) Is the KASLR correct? Try running the find_kaslr plugin on systems that use KASLR and see if there are more possible values. You can specify which offset to use using --vm_kernel_slide. (3) If you know the DTB, for example from knowing the value of the CR3 register at time of acquisition, you can set it using --dtb. On most 64-bit systems, you can use the DTB of any process, not just the kernel!
2018-08-21 12:43:22,263:CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
2018-08-21 12:43:22,263:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
```

**Comment by JustMyGithub** [comment]
```
C:\WINDOWS\system32>"C:\Program Files\Rekall\rekal.exe" --profile ./ntkrnlmp.json -f "D:\%PATH%.vmsn" --autodetect rsds -v find_kaslr
2018-08-21 12:49:22,361:DEBUG:rekall.1:Logging level set to 10
2018-08-21 12:49:22,361:DEBUG:rekall.1:Opened local file C:\WINDOWS\system32\ntkrnlmp.json
Traceback (most recent call last):
  File "rekal.py", line 11, in <module>
  File "rekall-core\rekall\rekal.py", line 98, in main
  File "rekall-core\rekall\args.py", line 435, in parse_args
rekall.plugin.PluginError: Plugin find_kaslr is not available for this configuration
[8644] Failed to execute script rekal
```
