### ISSUE TITLE
Cannot parse profile

### ISSUE THREAD

**Issue by McFlip** [google/rekall#444]
I attempted to analyze a vmware snapshot from a RHEL 7.5 system running kernel `3.10.0-862.14.4.el7.x86_64`. I created a new profile from scratch. I got the following error:
```
$ rekal -f '/home/denton/vmware/RHEL7/Red Hat Enterprise Linux 7 64-bit-Snapshot1.vmem' --profile rhel7-5.zip 
2018-10-03 18:34:47,522:ERROR:rekall.1:Cannot parse profile rhel7-5.zip because of decoding error ''utf8' codec can't decode byte 0x89 in position 10: invalid start byte'.
2018-10-03 18:34:47,867:ERROR:rekall.1:Cannot parse profile rhel7-5.zip because of decoding error ''utf8' codec can't decode byte 0x89 in position 10: invalid start byte'.
```

I have the vmem file and profile uploaded [here](https://drive.google.com/open?id=1fYCIKoykL3zN9JI1ECgYKNWVc3HwWoKm)

**Comment by McFlip** [comment]
Converting the profile worked. I attempted to use LiME but got an error about the DTB value. I'm using Workstation 12.
```
$ rekal -f rhel.lime --profile rhel7-5.json bash
2018-10-06 19:24:29,383:CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
Traceback (most recent call last):
  File "/home/denton/rekall/bin/rekal", line 11, in <module>
    sys.exit(main())
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 111, in main
    user_session.Flush()
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 1132, in Flush
    hook(*args)
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/cache.py", line 275, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/plugins/linux/misc.py", line 96, in calculate
    for task in self.session.plugins.pslist().filter_processes():
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/obj.py", line 153, in __call__
    return self._target(*(self._args + args), **new_kwargs)
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 888, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/home/denton/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 445, in GetVirtualAddressSpace
    "A DTB value was found but failed to verify. "
rekall.plugin.PluginError: A DTB value was found but failed to verify. See logging messages for more information
```

**Comment by scudette** [comment]
Since lime does not acquire /proc/kallsyms or /proc/iomem we cant deduce the kaslr offset. You will have to provide it on the command line. See this commit which adds support for this https://github.com/google/rekall/commit/896f40a7689222c801446ba8ec91886c040ff76a

try adding --kernel_slide 0 if you are sure there is not kaslr on this system.

**Comment by McFlip** [comment]
I attempted to use --kernel_slide without luck. See below for my calculations. I followed the technique from #239 using readelf and /proc/iomem:
```
$ python
>>> 0xffff93e200001000 - 0x1000
18446625197604732928L
>>> hex(_)
'0xffff93e200000000L'

ELF Header:                                                                                              
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00                                               
  Class:                             ELF64                                                               
  Data:                              2's complement, little endian                                       
  Version:                           1 (current)                                                         
  OS/ABI:                            UNIX - System V                                                     
  ABI Version:                       0                                                                   
  Type:                              CORE (Core file)                                                    
  Machine:                           Advanced Micro Devices X86-64                                       
  Version:                           0x1                                                                 
  Entry point address:               0x0                                                                 
  Start of program headers:          64 (bytes into file)                                                
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         11
  Size of section headers:           0 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

There are no sections to group in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  NOTE           0x00000000000002a8 0x0000000000000000 0x0000000000000000
                 0x00000000000011e4 0x0000000000000000         0
  LOAD           0x00007fffff602000 0xffffffffff600000 0xffffffffffffffff
                 0x0000000000800000 0x0000000000800000  RWE    1000
  LOAD           0x00007fffa1602000 0xffffffffa1600000 0x0000000069000000
                 0x0000000001659000 0x0000000001659000  RWE    1000
  LOAD           0x0000244b40002000 0xffffa44b40000000 0xffffffffffffffff
                 0x00001fffffffffff 0x00001fffffffffff  RWE    1000
  LOAD           0x00007fffc0002000 0xffffffffc0000000 0xffffffffffffffff
                 0x000000003f000000 0x000000003f000000  RWE    1000
  LOAD           0x000013e200003000 0xffff93e200001000 0x0000000000001000
                 0x000000000009d000 0x000000000009d000  RWE    1000
  LOAD           0x0000585c40002000 0xffffd85c40000000 0xffffffffffffffff
                 0x0000000000003000 0x0000000000003000  RWE    1000
  LOAD           0x000013e200102000 0xffff93e200100000 0x0000000000100000
                 0x000000007fde0000 0x000000007fde0000  RWE    1000
  LOAD           0x0000585c40006000 0xffffd85c40004000 0xffffffffffffffff
                 0x0000000001ff8000 0x0000000001ff8000  RWE    1000
  LOAD           0x000013e27ff02000 0xffff93e27ff00000 0x000000007ff00000
                 0x0000000000100000 0x0000000000100000  RWE    1000
  LOAD           0x0000585c41ffe000 0xffffd85c41ffc000 0xffffffffffffffff
                 0x0000000000004000 0x0000000000004000  RWE    1000

There is no dynamic section in this file.

There are no relocations in this file.

The decoding of unwind sections for machine type Advanced Micro Devices X86-64 is not currently supported.

Dynamic symbol information is not available for displaying symbols.

No version information found in this file.

Displaying notes found at file offset 0x000002a8 with length 0x000011e4:
  Owner                 Data size       Description
  CORE                 0x00000150       NT_PRSTATUS (prstatus structure)
  CORE                 0x00000088       NT_PRPSINFO (prpsinfo structure)
  CORE                 0x00000fd0       NT_TASKSTRUCT (task structure)

00000000-00000fff : reserved
00001000-0009e7ff : System RAM
0009e800-0009ffff : reserved
000a0000-000bffff : PCI Bus 0000:00
000c0000-000c7fff : Video ROM
000ca000-000cafff : Adapter ROM
000cb000-000ccfff : Adapter ROM
000d0000-000d3fff : PCI Bus 0000:00
000d4000-000d7fff : PCI Bus 0000:00
000d8000-000dbfff : PCI Bus 0000:00
000dc000-000fffff : reserved
  000f0000-000fffff : System ROM
00100000-7fedffff : System RAM
  2a000000-340fffff : Crash kernel
  69000000-6972d336 : Kernel code
  6972d337-69d4f9bf : Kernel data
  69f25000-6a22ffff : Kernel bss
7fee0000-7fefefff : ACPI Tables
7feff000-7fefffff : ACPI Non-volatile Storage
7ff00000-7fffffff : System RAM
c0000000-febfffff : PCI Bus 0000:00
  c0000000-c0007fff : 0000:00:0f.0
  c0008000-c000bfff : 0000:00:10.0
  e5b00000-e5bfffff : PCI Bus 0000:22
  e5c00000-e5cfffff : PCI Bus 0000:1a
  e5d00000-e5dfffff : PCI Bus 0000:12
  e5e00000-e5efffff : PCI Bus 0000:0a
  e5f00000-e5ffffff : PCI Bus 0000:21
  e6000000-e60fffff : PCI Bus 0000:19
  e6100000-e61fffff : PCI Bus 0000:11
  e6200000-e62fffff : PCI Bus 0000:09
  e6300000-e63fffff : PCI Bus 0000:20
  e6400000-e64fffff : PCI Bus 0000:18
  e6500000-e65fffff : PCI Bus 0000:10
  e6600000-e66fffff : PCI Bus 0000:08
  e6700000-e67fffff : PCI Bus 0000:1f
  e6800000-e68fffff : PCI Bus 0000:17
  e6900000-e69fffff : PCI Bus 0000:0f
  e6a00000-e6afffff : PCI Bus 0000:07
  e6b00000-e6bfffff : PCI Bus 0000:1e
  e6c00000-e6cfffff : PCI Bus 0000:16
  e6d00000-e6dfffff : PCI Bus 0000:0e
  e6e00000-e6efffff : PCI Bus 0000:06
  e6f00000-e6ffffff : PCI Bus 0000:1d
  e7000000-e70fffff : PCI Bus 0000:15
  e7100000-e71fffff : PCI Bus 0000:0d
  e7200000-e72fffff : PCI Bus 0000:05
  e7300000-e73fffff : PCI Bus 0000:1c
  e7400000-e74fffff : PCI Bus 0000:14
  e7500000-e75fffff : PCI Bus 0000:0c
  e7600000-e76fffff : PCI Bus 0000:04
  e7700000-e77fffff : PCI Bus 0000:1b
  e7800000-e78fffff : PCI Bus 0000:13
  e7900000-e79fffff : PCI Bus 0000:0b
  e7a00000-e7afffff : PCI Bus 0000:03
  e7b00000-e7ffffff : PCI Bus 0000:02
  e8000000-efffffff : 0000:00:0f.0
    e8000000-efffffff : vmwgfx probe
  f0000000-f7ffffff : PCI MMCONFIG 0000 [bus 00-7f]
    f0000000-f7ffffff : reserved
      f0000000-f7ffffff : pnp 00:06
  fb500000-fb5fffff : PCI Bus 0000:22
  fb600000-fb6fffff : PCI Bus 0000:1a
  fb700000-fb7fffff : PCI Bus 0000:12
  fb800000-fb8fffff : PCI Bus 0000:0a
  fb900000-fb9fffff : PCI Bus 0000:21
  fba00000-fbafffff : PCI Bus 0000:19
  fbb00000-fbbfffff : PCI Bus 0000:11
  fbc00000-fbcfffff : PCI Bus 0000:09
  fbd00000-fbdfffff : PCI Bus 0000:20
  fbe00000-fbefffff : PCI Bus 0000:18
  fbf00000-fbffffff : PCI Bus 0000:10
  fc000000-fc0fffff : PCI Bus 0000:08
  fc100000-fc1fffff : PCI Bus 0000:1f
  fc200000-fc2fffff : PCI Bus 0000:17
  fc300000-fc3fffff : PCI Bus 0000:0f
  fc400000-fc4fffff : PCI Bus 0000:07
  fc500000-fc5fffff : PCI Bus 0000:1e
  fc600000-fc6fffff : PCI Bus 0000:16
  fc700000-fc7fffff : PCI Bus 0000:0e
  fc800000-fc8fffff : PCI Bus 0000:06
  fc900000-fc9fffff : PCI Bus 0000:1d
  fca00000-fcafffff : PCI Bus 0000:15
  fcb00000-fcbfffff : PCI Bus 0000:0d
  fcc00000-fccfffff : PCI Bus 0000:05
  fcd00000-fcdfffff : PCI Bus 0000:1c
  fce00000-fcefffff : PCI Bus 0000:14
  fcf00000-fcffffff : PCI Bus 0000:0c
  fd000000-fd0fffff : PCI Bus 0000:04
  fd100000-fd1fffff : PCI Bus 0000:1b
  fd200000-fd2fffff : PCI Bus 0000:13
  fd300000-fd3fffff : PCI Bus 0000:0b
  fd400000-fd4fffff : PCI Bus 0000:03
  fd500000-fdffffff : PCI Bus 0000:02
    fd500000-fd50ffff : 0000:02:01.0
    fd510000-fd51ffff : 0000:02:05.0
    fd5c0000-fd5dffff : 0000:02:01.0
      fd5c0000-fd5dffff : e1000
    fd5ee000-fd5eefff : 0000:02:05.0
      fd5ee000-fd5eefff : ahci
    fd5ef000-fd5effff : 0000:02:03.0
      fd5ef000-fd5effff : ehci_hcd
    fdff0000-fdffffff : 0000:02:01.0
      fdff0000-fdffffff : e1000
  fe000000-fe7fffff : 0000:00:0f.0
    fe000000-fe7fffff : vmwgfx probe
  fe800000-fe9fffff : pnp 00:06
  feba0000-febbffff : 0000:00:10.0
    feba0000-febbffff : mpt
  febc0000-febdffff : 0000:00:10.0
    febc0000-febdffff : mpt
  febfe000-febfffff : 0000:00:07.7
fec00000-fec0ffff : reserved
  fec00000-fec003ff : IOAPIC 0
fed00000-fed003ff : HPET 0
  fed00000-fed003ff : pnp 00:04
fee00000-fee00fff : Local APIC
  fee00000-fee00fff : reserved
fffe0000-ffffffff : reserved
```

**Comment by McFlip** [comment]
I tried taking an image after booting with the [nokaslr](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_security_guide/sect-virtualization_security_guide-guest_security-kaslr) option and I still got the same error message.

**Comment by scudette** [comment]
Could you please share a sample image (support@rekall-forensic.com) maybe we do not parse lime format correctly?

**Comment by McFlip** [comment]
@scudette Email sent with G Drive links.

**Comment by McFlip** [comment]
@scudette Has the team had a chance to look at my sample image?

**Comment by McFlip** [comment]
So I ran through everything again and I realized that I forgot to run `grub2-mkconfig` when I added the `nokaslr` option to the grub config file. I also acquired an image from within the VM to simplify as much as possible. Everything worked with kaslr turned off, so I confirmed my profile works and that kaslr is the issue. I installed the latest version of rekal, re-enabled kaslr, and acquired an aff4 image. I attempted to use `find_kaslr` and I got the below error:
```
rekall.plugin.PluginError: Plugin find_kaslr is not available for this configuration
```

**Comment by McFlip** [comment]
I tried again using [linpmem3.0rc2](https://github.com/Velocidex/c-aff4/releases). That worked whereas `sudo rekal aff4acquire` did not work. Here is the command I ran: `sudo ./linpmem_3.0rc2.bin --format map -c snappy -o share/kaslrRHEL7-5.aff`

I was able to use the aff4 image like normal. I did not have to specify a shift.
