### ISSUE TITLE
Rekall and future: requires 0.16?

### ISSUE THREAD

**Issue by juju4** [google/rekall#448]
It seems latest 0.17 is incompatible

https://travis-ci.org/juju4/ansible-rekall/jobs/448731708#L2434
```
$ docker exec --tty "$(cat ${container_id})" /usr/local/share/env-rekall/bin/rekall --version
Traceback (most recent call last):
  File "/usr/local/share/env-rekall/bin/rekall", line 7, in <module>
    from rekall.rekal import main
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/share/env-rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (future 0.17.1 (/usr/local/share/env-rekall/lib/python2.7/site-packages), Requirement.parse('future==0.16.0'), set(['rekall-efilter']))
```

install from https://github.com/google/rekall/blob/8db49aa92439d4787023c1ea37561b6903cabf9b/rekall-agent/setup.py
No change on rekall side but new future release
https://pypi.org/project/future/#history

Thanks

**Comment by scudette** [comment]
We probably need to relax the future dependency 

I think the issue is that rekall-efilter pins the requirement on future 0.16 but the others do not:
https://github.com/rekall-innovations/efilter/blob/master/setup.py#L57

Something else is installing 0.17 which is not compatible. so python breaks. It is probably safe to relax the requirement on future in efilter because future should be pretty backwards compatible.

**Comment by mgg1776** [comment]
Is there anyway to install future 0.16.0 for the Python installation Rekall is using?

I installed future==0.16.0 for my system Python installation:
```
$sudo pip install future==0.16.0
Collecting future==0.16.0
Installing collected packages: future
  Found existing installation: future 0.17.1
    Uninstalling future-0.17.1:
      Successfully uninstalled future-0.17.1
Successfully installed future-0.16.0
```
But apparently Rekall isn't recognizing that:
```
$ rekall
Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/rekall/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (future 0.17.1 (/opt/rekall/lib/python2.7/site-packages), Requirement.parse('future==0.16.0'), set(['rekall-efilter']))
```
Or alternatively, can the future version pinned in efilter be changed on an existing installation?

I'm using Rekall that is pre-installed on SANS SIFT Workstation.

Thanks.

**Comment by mgg1776** [comment]
Nevermind, I answered my own question, though I don't know if this would be the best way to do it:
```
$ sudo /opt/rekall/bin/pip install future==0.16.0
Collecting future==0.16.0
Installing collected packages: future
  Found existing installation: future 0.17.1
    Uninstalling future-0.17.1:
      Successfully uninstalled future-0.17.1
Successfully installed future-0.16.0
```

**Comment by scudette** [comment]
For now this is the best workaround. Note too that using sudo is bad practice since you are not using a virtual environment. Rekall installation without a virtual environment is not support and will likely break your system.

**Comment by faizan-tallat** [comment]
> Oh sorry - you are installing in a docker container - that should be ok as that container is only going to have Rekall installed.

hi man
i am using kali linux and still facing issue even in using that in virtual env
`raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (future 0.18.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('future==0.16.0'), set(['rekall-efilter']))
`
already uninstall future 0.18.2 and install future 0.16.0
what to do now?

**Comment by faizan-tallat** [comment]
and which installation to follow 
there is alot of installation at your website and on github page ?
