### ISSUE TITLE
Windows 10 and WIndows Server 2008 R2 SPI targets - rekall not working - 1.7.2.rc1 

### ISSUE THREAD

**Issue by ruben03** [google/rekall#454]
Hello,
I'm new using rekall.

I installed 1.7.2.rc1 and I have been playing around with it with more bad results than good.

I can't analyze windows server 2008 r2 (I can analyze it with volatility using the profile Win2008R2SP1x64_24000) and a Windows 10 (vol profile Win10x64_10240_17770).
I was only able to analyze a Windows 7 (vol profile Win7SP1x64).

+++++++++++++++++++++++++++++++++++++++++++++++++
**Current version installed:**
(MyEnv) sansforensics@siftworkstation:~$ rekall -v
2018-11-28 16:10:15,660:DEBUG:rekall.1:Logging level set to 10
2018-11-28 16:10:15,662:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': None})

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.

+++++++++++++++++++++++++++++++++++++++++++++++++
**When trying to analyze the Windows 10 image, using _pslist_, I get this:**
(MyEnv) sansforensics@siftworkstation:~$ rekall -f /cases/Sample-errase/Sample.dmp pslist
  _EPROCESS            name          pid   ppid  thread_count handle_count session_id wow64    process_create_time       process_exit_time    
-------------- -------------------- ----- ------ ------------ ------------ ---------- ------ ------------------------ ------------------------
Traceback (most recent call last):
  File "/tmp/MyEnv/bin/rekall", line 11, in <module>
    sys.exit(main())
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/rekal.py", line 111, in main
    user_session.Flush()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 1132, in Flush
    hook(*args)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/cache.py", line 275, in Flush
    self.SetFingerprint(self.session.GetParameter("image_fingerprint"))
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/windows/misc.py", line 363, in calculate
    result.append((system_time_offset, phys_as.read(system_time_offset, 8)))
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/standard.py", line 74, in read
    addr = int(addr)
TypeError: int() argument must be a string or a number, not 'NoneType'

+++++++++++++++++++++++++++++++++++++++++++++++++
**When trying to analyze the Windows 10 image, _imageinfo_, I get this:**

![image](https://user-images.githubusercontent.com/32181184/49171544-0bb99100-f33f-11e8-8d03-8801d5e76e6a.png)

![image](https://user-images.githubusercontent.com/32181184/49171641-402d4d00-f33f-11e8-8356-4fed27718ae0.png)

+++++++++++++++++++++++++++++++++++++++++++++++++
**When trying to analyze the Windows Server 2008 R2 SPI image, _imageinfo_, I get this:**
![image](https://user-images.githubusercontent.com/32181184/49171898-de211780-f33f-11e8-9342-77c11ddd3c0b.png)

+++++++++++++++++++++++++++++++++++++++++++++++++
**When trying to analyze the Windows Server 2008 R2 SPI image, _pslist_, I get this:**
![image](https://user-images.githubusercontent.com/32181184/49171838-bdf15880-f33f-11e8-866b-43c4346b4fe1.png)

Any advice?

**Comment by scudette** [comment]
This looks like an issue with the profile. The message "TypeError: int() argument must be a string or a number, not 'NoneType'" means that the system time offset is not defined - this should be defined in the profile itself.

Also messages like XXXX has no offset in YYY means the struct definitions in the vtypes are missing.

Can you repeat with the -v flag and check exactly which profile it is trying to load? sometimes profiles downloaded from the MS symbol server are corrupted and do not have the right STRUCT definitions.

Another thing to try is to run rekall in python 3 which is the officially supported configuration. I think we try to support python 2.7 but not very hard so maybe there is some problem with 2.7 support.

**Comment by ruben03** [comment]
I run it from the Windows version and it was able to work both with the Windows 10 and Windows Server 2008:
![image](https://user-images.githubusercontent.com/32181184/49241017-f0b25400-f406-11e8-98b9-ca79f1fff374.png)
