### ISSUE TITLE
convert_profile and profile_tool.py errors

### ISSUE THREAD

**Issue by mgg1776** [google/rekall#469]
When trying to convert a Volatility profile with either `rekal convert_profile` or by directly invoking `profile_tool.py`, I get the following errors:

**rekal convert_profile**
```
$ rekal convert_profile Ubuntu16.04_4.4.0-1072-aws_x86_64.zip Ubuntu16.04_4.4.0-1072-aws_x86_64.rekall.json
2018-12-14 17:21:05,478:CRITICAL:rekall.1:Traceback (most recent call last):
  File "rekall/lib/python3.5/site-packages/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "rekall/lib/python3.5/site-packages/rekall/plugins/tools/profile_tool.py", line 390, in render
    profile = self.ConvertProfile(input)
  File "rekall/lib/python3.5/site-packages/rekall/plugins/tools/profile_tool.py", line 362, in ConvertProfile
    profile = converter(input, session=self.session).Convert()
  File "rekall/lib/python3.5/site-packages/rekall/plugins/tools/profile_tool.py", line 260, in Convert
    parser.feed_line(line)
  File "rekall/lib/python3.5/site-packages/rekall/plugins/overlays/linux/dwarfdump.py", line 147, in feed_line
    m = self.dwarf_header_regex.match(line)
TypeError: cannot use a string pattern on a bytes-like object

2018-12-14 17:21:05,478:CRITICAL:root:cannot use a string pattern on a bytes-like object. Try --debug for more information.
Traceback (most recent call last):
  File "rekall/bin/rekal", line 11, in <module>
    sys.exit(main())
  File "rekall/lib/python3.5/site-packages/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "rekall/lib/python3.5/site-packages/rekall/session.py", line 869, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "rekall/lib/python3.5/site-packages/rekall/session.py", line 866, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "rekall/lib/python3.5/site-packages/rekall/plugins/tools/profile_tool.py", line 390, in render
    profile = self.ConvertProfile(input)
  File "rekall/lib/python3.5/site-packages/rekall/plugins/tools/profile_tool.py", line 362, in ConvertProfile
    profile = converter(input, session=self.session).Convert()
  File "rekall/lib/python3.5/site-packages/rekall/plugins/tools/profile_tool.py", line 260, in Convert
    parser.feed_line(line)
  File "rekall/lib/python3.5/site-packages/rekall/plugins/overlays/linux/dwarfdump.py", line 147, in feed_line
    m = self.dwarf_header_regex.match(line)
TypeError: cannot use a string pattern on a bytes-like object
```
**profile_tool.py**
```
$ python profile_tool.py convert Ubuntu16.04_4.4.0-1072-aws_x86_64.zip Ubuntu16.04_4.4.0-1072-aws_x86_64.rekall.json
Traceback (most recent call last):
  File "profile_tool.py", line 329, in <module>
    class ConvertProfile(plugin.TypedProfileCommand, plugin.Command):
  File "rekall/lib/python3.5/site-packages/rekall_lib/registry.py", line 141, in __init__
    cls, cls.classes[cls.__name__]))
RuntimeError: Multiple definitions for class <class '__main__.ConvertProfile'> (<class 'rekall.plugins.tools.profile_tool.ConvertProfile'>)
```
**Rekall Installation and Version**
I installed Rekall in a virtual environment on an AWS EC2 instance running Ubuntu Server 16.04, as such:
```
python3 -m venv rekall
source rekall/bin/activate
(rekall) $ python3 -m pip install --upgrade pip
(rekall) $ python3 -m pip uninstall future
(rekall) $ python3 -m pip install future==0.16.0
(rekall) $ python3 -m pip install --upgrade setuptools
(rekall) $ python3 -m pip install --upgrade wheel
(rekall) $ python3 -m pip install rekall
(rekall) $ deactivate
```
```
$ rekal --version
This is Rekall Version 1.7.2.rc1 (Hurricane Ridge)
{'version': '1.7.2', 'rc': '1', 'pep440': '1.7.2.rc1', 'codename': 'Hurricane Ridge', 'post': '0', 'error': 'Not in a git repository.'}
```

**Comment by scudette** [comment]
Which python version is it? I think this error happens when your python is
too old.

**Comment by scudette** [comment]
Does it fix it if we convert the regex to bytes?

```
--- a/rekall-core/rekall/plugins/overlays/linux/dwarfdump.py
+++ b/rekall-core/rekall/plugins/overlays/linux/dwarfdump.py
@@ -30,11 +30,12 @@ class DWARFParser(object):
 
     # Nasty, but appears to parse the lines we need
     dwarf_header_regex = re.compile(
-        r'<(?P<level>\d+)><(?P<statement_id>[0-9+]+)><(?P<kind>\w+)>')
+        br'<(?P<level>\d+)><(?P<statement_id>[0-9+]+)><(?P<kind>\w+)>')
     dwarf_key_val_regex = re.compile(
-        '\s*(?P<keyname>\w+)<(?P<val>[^>]*)>')
+        b'\s*(?P<keyname>\w+)<(?P<val>[^>]*)>')
 
-    dwarf_header_regex2 = re.compile(r'<(?P<level>\d+)><(?P<statement_id>0x[0-9a-fA-F]+([+]0x[0-9a-fA-F]+)?)><(?P<kind>\w+)>')
+    dwarf_header_regex2 = re.compile(
+        br'<(?P<level>\d+)><(?P<statement_id>0x[0-9a-fA-F]+([+]0x[0-9a-fA-F]+)?)><(?P<kind>\w+)>')
 
     sz2tp = {8: 'long long', 4: 'int', 2: 'short', 1: 'char'}
     tp2vol = {
```

**Comment by scudette** [comment]
You would need to install from source to be able to run git head. There are instructions on the blog:

http://blog.rekall-forensic.com/2015/09/installing-rekall-on-windows.html
