### ISSUE TITLE
RuntimeError: RebuildM2PMapping recursed... aborting.

### ISSUE THREAD

**Issue by Matir** [google/rekall#481]
```2019-02-23 19:49:20,445:INFO:rekall.1:Autodetected physical address space FileAddressSpace
2019-02-23 19:49:20,447:DEBUG:rekall.1:Opened local file /tmp/profile.json
2019-02-23 19:49:20,923:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({'profile': 'profile.json', 'proc_regex': None, 'task': None, 'verbosity': 1, 'pids': None, 'method': ['InitTask']})
2019-02-23 19:49:20,924:DEBUG:rekall.1:DTB not specified. Delegating to find_dtb.
2019-02-23 19:49:20,924:DEBUG:rekall.1:Calculating page offset...
2019-02-23 19:49:20,924:DEBUG:rekall.1:Page offset is ffff80000000
2019-02-23 19:49:20,925:DEBUG:rekall.1:Detected paravirtualized XEN guest
2019-02-23 19:49:20,938:DEBUG:rekall.1:Rebuilding the machine to physical mapping...
2019-02-23 19:49:20,939:DEBUG:rekall.1:p2m_top = 0x0
2019-02-23 19:49:20,940:DEBUG:rekall.1:p2m_missing = 0x0
2019-02-23 19:49:20,940:DEBUG:rekall.1:p2m_mid_missing = 0x0
2019-02-23 19:49:20,941:DEBUG:rekall.1:p2m_identity = 0x0
2019-02-23 19:49:20,941:DEBUG:rekall.1:XENFEAT_auto_translated_physmap = 0
2019-02-23 19:49:20,943:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 862, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/session.py", line 921, in _GetPluginObj
    return plugin_cls(*args, **kwargs)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugin.py", line 888, in __init__
    self.session.plugins.load_as().GetVirtualAddressSpace()
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 424, in GetVirtualAddressSpace
    for address_space in find_dtb.address_space_hits():
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 258, in address_space_hits
    address_space = self.VerifyHit(hit)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/linux/common.py", line 164, in VerifyHit
    address_space = super(LinuxFindDTB, self).VerifyHit(dtb)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 248, in VerifyHit
    return self.CreateAS(hit)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 269, in CreateAS
    profile=self.profile)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 368, in __init__
    self._RebuildM2PMapping()
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 469, in _RebuildM2PMapping
    p2m_top_location, self.P2M_TOP_PER_PAGE):
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 401, in _ReadP2M
    self.read(offset, 0x1000))):
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 589, in read
    buf = self._read_chunk(addr, length)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/addrspace.py", line 550, in _read_chunk
    paddr = self.vtop(vaddr)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 617, in vtop
    return super(XenParaVirtAMD64PagedMemory, self).vtop(vaddr)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/intel.py", line 316, in vtop
    aligned_vaddr, PhysicalAddressDescriptorCollector(self.session))
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 79, in describe_vtop
    pml4e_value = self.read_pte(pml4e_addr, collection=collection)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 584, in read_pte
    pfn = self.m2p(mfn)
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 574, in m2p
    self._RebuildM2PMapping()
  File "/home/david/.virtualenvs/rekall/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/amd64.py", line 429, in _RebuildM2PMapping
    raise RuntimeError("RebuildM2PMapping recursed... aborting.")
RuntimeError: RebuildM2PMapping recursed... aborting.
```

I realize this might be similar to #97, #383, #388.  In this case, this happens both with an image acquired by dumping `/dev/pmem` as well as `virsh dump`.  The VM in question is running Ubuntu 12.04 (yes, it's ancient, but I wanted to try one before KASLR was enabled) running on Qemu/KVM.

**Comment by Matir** [comment]
For what it's worth, patching rekall to remove the Xen checks on lines 187-198 of rekall-core/rekall/plugins/linux/common.py "fixes" the issue.  I think the pv_info check is generating a false positive for my kernel.

**Comment by Matir** [comment]
And of course, the false positive is due to the kernel setting paravirt_enabled, even though it's on KVM and not really paravirtualized...

**Comment by ossie-git** [comment]
I just ran into the same issue and your fix on disabling the Xen checks did the trick.  I acquired the memory image from a KVM guest

**Comment by scudette** [comment]
Maybe we should have a flag or something to tell it is it is a xen image of
we can't rely on the kernel itself

**Comment by ossie-git** [comment]
I think KVM is more widely used than Xen.  So having it default to KVM with an optional flag to explicitly choose Xen might be useful
