### ISSUE TITLE
Recall fails to find a valid profile for windows 10

### ISSUE THREAD

**Issue by 0Slugcat0** [google/rekall#487]
I'm using a LibVMI script but this is technically a rekall issue, so I'm posting it here.
(Libvmi/tools/windows-offset-finder/rekall_offset_finder.py)

The script a provided by LibVMI which makes a dump of the virtual machine and uses Recall to generate a Offset config. 

However it seems that Recall fails to identify the dumped Windows 10 image.
`    "Unable to find a valid profile for this image. "`

```
./rekall_offset_finder.py -d win10 
Webconsole disabled: cannot import name 'webconsole_plugin'
INFO:root:Dumping win10 physical memory to /tmp/tmp5xia6bdq/tmp2sgamy8v
DEBUG:root:Running plugin (version_modules) with args (()) kwargs ({})
DEBUG:root:Voting round with base: None
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
DEBUG:root:Failed instantiating XenElf64CoreDump: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:root:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:root:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
DEBUG:root:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:root:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume: No physical memory categories found.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:root:Failed instantiating MacPmemAddressSpace: MacPmem would declare a YML device at /tmp/tmp5xia6bdq/tmp2sgamy8v_info
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:root:Succeeded instantiating FileAddressSpace
DEBUG:root:Voting round with base: FileAddressSpace
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x464c457f
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Not kcore
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Succeeded instantiating Elf64CoreDump
DEBUG:root:Voting round with base: Elf64CoreDump
DEBUG:root:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'> 
DEBUG:root:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:root:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:root:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0xf000ff53
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:root:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:root:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:root:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:root:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:root:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.elfcore.XenElf64CoreDump'> 
DEBUG:root:Failed instantiating XenElf64CoreDump: Header signature invalid
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:root:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:root:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.vmi.VMIAddressSpace'> 
DEBUG:root:Failed instantiating VMIAddressSpace: The LibVMI python bindings must be installed
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:root:Failed instantiating AFF4AddressSpace: Must stack on another address space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:root:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:root:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
DEBUG:root:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
DEBUG:root:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
DEBUG:root:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:root:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
DEBUG:root:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:root:Autodetected physical address space Elf64CoreDump
DEBUG:root:Will detect profile using these Detectors: rsds
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:root:Opened url http://profiles.rekall-forensic.com/v1.0/pe.gz
DEBUG:root:Adding pe to local cache.
INFO:root:Loaded profile pe from Local Cache - (in 0.08415699005126953 sec)
DEBUG:root:Trying method rsds, offset 0
DEBUG:root:Skipped profile nt/GUID/8B11040A5928757B11390AC78F6B69251 from http://profiles.rekall-forensic.com (Not in inventory)
DEBUG:root:Skipped profile nt/GUID/2AC01A5FDAC6452D82685CDD622F85971 from http://profiles.rekall-forensic.com (Not in inventory)
ERROR:root:No profiles match this image. Try specifying manually.
Traceback (most recent call last):
  File "./rekall_offset_finder.py", line 177, in <module>
    exit_code = main(args)
  File "./rekall_offset_finder.py", line 167, in main
    config = extract_offsets(domain.name(), ram_dump.name)
  File "./rekall_offset_finder.py", line 57, in extract_offsets
    s.RunPlugin("version_modules", output=strio)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 866, in RunPlugin
    plugin_obj = self._GetPluginObj(plugin_obj, *args, **kwargs)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 916, in _GetPluginObj
    plugin_cls = getattr(self.plugins, plugin_obj, None)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 155, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 135, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 986, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/guess_profile.py", line 765, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
```

**Comment by 0Slugcat0** [comment]
I ( By magical means ) made a profile for Windows 10 LTSC properly.
Have some info regarding ntoskrnl.exe:

```
          Attribute                                       Value                            
------------------------------ ------------------------------------------------------------
Machine                        IMAGE_FILE_MACHINE_AMD64                                    
TimeDateStamp                  2044-04-10 16:09:02Z                                        
Characteristics                IMAGE_FILE_EXECUTABLE_IMAGE, IMAGE_FILE_LARGE_ADDRESS_AWARE 
GUID/Age                       69247313056076BBCB3411FD964287141                           
PDB                            ntkrnlmp.pdb                                                
MajorOperatingSystemVersion    10                                                          
MinorOperatingSystemVersion    0                                                           
MajorImageVersion              10                                                          
MinorImageVersion              0                                                           
MajorSubsystemVersion          10                                                          
MinorSubsystemVersion          0 

[.. Snip ..]

CompanyName          Microsoft Corporation
FileDescription      NT Kernel & System
FileVersion          10.0.17763.107 (WinBuild.160101.0800)
InternalName         ntkrnlmp.exe
LegalCopyright       © Microsoft Corporation. All rights reserved.
OriginalFilename     ntkrnlmp.exe
ProductName          Microsoft® Windows® Operating System
ProductVersion       10.0.17763.107
VarFileInfo               
                     $   
䑁䥄䝎䅐䑄义塇偘䑁䥄䝎䅐䑄义塇偘䑁䥄䝎䅐      
䑄义塇偘䑁䥄䝎䅐䑄义塇偘䑁䥄䝎䅐䑄义塇       
Translation          \x09\x04\xb0\x04
[69247313056076BBCB3411FD964287141.gz](https://github.com/google/rekall/files/2968509/69247313056076BBCB3411FD964287141.gz)

```

**Comment by scudette** [comment]
Can you please run a version scan on the image? Why is it not seeing the RSDS signature?

```
rekall -f image version_scan name_regex='krnl'
```

**Comment by 0Slugcat0** [comment]
So with the name_regex it crashes I piped it to grep with "krnl" instead.

```
0x2999dc0 69247313056076BBCB3411FD964287141 ntkrnlmp.pdb                  
0x7eea3080 A1614AABA13845BF6BDC2AD1A768F11E1 dxgkrnl.pdb                   
0x17bd36b80 A65F3A293866403EBCFC6E67A5559BA91 ntoskrnl.pdb            
```      
Error with the name_regex:

rekal -f win10.dd version_scan name_regex='krnl'
```
Webconsole disabled: cannot import name 'webconsole_plugin'
    offset                   guid                             pdb              
-------------- --------------------------------- ------------------------------
2019-03-14 22:52:39,960:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/windows/modules.py", line 174, in collect
    for rsds, guid in self.ScanVersions():
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/windows/modules.py", line 158, in ScanVersions
    for hit in scanner.scan(0, self.physical_address_space.end()):
AttributeError: 'NoneType' object has no attribute 'end'

2019-03-14 22:52:39,960:CRITICAL:root:'NoneType' object has no attribute 'end'. Try --debug for more information.
Traceback (most recent call last):
  File "/home/user/libvmi/tools/windows-offset-finder/venv/bin/rekal", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekal')()
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/windows/modules.py", line 174, in collect
    for rsds, guid in self.ScanVersions():
  File "/home/user/libvmi/tools/windows-offset-finder/rekall/rekall-core/rekall/plugins/windows/modules.py", line 158, in ScanVersions
    for hit in scanner.scan(0, self.physical_address_space.end()):
AttributeError: 'NoneType' object has no attribute 'end'
```
