### ISSUE TITLE
Cannot install rekall

### ISSUE THREAD

**Issue by xQsme** [google/rekall#488]
Running a fully updated arch linux install, installing rekall from the Arch User Repositories results in:
```Processing ./rekall-git/rekall-gui
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4tq4_rxq/setup.py", line 30, in <module>
        exec(open("rekall_gui/_version.py").read(), VERSION_ENV)
    FileNotFoundError: [Errno 2] No such file or directory: 'rekall_gui/_version.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-4tq4_rxq/
==> ERROR: A failure occurred in package().
    Aborting...
Error making: rekall-git
```
Following the README.MD (using virtual.env), the install fails with the following output:
```  Running setup.py install for acora ... error
    Complete output from command /home/xqsme/rekall/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-o5xeemnu/acora/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jl866b6j/install-record.txt --single-version-externally-managed --compile --install-headers /home/xqsme/rekall/env/include/site/python3.7/acora:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/acora
    copying acora/__init__.py -> build/lib.linux-x86_64-3.7/acora
    copying acora/_acora.py -> build/lib.linux-x86_64-3.7/acora
    running build_ext
    building 'acora._acora' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/acora
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -c acora/_acora.c -o build/temp.linux-x86_64-3.7/acora/_acora.o
    gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now build/temp.linux-x86_64-3.7/acora/_acora.o -L/usr/lib -lpython3.7m -o build/lib.linux-x86_64-3.7/acora/_acora.cpython-37m-x86_64-linux-gnu.so
    building 'acora._cacora' extension
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fstack-protector-strong -fno-plt -fPIC -I/usr/include/python3.7m -c acora/_cacora.c -o build/temp.linux-x86_64-3.7/acora/_cacora.o
    acora/_cacora.c: In function '__Pyx_ExceptionSave':
    acora/_cacora.c:14708:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         *type = tstate->exc_type;
                         ^~~~~~~~
                         curexc_type
    acora/_cacora.c:14709:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         *value = tstate->exc_value;
                          ^~~~~~~~~
                          curexc_value
    acora/_cacora.c:14710:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         *tb = tstate->exc_traceback;
                       ^~~~~~~~~~~~~
                       curexc_traceback
    acora/_cacora.c: In function '__Pyx_ExceptionReset':
    acora/_cacora.c:14722:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    acora/_cacora.c:14723:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    acora/_cacora.c:14724:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    acora/_cacora.c:14725:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = type;
                 ^~~~~~~~
                 curexc_type
    acora/_cacora.c:14726:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = value;
                 ^~~~~~~~~
                 curexc_value
    acora/_cacora.c:14727:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    acora/_cacora.c: In function '__Pyx_GetException':
    acora/_cacora.c:14770:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    acora/_cacora.c:14771:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    acora/_cacora.c:14772:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    acora/_cacora.c:14773:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = local_type;
                 ^~~~~~~~
                 curexc_type
    acora/_cacora.c:14774:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = local_value;
                 ^~~~~~~~~
                 curexc_value
    acora/_cacora.c:14775:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = local_tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    acora/_cacora.c: In function '__Pyx_ExceptionSwap':
    acora/_cacora.c:16503:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tmp_type = tstate->exc_type;
                            ^~~~~~~~
                            curexc_type
    acora/_cacora.c:16504:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tmp_value = tstate->exc_value;
                             ^~~~~~~~~
                             curexc_value
    acora/_cacora.c:16505:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tmp_tb = tstate->exc_traceback;
                          ^~~~~~~~~~~~~
                          curexc_traceback
    acora/_cacora.c:16506:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
         tstate->exc_type = *type;
                 ^~~~~~~~
                 curexc_type
    acora/_cacora.c:16507:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
         tstate->exc_value = *value;
                 ^~~~~~~~~
                 curexc_value
    acora/_cacora.c:16508:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
         tstate->exc_traceback = *tb;
                 ^~~~~~~~~~~~~
                 curexc_traceback
    At top level:
    acora/_cacora.c:5071:18: warning: '__pyx_f_5acora_7_cacora_group_transitions_by_state' defined but not used [-Wunused-function]
     static PyObject *__pyx_f_5acora_7_cacora_group_transitions_by_state(PyObject *__pyx_v_transitions) {
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/xqsme/rekall/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-o5xeemnu/acora/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-jl866b6j/install-record.txt --single-version-externally-managed --compile --install-headers /home/xqsme/rekall/env/include/site/python3.7/acora" failed with error code 1 in /tmp/pip-install-o5xeemnu/acora/
```

running `sudo python setup.py install` the tool is installed but running `rekall` results in the following output:
```[xqsme@arch ~]$ rekall
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytz 2018.9 (/usr/lib/python3.7/site-packages), Requirement.parse('pytz==2017.3'), {'rekall-core'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/rekall", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (future 0.17.1 (/usr/lib/python3.7/site-packages), Requirement.parse('future==0.16.0'), {'rekall-efilter'})
```

**Comment by scudette** [comment]
It looks like your python headers are not compatible with acora - which version of python are you using? 

If you install a more recent version of acora does it build (pip install acora)?

It is not recommended to install to the system (with sudo ) because this will break your system. Virtual env is the recommended way to install any python application.

**Comment by xQsme** [comment]
Running Python 3.7.2
Cannot install rekall even with acora upgraded, same error
Also how can I uninstall the global install i made with setup.py?
Need rekall for a project, we're a 4 man group and we've tried to install it in multiple OSes, we ended up downloading REMnux (without upgrading packages rekall works there, after upgrading we end up with the same error as my global install)...

**Comment by yampelo** [comment]
This happens because the requirement is acora==2.1 while you need acora==2.2 for python3.7+ support

**Comment by Wenzel** [comment]
Related: #474

**Comment by HusseinBakri** [comment]
Can not install the framework on Windows 7 Ultimate, pip 19.3.1 and  Python 3.7.4 . I am trying to install the latest version Release 1.7.1: 
pip install rekall

```
Collecting rekall-yara==3.6.3.1
  Using cached https://files.pythonhosted.org/packages/c1/a2/a1fd733b5855208c20408cb74d6303c90dededc127e78fbca2dee52ef54a/rekall_yara-3.6.3.1.tar.gz
ERROR: Could not find a version that satisfies the requirement pypiwin32==220 (from rekall-core<1.8,>=1.7.0rc1->rekall) (from versions: 219, 223)
ERROR: No matching distribution found for pypiwin32==220 (from rekall-core<1.8,>=1.7.0rc1->rekall)
```
Any suggestions of how to solve this are greatly appreciated. Also is there any example of how to capture MS Windows 7 RAM  through Python 3 code using the framework?

**Comment by xQsme** [comment]
From what I "rekall" I had to force the usage of python 3.6 and also force specific versions for certain dependencies.
Check @rschmidt-ht 's comment:


> same issues here for both acora and PyYAML (can't build wheel) via Python 3.7.0
> 
> Installing from https://www.python.org/downloads/release/python-368/ on macOS allows 2.7.16 / 3.7.0 / 3.6.8 to all coexist, just setup virtualenv using the 3.6.8 python environment:
> 
> `virtualenv -p python3.6 ./rekall_env3/`
> `cd rekall_env3`
> `pip install rekall-agent rekall`
> 
> ```
> ...
>   Stored in directory: /Users/rschmidt/Library/Caches/pip/wheels/89/36/b5/2b5462499df3ba2625c498b9c8959d02f42b5751529505aa0d
>   Building wheel for PyYAML (setup.py) ... done
>   Stored in directory: /Users/rschmidt/Library/Caches/pip/wheels/d1/93/b2/446af26df95f3031d9223ca4c69b36c54c9ac703c196e57a15
>   Building wheel for acora (setup.py) ... done
> ...
> ```
> 
> Still have to fixup for future now having 0.17.x release:
> `pip uninstall future`
> `pip install future==0.16.0`
> `rekal`
