### ISSUE TITLE
TypeError: Set() missing 1 required positional argument: 'value'

### ISSUE THREAD

**Issue by Wenzel** [google/rekall#493]
Hi,

I installed Rekall from source today, but couldn't open a Xen memory dump:

~~~
(rekall)  ✘ wenzel@localhost  ~/Projets  rekall -f pyvmidbg/winxp.dump
Webconsole disabled: cannot import name 'webconsole_plugin' from 'rekall.plugins.tools' (/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/tools/__init__.py)
2019-04-23 02:36:12,704:CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/tools/ipython.py", line 211, in render
    if not IPython012Support(self.session):
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/tools/ipython.py", line 53, in IPython012Support
    return ipython_support.Shell(user_session)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/ipython_support.py", line 267, in Shell
    shell = RekallShell(config=cfg, user_ns=user_session.locals)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/embed.py", line 159, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 430, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 527, in __init__
    self.init_magics()
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/embed.py", line 174, in init_magics
    super(InteractiveShellEmbed, self).init_magics()
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 413, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2086, in init_magics
    self.run_line_magic('colors', self.colors)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2123, in run_line_magic
    magic_arg_s = self.var_expand(line, stack_depth)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3117, in var_expand
    ns = self.user_ns.copy()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 1183, in keys
    return list(self)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 1172, in __iter__
    res.update(self["plugins"].__dir__())
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 164, in __dir__
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 164, in <listcomp>
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugin.py", line 403, in GetActiveClasses
    if command_cls.is_active(session):
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/wenzel/Projets/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/guess_profile.py", line 731, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/wenzel/Projets/rekall/rekall-lib/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/addrspaces/aff4.py", line 125, in __init__
    os.path.join(cache_dir, "aff4_cache")))
TypeError: Set() missing 1 required positional argument: 'value'

2019-04-23 02:36:12,704:CRITICAL:root:Set() missing 1 required positional argument: 'value'. Try --debug for more information.
Traceback (most recent call last):
  File "/home/wenzel/softs/rekall/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/tools/ipython.py", line 211, in render
    if not IPython012Support(self.session):
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/tools/ipython.py", line 53, in IPython012Support
    return ipython_support.Shell(user_session)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/ipython_support.py", line 267, in Shell
    shell = RekallShell(config=cfg, user_ns=user_session.locals)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/embed.py", line 159, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 430, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 527, in __init__
    self.init_magics()
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/embed.py", line 174, in init_magics
    super(InteractiveShellEmbed, self).init_magics()
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 413, in init_magics
    super(TerminalInteractiveShell, self).init_magics()
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2086, in init_magics
    self.run_line_magic('colors', self.colors)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2123, in run_line_magic
    magic_arg_s = self.var_expand(line, stack_depth)
  File "/home/wenzel/softs/rekall/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3117, in var_expand
    ns = self.user_ns.copy()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 1183, in keys
    return list(self)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 1172, in __iter__
    res.update(self["plugins"].__dir__())
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 164, in __dir__
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 164, in <listcomp>
    cls.name for cls in plugin.Command.GetActiveClasses(self.session)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugin.py", line 403, in GetActiveClasses
    if command_cls.is_active(session):
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/home/wenzel/Projets/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/guess_profile.py", line 731, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/home/wenzel/Projets/rekall/rekall-lib/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/home/wenzel/Projets/rekall/rekall-core/rekall/plugins/addrspaces/aff4.py", line 125, in __init__
    os.path.join(cache_dir, "aff4_cache")))
TypeError: Set() missing 1 required positional argument: 'value'
~~~

It looks like a trivial error, but I don't know code.

@scudette can you fix it ?

Thanks :slightly_smiling_face:

**Comment by Wenzel** [comment]
Even when I install the latest release from pip, it fails at the same location:

~~~
[1] winxp.dump 02:48:31> pslist
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/wenzel/local/venv/lib/python2.7/site-packages/IPython/core/prefilter.pyc in prefilter_lines(self, lines, continue_prompt)
    333                              for lnum, line in enumerate(llines) ])
    334         else:
--> 335             out = self.prefilter_line(llines[0], continue_prompt)
    336 
    337         return out

/home/wenzel/local/venv/lib/python2.7/site-packages/IPython/core/prefilter.pyc in prefilter_line(self, line, continue_prompt)
    308             return normal_handler.handle(line_info)
    309 
--> 310         prefiltered = self.prefilter_line_info(line_info)
    311         # print "prefiltered line: %r" % prefiltered
    312         return prefiltered

/home/wenzel/local/venv/lib/python2.7/site-packages/IPython/core/prefilter.pyc in prefilter_line_info(self, line_info)
    250         """
    251         # print "prefilter_line_info: ", line_info
--> 252         handler = self.find_handler(line_info)
    253         return handler.handle(line_info)
    254 

/home/wenzel/local/venv/lib/python2.7/site-packages/IPython/core/prefilter.pyc in find_handler(self, line_info)
    257         for checker in self.checkers:
    258             if checker.enabled:
--> 259                 handler = checker.check(line_info)
    260                 if handler:
    261                     return handler

/home/wenzel/local/venv/lib/python2.7/site-packages/IPython/core/prefilter.pyc in check(self, line_info)
    413 
    414     def check(self, line_info):
--> 415         obj = self.shell.user_ns.get(line_info.ifun)
    416         if isinstance(obj, Macro):
    417             return self.prefilter_manager.get_handler_by_name('macro')

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in get(self, item, default)
   1183     def get(self, item, default=None):
   1184         try:
-> 1185             return self[item]
   1186         except KeyError:
   1187             return default

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in __getitem__(self, item)
   1176             return super(DynamicNameSpace, self).__getitem__(item)
   1177         except KeyError:
-> 1178             if getattr(self["session"].plugins, item):
   1179                 return self._prepare_runner(item)
   1180 

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in __getattr__(self, name)
    153         pslist_plugin = plugins.pslist()
    154         """
--> 155         plugin_cls = self.GetPluginClass(name)
    156         if plugin_cls == None:
    157             return plugin_cls

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in GetPluginClass(self, name)
    133         """
    134         # Try to see if the requested plugin is active right now.
--> 135         metadata = self.plugin_db.GetActivePlugin(name)
    136         if metadata == None:
    137             return metadata

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/plugin.pyc in GetActivePlugin(self, plugin_name)
    980         for command_metadata in self.db.get(plugin_name, []):
    981             plugin_cls = command_metadata.plugin_cls
--> 982             if plugin_cls.is_active(self.session):
    983                 results.append(command_metadata)
    984 

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/plugin.pyc in is_active(cls, session)
    432             # completing the available plugins we will trigger profile
    433             # autodetection in order to determine which plugins are active.
--> 434             profile = (session.profile != None and
    435                        super(ProfileCommand, cls).is_active(session))
    436 

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall_lib/utils.pyc in __get__(self, *args, **kwargs)
   1089     def __get__(self, *args, **kwargs):
   1090         try:
-> 1091             return super(safe_property, self).__get__(*args, **kwargs)
   1092         except AttributeError as e:
   1093             message = "AttributeError raised: %s" % e

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in profile(self)
   1060             return process_context
   1061 
-> 1062         res = self.GetParameter("profile_obj")
   1063         return res
   1064 

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in GetParameter(self, item, default, cached)
    766         # can get if from a hook.
    767         try:
--> 768             result = self._RunParameterHook(item)
    769             if result is not None:
    770                 return result

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/session.pyc in _RunParameterHook(self, name)
    801                     self._hook_locks.add(name)
    802                     hook = cls(session=self)
--> 803                     result = hook.calculate()
    804 
    805                     # Cache the output from the hook directly.

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/plugins/guess_profile.pyc in calculate(self)
    728         if not self.session.physical_address_space:
    729             # Try to load the physical_address_space so we can scan it.
--> 730             if not self.session.plugins.load_as().GetPhysicalAddressSpace():
    731                 # If a filename was specified this should have worked, unless we
    732                 # could not open it.

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/plugins/core.pyc in GetPhysicalAddressSpace(self)
    376             # Try to get a physical address space.
    377             if self.pas_spec == "auto":
--> 378                 self.session.physical_address_space = self.GuessAddressSpace()
    379             else:
    380                 self.session.physical_address_space = self.AddressSpaceFactory(

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/plugins/core.pyc in GuessAddressSpace(self, base_as, **kwargs)
    475                 try:
    476                     base_as = cls(base=base_as, session=self.session,
--> 477                                   **kwargs)
    478                     self.session.logging.debug("Succeeded instantiating %s",
    479                                                base_as)

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall_lib/registry.pyc in __call__(cls, *args, **kwargs)
     94 
     95     def __call__(cls, *args, **kwargs):
---> 96         res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
     97         res._object_id = UniqueObjectIdMetaclass.ID  # pylint: disable=protected-access
     98         UniqueObjectIdMetaclass.ID += 1

/home/wenzel/local/venv/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.pyc in __init__(self, filename, **kwargs)
    123                                   lexicon.AFF4_FILE_NAME,
    124                                   rdfvalue.XSDString(
--> 125                                       os.path.join(cache_dir, "aff4_cache")))
    126         except IOError:
    127             pass

TypeError: Set() takes exactly 5 arguments (4 given)
~~~

It looks like Rekall is broken for now :(

**Comment by scudette** [comment]
It seems the pyaff4 pushed a new version to pypi which has incompatible api. You should be able to force the install of the old version:

```
pip install pyaff4==0.26.post6
```

We should maybe pin this version in our setup.py.

**Comment by Wenzel** [comment]
Hi,

I installed rekall from pip today and it was still broken (I had to check this issue and `pip install pyaff4==0.26.post6`).

Can you fix this in pip ?

Thanks.

**Comment by ChrisDukarm** [comment]
Having the exact same issue, any help?

**Comment by s0i37** [comment]
I had the same error and downgrade to `pyaff4==0.26.post6` helped me.
Thank you!

**Comment by rhertzog** [comment]
rekall needs to be updated to work with the latest version of pyaff4, while pinning the version is an acceptable work around in the short term, it can't be a long term solution... this change happened more than 11 months ago and pyaff4 0.27 is available since April now.
