### ISSUE TITLE
Can't run commands in Rekall on Ubuntu 16.04 Desktop

### ISSUE THREAD

**Issue by heyquentin** [google/rekall#495]
Hi. I'm trying to get rekall to run on my Ubuntu 16.04 Desktop machine running in VirtualBox but I'm having some problems when actually doing something like a pslist. I'll start from the beginning.

Virtualenv as per instructions
````
root@rekall:~# virtualenv  /tmp/MyEnv
New python executable in /tmp/MyEnv/bin/python
Installing setuptools, pip, wheel...
done.
root@rekall:~# source /tmp/MyEnv/bin/activate
````

Install Rekall
````
(MyEnv) root@rekall:~# pip install rekall
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting rekall
Collecting rekall-core<1.8,>=1.7.0rc1 (from rekall)
Collecting rekall-agent<1.8,>=1.7.0rc1 (from rekall)
Collecting rekall-lib<1.8,>=1.7.0rc1 (from rekall)
Collecting readline; sys_platform != "win32" (from rekall)
Collecting ipython<7.0,>=5.0.0 (from rekall)
  Using cached https://files.pythonhosted.org/packages/b0/88/d996ab8be22cea1eaa18baee3678a11265e18cf09974728d683c51102148/ipython-5.8.0-py2-none-any.whl
Collecting parsedatetime==2.4 (from rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/1d/48/ac8d4c6239437592852e951bcb9438dc585f80c29777c391aef69c67dc79/parsedatetime-2.4-py2-none-any.whl
Collecting pyaff4<0.30,>=0.26 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting pyparsing==2.1.5 (from rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/24/c5/3ce00e6a5fca0eb962553467a51b44de1a13e1bc23dabf58e2e9799b8807/pyparsing-2.1.5-py2.py3-none-any.whl
Collecting acora==2.0 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting psutil<6.0,>=5.0 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting ipaddr==2.2.0 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting PyYAML==3.12 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting pycryptodome==3.4.7 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting rekall-yara==3.6.3.1 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting arrow==0.10.0 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting pytz==2017.3 (from rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/a3/7f/e7d1acbd433b929168a4fb4182a2ff3c33653717195a26c1de099ad1ef29/pytz-2017.3-py2.py3-none-any.whl
Collecting future (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting rekall-capstone==3.0.5.post2 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting artifacts==20170909 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting pytsk3==20170802 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting intervaltree==2.1.0 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting python-dateutil==2.6.1 (from rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/4b/0d/7ed381ab4fe80b8ebf34411d14f253e1cf3e56e2820ffa1d8844b23859a2/python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pyelftools==0.24 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting rekall-efilter<1.7,>=1.6 (from rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting portpicker==1.1.1 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
Collecting httplib2==0.9.2 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
Collecting oauth2client==3.0.0 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
Collecting filelock==2.0.6 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
Collecting requests==2.18.1 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/5a/58/671011e3ff4a06e2969322267d78dcfda1bf4d1576551df1cce93cd7239d/requests-2.18.1-py2.py3-none-any.whl
Collecting sseclient==0.0.18 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
Collecting pathlib==1.0.1 (from rekall-agent<1.8,>=1.7.0rc1->rekall)
Collecting sortedcontainers==1.5.7 (from rekall-lib<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/b8/8c/d7de1a8f5bc878c1ff143aed7e0bb96846785b1d899fb15047376b4ad50e/sortedcontainers-1.5.7-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/4e/4e/e5545e8bebf89790455b31112a0f886580c7b3624a05abec416efa5c3a08/prompt_toolkit-1.0.16-py2-none-any.whl
Collecting decorator (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/0e/3e/377007e3f36ec42f1b84ec322ee12141a9e10d808312e5738f52f80a232c/pexpect-4.7.0-py2.py3-none-any.whl
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=18.5 in /tmp/MyEnv/lib/python2.7/site-packages (from ipython<7.0,>=5.0.0->rekall) (41.0.1)
Collecting pygments (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl
Collecting traitlets>=4.2 (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython<7.0,>=5.0.0->rekall)
Collecting pickleshare (from ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting expiringdict==1.1.4 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting fastchunking (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/64/89/f9ede0f8c27c34ca7794beb3eede54aa630e7a1be9449aede50100db10ab/fastchunking-0.0.3.tar.gz
Collecting tzlocal (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting aff4-snappy==0.5.1 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting rdflib[sparql]==4.2.2 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting html5lib (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting pyblake2>=0.9.3 (from pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
Collecting six>=1.5 (from python-dateutil==2.6.1->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client==3.0.0->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client==3.0.0->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/91/f0/b03e00ce9fddf4827c42df1c3ce10c74eadebfb706231e8d6d1c356a4062/pyasn1_modules-0.2.5-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client==3.0.0->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.1->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.1->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests==2.18.1->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/24/53/f397db567de0aa0e81b211d81c13c41a779f14893e42189cf5bdb97611b2/urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests==2.18.1->rekall-agent<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/11/7d/9bbbd7bb35f34b0169542487d2a8859e44306bb2e6a4455d491800a5621f/idna-2.5-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython<7.0,>=5.0.0->rekall)
Collecting ipython-genutils (from traitlets>=4.2->ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting enum34; python_version == "2.7" (from traitlets>=4.2->ipython<7.0,>=5.0.0->rekall)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting pybindgen (from fastchunking->pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/1b/49/6132e0bcfe4d6657d6b5addc89cc013730eedfd5a1dad314c055e1fb8e6e/PyBindGen-0.19.0-py2.py3-none-any.whl
Collecting isodate (from rdflib[sparql]==4.2.2->pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/9b/9f/b36f7774ff5ea8e428fdcfc4bb332c39ee5b9362ddd3d40d9516a55221b2/isodate-0.6.0-py2.py3-none-any.whl
Collecting SPARQLWrapper; extra == "sparql" (from rdflib[sparql]==4.2.2->pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/e4/ec/515152e9bdec175131ee6d6af3ef2ba8060da4d8115d30534fc49e4cda10/SPARQLWrapper-1.8.4-py2-none-any.whl
Collecting webencodings (from html5lib->pyaff4<0.30,>=0.26->rekall-core<1.8,>=1.7.0rc1->rekall)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Building wheels for collected packages: fastchunking
  Building wheel for fastchunking (setup.py) ... error
  ERROR: Complete output from command /tmp/MyEnv/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-e4yu8E/fastchunking/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8mcNJN --python-tag cp27:
  ERROR: WARNING: Failed to import pybindgen. If you called setup.py egg_info,this is probably acceptable; otherwise, build will fail.You can resolve this problem by installing pybindgen beforehand.
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/fastchunking
  copying fastchunking/__init__.py -> build/lib.linux-x86_64-2.7/fastchunking
  copying fastchunking/test.py -> build/lib.linux-x86_64-2.7/fastchunking
  copying fastchunking/benchmark.py -> build/lib.linux-x86_64-2.7/fastchunking
  creating build/lib.linux-x86_64-2.7/lib
  copying lib/rabinkarpgen.py -> build/lib.linux-x86_64-2.7/lib
  copying lib/__init__.py -> build/lib.linux-x86_64-2.7/lib
  copying lib/rabinkarp_gen.py -> build/lib.linux-x86_64-2.7/lib
  running build_ext
  building 'fastchunking._rabinkarprh' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/tmp
  creating build/temp.linux-x86_64-2.7/tmp/pip-install-e4yu8E
  creating build/temp.linux-x86_64-2.7/tmp/pip-install-e4yu8E/fastchunking
  creating build/temp.linux-x86_64-2.7/tmp/pip-install-e4yu8E/fastchunking/build
  creating build/temp.linux-x86_64-2.7/lib
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilib -I/usr/include/python2.7 -c /tmp/pip-install-e4yu8E/fastchunking/build/rabinkarprh.cpp -o build/temp.linux-x86_64-2.7/tmp/pip-install-e4yu8E/fastchunking/build/rabinkarprh.o
  x86_64-linux-gnu-gcc: error: /tmp/pip-install-e4yu8E/fastchunking/build/rabinkarprh.cpp: No such file or directory
  x86_64-linux-gnu-gcc: fatal error: no input files
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastchunking
  Running setup.py clean for fastchunking
Failed to build fastchunking
ERROR: rekall-efilter 1.6.0 has requirement future==0.16.0, but you'll have future 0.17.1 which is incompatible.
Installing collected packages: future, parsedatetime, expiringdict, pybindgen, fastchunking, pytz, tzlocal, aff4-snappy, six, isodate, pyparsing, SPARQLWrapper, rdflib, webencodings, html5lib, PyYAML, python-dateutil, sortedcontainers, intervaltree, pyblake2, pyaff4, acora, psutil, ipaddr, pycryptodome, rekall-yara, arrow, rekall-capstone, artifacts, rekall-lib, pytsk3, pyelftools, rekall-efilter, rekall-core, portpicker, httplib2, pyasn1, pyasn1-modules, rsa, oauth2client, filelock, certifi, chardet, urllib3, idna, requests, sseclient, pathlib, rekall-agent, readline, wcwidth, prompt-toolkit, decorator, ptyprocess, pexpect, backports.shutil-get-terminal-size, pygments, scandir, pathlib2, ipython-genutils, enum34, traitlets, simplegeneric, pickleshare, ipython, rekall
  Running setup.py install for fastchunking ... done
Successfully installed PyYAML-3.12 SPARQLWrapper-1.8.4 acora-2.0 aff4-snappy-0.5.1 arrow-0.10.0 artifacts-20170909 backports.shutil-get-terminal-size-1.0.0 certifi-2019.3.9 chardet-3.0.4 decorator-4.4.0 enum34-1.1.6 expiringdict-1.1.4 fastchunking-0.0.3 filelock-2.0.6 future-0.17.1 html5lib-1.0.1 httplib2-0.9.2 idna-2.5 intervaltree-2.1.0 ipaddr-2.2.0 ipython-5.8.0 ipython-genutils-0.2.0 isodate-0.6.0 oauth2client-3.0.0 parsedatetime-2.4 pathlib-1.0.1 pathlib2-2.3.3 pexpect-4.7.0 pickleshare-0.7.5 portpicker-1.1.1 prompt-toolkit-1.0.16 psutil-5.6.2 ptyprocess-0.6.0 pyaff4-0.27 pyasn1-0.4.5 pyasn1-modules-0.2.5 pybindgen-0.19.0 pyblake2-1.1.2 pycryptodome-3.4.7 pyelftools-0.24 pygments-2.3.1 pyparsing-2.1.5 python-dateutil-2.6.1 pytsk3-20170802 pytz-2017.3 rdflib-4.2.2 readline-6.2.4.1 rekall-1.7.1 rekall-agent-1.7.1 rekall-capstone-3.0.5.post2 rekall-core-1.7.2rc1 rekall-efilter-1.6.0 rekall-lib-1.7.2rc1 rekall-yara-3.6.3.1 requests-2.18.1 rsa-4.0 scandir-1.10.0 simplegeneric-0.8.1 six-1.12.0 sortedcontainers-1.5.7 sseclient-0.0.18 traitlets-4.3.2 tzlocal-1.5.1 urllib3-1.21.1 wcwidth-0.1.7 webencodings-0.5.1
````

There's some big red error text during the install but let's try anyway
````
(MyEnv) root@rekall:~# rekall -h
Traceback (most recent call last):
  File "/tmp/MyEnv/bin/rekall", line 6, in <module>
    from rekall.rekal import main
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2433, in load
    self.require(*args, **kwargs)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2456, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (future 0.17.1 (/tmp/MyEnv/lib/python2.7/site-packages), Requirement.parse('future==0.16.0'), set(['rekall-efilter']))
````

Nope. Did a little reading and I think this is due to the future==0.16.0 thing so..
````
(MyEnv) root@rekall:~# pip install future==0.16.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting future==0.16.0
Installing collected packages: future
  Found existing installation: future 0.17.1
    Uninstalling future-0.17.1:
      Successfully uninstalled future-0.17.1
Successfully installed future-0.16.0
````

And now
````
(MyEnv) root@rekall:~# rekall -h
usage: rekall [-p PROFILE] [-v] [-q] [--debug] [--output_style {concise,full}]
              [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
              [--log_domain [{PageTranslation} [{PageTranslation} ...]]]
              [--pager PAGER] [--paging_limit PAGING_LIMIT]
              [--colors {auto,yes,no}] [-F FORMAT]
              [--plugin [PLUGIN [PLUGIN ...]]] [-h] [--cache CACHE]
              [--repository_path [REPOSITORY_PATH [REPOSITORY_PATH ...]]]
              [-f FILENAME] [--buffer_size BUFFER_SIZE] [--output OUTPUT]
              [--max_collector_cost MAX_COLLECTOR_COST] [--home HOME]
              [--logging_format LOGGING_FORMAT]
              [--performance {normal,fast,thorough}] [--live LIVE]
              [--cpu_quota CPU_QUOTA] [--load_quota LOAD_QUOTA] [--dtb DTB]
              [-o FILE_OFFSET] [--ept EPT [EPT ...]] [--timezone TIMEZONE]
              [--cache_dir CACHE_DIR]
              [--highlighting_style
---Truncated by me
````

Ayyyy! This looks good! Let's try it out on a Windows 7 memory image I grabbed
````
(MyEnv) root@rekall:~# rekall -f /media/sf_Memory_Dumps/NUGGET7/20190425141605/memory.3a4a743b.img

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] memory.3a4a743b.img 06:24:07> 
````

Promising! Trying a pslist
````
[1] memory.3a4a743b.img 06:24:51> pslist
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/MyEnv/local/lib/python2.7/site-packages/IPython/core/prefilter.pyc in prefilter_lines(self, lines, continue_prompt)
    333                              for lnum, line in enumerate(llines) ])
    334         else:
--> 335             out = self.prefilter_line(llines[0], continue_prompt)
    336 
    337         return out

/tmp/MyEnv/local/lib/python2.7/site-packages/IPython/core/prefilter.pyc in prefilter_line(self, line, continue_prompt)
    308             return normal_handler.handle(line_info)
    309 
--> 310         prefiltered = self.prefilter_line_info(line_info)
    311         # print "prefiltered line: %r" % prefiltered
    312         return prefiltered

/tmp/MyEnv/local/lib/python2.7/site-packages/IPython/core/prefilter.pyc in prefilter_line_info(self, line_info)
    250         """
    251         # print "prefilter_line_info: ", line_info
--> 252         handler = self.find_handler(line_info)
    253         return handler.handle(line_info)
    254 

/tmp/MyEnv/local/lib/python2.7/site-packages/IPython/core/prefilter.pyc in find_handler(self, line_info)
    257         for checker in self.checkers:
    258             if checker.enabled:
--> 259                 handler = checker.check(line_info)
    260                 if handler:
    261                     return handler

/tmp/MyEnv/local/lib/python2.7/site-packages/IPython/core/prefilter.pyc in check(self, line_info)
    413 
    414     def check(self, line_info):
--> 415         obj = self.shell.user_ns.get(line_info.ifun)
    416         if isinstance(obj, Macro):
    417             return self.prefilter_manager.get_handler_by_name('macro')

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in get(self, item, default)
   1183     def get(self, item, default=None):
   1184         try:
-> 1185             return self[item]
   1186         except KeyError:
   1187             return default

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in __getitem__(self, item)
   1176             return super(DynamicNameSpace, self).__getitem__(item)
   1177         except KeyError:
-> 1178             if getattr(self["session"].plugins, item):
   1179                 return self._prepare_runner(item)
   1180 

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in __getattr__(self, name)
    153         pslist_plugin = plugins.pslist()
    154         """
--> 155         plugin_cls = self.GetPluginClass(name)
    156         if plugin_cls == None:
    157             return plugin_cls

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in GetPluginClass(self, name)
    133         """
    134         # Try to see if the requested plugin is active right now.
--> 135         metadata = self.plugin_db.GetActivePlugin(name)
    136         if metadata == None:
    137             return metadata

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugin.pyc in GetActivePlugin(self, plugin_name)
    980         for command_metadata in self.db.get(plugin_name, []):
    981             plugin_cls = command_metadata.plugin_cls
--> 982             if plugin_cls.is_active(self.session):
    983                 results.append(command_metadata)
    984 

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugin.pyc in is_active(cls, session)
    432             # completing the available plugins we will trigger profile
    433             # autodetection in order to determine which plugins are active.
--> 434             profile = (session.profile != None and
    435                        super(ProfileCommand, cls).is_active(session))
    436 

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall_lib/utils.pyc in __get__(self, *args, **kwargs)
   1089     def __get__(self, *args, **kwargs):
   1090         try:
-> 1091             return super(safe_property, self).__get__(*args, **kwargs)
   1092         except AttributeError as e:
   1093             message = "AttributeError raised: %s" % e

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in profile(self)
   1060             return process_context
   1061 
-> 1062         res = self.GetParameter("profile_obj")
   1063         return res
   1064 

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in GetParameter(self, item, default, cached)
    766         # can get if from a hook.
    767         try:
--> 768             result = self._RunParameterHook(item)
    769             if result is not None:
    770                 return result

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.pyc in _RunParameterHook(self, name)
    801                     self._hook_locks.add(name)
    802                     hook = cls(session=self)
--> 803                     result = hook.calculate()
    804 
    805                     # Cache the output from the hook directly.

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.pyc in calculate(self)
    728         if not self.session.physical_address_space:
    729             # Try to load the physical_address_space so we can scan it.
--> 730             if not self.session.plugins.load_as().GetPhysicalAddressSpace():
    731                 # If a filename was specified this should have worked, unless we
    732                 # could not open it.

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/core.pyc in GetPhysicalAddressSpace(self)
    376             # Try to get a physical address space.
    377             if self.pas_spec == "auto":
--> 378                 self.session.physical_address_space = self.GuessAddressSpace()
    379             else:
    380                 self.session.physical_address_space = self.AddressSpaceFactory(

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/core.pyc in GuessAddressSpace(self, base_as, **kwargs)
    475                 try:
    476                     base_as = cls(base=base_as, session=self.session,
--> 477                                   **kwargs)
    478                     self.session.logging.debug("Succeeded instantiating %s",
    479                                                base_as)

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall_lib/registry.pyc in __call__(cls, *args, **kwargs)
     94 
     95     def __call__(cls, *args, **kwargs):
---> 96         res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
     97         res._object_id = UniqueObjectIdMetaclass.ID  # pylint: disable=protected-access
     98         UniqueObjectIdMetaclass.ID += 1

/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.pyc in __init__(self, filename, **kwargs)
    123                                   lexicon.AFF4_FILE_NAME,
    124                                   rdfvalue.XSDString(
--> 125                                       os.path.join(cache_dir, "aff4_cache")))
    126         except IOError:
    127             pass

TypeError: Set() takes exactly 5 arguments (4 given)
````

Womp womp :( Can anyone tell me how to fix that? I'm out of ideas. Thanks!

**Comment by Krypterya** [comment]
Dear all,

We had a similar issue on Debian 9.9 and Debian "10" Buster.
When checking the error, it seems to be caused by the "pyaff4" python library.

We tried downgrading the pyaff4 to version 0.26.post6 which solved the error above.

We haven't had yet the time to confirm what other implication this may have.
But this indicates that something has changed between pyaff4 0.26.post6 and 0.27 which lead to Rekall to not function properly anymore.

To downgrade you can:

```
pip uninstall pyaff4

pip install pyaff4==0.26.post6
```

Regards,
Krypterya

**Comment by aoshiken** [comment]
@Krypterya , @heyquentin 

take a look to the PR #521
