### ISSUE TITLE
Unable to dump memory. Specified service has been marked for deletion.

### ISSUE THREAD

**Issue by kakokvantaliani** [google/rekall#506]
Hi,

On Win 10 X64 build 17134 downloaded latest rekall. Tried to run winpmem.py and get following error:
```
%Path%\winpmem>winpmem.py -d %Path%\winpmem\VS14 -l -f c:
(1072, 'CreateService', 'The specified service has been marked for deletion.')
(1058, 'StartService', 'The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.'): will try to continue
Traceback (most recent call last):
  File "%Path%\winpmem\winpmem.py", line 258, in <module>
    main()
  File "%Path%\winpmem\winpmem.py", line 222, in main
    None)
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')
```

**Comment by scudette** [comment]
Can you dump memory using winpmem? 

https://winpmem.velocidex.com/

The python script is not supported as it is just an example of how to use the driver from python.

**Comment by kakokvantaliani** [comment]
No.
```
%Path%\winpmem_v3.3.rc2.exe --output t1.raw
IO_ERROR: at win_pmem.cc: 685
2019-08-18 14:44:32 E Imaging failed with error: IO_ERROR
```

**Comment by scudette** [comment]
Can you repeat with -dd for extra details.

**Comment by scudette** [comment]
Also there might be something in the eventlog that helps shed light on this.

**Comment by kakokvantaliani** [comment]
Same!
```
%Path>winpmem_v3.3.rc2.exe -o t1.raw -d
IO_ERROR: at win_pmem.cc: 685
2019-08-18 14:59:21 E Imaging failed with error: IO_ERROR
```

Nothing specific in eventlog

**Comment by kakokvantaliani** [comment]
Do I need to install driver separately?

**Comment by kakokvantaliani** [comment]
Some problem with the driver?
```
> winpmem_v3.3.rc2.exe -L -dd
> 2019-08-18 15:17:27 I This is The WinPmem memory imager. version 3.3rc2
> 2019-08-18 15:17:27 I Extracted 45368 bytes into C:\Users\KAKOKV~1\AppData\Local\Temp\pme310B.tmp
> 2019-08-18 15:17:27 I Driver Unloaded.
> 2019-08-18 15:17:27 I Trying to load non-attestation signed driver.
> 2019-08-18 15:17:27 I Extracted 36176 bytes into C:\Users\KAKOKV~1\AppData\Local\Temp\pme315A.tmp
> 2019-08-18 15:17:27 I Driver Unloaded.
> IO_ERROR: at win_pmem.cc: 685
> 2019-08-18 15:17:27 E Imaging failed with error: IO_ERROR
> 2019-08-18 15:17:27 I Removed C:\Users\KAKOKV~1\AppData\Local\Temp\pme310B.tmp
> 2019-08-18 15:17:27 I Removed C:\Users\KAKOKV~1\AppData\Local\Temp\pme315A.tmp
```
