### ISSUE TITLE
Convert Volatility Linux Profile to Rekall

### ISSUE THREAD

**Issue by PracaGrande** [google/rekall#509]
Hello Rekall team, 

I have a Linux volatility profile that was created using the Volatility Linux tools. The outcome is a ZIP file that contains the files module.dwarf and System.map-4.13.0-41-generic. 

```
`$ ls -hl profile/
total 6.8M
-rw-rw-r-- 1 user user  2.1M Sep 18 01:57 module.dwarf
-rw------- 1 user user  3.8M Sep 18 02:00 System.map-4.13.0-41-generic
-rw-r--r-- 1 user user 1022K Sep 18 02:01 volatility-4.13.0-41-generic.zip`
```

How could I use Rekall convert command to convert this into Rekall linux profile? 
I believe it should be possible according to the documentation but it fails for me.
I am using The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge) version.

```
`c:\Program Files\Rekall>rekal.exe convert_profile C:\TEMP\volatility-4.13.0-41-generic.zip volatility.json
2019-09-18 09:13:03,740:CRITICAL:rekall.1:Traceback (most recent call last):
  File "rekall-core\rekall\session.py", line 870, in RunPlugin
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 390, in render
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 362, in ConvertProfile
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 260, in Convert
  File "rekall-core\rekall\plugins\overlays\linux\dwarfdump.py", line 147, in feed_line
TypeError: cannot use a string pattern on a bytes-like object

2019-09-18 09:13:03,755:CRITICAL:root:cannot use a string pattern on a bytes-like object. Try --debug for more information.
Traceback (most recent call last):
  File "rekal.py", line 11, in <module>
  File "rekall-core\rekall\rekal.py", line 104, in main
  File "rekall-core\rekall\session.py", line 873, in RunPlugin
  File "rekall-core\rekall\session.py", line 870, in RunPlugin
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 390, in render
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 362, in ConvertProfile
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 260, in Convert
  File "rekall-core\rekall\plugins\overlays\linux\dwarfdump.py", line 147, in feed_line
TypeError: cannot use a string pattern on a bytes-like object
[3952] Failed to execute script rekal`
```

Not sure what are those errors, so tried to change the name of the file module.dwarf into module_dwarf.ko just for testing purposes. Of course it also fails.

```
`c:\Program Files\Rekall>rekal.exe convert_profile C:\TEMP\volatility-4.13.0-41-generic.zip volatility.json
2019-09-18 09:14:33,209:CRITICAL:rekall.1:Traceback (most recent call last):
  File "rekall-core\rekall\session.py", line 870, in RunPlugin
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 390, in render
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 362, in ConvertProfile
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 248, in Convert
  File "rekall-core\rekall\plugins\overlays\linux\dwarfparser.py", line 427, in __init__
  File "site-packages\elftools\elf\elffile.py", line 61, in __init__
  File "site-packages\elftools\elf\elffile.py", line 229, in _identify_file
  File "site-packages\elftools\common\utils.py", line 69, in elf_assert
  File "site-packages\elftools\common\utils.py", line 101, in _assert_with_exception
elftools.common.exceptions.ELFError: Magic number does not match

2019-09-18 09:14:33,209:CRITICAL:root:Magic number does not match. Try --debug for more information.
Traceback (most recent call last):
  File "rekal.py", line 11, in <module>
  File "rekall-core\rekall\rekal.py", line 104, in main
  File "rekall-core\rekall\session.py", line 873, in RunPlugin
  File "rekall-core\rekall\session.py", line 870, in RunPlugin
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 390, in render
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 362, in ConvertProfile
  File "rekall-core\rekall\plugins\tools\profile_tool.py", line 248, in Convert
  File "rekall-core\rekall\plugins\overlays\linux\dwarfparser.py", line 427, in __init__
  File "site-packages\elftools\elf\elffile.py", line 61, in __init__
  File "site-packages\elftools\elf\elffile.py", line 229, in _identify_file
  File "site-packages\elftools\common\utils.py", line 69, in elf_assert
  File "site-packages\elftools\common\utils.py", line 101, in _assert_with_exception
elftools.common.exceptions.ELFError: Magic number does not match
[3160] Failed to execute script rekal`

```

I won't be able to create a Rekall profile on this particular system, Any suggestions on how I could convert this profile?

thank you

**Comment by scudette** [comment]
This bug was fixed with https://github.com/google/rekall/commit/a82349758fdc15274501cf41ff5b4bc913698494 but we have not had a binary release since. You could install from pip.

If the kernel is fairly recent it is unlikely that Rekall will support it better than Volatility since it is not maintained at the moment.

**Comment by PracaGrande** [comment]
I was able to pip install the latest version and use the converter successful. At least it produced the .json file, thank for for that Michael!

When I go back with this .json file to load it into rekall, it seems I get another error, but now about the DTB

```
`
c:\Program Files\Rekall>rekal.exe -p converted_profile.json -f memdump pslist

2019-09-18 13:52:41,345:CRITICAL:rekall.1:A DTB value was found but failed to verify. See logging messages for more information.
Traceback (most recent call last):
  File "rekal.py", line 11, in <module>
  File "rekall-core\rekall\rekal.py", line 111, in main
  File "rekall-core\rekall\session.py", line 1136, in Flush
  File "rekall-core\rekall\cache.py", line 275, in Flush
  File "rekall-core\rekall\session.py", line 768, in GetParameter
  File "rekall-core\rekall\session.py", line 807, in _RunParameterHook
  File "rekall-core\rekall\plugins\linux\misc.py", line 96, in calculate
  File "rekall-core\rekall\obj.py", line 153, in __call__
  File "rekall-lib\rekall_lib\registry.py", line 96, in __call__
  File "rekall-core\rekall\plugin.py", line 888, in __init__
  File "rekall-core\rekall\plugins\core.py", line 445, in GetVirtualAddressSpace
rekall.plugin.PluginError: A DTB value was found but failed to verify. See logging messages for more information.
[6900] Failed to execute script rekal
`

```
Kernel version of the target system where memory was acquired is 2.6.32-754.10.1.el6.x86_64

Trying to find the cause of this now ..

**Comment by PracaGrande** [comment]
Don't know the root cause but it worked with an older version of rekall and converted profile was 
well received by rekall. I have now a different problem but already reported it on  https://github.com/google/rekall/issues/191

Case closed

**Comment by Dude20** [comment]
i get the same errors trying to convert a volatility profile with zipped dwarf and system.map.
@PracaGrande @scudette  how did you solve the problem ?

**Comment by scudette** [comment]
@Dude20 the bug is fixed in head so you can just install from master to convert the profile.

**Comment by Dude20** [comment]
i tried to fresh install from source after git clone and the same error occurred:
`rekal.py convert_profile ../CentOS8-2.zip  Centos8.json`

> No handlers could be found for logger "rekall.plugins.tools"
> 2020-02-04 11:06:20,612:CRITICAL:rekall.1:Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/session.py", line 870, in RunPlugin
>     result = plugin_obj.render(ui_renderer) or plugin_obj
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/tools/profile_tool.py", line 391, in render
>     profile = self.ConvertProfile(input)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/tools/profile_tool.py", line 363, in ConvertProfile
>     profile = converter(input, session=self.session).Convert()
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/tools/profile_tool.py", line 249, in Convert
>     session=self.session)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/overlays/linux/dwarfparser.py", line 427, in __init__
>     self.elffile = elffile.ELFFile(fd)
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/elf/elffile.py", line 61, in __init__
>     self._identify_file()
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/elf/elffile.py", line 229, in _identify_file
>     elf_assert(magic == b'\x7fELF', 'Magic number does not match')
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/common/utils.py", line 69, in elf_assert
>     _assert_with_exception(cond, msg, ELFError)
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/common/utils.py", line 101, in _assert_with_exception
>     raise exception_type(msg)
> ELFError: Magic number does not match
> 
> 2020-02-04 11:06:20,613:CRITICAL:root:Magic number does not match. Try --debug for more information.
> Traceback (most recent call last):
>   File "/usr/local/bin/rekal.py", line 4, in <module>
>     __import__('pkg_resources').run_script('rekall-core==1.7.3.dev59', 'rekal.py')
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
>     exec(code, namespace, namespace)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/EGG-INFO/scripts/rekal.py", line 114, in <module>
>     main()
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/EGG-INFO/scripts/rekal.py", line 104, in main
>     user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/session.py", line 873, in RunPlugin
>     self._HandleRunPluginException(ui_renderer, e)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/session.py", line 870, in RunPlugin
>     result = plugin_obj.render(ui_renderer) or plugin_obj
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/tools/profile_tool.py", line 391, in render
>     profile = self.ConvertProfile(input)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/tools/profile_tool.py", line 363, in ConvertProfile
>     profile = converter(input, session=self.session).Convert()
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/tools/profile_tool.py", line 249, in Convert
>     session=self.session)
>   File "/usr/local/lib/python2.7/dist-packages/rekall_core-1.7.3.dev59-py2.7.egg/rekall/plugins/overlays/linux/dwarfparser.py", line 427, in __init__
>     self.elffile = elffile.ELFFile(fd)
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/elf/elffile.py", line 61, in __init__
>     self._identify_file()
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/elf/elffile.py", line 229, in _identify_file
>     elf_assert(magic == b'\x7fELF', 'Magic number does not match')
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/common/utils.py", line 69, in elf_assert
>     _assert_with_exception(cond, msg, ELFError)
>   File "/usr/local/lib/python2.7/dist-packages/pyelftools-0.24-py2.7.egg/elftools/common/utils.py", line 101, in _assert_with_exception
>     raise exception_type(msg)
> elftools.common.exceptions.ELFError: Magic number does not match

am i doing something wrong?

**Comment by scudette** [comment]
How are you generating your zip file? Rekal is expecting an elf file inside
it (the compiled kernel middle) but it seems to not be an elf file at all.
