### ISSUE TITLE
Rekall RuntimeError: Unable to instantiate physical_address_space from filename 

### ISSUE THREAD

**Issue by Alibm73** [google/rekall#511]
Hello everyone
I have installed rekall and it runs ok when i type `rekall`::
`
----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.2.rc1 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------

>>> 
`
but when i use `rekall -f vmi://windows7 pslist` or `rekall -f vmi://xen/windows7 pslist` i get this output error:
F.Y.I: I'm running it on `python 3.6`
`Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.2rc1', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python3.6/dist-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/usr/local/lib/python3.6/dist-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/aliadmin/.local/lib/python3.6/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi://windows7.`

I have python `3.5.7` installed too.
when i run `/opt/python3.5.7/bin/rekal.py -f vmi://kvm/windows7 pslist` i get the same exact error:
`Traceback (most recent call last):
  File "/usr/local/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core==1.7.2rc1', 'console_scripts', 'rekall')()
  File "/usr/local/lib/python3.6/dist-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/usr/local/lib/python3.6/dist-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/home/aliadmin/.local/lib/python3.6/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/usr/local/lib/python3.6/dist-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/guess_profile.py", line 737, in calculate
    "filename %s." % filename)
RuntimeError: Unable to instantiate physical_address_space from filename vmi://windows7.`
@willnorris @sroberts @tweksteen @cdibona @dberlin @Wenzel

**Comment by Wenzel** [comment]
Hi,
I think the `VMIAddressSpace` has not been released yet.
You are running Rekall `1.7.2rc1`, and it's not part of it.
Last relase was on December 2017:
https://github.com/google/rekall/releases

The `VMIAddressSpace` has been merged on March 2018:
https://github.com/google/rekall/pull/374

You should install Rekall from git master.

**Comment by Alibm73** [comment]
Thanks @Wenzel

**Comment by Alibm73** [comment]
I commented `#from rekall.plugins.addrspaces import vmi` but now i have this issue when i run `rekall -f vmi://windows7 pslist`  :
```python
Traceback (most recent call last):
  File "/tmp/MyEnv/bin/rekall", line 8, in <module>
    sys.exit(main())
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugin.py", line 982, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall_lib/utils.py", line 1091, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 1062, in profile
    res = self.GetParameter("profile_obj")
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/session.py", line 803, in _RunParameterHook
    result = hook.calculate()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/guess_profile.py", line 730, in calculate
    if not self.session.plugins.load_as().GetPhysicalAddressSpace():
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 378, in GetPhysicalAddressSpace
    self.session.physical_address_space = self.GuessAddressSpace()
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/core.py", line 477, in GuessAddressSpace
    **kwargs)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/tmp/MyEnv/local/lib/python2.7/site-packages/rekall/plugins/addrspaces/aff4.py", line 125, in __init__
    os.path.join(cache_dir, "aff4_cache")))
TypeError: Set() takes exactly 5 arguments (4 given)

```

**Comment by Wenzel** [comment]
> I commented #from rekall.plugins.addrspaces import vmi

Why ??

The error you have is a rekall issue:
pin pyaff4:
`pip install pyaff4==0.26 future==0.16.0`

**Comment by Alibm73** [comment]
Hi @Wenzel 
I Have Managed to install Rekall 1.7.3.dev54 outside of virtual environment. 
`aliadmin@ubuntu:~$ rekall
Webconsole disabled: cannot import name 'webconsole_plugin'

----------------------------------------------------------------------------
The Rekall Digital Forensic/Incident Response framework 1.7.3.dev54 (Hurricane Ridge).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------

>>> 
`
i want to post it so everyone who need it can see. Should I post a new issue or just show the installation steps here??

**Comment by Wenzel** [comment]
@Alibm73 I'm not a Rekall maintainer, so you better ask @scudette :)

**Comment by scudette** [comment]
Installing a python program outside of a  virtual env is not supported and
will probably damage your system.

Sorry this is just a python limitation. It may appear to work until you
will get subtle errors with other python programs. This is especially
problematic to system management tools written in python.

Thanks
Mike
