### ISSUE TITLE
help installing rekal on ubuntu 18.01

### ISSUE THREAD

**Issue by siftuser** [google/rekall#512]
During installation noticed this error => 

```
  Building wheel for fastchunking (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/app/rekall/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-BnolPq/fastchunking/setup.py'"'"'; __file__='"'"'/tmp/pip-install-BnolPq/fastchunking/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-HQfRjB --python-tag cp27
       cwd: /tmp/pip-install-BnolPq/fastchunking/
  Complete output (26 lines):
  WARNING: Failed to import pybindgen. If you called setup.py egg_info,this is probably acceptable; otherwise, build will fail.You can resolve this problem by installing pybindgen beforehand.
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/fastchunking
  copying fastchunking/__init__.py -> build/lib.linux-x86_64-2.7/fastchunking
  copying fastchunking/test.py -> build/lib.linux-x86_64-2.7/fastchunking
  copying fastchunking/benchmark.py -> build/lib.linux-x86_64-2.7/fastchunking
  creating build/lib.linux-x86_64-2.7/lib
  copying lib/__init__.py -> build/lib.linux-x86_64-2.7/lib
  copying lib/rabinkarp_gen.py -> build/lib.linux-x86_64-2.7/lib
  copying lib/rabinkarpgen.py -> build/lib.linux-x86_64-2.7/lib
  running build_ext
  building 'fastchunking._rabinkarprh' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/tmp
  creating build/temp.linux-x86_64-2.7/tmp/pip-install-BnolPq
  creating build/temp.linux-x86_64-2.7/tmp/pip-install-BnolPq/fastchunking
  creating build/temp.linux-x86_64-2.7/tmp/pip-install-BnolPq/fastchunking/build
  creating build/temp.linux-x86_64-2.7/lib
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-PPrPZj/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilib -I/usr/include/python2.7 -c /tmp/pip-install-BnolPq/fastchunking/build/rabinkarprh.cpp -o build/temp.linux-x86_64-2.7/tmp/pip-install-BnolPq/fastchunking/build/rabinkarprh.o
  x86_64-linux-gnu-gcc: error: /tmp/pip-install-BnolPq/fastchunking/build/rabinkarprh.cpp: No such file or directory
  x86_64-linux-gnu-gcc: fatal error: no input files
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastchunking
  Running setup.py clean for fastchunking
Failed to build fastchunking
ERROR: rekall-efilter 1.6.0 has requirement future==0.16.0, but you'll have future 0.18.1 which is incompatible.

```

as suggested [here](https://github.com/google/rekall/issues/495) ... updated corrected packs

```
pip install pyaff4==0.26.post6   

pip install future==0.16.0
```

but continue to get error, running rekal -h under virtual envinment

```
rekal -h
Traceback (most recent call last):
  File "/usr/local/bin/rekal", line 5, in <module>
    from rekall.rekal import main
  File "/usr/local/lib/python3.6/dist-packages/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/tools/__init__.py", line 30, in <module>
    from rekall.plugins.tools import disassembler
  File "/usr/local/lib/python3.6/dist-packages/rekall/plugins/tools/disassembler.py", line 29, in <module>
    import capstone
  File "/usr/local/lib/python3.6/dist-packages/capstone/__init__.py", line 252, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

Any help would be appreciated!

**Comment by siftuser** [comment]
reinstalled ... so works well until -h (help) ... closing
