### ISSUE TITLE
prompt-toolkit is incompatible.

### ISSUE THREAD

**Issue by Alibm73** [google/rekall#513]
hi @Wenzel @scudette 
When i install rekall from get repository i get this error `ERROR: aiocmd 0.1.2 has requirement prompt-toolkit>=2.0.9, but you'll have prompt-toolkit 1.0.18 which is incompatible.` when  i run `pip install --editable rekall`:
```
Building wheels for collected packages: readline, simplegeneric, backcall
  Building wheel for readline (setup.py) ... done
  Created wheel for readline: filename=readline-6.2.4.1-cp36-cp36m-linux_x86_64.whl size=348450 sha256=9c1565f97694975d17cc4826f6a5283626851b54f70414a9e1717aa922e2b082
  Stored in directory: /home/aliadmin/.cache/pip/wheels/96/07/69/2774126699bd65537b917648c6a940ea33b21f0fdba296c39d
  Building wheel for simplegeneric (setup.py) ... done
  Created wheel for simplegeneric: filename=simplegeneric-0.8.1-cp36-none-any.whl size=5073 sha256=dcd87432edd40cbec7a4e14bfa0fe5d043c59fabb1294eb912622edd429b8949
  Stored in directory: /home/aliadmin/.cache/pip/wheels/a9/28/53/f24776b4c5bcbe91aaf1f1e247bd6fadd17191aa12fac63902
  Building wheel for backcall (setup.py) ... done
  Created wheel for backcall: filename=backcall-0.1.0-cp36-none-any.whl size=10411 sha256=5e38fd8eafa0ccdde79f3de1c3d08d095b3dbff8bf17d861bc430656376ad429
  Stored in directory: /home/aliadmin/.cache/pip/wheels/98/b0/dd/29e28ff615af3dda4c67cab719dd51357597eabff926976b45
Successfully built readline simplegeneric backcall
ERROR: aiocmd 0.1.2 has requirement prompt-toolkit>=2.0.9, but you'll have prompt-toolkit 1.0.18 which is incompatible.
Installing collected packages: ptyprocess, pexpect, prompt-toolkit, pickleshare, simplegeneric, backcall, parso, jedi, pygments, ipython-genutils, decorator, traitlets, ipython, readline, rekall
  Found existing installation: prompt-toolkit 2.0.10
    Uninstalling prompt-toolkit-2.0.10:
      Successfully uninstalled prompt-toolkit-2.0.10
  Running setup.py develop for rekall
Successfully installed backcall-0.1.0 decorator-4.4.1 ipython-6.5.0 ipython-genutils-0.2.0 jedi-0.15.1 parso-0.5.1 pexpect-4.7.0 pickleshare-0.7.5 prompt-toolkit-1.0.18 ptyprocess-0.6.0 pygments-2.4.2 readline-6.2.4.1 rekall simplegeneric-0.8.1 traitlets-4.3.3
```
then i fix it using `pip install prompt_toolkit==2.0.10` command but i get a new error `ERROR: ipython 6.5.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you'll have prompt-toolkit 2.0.10 which is incompatible.:`
```
Collecting prompt_toolkit==2.0.10
  Using cached https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python3.6/site-packages (from prompt_toolkit==2.0.10) (1.12.0)
Requirement already satisfied: wcwidth in ./venv/lib/python3.6/site-packages (from prompt_toolkit==2.0.10) (0.1.7)
ERROR: ipython 6.5.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you'll have prompt-toolkit 2.0.10 which is incompatible.
Installing collected packages: prompt-toolkit
  Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      Successfully uninstalled prompt-toolkit-1.0.18
Successfully installed prompt-toolkit-2.0.10
```
what should i do??
this is all of the commands i ran for installing it in virtual env:
```
sudo apt install python3-pip -y
sudo apt install git -y
sudo apt-get install libncurses5-dev libncursesw5-dev -y
sudo apt install python3.6-dev -y
sudo apt install virtualenv -y

virtualenv -p /usr/bin/python3 /tmp/MyEnv
source /tmp/MyEnv/bin/activate
pip install --upgrade setuptools pip wheel
git clone https://github.com/google/rekall.git rekall
pip install --editable rekall/rekall-lib
pip install --editable rekall/rekall-core
pip install future==0.16.0
pip install --editable rekall/rekall-agent
pip install --editable rekall
```

**Comment by scudette** [comment]
Just like you pinned the future version you might try to pin the ipython version as well. I think 5.1 should work.

**Comment by Alibm73** [comment]
i did `pip install ipython==5.1.0`
but i still get this error:
```
pip install ipython==5.1.0
Requirement already satisfied: ipython==5.1.0 in ./venv/lib/python3.6/site-packages (5.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (4.7.0)
Requirement already satisfied: decorator in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (4.4.1)
Requirement already satisfied: pickleshare in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (41.6.0)
Requirement already satisfied: simplegeneric>0.8 in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (0.8.1)
Requirement already satisfied: traitlets>=4.2 in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (4.3.3)
Collecting prompt-toolkit<2.0.0,>=1.0.3
  Using cached https://files.pythonhosted.org/packages/64/27/5fd61a451d086ad4aa806dc72fe1383d2bc0e74323668672287f616d5d51/prompt_toolkit-1.0.18-py3-none-any.whl
Requirement already satisfied: pygments in ./venv/lib/python3.6/site-packages (from ipython==5.1.0) (2.4.2)
Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython==5.1.0) (0.6.0)
Requirement already satisfied: six in ./venv/lib/python3.6/site-packages (from traitlets>=4.2->ipython==5.1.0) (1.12.0)
Requirement already satisfied: ipython-genutils in ./venv/lib/python3.6/site-packages (from traitlets>=4.2->ipython==5.1.0) (0.2.0)
Requirement already satisfied: wcwidth in ./venv/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython==5.1.0) (0.1.7)
ERROR: aiocmd 0.1.2 has requirement prompt-toolkit>=2.0.9, but you'll have prompt-toolkit 1.0.18 which is incompatible.
Installing collected packages: prompt-toolkit
  Found existing installation: prompt-toolkit 2.0.10
    Uninstalling prompt-toolkit-2.0.10:
      Successfully uninstalled prompt-toolkit-2.0.10
Successfully installed prompt-toolkit-1.0.18
```
and it goes on like this!

**Comment by Alibm73** [comment]
@scudette when i correct one, the other gets damaged.
i don't know what to do

**Comment by aoshiken** [comment]
Take a look to the PR #521

**Comment by Xavier59** [comment]
My psxview works but not my pslist :/

I have the same error with last version from master : 
{'codename': 'Hurricane Ridge', 'post': '0', 'rc': '1', 'version': '1.7.3', 'revisionid': b'c5d68e31705f4b5bd2581c1d951b7f6983f7089c', 'dirty': True, 'dev': 59, 'pep440': '1.7.3.dev59'}

Running : Linux kali 5.4.0-kali4-amd64 #1 SMP Debian 5.4.19-1kali1 (2020-02-17) x86_64 GNU/Linux

When running pslist : 

```
Traceback (most recent call last):
  File "/tmp/rekall/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/rekal.py", line 104, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/session.py", line 873, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/session.py", line 870, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/plugin.py", line 761, in render
    for row in self.collect():
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/plugins/linux/pslist.py", line 63, in collect
    dtb = self.kernel_address_space.vtop(task.mm.pgd)
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/obj.py", line 926, in __getattr__
    return getattr(result, attr)
  File "/home/xavier/hack/ctf/fcsc/forensic/rekall/rekall/rekall-core/rekall/obj.py", line 1497, in __getattr__
    raise AttributeError(attr)
AttributeError: pgd
```
