### ISSUE TITLE
Webconsole does not seem to work

### ISSUE THREAD

**Issue by kiddinn** [google/rekall#52]
Using the latest commit: a96578924ef5dabec1a3ebe6fea430b3a218bbfd

I get an error while trying to start up the webconsole, 

**$ rekall webconsole --browser**

    ERROR:root:Traceback (most recent call last):
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/rekall-1.2.1-py2.7.egg/rekall/session.py", line 607, in _RunPlugin
        return plugin_obj.render(ui_renderer) or plugin_obj
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/rekall-1.2.1-py2.7.egg/rekall/plugins/tools/webconsole_plugin.py", line 230, in render
        if os.path.isdir(self.pre_load):
      File "/PATHTOVIRTUALENV/lib/python2.7/genericpath.py", line 41, in isdir
        st = os.stat(s)
    TypeError: coercing to Unicode: need string or buffer, NoneType found

Looking at the code that got submitted in: https://codereview.appspot.com/215210043/diff/20001/rekall/plugins/tools/webconsole_plugin.py

self.pre_load is set to worksheet during init, and worksheet has a default value of None. Thus self.pre_load has a None value... and thus fails the os.path.isdir test.

    230c230
    <         if os.path.isdir(self.pre_load):
    ---
    >         if self.pre_load and os.path.isdir(self.pre_load):

This little fix will prevent that check from failing and crashing the tool, which leads to this:

    Starting Manuskript web console.
    Press Ctrl-c to return to the interactive shell.
    Created new window in existing browser session.
    Traceback (most recent call last):
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
        self.run_application()
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 76, in run_application
        self.run_websocket()
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/geventwebsocket/handler.py", line 52, in run_websocket
        self.application(self.environ, lambda s, h: [])
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/flask_sockets.py", line 39, in __call__
        handler(environment)
      File "/PATHTOVIRTUALENV/local/lib/python2.7/site-packages/rekall-1.2.1-py2.7.egg/rekall/plugins/tools/webconsole/runplugin.py", line 380, in rekall_load_nodes
        sessions=worksheet.GetSessionsAsJson(),
    AttributeError: 'ZipFileManager' object has no attribute 'GetSessionsAsJson'
    {'GATEWAY_INTERFACE': 'CGI/1.1',
     'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
     'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,is;q=0.6',
     'HTTP_CACHE_CONTROL': 'no-cache',
     'HTTP_CONNECTION': 'Upgrade',
     'HTTP_DNT': '1',
     'HTTP_HOST': 'localhost:46760',
     'HTTP_ORIGIN': 'http://localhost:46760',
     'HTTP_PRAGMA': 'no-cache',
     'HTTP_SEC_WEBSOCKET_EXTENSIONS': 'permessage-deflate; client_max_window_bits',
     'HTTP_SEC_WEBSOCKET_KEY': ....',
     'HTTP_SEC_WEBSOCKET_VERSION': '13',
     'HTTP_UPGRADE': 'websocket',
     'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64...,
     'PATH_INFO': '/rekall/load_nodes',
     'QUERY_STRING': '',
     'REMOTE_ADDR': '127.0.0.1',
     'REMOTE_PORT': '38383',
     'REQUEST_METHOD': 'GET',
     'SCRIPT_NAME': '',
     'SERVER_NAME': 'localhost',
     'SERVER_PORT': '46760',
     'SERVER_PROTOCOL': 'HTTP/1.1',
     'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
     'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f3298ff71e0>,
     'wsgi.input': <gevent.pywsgi.Input object at 0x7f32900ce090>,
     'wsgi.multiprocess': False,
     'wsgi.multithread': False,
     'wsgi.run_once': False,
     'wsgi.url_scheme': 'http',
     'wsgi.version': (1, 0),
     'wsgi.websocket': None,
     'wsgi.websocket_version': '13'} failed with AttributeError

**Comment by scudette** [comment]
Hi Kiddinn
  This code is still in flux, so our error checking is not quite where it should be :-). The webconsole is supposed to be started with a directory like this:

rekal -v webconsole --port 8001 /tmp/rekall_test/ 

I will make the directory arg mandatory. Thanks for the feedback!

**Comment by kiddinn** [comment]
which is the reason I didn't want to send in a CL ;)

but making the directory arg mandatory when running the webconsole SGTM, since that wasn't obvious (well it wasn't needed in the older version, and according to the main site the way to envoke the web console is still **$ rekall webconsole --browser**, guess that documentation will get updated as soon as the next version gets more stable)

**Comment by scudette** [comment]
Yes. Previous versions made a temporary file if it was not given but I
think saving the user from making a directory is not worth it (because the
temp file has a complicated name to find in the filesystem).
