### ISSUE TITLE
ModuleNotFoundError: No module named 'minikerberos.asn1_structs'

### ISSUE THREAD

**Issue by debugshow** [google/rekall#526]
(venv) ding@yang:~$ rekall -h
Traceback (most recent call last):
  File "/home/ding/venv/bin/rekall", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekall')()
  File "/home/ding/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ding/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/ding/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/ding/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ding/rekall/rekall-core/rekall/rekal.py", line 41, in <module>
    entry_point.load()
  File "/home/ding/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/ding/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ding/rekall/rekall-core/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/home/ding/rekall/rekall-core/rekall/plugins/addrspaces/__init__.py", line 8, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/home/ding/rekall/rekall-core/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/home/ding/rekall/rekall-core/rekall/plugins/tools/__init__.py", line 36, in <module>
    from rekall.plugins.tools import profile_tool
  File "/home/ding/rekall/rekall-core/rekall/plugins/tools/profile_tool.py", line 109, in <module>
    from rekall.plugins.windows import common
  File "/home/ding/rekall/rekall-core/rekall/plugins/windows/__init__.py", line 45, in <module>
    from rekall.plugins.windows import pypykatz
  File "/home/ding/rekall/rekall-core/rekall/plugins/windows/pypykatz.py", line 4, in <module>
    from pypykatz.pypykatz import pypykatz
  File "/home/ding/venv/lib/python3.6/site-packages/pypykatz/pypykatz.py", line 9, in <module>
    from .lsadecryptor import *
  File "/home/ding/venv/lib/python3.6/site-packages/pypykatz/lsadecryptor/__init__.py", line 3, in <module>
    from .packages import *
  File "/home/ding/venv/lib/python3.6/site-packages/pypykatz/lsadecryptor/packages/__init__.py", line 5, in <module>
    from .kerberos.decryptor import *
  File "/home/ding/venv/lib/python3.6/site-packages/pypykatz/lsadecryptor/packages/kerberos/decryptor.py", line 10, in <module>
    from pypykatz.commons.kerberosticket import *
  File "/home/ding/venv/lib/python3.6/site-packages/pypykatz/commons/kerberosticket.py", line 10, in <module>
    from minikerberos.asn1_structs import *
ModuleNotFoundError: No module named 'minikerberos.asn1_structs'
thanks

**Comment by 2xyo** [comment]
`asn1_structs` has move to `minikerberos.protocol.asn1_structs`, see https://github.com/skelsec/minikerberos/blob/master/minikerberos/protocol/asn1_structs.py 

Fixed since `pypykatz` version 0.3.5, see https://github.com/skelsec/pypykatz/commit/4bdf4333130c9c2295ef5abcb548caed1aa06b39 

But version 0.0.8 is need in https://github.com/google/rekall/blob/c5d68e31705f4b5bd2581c1d951b7f6983f7089c/rekall-core/setup.py#L73
