### ISSUE TITLE
Please, is there a way to solve the repository problem?

### ISSUE THREAD

**Issue by dougcello** [google/rekall#552]
I've been trying to investigate a memory dump extracted with WinPmem from Windows 10 Build 18363.1082 64 bits. I couldn't get results. Apparently, when you run the command rekal -f <image file> pslist the following appears:

Webconsole disabled: cannot import name 'webconsole_plugin' from partially initialized module 'rekall.plugins.tools' (most likely due to a circular import) (/root/rekall/rekall-core/rekall/plugins/tools/__init__.py)
2020-10-03 00:40:40,509:WARNING:rekall.1:Inventory for repository "http://profiles.rekall-forensic.com" seems malformed. Are you behind a captive portal or proxy? If this is a custom repository, did you forget to create an inventory? You must use the tools/profiles/build_profile_repo.py tool with the --inventory flag.
2020-10-03 00:40:40,509:WARNING:rekall.1:Repository http://profiles.rekall-forensic.com will be disabled.
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/26402FD82020-10-03 00:41:09,033:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrnlpa.pdb/26402FD82020-10-03 00:41:09,420:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntkrpamp.pdb/26402FD82020-10-03 00:41:09,801:ERROR:rekall.1:Error: HTTP Error 404: Not Found
 Trying to fetch http://msdl.microsoft.com/download/symbols/ntoskrnl.pdb/26402FD82020-10-03 00:41:10,158:ERROR:rekall.1:Error: HTTP Error 404: Not Found
2020-10-03 00:41:16,486:ERROR:rekall.1:No profiles match this image. Try specifying manually.
Traceback (most recent call last):                   
  File "/tmp/MyEnv/bin/rekal", line 33, in <module>
    sys.exit(load_entry_point('rekall-core', 'console_scripts', 'rekal')())
  File "/root/rekall/rekall-core/rekall/rekal.py", line 96, in main
    plugin_cls, flags = args.parse_args(
  File "/root/rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/root/rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/root/rekall/rekall-core/rekall/plugin.py", line 986, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/root/rekall/rekall-core/rekall/plugin.py", line 440, in is_active
    return super(ProfileCommand, cls).is_active(session)
  File "/root/rekall/rekall-core/rekall/plugin.py", line 227, in is_active
    if not session.GetParameter(mode):
  File "/root/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/root/rekall/rekall-core/rekall/plugins/modes.py", line 115, in calculate
    if self.session.profile:
  File "/root/rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/root/rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/root/rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/root/rekall/rekall-core/rekall/plugins/guess_profile.py", line 764, in calculate
    raise RuntimeError(
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.

I am waiting.

**Comment by scudette** [comment]
Hi, we are about to officially shut the project down very soon, I recommend
you try to use one of the other memory analysis tools out there.

Thanks
Mike

**Comment by dougcello** [comment]
Well, I'm sorry for the news.
I bring bad news too. I previously tried to extract an image from memory with WinPmem and use it in the Framework Volatility, and none of the available formats (including --format and --volume_format) worked.
I would therefore like a suggestion.

**Comment by vivianezw** [comment]
Use https://github.com/Velocidex/WinPmem , but _please_ read the instructions before using the provided winpmem executables. They will work. Volatility (3) is also under construction right now. If you follow my instructions, you will be able to load memory dumps at least in Volatility 2.6.
