### ISSUE TITLE
'PROTOCOL_SSLv3' is not defined

### ISSUE THREAD

**Issue by tklengyel** [google/rekall#59]
I get the following error on Debian Jessie when trying to run fetch_pdb:

./rekall/rekal.py fetch_pdb -F ntkrnlmp.pdb --guid 98efda99bb514fcfa83a813705fec8312
Traceback (most recent call last):
  File "./rekall/rekal.py", line 36, in <module>
    from rekall import plugins  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/rekall-1.3.1-py2.7.egg/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/usr/local/lib/python2.7/dist-packages/rekall-1.3.1-py2.7.egg/rekall/plugins/addrspaces/__init__.py", line 10, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/usr/local/lib/python2.7/dist-packages/rekall-1.3.1-py2.7.egg/rekall/plugins/addrspaces/ewf.py", line 26, in <module>
    from rekall.plugins.tools import ewf
  File "/usr/local/lib/python2.7/dist-packages/rekall-1.3.1-py2.7.egg/rekall/plugins/tools/__init__.py", line 35, in <module>
    from rekall.plugins.tools import webconsole_plugin
  File "/usr/local/lib/python2.7/dist-packages/rekall-1.3.1-py2.7.egg/rekall/plugins/tools/webconsole_plugin.py", line 43, in <module>
    from rekall.plugins.tools.webconsole import runplugin
  File "/usr/local/lib/python2.7/dist-packages/rekall-1.3.1-py2.7.egg/rekall/plugins/tools/webconsole/runplugin.py", line 49, in <module>
    from flask_sockets import Sockets
  File "/usr/local/lib/python2.7/dist-packages/Flask_Sockets-0.1-py2.7.egg/flask_sockets.py", line 15, in <module>
    from geventwebsocket.gunicorn.workers import GeventWebSocketWorker as Worker
  File "/usr/local/lib/python2.7/dist-packages/gevent_websocket-0.9.3-py2.7.egg/geventwebsocket/__init__.py", line 18, in <module>
    from .server import WebSocketServer
  File "/usr/local/lib/python2.7/dist-packages/gevent_websocket-0.9.3-py2.7.egg/geventwebsocket/server.py", line 1, in <module>
    from gevent.pywsgi import WSGIServer
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/pywsgi.py", line 12, in <module>
    from gevent import socket
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/socket.py", line 659, in <module>
    from gevent.ssl import sslwrap_simple as ssl, SSLError as sslerror, SSLSocket as SSLType
  File "/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

Seems to be caused by https://github.com/gevent/gevent/issues/513

**Comment by bentau** [comment]
Did someone found a bugfix or workaround for this problem?

**Comment by grrrrrrrrr** [comment]
It seems like gevent has fixed this back in December:
https://github.com/gevent/gevent/commit/fd216f9b834c75beacace48fd1e877fcf144b268

Can you update gevent to a newer version? Does that help?

**Comment by bentau** [comment]
Thanks, that helped

**Comment by scudette** [comment]
This issue does not seem to occur when installing though pip which is the recommended installer.
