### ISSUE TITLE
Commit 2103dc7168a35d122d5b12438a575bf347938bec seems to have broken setup.py

### ISSUE THREAD

**Issue by parkisan** [google/rekall#63]
It looks like we made rekall/efilter_protocols.py part of the base rekall namespace and it's pulling the yaml module via dependencies. As we get the version in the setup.py file from rekall/constants.py, we now require yaml to install the prerequisites (one of which is yaml :) )

Can you fix this?
Why do we need efilter_protocols as part of the rekall namespace?

```bash
$ git pull origin master
From https://github.com/google/rekall
 * branch            master     -> FETCH_HEAD
Already up-to-date.
$ virtualenv head-environment
New python executable in head-environment/bin/python
Installing setuptools, pip...done.
$ . head-environment/bin/activate
(head-environment)
$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    from rekall import constants
  File "./rekall/__init__.py", line 2, in <module>
    from rekall import efilter_protocols
  File "./rekall/efilter_protocols.py", line 30, in <module>
    from rekall import obj
  File "./rekall/obj.py", line 45, in <module>
    from rekall.ui import renderer
  File "./rekall/ui/__init__.py", line 4, in <module>
    from rekall import config
  File "./rekall/config.py", line 36, in <module>
    import yaml
ImportError: No module named yaml

(head-environment)
$ pip install "PyYAML >= 2.10"
Downloading/unpacking PyYAML>=2.10
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/usr/local/google/home/jordisanchez/projects/rekall/head-environment/build/PyYAML/setup.py) egg_info for package PyYAML
    
Installing collected packages: PyYAML
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
Successfully installed PyYAML
Cleaning up...
(head-environment)
$ python setup.py develop
[... ok ...]
```

**Comment by scudette** [comment]
Yeah I think there is an import from __init__.py which causes problems:

from rekall import efilter_protocols 

This is obviously needed in order to register the efilter interfaces but it does so at import time (which is a problem in itself). This stuff should probably be a plugin in the plugins directory - since it is only used by some plugins (mainly the efilter ones).

I suggest to move this import to rekall/plugins/common/entities.py

**Comment by scudette** [comment]
Actually lets move all the efilter files into their own directory inside  rekall/plugins/common/entities.py since these are not related to rekall generally but simply are used in implementing the rekall/efilter glue.

We should move to a place where we can split the package into core and plugins or maybe even finer grained (e.g. windows/osx/linux packages) so lets try to compartmentalize code as much as possible.

**Comment by scudette** [comment]
Fixed.
