### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by tankbusta** [google/rekall#66]
What are the plans (if any) to support Python 3? All of the third-party components rekall uses support Python 3.

**Comment by scudette** [comment]
We currently have no firm plans to support python 3. We did discuss it briefly but it is not a priority at the moment. Do you see it as an important feature?

**Comment by tankbusta** [comment]
I do, especially with future Ubuntu distributions switching over to Python 3 by [default](http://news.softpedia.com/news/Ubuntu-15-10-to-Finally-Drop-Python-2-X-Support-477830.shtml). Rekall is the only component I'm using that forces me down to Python 2.7.X. 

I've started working on a Py3 build but I probably won't have anything to show for at least another week (and it currently doesn't work in Python 2). The two big issues I see are how metaclasses are implemented in Python 3 and the use of unicode(). 

An easy win going forward would be to at least standardize on a few things...

1. Catching multiple exceptions:

        except ValueError, TypeError

        #should be...

        except (ValueError, TypeError):

2. Declaring exceptions as variable

        except Exception, e:

        # should be

        except Exception as e:

3. Switching print over to the function


That said, I'll focus on getting my changes working again on Python 2 and get it pushed up into my fork. I have the session object working and loading profiles but whenever it starts reading from the winpmem driver, it hangs on on [scan.py](https://github.com/google/rekall/blob/master/rekall/scan.py#L420)/[win32.py](https://github.com/google/rekall/blob/master/rekall/plugins/addrspaces/win32.py#L153) in Python 3

**Comment by scudette** [comment]
Yes I totally agree with the style changes. There are probably some areas of the code which need to be updated. We would certainly appreciate any patches towards python 3 compatibility.

**Comment by tankbusta** [comment]
Would you also support a switch to dict literals instead of the constructor? I'm not too familiar with the code base yet but it should increase performance if we're creating a lot of dictionaries somewhere.

**Comment by scudette** [comment]
I did not know there was a performance different actually but this reference proves it (I wonder if this is also the case for python 3):

http://doughellmann.com/2012/11/12/the-performance-impact-of-using-dict-instead-of-in-cpython-2-7-2.html

So thanks for bringing it up. Realistically though we do not allocate many dicts often. We mostly use dicts to define the Struct definitions which are done at import time and never again. I personally prefer the dict() notation because I think it is clearer and easier to type (It also looks like function calls rather than a dedicated syntax for dicts).

If there is clear evidence that a specific use is very "hot" we can change it, but I would not recommend a wider search/replace. I would like to do some solid profiling first to be convinced it is an issue (quite often the 6x difference in speed is negligible because its not done so often anyway and something else is more of a bottleneck).

**Comment by tankbusta** [comment]
Style changes are up at #67

**Comment by tankbusta** [comment]
Progress for this can be seen at https://github.com/tankbusta/rekall/tree/cs_py3k

**Comment by scudette** [comment]
Thanks, this looks very cool.

**Comment by tankbusta** [comment]
I have an (almost) working build... It still functions in Python 2 but it's currently blowing up in the rendering plugins in Python 3. `unicode()` has been removed in python 3 because all strings are treated as unicode. The rendering plugins as they stand (ab)use `unicode`. 

@scudette If this is something you could help with, I'd greatly appreciate it. 

I really think we're close to at least *something* working in Python 3. Damn unicode...

```
➜  rekall git:(cs_py3k) python3 -m rekall.rekal --plugin lsmod --filename /dev/pmem -v -p OSX/10.10.3_14D136.64bit
DEBUG:rekall-1014c6f60:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz
DEBUG:rekall-1014c6f60:Opened local file /Users/cschmitt/.rekall_cache/v1.0/inventory.gz
DEBUG:rekall-1014c6f60:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:rekall-1014c6f60:Opened local file /Users/cschmitt/.rekall_cache/v1.0/inventory.gz
DEBUG:rekall-1014c6f60:Opened local file /Users/cschmitt/.rekall_cache/v1.0/OSX/10.10.3_14D136.64bit.gz
INFO:rekall-1014c6f60:Loaded profile OSX/10.10.3_14D136.64bit from Local Cache Directory:/Users/cschmitt/.rekall_cache
DEBUG:rekall-1014c6f60:Voting round with base: None
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:rekall-1014c6f60:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:rekall-1014c6f60:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:rekall-1014c6f60:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:rekall-1014c6f60:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:rekall-1014c6f60:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
DEBUG:rekall-1014c6f60:Succeeded instantiating MacPmemAddressSpace
DEBUG:rekall-1014c6f60:Voting round with base: MacPmemAddressSpace
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x7ea6766
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:rekall-1014c6f60:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:rekall-1014c6f60:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:rekall-1014c6f60:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:rekall-1014c6f60:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:rekall-1014c6f60:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
DEBUG:rekall-1014c6f60:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:rekall-1014c6f60:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
DEBUG:rekall-1014c6f60:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:rekall-1014c6f60:Autodetected physical address space MacPmemAddressSpace
   Address          Size        Refs     Version    Name
-------------- -------------- -------- ------------ ----
<class 'rekall.plugins.overlays.basic.String'>
<class 'rekall.plugins.overlays.basic.UnicodeString'>
CRITICAL:rekall-1014c6f60:Traceback (most recent call last):
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/session.py", line 693, in _RunPlugin
    return plugin_obj.render(ui_renderer) or plugin_obj
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/plugins/darwin/lsmod.py", line 66, in render
    mod.name)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/text.py", line 1367, in table_row
    super(TextRenderer, self).table_row(*args, **kwargs)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/renderer.py", line 443, in table_row
    self.table.render_row(row=row, **kwargs)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/text.py", line 1151, in render_row
    highlight=highlight)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/text.py", line 1123, in write_row
    line, foreground=foreground, background=background) + "\n")
TypeError: can't concat bytes to str

CRITICAL:root:can't concat bytes to str. Try --debug for more information.
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/rekal.py", line 83, in <module>
    main()
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/rekal.py", line 69, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/session.py", line 1100, in RunPlugin
    self.last = super(InteractiveSession, self).RunPlugin(*args, **kwargs)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/session.py", line 637, in RunPlugin
    *pos_args, **kwargs)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/session.py", line 693, in _RunPlugin
    return plugin_obj.render(ui_renderer) or plugin_obj
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/plugins/darwin/lsmod.py", line 66, in render
    mod.name)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/text.py", line 1367, in table_row
    super(TextRenderer, self).table_row(*args, **kwargs)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/renderer.py", line 443, in table_row
    self.table.render_row(row=row, **kwargs)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/text.py", line 1151, in render_row
    highlight=highlight)
  File "/Users/cschmitt/code/thirdparty/rekall/rekall/ui/text.py", line 1123, in write_row
    line, foreground=foreground, background=background) + "\n")
TypeError: can't concat bytes to str
```

**Comment by scudette** [comment]
The place it blows up is here:

```
          self.renderer.write(
                self.renderer.colorizer.Render(
                    line, foreground=foreground, background=background) + "\n")
```

The colorizer is the thing which emits tty controls (for the colors) so it is supposed to emit bytes, but we append "\n" - a string. Does it work better if you specify b"\n"?

**Comment by tankbusta** [comment]
Actually yes it does! I didn't try it earlier because it's getting late over here. It's blowing up at some more bytes stuff but I'll spend some more time on it later.

:tada: Something working on python3! 

```
➜  rekall git:(cs_py3k) ✗ python3 -m rekall.rekal --plugin lsmod --filename /dev/pmem -v -p OSX/10.10.3_14D136.64bit
DEBUG:rekall-106004160:Opened url https://raw.githubusercontent.com/google/rekall-profiles/master/v1.0/inventory.gz
DEBUG:rekall-106004160:Opened local file /Users/cschmitt/.rekall_cache/v1.0/inventory.gz
DEBUG:rekall-106004160:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
DEBUG:rekall-106004160:Opened local file /Users/cschmitt/.rekall_cache/v1.0/inventory.gz
DEBUG:rekall-106004160:Opened local file /Users/cschmitt/.rekall_cache/v1.0/OSX/10.10.3_14D136.64bit.gz
INFO:rekall-106004160:Loaded profile OSX/10.10.3_14D136.64bit from Local Cache Directory:/Users/cschmitt/.rekall_cache
DEBUG:rekall-106004160:Voting round with base: None
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:rekall-106004160:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:rekall-106004160:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:rekall-106004160:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:rekall-106004160:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:rekall-106004160:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
DEBUG:rekall-106004160:Succeeded instantiating MacPmemAddressSpace
DEBUG:rekall-106004160:Voting round with base: MacPmemAddressSpace
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating VMemAddressSpace: Only VMEM files supported.
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
DEBUG:rekall-106004160:Failed instantiating MACHOCoreDump: Header signature invalid
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x7ea6766
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating EWFAddressSpace: EWF signature not present
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
DEBUG:rekall-106004160:Failed instantiating WindowsCrashBMP: Header signature invalid
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating KCoreAddressSpace: Header signature invalid
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
DEBUG:rekall-106004160:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
DEBUG:rekall-106004160:Failed instantiating Elf64CoreDump: Header signature invalid
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
DEBUG:rekall-106004160:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating LimeAddressSpace: Invalid Lime header signature
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating FileAddressSpace: Must be first Address Space
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
DEBUG:rekall-106004160:Failed instantiating VTxPagedMemory: No more EPTs specified
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:rekall-106004160:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
DEBUG:rekall-106004160:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
INFO:rekall-106004160:Autodetected physical address space MacPmemAddressSpace
DEBUG:rekall-106004160:Opened local file /Users/cschmitt/.rekall_cache/v1.0/OSX/10.10.3_14D136.64bit.gz
INFO:rekall-106004160:Loaded profile OSX/10.10.3_14D136.64bit from Local Cache Directory:/Users/cschmitt/.rekall_cache
   Address          Size        Refs     Version    Name
-------------- -------------- -------- ------------ ----
0xff8005a00000 0x000003213000       -1       14.3.0 __kernel__
0xff7f88804000 0x000000059000        0        3.0.1 com.apple.filesystems.smbfs
0xff7f887b1000 0x000000053000        0         11.0 com.apple.filesystems.afpfs
0xff7f887a0000 0x000000011000        1          1.0 com.apple.security.SecureRemotePassword
<snipped>
```

**Comment by Wenzel** [comment]
Hi !

I'm really interested by this issue since i'm working on a Python3 which has to use a Python2 subprocess to import `Rekall` APIs.

What's the status here ? Is there any ongoing work already ?


Thanks !

**Comment by tankbusta** [comment]
@Wenzel I had gotten some audit modules to work in Python 3 while still maintaining some support for Python 2 but unless someone on the Rekall team has been working on this, my Py3 branch has stalled indefinitely.

**Comment by Wenzel** [comment]
Can you estimate how much work is needed to port Rekall to Python3 ?

Can this be acomplished by a beginner/intermediate python user like me (just googling the new API, making use of the new features) ?, or is it more complex ?

Maybe @scudette knows better the status here :)

**Comment by scudette** [comment]
I dont think it would be very difficult. IIRC the last person to work on it was @the80srobot  but he was discouraged because the result was a very significant loss in performance since python3 seems to be much slower (at least for the operations we do frequently).

I am happy to revive the effort though. I think it is a worthwhile long term investment.

**Comment by tankbusta** [comment]
@scudette / @the80srobot What operations were you noticing a significant performance loss in? Happen to have any benchmarks or data?

**Comment by Wenzel** [comment]
I don't see any python3 related branch on @the80srobot rekall fork.

From who should i pull to take the latest efforts ?

**Comment by scudette** [comment]
I have been looking more into this issue. In the past we have needed to keep python 27 support because Rekall was integrated with GRR. Now since this is no longer relevant I am struggling to think why we would actually need to keep 2.7 compatibility? Does anyone need 2.7 compatibility? I am thinking to just switch to python 3 cold turkey for the next release. This will be easier because we wont need to worry about backwards compatibility and have subtle bugs related to unicode/str/bytes.

What do people think?

**Comment by tankbusta** [comment]
It would definitely be a lot of work to support both versions. My vote would be to ditch 2.7 support entirely given the future is in 3.X

**Comment by scudette** [comment]
I am making some progress in this branch https://github.com/scudette/rekall/tree/python3, feel free to play with it. I have some plugins working and will run through the test suite to make sure they all pass.
