### ISSUE TITLE
Problems with "-s": can't create session, can't load session, not working as documented. 

### ISSUE THREAD

**Issue by aapo** [google/rekall#72]
Happens with 1.2.1 / 1.3.1 and git-head (4c3b7219226121ad0fa3cfe63b4e690cc4342a66)
Documentation on http://www.rekall-forensic.com/docs/Manual/tutorial.html#_the_rekall_session (4.1. Saving the session) says

    rekal -v -f ~/images/win7.elf -s my_session.rekall pslist

I have imagefile, but I do not have my_session.rekall. Running above command stops with error:

    ERROR:rekall.1:Traceback (most recent call last):
     File "rekall-1.3.2-py2.7.egg/rekall/session.py", line 916, in LoadFromFile
        lexicon, data = json.load(open(filename, "rb"))
    IOError: [Errno 2] No such file or directory: 'my_session.rekall'

    Traceback (most recent call last):
      File "rekal", line 9, in <module>
        load_entry_point('rekall==1.3.2', 'console_scripts', 'rekal')()
      File "rekall-1.3.2-py2.7.egg/rekall/rekal.py", line 59, in main
        user_session=user_session)
      File "rekall-1.3.2-py2.7.egg/rekall/args.py", line 408, in parse_args
        ParseGlobalArgs(parser, argv, user_session)
      File "rekall-1.3.2-py2.7.egg/rekall/args.py", line 238, in ParseGlobalArgs
        state.Set(arg, value)
      File "rekall-1.3.2-py2.7.egg/rekall/session.py", line 348, in __exit__
        res = hook(value, self._pending_parameters)
      File "rekall-1.3.2-py2.7.egg/rekall/session.py", line 257, in _set_autodetect_build_local_tracked
        return set(tracked)
    TypeError: 'NoneType' object is not iterable

Tried with

    rekal -v -f ~/images/win7.elf
    session.SaveToFile("my_session.rekall")
    ERROR:rekall.1:Unable to encode objects of type <class 'rekall.utils.JITIterator'>

Despite of error, it creates file my_session.rekall which is json-file.

But loading it will not work:

    rekal -f image.elf -s my_session.rekall
    Traceback (most recent call last):
      File "rekal", line 9, in <module>
        load_entry_point('rekall==1.3.2', 'console_scripts', 'rekal')()
      File "rekall-1.3.2-py2.7.egg/rekall/rekal.py", line 59, in main
        user_session=user_session)
      File "rekall-1.3.2-py2.7.egg/rekall/args.py", line 408, in parse_args
        ParseGlobalArgs(parser, argv, user_session)
      File "rekall-1.3.2-py2.7.egg/rekall/args.py", line 238, in ParseGlobalArgs
        state.Set(arg, value)
      File "rekall-1.3.2-py2.7.egg/rekall/session.py", line 348, in __exit__
        res = hook(value, self._pending_parameters)
      File "rekall-1.3.2-py2.7.egg/rekall/session.py", line 257, in _set_autodetect_build_local_tracked
        return set(tracked)
    TypeError: 'NoneType' object is not iterable

**Comment by scudette** [comment]
Thanks for reporting. The -s option will disappear really soon. There is a patch under review to replace this with a persistent cache which is enabled by default (https://codereview.appspot.com/245300043/).
