### ISSUE TITLE
MACTime Flow unexpected keyword argument  'limit'

### ISSUE THREAD

**Issue by chlete** [google/rekall#74]
Hi!

I'm running GRR 3.0.6 on Ubuntu 14.04.2 on x86_64. While executing on the GUI the MACTimes flow, I got the following error:

``` python
Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 318, in Decorated
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/grr/gui/views.py", line 160, in RenderGenericRenderer
    result = method(request, result) or result
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 955, in Layout
    id="%s_rightTopPane" % self.id).RawHTML(request)
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 373, in RawHTML
    method(request, result, **kwargs)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 618, in Layout
    return super(FileTable, self).Layout(request, response)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 478, in Layout
    response = super(AbstractFileTable, self).Layout(request, response)
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 656, in Layout
    self.table_contents = delegate_renderer.RenderAjax(request, tmp).content
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 468, in RenderAjax
    response = super(AbstractFileTable, self).RenderAjax(request, response)
  File "/usr/lib/python2.7/dist-packages/grr/gui/renderers.py", line 691, in RenderAjax
    limit_row + start_row, request)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 623, in BuildTable
    return super(FileTable, self).BuildTable(start_row, end_row, request)
  File "/usr/lib/python2.7/dist-packages/grr/gui/plugins/fileview.py", line 528, in BuildTable
    limit=100000))
TypeError: Query() got an unexpected keyword argument 'limit'
```

fileview.py line 528

``` python
 # Open the directory as a directory.
      directory_node = aff4.FACTORY.Open(urn, token=request.token).Upgrade(
          "VFSDirectory")
      if not directory_node:
        raise IOError()

      key += str(directory_node.Get(directory_node.Schema.LAST))
      key += ":" + str(request.token)
      try:
        children = self.content_cache.Get(key)
      except KeyError:
        # Only show the direct children.
        children = sorted(directory_node.Query(filter_string=filter_string, limit=1000))


``` 
I have seen that Query() is defined in two different classes: 

https://github.com/google/grr/blob/master/lib/aff4.py

* AFF4Volume

``` Python
class AFF4Volume(AFF4Object):
[...]
  def Query(self, filter_string="", limit=1000, age=NEWEST_TIME):
    """Lists all direct children of this object.
```

* AFF4Root

``` Python
class AFF4Root(AFF4Volume):
 [...]
  def Query(self, filter_string="", filter_obj=None, subjects=None, limit=100):

```

 Looks like AFF4Root's Query() overwrites AFF4Volume's Query().

Cheers,
Christian

**Comment by chlete** [comment]
Should be actually  in the GRR issues :)
