### ISSUE TITLE
Linux 3.19 (or earlier) changed timekeeping again

### ISSUE THREAD

**Issue by parkisan** [google/rekall#76]
CRITICAL:rekall.1:Traceback (most recent call last):
  File "/home/jordisanchez/rekall/rekall-core/rekall/session.py", line 706, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/jordisanchez/rekall/rekall-core/rekall/plugins/linux/pslist.py", line 53, in render
    start_time = task.start_time.as_timestamp()
AttributeError: 'NativeType' object has no attribute 'as_timestamp'

CRITICAL:root:'NativeType' object has no attribute 'as_timestamp'. Try --debug for more information.
Traceback (most recent call last):
  File "/home/jordisanchez/rekallenv/bin/rekal", line 9, in <module>
    load_entry_point('rekall-core==1.3.2.post.dev74', 'console_scripts', 'rekal')()
  File "/home/jordisanchez/rekall/rekall-core/rekall/rekal.py", line 81, in main
    user_session.RunPlugin(plugin_cls, **config.RemoveGlobalOptions(flags))
  File "/home/jordisanchez/rekall/rekall-core/rekall/session.py", line 709, in RunPlugin
    self._HandleRunPluginException(ui_renderer, e)
  File "/home/jordisanchez/rekall/rekall-core/rekall/session.py", line 706, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "/home/jordisanchez/rekall/rekall-core/rekall/plugins/linux/pslist.py", line 53, in render
    start_time = task.start_time.as_timestamp()
AttributeError: 'NativeType' object has no attribute 'as_timestamp'

(Pdb) task.start_time
 [long long unsigned int:start_time]: 0x02DC6C00

**Comment by parkisan** [comment]
Fixed in https://codereview.appspot.com/261730043
