### ISSUE TITLE
500 Error from Webconsole: Unable to find manuskript/static/index.html

### ISSUE THREAD

**Issue by chrisbdaemon** [google/rekall#89]
I tried starting up the webconsole in a SIFT 3.0 vm bound to 0.0.0.0:8080.  Everything looked good till I tried to connected and I got a server error:

```
> rekal webconsole worksheet --host 0.0.0.0 --port 8080 -v
DEBUG:rekall.1:Running plugin (webconsole) with args (()) kwargs ({'worksheet': 'worksheet', 'export_root_url': '/', 'export_root_url_path': None, 'host': '0.0.0.0', 'export': None, 'port': 8080, 'browser': False})
Starting Manuskript web console.
Press Ctrl-c to return to the interactive shell.
DEBUG:rekall.1:Opened local file /home/sansforensics/hn3/worksheet/metadata.rkl
DEBUG:rekall.1:Opened local file /home/sansforensics/hn3/worksheet/sessions
DEBUG:rekall.2:Voting round with base: None
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'> 
DEBUG:rekall.2:Failed instantiating VMSSAddressSpace: No base address space provided
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'> 
DEBUG:rekall.2:Failed instantiating MACHOCoreDump: Must stack on another address space
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'> 
DEBUG:rekall.2:Failed instantiating VMemAddressSpace: No base address space provided
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'> 
DEBUG:rekall.2:Failed instantiating EWFAddressSpace: No base address space provided
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'> 
DEBUG:rekall.2:Failed instantiating WindowsCrashBMP: Must stack on another address space
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'> 
DEBUG:rekall.2:Failed instantiating KCoreAddressSpace: Must stack on another address space
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'> 
DEBUG:rekall.2:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'> 
DEBUG:rekall.2:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'> 
DEBUG:rekall.2:Failed instantiating Elf64CoreDump: Must stack on another address space
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'> 
DEBUG:rekall.2:Failed instantiating LimeAddressSpace: Must be layered on another address space.
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'> 
DEBUG:rekall.2:Failed instantiating AFF4AddressSpace: Filename must be specified
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'> 
DEBUG:rekall.2:Failed instantiating MacPmemAddressSpace: Filename must be specified.
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'> 
DEBUG:rekall.2:Failed instantiating FileAddressSpace: Filename must be specified in session (e.g. session.SetParameter('filename', 'MyFile.raw').
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'> 
DEBUG:rekall.2:Failed instantiating MmapFileAddressSpace: Must be first Address Space
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'> 
DEBUG:rekall.2:Failed instantiating VTxPagedMemory: 
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'> 
DEBUG:rekall.2:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
DEBUG:rekall.2:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'> 
DEBUG:rekall.2:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
DEBUG:root:Loaded configuration from /home/sansforensics/.rekallrc
DEBUG:rekall.1:Logging level set to 30
Server running at http://0.0.0.0:8080
DEBUG:geventwebsocket.handler:Initializing WebSocket
DEBUG:geventwebsocket.handler:Validating WebSocket request
ERROR:manuskript.server:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/manuskript/server.py", line 62, in index
    StringIO.StringIO(ExpandManuskriptHeaders(plugins)),
  File "/usr/local/lib/python2.7/dist-packages/manuskript/server.py", line 42, in ExpandManuskriptHeaders
    with open(os.path.join(STATIC_PATH, "index.html")) as fd:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/manuskript/static/index.html'
INFO:geventwebsocket.handler:192.168.156.1 - - [2015-09-02 19:15:58] "GET / HTTP/1.1" 500 412 0.013525
```

SIFT came with an older version of rekall preinstall so I got the latest version from Github and did `sudo python setup.py install` while in the master branch and everything looked like it had installed alright until I got this error.

**Comment by scudette** [comment]
The setup.py file in the rekall directory just installs the pip version.
You should go into the rekall-core and rekall-gui directories and run
setup.py install from there.

There was a bug in 140 which did not copy the right html files. This should
be fixed in git head.
Am 02.09.2015 21:20 schrieb "chrisbdaemon" <notifications@github.com>:

**Comment by jklipsch** [comment]
My installation of Rekall came from the SIFT Workstation and got the same 500 error. I had to re-download the binary and perform the steps outlined above.

**Comment by trolldbois** [comment]
Same error with rekall 1.4.1

**Comment by vegardvaage** [comment]
@jklipsch , where are the rekall directories with the correct setup.py located?

**Comment by zekoso** [comment]
a solution I found was copying the missing folder to the right directory `sudo cp -R /usr/local/manuskript/static /usr/local/lib/python2.7/dist-packages/manuskript/`

**Comment by scudette** [comment]
This problem should be solved in the current release. Thanks for reporting.
